### ISSUE TITLE
Allow use of different icons via the config.yml file

### ISSUE THREAD

**Issue by BinaryBen** [netlify/netlify-cms#1040]
**- Do you want to request a *feature* or report a *bug*?**

Feature request

&nbsp;

**- What is the current behavior?**

All icons for collections are the same. It is hard to quickly differentiate if there is a large number of collection types.

&nbsp;

**- What is the expected behavior?**

Possibly through using something like font awesome instead of SVG's, allow developers to change the look of the icon next to each category in the side bar.

&nbsp;

**- Please link or paste your `config.yml` below if applicable.**

See the addition of the icon attribute below as an example:

```yaml
collections:
  - name: settings
    label: Settings
    icon: fa-cog
    files: 
      - label: Global Settings
        name: global
        file: global-settings.yml
```

Many users probably have font awesome cached in their browser as well if that helps.
