### ISSUE TITLE
[Media Library] Ability to work with folders

### ISSUE THREAD

**Issue by ww7** [netlify/netlify-cms#1046]
Browse at first.

**Comment by tech4him1** [comment]
@ww7 Can you explain in more detail?

**Comment by erquhart** [comment]
Guessing this is about breaking assets into multiple folders instead of just the media folder. We're planning to solve this eventually with asset collections, but I don't think there's an issue for it yet.

**Comment by dudil** [comment]
@erquhart - do you have a design or issue for assets collections? That means being able to put media in realtime path (inside static) to the collections?

I'll be happy to contribute that if it's in your plan or have an open issues about it (couldn't find one...)

**Comment by erquhart** [comment]
@dudil that would be awesome. No design work has been done - do you work in design, development or both? I'm expecting to just have a vertical list of asset collections on the left side, which would map to folders, and you could specify for an image or file field which asset collections it could pull from.

I'll get a proper issue together.

**Comment by dudil** [comment]
@erquhart - I'm more on the development side.
What I had was something more simple and maybe different.
To be able to override the media_folder and public_folder per collection
for example:

```
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    media_folder: "static/images/blog/" # override for blog collection
   public_folder: "/images/uploads/blog/" # override for blog collection
```

BTW - if that could be changed to include also the parameter options, it will be even better something like {{slug}} etc.

What do you think about this?
