### ISSUE TITLE
Relation widget: store related item's slug value in `valueField`

### ISSUE THREAD

**Issue by criticalmash** [netlify/netlify-cms#1063]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
The relation widget's `valueField` allows you to specify a field in another collection as a lookup value for items in that collection. The sample case given is the related item's title.

```yml
- label: "location"
        name: "Location"
        widget: "relation"
        collection: "locations"
        searchFields: ["title", "streetAddress"]
        valueField: "title"
```

**- What is the expected behavior?**
I would prefer to store the related item's slug/filename in the `valueField` instead. This would allow me to easily lookup and include the file or it's data when generating the site.

Also, by using the filename, CMS can provide some guarantee that keys are unique.

```yml
- label: "location"
        name: "Location"
        widget: "relation"
        collection: "locations"
        searchFields: ["title", "streetAddress"]
        valueField: "{{slug}}"
```

With this type of config, I can load in a collection of files as a JS object and lookup an item by it's slug.

```js
var locationSlug = frontmatter.location;
var locationData = locations[locationSlug];
```

**- Please mention your CMS, node.js, and operating system version.**
CMS v1.1.0

Thanks,
John
