### ISSUE TITLE
File Collections behave strange / don't work locally

### ISSUE THREAD

**Issue by andreasremdt** [netlify/netlify-cms#1082]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug.

**- What is the current behavior?**
I'm editing my Jekyll site on a local development environment and pushing changes to GitHub. To verify that my `config.yml` is correctly set up I log into the CMS's backend on my localhost. However, the collections are behaving strange.
If I do any changes in the `config.yml` file, it often goes crazy in the CMS's GUI. It either stops displaying the collections, displays them as empty even through they have content or displays an error message. Just changing a file's name can cause this strange behavior. Sometimes it just works and I have no clue why. *This only happens locally, once pushed to the Netlify CDN it works well.*

I double and trible-checked my Markdown and YAML files and my `config.yml`, there is no syntax error or anything that would explain this behavior.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Create a `config.yml` file like below and open it on localhost. Now make changes to the Markdown or YAML files or to the `config.yml`. Log into the backend and watch what happens to the Collections.

**- What is the expected behavior?**
It should display the collections as referenced in the `config.yml`.

* CMS version: 1.1.0
* Node.js version: 8.9.4
* OS version: Solus OS 3.26.2
* Browser version: Chrome 64.0.3282.119 & Firefox 58.0
* GitHub Repository: https://github.com/andreasremdt/instituto-nacional

**config.yml**
```
backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "images/"

collections:
  - name: "careers"
    label: "Careers"
    folder: "_carreras"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "careers" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - label: "Blog"
    name: "blog"
    folder: "_posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widhet: "string" }
      - { label: "Publish date", name: "date", widget: "datetime" }
      - { label: "Featured image", name: "image_path", widget: "image" }
      - { label: "Tag", name: "tag", widget: "select", options: ["news", "nature", "other"] }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Páginas"
    name: "pages"
    create: false
    files:
      - label: "Historia"
        name: "history"
        file: "historia.md"
        fields:
          - { label: "Pre-encabezado", name: "pre_heading", widget: "string" }
          - { label: "Encabezado", name: "heading", widget: "string" }
          - label: "Entradas"
            name: "entries"
            widget: "list"
            fields:
              - { label: "Año", name: "year", widget: "number" }
              - { label: "Contenido", name: "content", widget: "markdown" }
      - label: "Profesores"
        name: "profesores"
        file: "profesores.md"
        fields:
          - { label: "Título de la página", name: "title", widget: "string" }
          - { label: "Contenido", name: "body", widget: "markdown" }
          - label: "Lista de profesores"
            name: "teachers"
            widget: "list"
            fields:
              - { label: "Nombre de profesor", name: "name", widget: "string" }
              - { label: "Descripción", name: "description", widget: "text" }
              - { label: "Imagen", name: "image_path", widget: "image" }
      - label: "Inicio"
        name: "home"
        file: "index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - label: Sections
            name: sections
            widget: object
            fields:
              - label: Hero Section
                name: hero
                widget: object
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Subtitle, name: subtitle, widget: string }
                  - label: Links
                    name: buttons
                    widget: list
                    fields:
                      - { label: Title, name: title, widget: string }
                      - label: URL
                        name: url
                        widget: select
                        options:
                          - { label: Homepage, value: / }
                          - { label: La Escuela, value: /escuela/ }
                          - { label: Campus, value: /campus/ }
                          - { label: Carreras, value: /carreras/ }
                          - { label: Profesores, value: /profesores/ }
                          - { label: Servicios, value: /servicios/ }
                          - { label: Blog, value: /blog/ }
                          - { label: Contáctenos, value: /contactenos/ }
                      - { label: Color, name: color, default: green, widget: select, options: [green, transparent] }
              - label: About Section
                name: about
                widget: object
                fields:
                  - { label: Pre-title, name: pretitle, widget: string }
                  - { label: Title, name: title, widget: string }
                  - label: Items
                    name: items
                    widget: list
                    fields:
                      - { label: Title, name: title, widget: string }
                      - { label: Text, name: caption, widget: string }
                      - { label: Image, name: image_path, widget: image }
                      - label: URL
                        name: url
                        widget: select
                        options:
                          - { label: Homepage, value: / }
                          - { label: La Escuela, value: /escuela/ }
                          - { label: Campus, value: /campus/ }
                          - { label: Carreras, value: /carreras/ }
                          - { label: Profesores, value: /profesores/ }
                          - { label: Servicios, value: /servicios/ }
                          - { label: Blog, value: /blog/ }
                          - { label: Contáctenos, value: /contactenos/ }
              - label: News Section
                name: news
                widget: object
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Subtitle, name: subtitle, widget: string }
```
