### ISSUE TITLE
Relation widget crashes if `valueField` doesn't return string or component.

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#1116]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
If the `valueField` for a relation widget isn't a string (or other renderable object in React), the CMS will crash.
**- If the current behavior is a bug, please provide the steps to reproduce.**
Example:
```yaml
    fields:
      - label: "Related Post Date"
        name: "post_date"
        widget: "relation"
        collection: "posts"
        searchFields: ["title", "date"]
        valueField: "date"
```
Try to type into the relation widget.
**- What is the expected behavior?**
The relation widget should still work with fields that don't return strings or React components.

**- Please mention your CMS, node.js, and operating system version.**

1.2.0-dev

**- Please link or paste your `config.yml` below if applicable.**
