### ISSUE TITLE
Error creating collection entry depending on title value

### ISSUE THREAD

**Issue by ianmilliken** [netlify/netlify-cms#1121]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
On production, I'm creating an entry in an already populated collection called 'Services'. Depending solely on the title of the entry, NetlifyCMS fails to create it and returns an error.

**- If the current behaviour is a bug, please provide the steps to reproduce.**
1. I create a new entry with a specific title of 'Advertising', 'Advert', or 'Advertise' (the title generates the URL)
2. I click to save
3. CMS returns a popup error of 'Error: Failed to load entry. Failed to fetch' and then fails to save the entry, refreshing to a blank screen (except for the CMS navbar)
4. The browser console shows the same error

**- What is the expected behavior?**
The entry should be created, and would be if the name were anything else it seems

**- Please mention your CMS, node.js, and operating system version.**

- Netlify CMS version 1.2.0
- Node version v6.13.0
- Running on Netlify

**- Please link or paste your `config.yml` below if applicable.**
```
- label: Services
    name: services
    folder: site/content/services
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Intro, name: intro, widget: text, required: false }
      - { label: Icon, name: icon, widget: image, required: false }
      - { label: Icon Reverse Color Scheme, name: icon_reverse, widget: image, required: false }
      - { label: Image, name: image, widget: image, required: false }
      - { label: Content, name: body, widget: markdown, required: false }
```

I know this is ultra specific, so I'm not expecting any definitive answers, but if anybody has an idea about what might be causing this or has experienced something similar then it'd be great to hear from you.
