### ISSUE TITLE
CMS won't generate content files that match the archtype.

### ISSUE THREAD

**Issue by zberwaldt** [netlify/netlify-cms#1125]
**- Do you want to request a *feature* or report a *bug*?**

I think this is a Feature request, but it could be a bug. Sorry I can't be more clear. Maybe it'll be more clear after I describe it?

**- What is the current behavior?**

When I create content types for the different sections of my site with the cms the content files don't follow the archtypes I've defined in the site.  

The archtype is built as follows:

```
---
title: "{{ replace .TranslationBaseName "-" " " | title }}"
date: {{ .Date }}
image: #include image location here
draft: false
---

{{< frontmatterImg >}}
```
but any files generated by the CMS are output as follows:

```
---
title: Folders
image: /img/gallery/capture.png
content: A screen grab of a directory structure on my computer.
---
```

**- Please link or paste your `config.yml` below if applicable.**

```
  - name: gallery
    label: "Gallery Image"
    folder: "content/gallery"
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Gallery Image", name: "image", widget: "image"}
      - {label: "Image Description", name: "content", widget: "markdown"}
```

**- Please mention your CMS, node.js, and operating system version.**

Hugo v0.34
Node v9.3.0
Windows 10
