### ISSUE TITLE
Select widget inside List widget crashing

### ISSUE THREAD

**Issue by tomhamiltonstubber** [netlify/netlify-cms#1139]
**Bug**

**What is the current behavior?**

I've got a List widget with a Select widget as the field:

```yaml
- label: "Tags"
 name: "tags"
 widget: "list"
 field:
   - label: "Tag"
     name: "tag"
     widget: "select"
     options: [
       '11 Plus','A-Level Results','API','Accounting','Analytics','Business Management','CRM','Compare','Edtech',
       'Education','Exam','Features','Grammar Schools','Internship','Language Learning',
       'Managing a tutoring agency','Marketing','Mobile','National Tutoring Conference','Newsletter',
       'Online Tutoring','Open Source','Oxbridge Admissions','Recruitment','SEO','SaaS','Sales',
       'Small Business','Small business','Starting a business','Startup','Stripe','Teaching',
       'Technology','Testimonial','TutorCruncher','Tutoring','User Experience','VAT'
     ]
```
It renders like so:

![image](https://user-images.githubusercontent.com/8955690/36678132-de6fb78e-1b07-11e8-9357-6ce5c4cf3c2b.png)

Which I presume is wrong? The standard drop down renders properly when not in a List widget.

The field that should be a Select here renders as a text field, and when I input two letters (or add one and delete one), I get an error in the console (in `ListControl.js:156`)

```js
Uncaught TypeError: t.getObjectValue(...).set is not a function
    at ListControl.js:156
    at onChange (EditorControl.js:68)
    at onChange (StringControl.js:30)
    at Object.s (react-dom.production.min.js:25)
    at Object.invokeGuardedCallback (react-dom.production.min.js:24)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:24)
    at p (react-dom.production.min.js:29)
    at v (react-dom.production.min.js:31)
    at y (react-dom.production.min.js:31)
    at Array.forEach (<anonymous>)
```

I'm using Jekyll, Netlify CMS version 1.2.2 and I've tried Chrome and Firefox on Ubuntu and Windows.

I seem unable to find an example of this on someone's site working, so if anyone can point me towards that I'd be happy to take a look.
