### ISSUE TITLE
Don’t try to validate an optional field if it is empty

### ISSUE THREAD

**Issue by delucis** [netlify/netlify-cms#1175]
- **Bug report**

- **What is the current behavior?**
  If a field has a `pattern` option to validate input _and_ a `required` option set to `false`, Netlify CMS initially tries to validate the empty field and rejects it. If the `pattern` accounts for an empty string — e.g. `^(pattern)?$` — this will only validate once a value has been input and then removed. I don’t know, but I assume this is perhaps because the initial validation tries to run the `RegEx` on `undefined` and only after input runs it against an empty string.

- **If the current behavior is a bug, please provide the steps to reproduce.**

  1. Create a field with the following parameters (for example):
      ```yml
      - name: url
        label: URL
        pattern: ['^(https?:\/\/.+)?$', 'Must start with http:// or https://']
        widget: string
        required: false
      ```

  2. Create a new post, leave the `url` field blank, and try to save the post. The `url` field should flag as invalid.

  3. Enter some text into the `url` field and then delete it. Try to save the post. The `url` field should now validate.

- **What is the expected behavior?**
  If a field is marked as optional (i.e. `required: false`), validation should not be run if the field is `undefined`, `null`, or an empty string.

- **Please mention your CMS, node.js, and operating system version.**
  - Netlify CMS: 1.3.5
  - Node: not applicable
  - OS: OS X 10.9.5, using Chrome 64.0.3282.186
