### ISSUE TITLE
Boolean widget inside object widget does not accept default or existing value of `true`

### ISSUE THREAD

**Issue by gkogan** [netlify/netlify-cms#1177]
**- Do you want to request a *feature* or report a *bug*?**

Report a bug

**- What is the current behavior?**

The boolean widget defaults to `false` even if `default: true` is set, and even if the item's frontmatter has the field set to `true`.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Either:

* A) Add boolean widget inside an object widget, and set `default: true`.
* B) Add boolean widget inside an object widget, and open (in CMS) a collection item where that frontmatter key is set to `true`.

**- What is the expected behavior?**

The boolean widget would show `true` either because that's the default, or because that's the current value set in the collection item.

**- Please mention your CMS, node.js, and operating system version.**

* CMS 1.3.5
* NPM 5.5.1
* Chrome 65.0.3325.162 (Official Build) (64-bit)
* Mac OS 10.13.3

**- Please link or paste your `config.yml` below if applicable.**

```
# documentation: https://www.netlifycms.org/docs/

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img/uploads" # Media files will be stored in the repo under img/uploads
publish_mode: editorial_workflow # This enables saving and editing drafts

collections:
  - name: "resources"
    label: "Resources"
    folder: "resources"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "resource-form"}
      - {label: "Title", name: "title", widget: "string"}
      - label: Resource details
        name: resource
        widget: object
        fields:
          - { name: name, label: Name, widget: string }
          - { name: type, label: Type, widget: string}
          - { name: gated, label: "Gated", widget: boolean, default: true }
          - { name: url, label: "Resource URL (optional)", widget: string, required: false }
          - { name: action, label: "Call-to-Action Text", widget: string, default: "Get the Resource" }
          - { name: description, label: "Short description for the index", widget: string }
      - {label: "Body content", name: body, widget: markdown }
```
