### ISSUE TITLE
"Publish and create new" on file collection

### ISSUE THREAD

**Issue by bert-bruggeman** [netlify/netlify-cms#1183]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
"Publish and create new" on a file collection is present in the publish dropdown menu, "create: false" is set in the config file even though a single file should always have this setting).

**- If the current behavior is a bug, please provide the steps to reproduce.**
config example:
```
- name: "info"
        label: "Info"
        file: "_data/info.yml"
        delete: false
        create: false
        fields:
          - {label: "Title", name: "title", widget: "string", required: false }
          - {label: "Name", name: "name", widget: "string", required: false }
          - {label: "Street", name: "street", widget: "string", required: false }
          - {label: "Postal", name: "postal", widget: "string", required: false }
          - {label: "Locality", name: "locality", widget: "string", required: false }
          - {label: "Phone", name: "tel", widget: "string", required: false }
          - {label: "Mobile", name: "mobile", widget: "string", required: false }
          - {label: "Email", name: "email", widget: "string", required: false }
```
**- What is the expected behavior?**
"Publish and create new" shouldn't be in the publish dropdown for single files... 

**- Please mention your CMS, node.js, and operating system version.**
CMS 1.3.5 / OSX 10.13.3
