### ISSUE TITLE
Editor crashes when trying to edit a file collection type.

### ISSUE THREAD

**Issue by zolamk** [netlify/netlify-cms#1185]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Editor crashes. Message:
`Sorry! there's been an error - please report it!`
this is printed in console

```
TypeError: t.get is not a function
Stack trace:
e/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:135947
reduce/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:50355
Me.prototype.__iterate@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:36979
reduce@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:50309
e@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:135902
e/</<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:136067
Qe/r.__iterateUncached/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:14816
Me.prototype.__iterate@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:36979
Qe/r.__iterateUncached@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:14775
z@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:3696
N.prototype.__iterate@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:23555
toArray@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:47973
Me@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:10243
st@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:19098
map@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:50206
e/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:136042
reduce/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:50355
Me.prototype.__iterate@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:36979
reduce@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:50309
e@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:135902
value/a<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:202721
value@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:202700
updateClassInstance@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:281271
beginWork@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:282996
o@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:286941
a@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:287261
l@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:287499
_@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:290830
b@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:290558
h@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:289801
p@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:289211
enqueueSetState@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:279756
o.prototype.setState@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:285
o/</n</r.prototype.handleChange@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:190:38885
l@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:36:20198
d/</<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:3906
e.exports/</<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:190:52250
dispatch@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:36:23493
ee/</<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:17178
a@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:190:72320
M/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:190:72442
u@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:190:75567
 cms.js:182:288777
You tried to return focus to  but it is not in the DOM anymore cms.js:202:152545
TypeError: t.get is not a function
Stack trace:
e/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:135947
reduce/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:50355
Me.prototype.__iterate@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:36979
reduce@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:50309
e@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:135902
e/</<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:136067
Qe/r.__iterateUncached/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:14816
Me.prototype.__iterate@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:36979
Qe/r.__iterateUncached@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:14775
z@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:3696
N.prototype.__iterate@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:23555
toArray@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:47973
Me@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:10243
st@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:19098
map@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:50206
e/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:136042
reduce/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:50355
Me.prototype.__iterate@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:36979
reduce@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:50309
e@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:135902
value/a<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:202721
value@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:202700
updateClassInstance@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:281271
beginWork@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:282996
o@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:286941
a@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:287261
l@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:287499
_@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:290830
b@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:290558
h@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:289801
p@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:289211
enqueueSetState@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:279756
o.prototype.setState@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:285
o/</n</r.prototype.handleChange@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:190:38885
l@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:36:20198
d/</<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:3906
e.exports/</<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:190:52250
dispatch@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:36:23493
ee/</<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:182:17178
a@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:190:72320
M/<@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:190:72442
u@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:190:75567
 cms.js:182:84585

```

**- If the current behavior is a bug, please provide the steps to reproduce.**

- add a file collection type to config.yml
- try to edit it and the editor crashes

**- What is the expected behavior?**
it should be showing the editor interface

Hugo : 0.37.1
Node.js: 8.10.0
Netlify CMS: 1.3.5

**- Please link or paste your `config.yml` below if applicable.**

```yaml
backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", "name": "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Contacts"
        name: "contacts"
        file: "/data/contacts.yml"
        fields:
          - {label: Address, name: address, widget: string}
          - label: "Phone Numbers"
            name: phone_numbers
            widget: list
            fields:
            - {label: Number, name: "number", widget: string}
          - label: "Emails"
            name: emails
            widget: list
            fields:
            - {label: Email, name: "email", widget: string}
```

(edit by @tech4him1: fix formatting)
