### ISSUE TITLE
UNPUBLISHED_ENTRY_PERSIST_FAILURE after enabling publish_mode: editorial_workflow 

### ISSUE THREAD

**Issue by thauvette** [netlify/netlify-cms#1187]
**- Do you want to request a *feature* or report a *bug*?**

Bug
 
**- What is the current behavior?**

I had everything working as expected. I was able to sign in, create posts, and all my widgets worked correctly. Once I add publish_mode: editorial_workflow I started getting a UNPUBLISHED_ENTRY_PERSIST_FAILURE when attempting to save a post. 

This error in the CMS 
![screen shot 2018-03-23 at 10 41 42 am](https://user-images.githubusercontent.com/7917553/37832229-d1608338-2e86-11e8-82e1-5e85bf049bf8.png)

And in the console 
![screen shot 2018-03-23 at 10 41 07 am](https://user-images.githubusercontent.com/7917553/37832236-de07312c-2e86-11e8-967d-aeb0a2909656.png)

The 422 error makes me think the post is getting processed correctly but not being accepted. Although I've read sometimes 422's are mistaken for 400's. 

Also when trying to access the Workflow tab I get the following error...

![screen shot 2018-03-23 at 11 06 02 am](https://user-images.githubusercontent.com/7917553/37833624-84801e30-2e8a-11e8-99b4-b50a560fa88f.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

Gatsby site hosted on netlify.

static/admin/config.yml 

```
backend:
  name: git-gateway
  branch: cms

publish_mode: editorial_workflow
media_folder: "static/images/uploads" 
public_folder: "/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["title", "firstName", "lastName"], valueField: "title"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "authors"
    label: "Authors"
    folder: "src/authors"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "author"}
      - {label: "Full Name", name: "title", widget: "string"}
      - {label: "First Name", name: "firstName", widget: "string"}
      - {label: "Last Name", name: "lastName", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Profile Picture", name: "profilePicture", widget: "image"}
      - {label: "Email", name: "email", widget: "string"}
```

static/admin/index.html
```

<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>

  <!-- Include the styles for the Netlify CMS UI, after your own styles -->
  <link rel="stylesheet" href="https://unpkg.com/netlify-cms@^1.0.0/dist/cms.css" />
  <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>

</head>
<body>
  <!-- Include the script that builds the page and powers Netlify CMS -->
  <script src="https://unpkg.com/netlify-cms@^1.0.0/dist/cms.js"></script>
</body>
</html>
```

**- What is the expected behavior?**

I should be able to save post. 

**- Please mention your CMS, node.js, and operating system version.**

CMS - netlify-cms@1.3.5 
node v8.9.4 on Netlify
