### ISSUE TITLE
Can't edit pages in collection

### ISSUE THREAD

**Issue by martinmodighkarlsson** [netlify/netlify-cms#1190]
**- Do you want to request a *feature* or report a *bug*?**

Bug or handling error (by me :))

**- What is the current behavior?**

Can't edit pages in collection

**- What is the expected behavior?**

Edit at least body content in cms

**- Please link or paste your `config.yml` below if applicable.**

```
backend:
  name: git-gateway
  branch: development # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - label: "Post" # Used in routes, ie.: /admin/collections/:slug/edit
    name: "post" # Used in the UI, ie.: "New Post"
    folder: "content/_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Number", name: "number", widget: "number"}
      - {label: "LinkedIn", name: "linkedin", widget: "string", default: "https://www.linkedin.com/groups/XXXX"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - label: "Pages"
    name: "page"
    files:
      - label: "How"
        name: "how"
        file: "content/_pages/how.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Menu-title", name: "menu-title", widget: "string"}
          - {label: "Description", name: "discription", widget: "string"}
          - {label: "menu-title", name: "discription", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
```

Page looking like this, i.e. cms doesn't pull anything from the file but can find it: https://www.dropbox.com/s/fvdggzp3oc3txi5/Sk%C3%A4rmklipp%202018-03-23%2017.04.27.png?dl=0

https://www.dropbox.com/s/ryec38wrc8o7e2l/Sk%C3%A4rmklipp%202018-03-23%2017.05.19.png?dl=0
