### ISSUE TITLE
uploaded filenames not being slugified  

### ISSUE THREAD

**Issue by thauvette** [netlify/netlify-cms#1196]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
If I upload an image with a space in the filename, let's say "my picture.jpg" the following happens.

I get a 404 error in the console saying can't find " https://raw.githubusercontent.com/myusername/reponame/branch/path/to/my/uploads/my%20picture.jpg".
I can still "Choose Selected" on the un-previewable thumbnail and the image shows in the CMS preview with the file name "my picture.jpg". If I publish the post the image is saved as "/path/to/my/uploads/my picture.jpg" and not "/path/to/my/uploads/my%20picture.jpg". This, of course, doesn't work well with Gatsby. 
 
**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

I think the files should save as "my%20picture.jpg" not "my picture.jpg"

**- Please mention your CMS, node.js, and operating system version.**

CMS - netlify-cms@1.3.5
node v8.9.4

**- Please link or paste your `config.yml` below if applicable.**
```

backend:
  name: git-gateway
  branch: development

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Author - type to select", name: "author", widget: "relation", collection: "authors", searchFields: ["title", "firstName", "lastName"], valueField: "title"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image - filename must have NO spaces", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "authors"
    label: "Authors"
    folder: "src/authors"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "author"}
      - {label: "Full Name", name: "title", widget: "string"}
      - {label: "First Name", name: "firstName", widget: "string"}
      - {label: "Last Name", name: "lastName", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Profile Picture - filename must have NO spaces", name: "profilePicture", widget: "image"}
      - {label: "Email", name: "email", widget: "string"}
  - name: "investors"
    label: "Investors"
    folder: "src/investors"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "investor"}
      - {label: "Full Name", name: "title", widget: "string"}
      - {label: "First Name", name: "firstName", widget: "string"}
      - {label: "Last Name", name: "lastName", widget: "string"}
      - {label: "Bio", name: "bio", widget: "markdown" }
      - {label: "Picture - filename must have NO spaces", name: "picture", widget: "image", required: false}
```
