### ISSUE TITLE
Preview Template for File Collection

### ISSUE THREAD

**Issue by thekevinbrown** [netlify/netlify-cms#1197]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

When I use `CMS.registerPreviewTemplate` for my file collection it doesn't work.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Create a file collection.
Run `registerPreviewTemplate`

**- What is the expected behavior?**

I would expect to get my preview template rendered so that I can show previews for this content.

**- Please mention your CMS, node.js, and operating system version.**

Netlify CMS version 1.3.5
Node v8.9.4
OS X 10.13.3

**- Please link or paste your `config.yml` below if applicable.**
Excerpt:
```
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "about-us"
        label: "About Us Page"
        description: "Content for the About Us Page"
        file: "content/about-us-page.json"
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body_markdown", widget: "markdown"}
```

Then:
```javascript
CMS.registerPreviewTemplate('pages', PagesPreviewTemplate);
```

Any help anyone can provide would be greatly appreciated.
