### ISSUE TITLE
Using underscores in field names

### ISSUE THREAD

**Issue by thales17** [netlify/netlify-cms#1201]
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
When defining names in the config.yml using names with underscores Publishing generates the following error
```
unpkg.com/netlify-cms@1.3.5/dist/cms.js:182 Uncaught (in promise) Error: Collection must have a field name that is a valid entry identifier
    at unpkg.com/netlify-cms@1.3.5/dist/cms.js:182
    at unpkg.com/netlify-cms@1.3.5/dist/cms.js:182
    at String.replace (<anonymous>)
    at unpkg.com/netlify-cms@1.3.5/dist/cms.js:182
    at e.value (unpkg.com/netlify-cms@1.3.5/dist/cms.js:182)
    at unpkg.com/netlify-cms@1.3.5/dist/cms.js:182
    at unpkg.com/netlify-cms@1.3.5/dist/cms.js:190
    at unpkg.com/netlify-cms@1.3.5/dist/cms.js:36
    at t.<anonymous> (unpkg.com/netlify-cms@1.3.5/dist/cms.js:182)
    at r (unpkg.com/netlify-cms@1.3.5/dist/cms.js:190)
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
To reproduce create a field with a name that has an underscore in it.  For example: `- {label: "Meta Description", name: "meta_description", widget: "string"}`
**- What is the expected behavior?**
I would expect names with underscores to be allowed.

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: git-gateway
  branch: master


media_folder: "site/static/uploads"
public_folder: "/uploads"

collections:
  - name: "videos" # Used in routes, e.g., /admin/collections/blog
    label: "Story" # Used in the UI
    folder: "site/content/videos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "videos"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Title", name: "meta_title", widget: "string"}
      - {label: "Meta Description", name: "meta_description", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Youtube URL", name: "media", widget: "string"}
      - {label: "Hero Image", name: "hero", widget: "image"}
      - {label: "Abstract", name: "abstract", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
```
