### ISSUE TITLE
Failed to configure custom identity endpoint via config.yml

### ISSUE THREAD

**Issue by mdehollander** [netlify/netlify-cms#1213]
I am hosting a hugo site with netlify-cms on a custom hosting including it via a script tag. I would like to make use of the netlify identity service. Therefore a custom endpoint needs to be configured via `APIUrl`. I got some help via Gitter on this from @tech4him1 and @erquhart, but after that it was suggested to file a bug report.

I configured custom endpoint in the `config.yml`  like this:
```
backend:
  name: git-gateway
  identity_url: "https://www.my-netlify-site.com/.netlify/identity"
  gateway_url: "https://www.my-netlify-site.com/.netlify/git/github"
```

This should work according to the implementation (https://github.com/netlify/netlify-cms/blob/master/src/backends/git-gateway/implementation.js) and this should set the `APIurl` correctly. However, when rendered the endpoint is still going to the custom hosting and not to the endpoint at netlify raising an error: `Failed to load settings from /.netlify/identity`. @tech4him1 suggested that the `APIurl` is not correctly set when using the widget. 

@biilmann, can you have a look at it?
