### ISSUE TITLE
Markdown Character Limit in yaml file.

### ISSUE THREAD

**Issue by scwambach** [netlify/netlify-cms#1218]
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
Having some trouble with registerEditorComponent. After the page reloads, I lose the UI in the markdown editor.
**- If the current behavior is a bug, please provide the steps to reproduce.**
Create a Editor Component with markdown that is writing to a yaml file. If the return is longer than a certain character limit, it breaks the line and the Pattern no longer matches.
**- What is the expected behavior?**
For the line to not break unless I tell it to OR have the ability to change the character limit per line in my yaml file

**- Please mention your CMS, node.js, and operating system version.**

CMS 1.4.0
Node 6.10.2
Sierra 10.12.6

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: github
  repo: Redstitch/redstitch-website # Path to your GitHub repository
  branch: dev # Branch to update (master by default)

publish_mode: editorial_workflow

media_folder: "/source/images/uploads"
public_folder: "/images/uploads"

collections:
  ###########################################
  ################## PAGES ##################
  ###########################################

  - name: "pages" # Used in routes, e.g., /admin/collections/pages
    label: "Pages" # Used in the UI
    editor:
      preview: true
    folder: "data/pages" # The path to the folder where the documents are stored
    format: yaml
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Custom URL", name: "custom_slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Featured Image"
        name: "og_image"
        widget: "image"

      - label: "Aspot"
        name: "aspot"
        widget: "object"
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Sub Heading", name: "sub_paragraph", widget: "text"}
          - {label: "Text Large", name: "txt_lrg", widget: "boolean", default: false}
          - {label: "Text Small", name: "txt_sml", widget: "boolean", default: false}
      - label: "Sections"
        name: "sections"
        widget: "list"
        fields:
          - label: "Section Content"
            name: "section_content"
            widget: "object"
            fields:
              - label: "Section Image"
                name: "float_image"
                widget: "image"
              - {label: "Content", name: "content", widget: "markdown"}
```

**- Example Editor Component**
```js
CMS.registerEditorComponent({
  // Internal id of the component
  id: "main-heading",
  // Visible label
  label: "Main Heading",
  // Fields the user need to fill out when adding an instance of the component
  fields: [{
    name: 'heading',
    label: 'Heading',
    widget: 'string',
  }, {
    name: 'bg_text',
    label: 'Background Text',
    widget: 'string',
  }],
  // Pattern to identify a block as being an instance of this component
  pattern: /^<div class="main-heading"><p class="bg-heading" style="font-size: 57px;">((.|\n)*)<\/p><h2>((.|\n)*)<\/h2><\/div>$/,
  // Function to extract data elements from the regexp match
  fromBlock: function(match) {
    return {
      heading: match[1],
      bg_text: match[2],
    };
  },
  // Function to create a text block from an instance of this component
  toBlock: function(obj) {
    return '<div class="main-heading"><p class="bg-heading" style="font-size: 57px;">' + obj.bg_text + '</p><h2>' + obj.heading + '</h2></div>';
  },
  // Preview output for this component. Can either be a string or a React component
  // (component gives better render performance)
  toPreview: function(obj) {
    return (
      '<div class="main-heading"><p class="bg-heading" style="font-size: 57px;">' + obj.bg_text + '</p><h2>' + obj.heading + '</h2></div>'
    );
  }
});
```
