### ISSUE TITLE
Regression: Image card with thumbnails not showing after upload

### ISSUE THREAD

**Issue by buzzlightyear182** [netlify/netlify-cms#1220]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug

**- What is the current behavior?**
When I upload an image, page needs to be reloaded in order for image block to appear. I can see the photo is uploaded when the button changes back to "Upload New". Deleting an image works fine as expected. Attached is a screenshot of the errors in console. Not sure why API.js is unauthorized as I can login and publish articles already.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Code is hosted on a public repo. I used `<script src="https://unpkg.com/netlify-cms@^1.4.0/dist/cms.js"></script>` and `<link rel="stylesheet" href="https://unpkg.com/netlify-cms@^1.4.0/dist/cms.css" />` in admin/index.html
Upload image in Media

**- What is the expected behavior?**
When image is uploaded, thumbnail and file name should appear once done.

**- Please mention your CMS, node.js, and operating system version.**

Netlify v1.4.0

**- Please link or paste your `config.yml` below if applicable.**
<img width="806" alt="screen shot 2018-04-01 at 3 10 31 pm" src="https://user-images.githubusercontent.com/7237741/38170732-3522775c-35bf-11e8-9a95-699e47dd2301.png">

config.yml
``` 
backend:
  name: git-gateway
  branch: master # Branch to update (master by default)
  
media_folder: "source/blog/images" # Folder where user uploaded files should go
public_folder: "/blog/images" # CMS now knows 'source' is the public folder and will strip this from the path

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Create News Article" # Used in the UI, ie.: "New Post"
    folder: "source/blog/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Category", name: "category", widget: "hidden", default: "news"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Featured Image", name: "cover_image", widget: "image"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Summary", name: "metadescription", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "learning-zone" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Create Learning Zone Article" # Used in the UI, ie.: "New Post"
    folder: "source/blog/learning-zone" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Category", name: "category", widget: "hidden", default: "learning-zone"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Featured Image", name: "cover_image", widget: "image"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
```
