### ISSUE TITLE
Read and edit my previously saved .md files

### ISSUE THREAD

**Issue by ThiagoMiranda** [netlify/netlify-cms#1260]
**- Do you want to request a *feature* or report a *bug*?**
Not getting my previously local collections on the /admin/ tab

**- What is the current behavior?**
I have a /admin/collections tab and when I click on a collection it shows an error "Sorry!
There's been an error - please report it!". I´m not seeing my current images too

**- If the current behavior is a bug, please provide the steps to reproduce.**
```yaml
collections: 
  - name: home
    label: Página inicial
    folder: src/pages/banco
    create: true
    fields: 
      - { label: Section, name: section, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: date }
      - { label: Path, name: path, widget: string }
      - { label: Template, name: template, widget: string }
      - { label: Body, name: body, widget: markdown }

  - name: product
    label: Produto
    files: 
      file: src/pages/produto/index.md
      create: true
      fields: 
        - { label: Section, name: section, widget: string }
        - { label: Title, name: title, widget: string }
        - { label: Date, name: date, widget: date }
        - { label: Path, name: path, widget: string }
        - { label: Template, name: template, widget: string }     
        - { label: Body, name: body, widget: markdown } 
```

Index.md on the Product page for example:
```markdown
---
section: Loans
title: Loans Title
date: "2015-05-28T22:40:32.169Z"
path: "/produto"
template: "content"
---

## Title 1
```

**- What is the expected behavior?**
Read and edit my current saved .md files and see all my image files

**- Please mention your CMS, node.js, and operating system version.**
Using GatsbyJS + node v8.10 + Windows 10

**- Please link or paste your `config.yml` below if applicable.**
```yaml
backend:
  name: test-repo
  branch: netlify-cms

media_folder: src/images/

collections: 
  - name: home
    label: Página inicial
    folder: src/pages/banco
    create: true
    fields: 
      - { label: Section, name: section, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: date }
      - { label: Path, name: path, widget: string }
      - { label: Template, name: template, widget: string }
      - { label: Body, name: body, widget: markdown }

  - name: product
    label: Produto
    files: 
      file: src/pages/produto/index.md
      create: true
      fields: 
        - { label: Section, name: section, widget: string }
        - { label: Title, name: title, widget: string }
        - { label: Date, name: date, widget: date }
        - { label: Path, name: path, widget: string }
        - { label: Template, name: template, widget: string }     
        - { label: Body, name: body, widget: markdown } 
```

**Comment by talves** [comment]
@ThiagoMiranda you will not be able to use the `test-repo` for the backend type. If this is a github repo use `github` or if you enabled identity within your site on Netlify you can use git-gateway

You can try to get some help in the community at also https://gitter.im/netlify/NetlifyCMS

**Comment by tech4him1** [comment]
File collections need to contain an array of files:
Corrected example:
```yaml
  - name: product
    label: Produto
    files:
      - name: index
        label: Produto Index
        file: src/pages/produto/index.md
        ...
```
