### ISSUE TITLE
Error: Unrecognized front-matter format. + TypeError: e.commit is undefined

### ISSUE THREAD

**Issue by ouarez** [netlify/netlify-cms#1272]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**- Do you want to request a *feature* or report a *bug*?**
Report a bug.

**- What is the current behavior?**
Nothing works. Maybe I'm just tired but I can't get Netlify to work and keep running into these 2 errors.

**- If the current behavior is a bug, please provide the steps to reproduce.**
- Start up a fresh Jekyll Project.
- Add the Netlify CMS code to the /admin folder (config.yml + index.html)
- add the required scripts to the default layout
- create a new repo with Github, launch the site with Netlify
- visit mywebsite.netlify.com/admin, log in

**- What is the expected behavior?**

I keep running into strange error console messages and 404 network errors. I can't post new pages, and I can't upload images. Basically, nothing works and I don't understand the errors the console has thrown at me.

Thinking I must have done a mistake setting up Netlify CMS, I cloned one of my previous projects (which is also using Netlify CMS, and everything is working fine) and deployed it using Netlify, with a temporary URL.

When I log in to this new, freshly cloned website, I get the same errors.. even though the code is identical as my currently working project.

I'm stumped, since the code and configuration are identical. Yet, on any freshly deployed Netlify websites, the Netlify CMS isn't working for me, at all.

I'm going to try adding a custom domain to these new instances, since that is the only difference I can think of between the new projects and the old, working one.

Please take a look at the included screenshots for the error messages.

**INFO:**

Netlify CMS version 1.5.0
Client-side Node: v8.11.0
Netlify-side Node: node v8.11.1 (npm v5.6.0)
OS: Fedora 26 (x86-64)

**- Please link or paste your `config.yml` below if applicable.**

(I don't think this is an issue with the config.yml, but here it is just in case I made an obvious mistake?)

```
backend:

  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img"

collections:

  - name: "special-pages"
    label: "Pages uniques"
    delete: false # Prevent users from deleting documents in this collection
    files:
      - name: "home"
        file: "index.md"
        label: "Éditer la page d'accueil"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Paragraphe d'introduction", name: "home_intro", widget: "markdown"}
          - {label: "Paragraphe pour matériel premier soins", name: "home_materiel", widget: "markdown"}
          - {label: "Lien vers matériel premier soins", name: "link_materiel", widget: "string"}
          - {label: "Paragraphe pour formations", name: "home_formations", widget: "markdown"}
          - {label: "Lien vers formations", name: "link_formations", widget: "string"}
```
