### ISSUE TITLE
User interface non-user responsive

### ISSUE THREAD

**Issue by ccsource** [netlify/netlify-cms#1277]
**- Do you want to request a *feature* or report a *bug*?**

bug, I think.

**- What is the current behavior?**

It looks like (yes, **looks like**, since I haven't look into source) the Netlify CMS admin panel have locked the UI to 9:16, which looks well on a PC but pretty suck on mobile devices (or at least on my iPhone 5)

**- If the current behavior is a bug, please provide the steps to reproduce.**

No idea, really since most time the site should be responsive (even content stack on each other or content being a mess, but at least it should be in screen border), the only possibility is they set width+height for some element.

**- What is the expected behavior?**

For mobile UI design, it's really an opinion only, I'll suggest merge the top-nav (which shows content and media) and left-nav (the collection one) into one nav and hide it on mobile (the click to display nav).

For editing part, you can but a arrow on top-left corner which can switch to preview (or vice-versa).

**- Please mention your versions where applicable.**

Netlify CMS version: [1.0.3](https://unpkg.com/netlify-cms@^1.0.3/dist/cms.js)
Browser version: Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

Node.JS version: node v8.11.1 (npm v5.6.0)
Operating System: no idea (using Netlify CDN)

**- Please link or paste your `config.yml` below if applicable.**

I think it doesn't matter much, but here is it.

```
backend:
  name: git-gateway
  branch: site

media_folder: "files"
public_folder: "/files"

display_url: https://ccsource.org

slug:
  encoding: "unicode"

collections:
  - name: "story"
    label: "Story"
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "excerpt", widget: "string", required: false}
      - label: "Publish date"
        name: "date"
        widget: "date"
        default: ""
        format: "YYYY-MM-DD"
      - {label: "Article", name: "body", widget: "markdown", required: true}
      - label: "Tag"
        name: "tag"
        widget: "list"
        allow_add: true
        default: ["story"]
```
