### ISSUE TITLE
CSS of the authentication button text

### ISSUE THREAD

**Issue by severo** [netlify/netlify-cms#1316]
**- Do you want to request a *feature* or report a *bug*?**

Report a bug

**- What is the current behavior?**

The text "Login with GitHub" is showing outside of the button.

![captura de pantalla de 2018-04-24 07-08-02](https://user-images.githubusercontent.com/1676121/39183574-7fe70948-478e-11e8-881a-7a60d5828ca6.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

In a jekyll website (even if I understand that being jekyll has no importance), create the `admin/config.yml` file with the `github` backend:

```
backend:
  name: github
  repo: USER/REPO   # Path to your Github repository
  branch: master    # Branch to update
  base_url: https://URL # Path to ext auth provider

publish_mode: editorial_workflow
media_folder: "assets/img/" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
```

and publish with

```
bundle exec jekyll serve
```

**- What is the expected behavior?**

The text should be placed inside the button. I imagine this is due to the GitHub icon (if you delete the "span" tag with your browser's developer tools, the text goes back inside the button)

**- Please mention your versions where applicable.**

Netlify CMS version: 1.0.0
Browser version: Firefox Developer Edition 60.0b14, and the same with Chromium Version 62.0.3202.89

Node.JS version: v6.12.2
Operating System: Debian buster

**- Please link or paste your `config.yml` below if applicable.**

```
backend:
  name: github
  repo: USER/REPO   # Path to your Github repository
  branch: master    # Branch to update
  base_url: https://URL # Path to ext auth provider

publish_mode: editorial_workflow
media_folder: "assets/img/" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
```
