### ISSUE TITLE
How to deal with collections with nested properties

### ISSUE THREAD

**Issue by dioptre** [netlify/netlify-cms#1326]
*feature*

**- What is the current behavior?**
https://www.netlifycms.org/docs/collection-types/

**- What is the expected behavior?**
Maybe use 
name: "user.firstname", from example?

**Comment by tech4him1** [comment]
Right now you will need to use the `object` widget:
```yaml
fields:
  - label: User
    name: user
    widget: object
    fields:
      - {label: "First Name", name: firstname, widget: string}
```

It is not yet possible to nest without having to use the object widget, see https://github.com/netlify/netlify-cms/issues/595 for details.
