### ISSUE TITLE
Feature Request: Switch Widget

### ISSUE THREAD

**Issue by knpwrs** [netlify/netlify-cms#1354]
Maybe there's a way to accomplish what I'm looking for already, but I can't figure it out. I have pages which are composed of `block`s. Each `block` can be one of several widgets. I would like to be able to switch between those widgets on the admin page. Consider the following configuration representing a `list` of `block`s:

```yaml
---
collections:
  - name: page
    label: Page
    folder: content/pages
    extension: yml
    create: true
    fields:
      - label: Page Title
        name: title
        widget: string
      - label: Page Content
        name: content
        widget: list
        field:
          label: Block
          widget: switch
          widgets:
            - type: image
            - type: markdown
            - type: custom-widget
```

A page edited by the above might look like the following:

```yaml
---
title: Foo Bar Banana
content:
  - widget: image
    value: foo/bar/banana.png
  - widget: markdown
    value: bears and bananas
  - widget: custom-widget
    value: some value
  - widget: markdown
    value: other bears and other bananas
  - widget: image
    value: i/think/you/get/it.jpg
```

The key part being that you can add and reorder `block`s, it will default its widget to the first one in the configuration, but the user can change the type of widget represented by that block.

Is this currently possible? Would it need to be implemented and if so would the netlify team be interested in either implementing this or accepting a PR?
