### ISSUE TITLE
label_singular somehow overrides the default "plural" label

### ISSUE THREAD

**Issue by papandreou** [netlify/netlify-cms#1397]
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

When a field using the `list` widget has a `label_singular` defined, the regular `label` is not displayed when the list has 0 or 2+ items.

![screen shot 2018-05-31 at 16 54 41](https://user-images.githubusercontent.com/373545/40790114-6101d584-64f4-11e8-9887-b6524d661607.png)
![screen shot 2018-05-31 at 16 54 50](https://user-images.githubusercontent.com/373545/40790120-64453146-64f4-11e8-9f6e-d6deb64be648.png)
![screen shot 2018-05-31 at 16 54 59](https://user-images.githubusercontent.com/373545/40790124-65f2cc42-64f4-11e8-85ce-d0b988864c22.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a new item in the collection
2. Observe that it says "0 foobar"
3. Add a "Foobar" by clicking the `Add foobar +` button
4. Observe that it says "1 foobar"
5. Add another one
6. Observe that it says "2 foobar"

**- What is the expected behavior?**

That the `label_singular` is used only when there is exactly one item, so that it would say "0 foobars" and "2 foobars".

**- Please mention your versions where applicable.**

Netlify CMS version: 1.8.4
Browser version: Chrome 66.0.3359.181/OSX

**- Please link or paste your `config.yml` below if applicable.**

```yml
collections:
  -
    name: mycollection
    label: My collection
    folder: thefolder
    slug: "{{id}}"
    create: true
    fields:
      -
        name: 'foobars'
        label: 'Foobars'
        label_singular: 'Foobar'
        widget: 'list'
        fields:
          -
            name: 'foobar'
            label: 'Foobar'
            widget: 'string'
```
