### ISSUE TITLE
API Overhaul: Widgets

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#1409]
Placeholder, reference: https://github.com/netlify/netlify-cms/pull/1131#issuecomment-386804125

**Comment by talves** [comment]
@erquhart I like this approach. Allows for extensible widgets without breaking prior widgets in the future also.

**Comment by erquhart** [comment]
Came back to this with fresh eyes while considering #2037. We've talked about the concept of [events](https://github.com/netlify/netlify-cms/issues/1348) and also dynamic defaults as mentioned in the OP. We can combine these two concepts for widgets.

**Example**
```yaml
fields:
  - { name: id, widget: id }
  - name: publish_date
    widget: datetime
    update_on: ['publish_initial']
    required: false
  - name: last_modified_at
    widget: datetime
    visible: false
    update_on: ['publish']
```

Quick breakdown of what these keys would mean:

**update_on**: list of events to automatically update the value. A widget would need to opt in to supporting this by providing a function outside of the React component. I imagine the function would receive the event name, the entry object, and maybe some other things.

**visible**: the field doesn't appear in the editor at all, and so would only be populated via `update_on`.

We could also provide an `allow_edit` property so a field can be made read only, if that really feels necessary. Not certain it is.

### Defaults
Lastly, the ID field demonstrates another concept - that widgets should be able to set their own defaults. I shouldn't need to do this every time for the ID widget:

```yaml
- name: id
  widget: id
  update_on: ['create']
  visible: false
```

Thoughts? Better than dynamic defaults?
