### ISSUE TITLE
Having issues with Phenomic integration to Netlify CMS

### ISSUE THREAD

**Issue by nickeblewis** [netlify/netlify-cms#142]
I have been trying to set up Netlify with my Phenomic project and found some instructions at [https://phenomic.io/docs/usage/cms/netlify/](https://phenomic.io/docs/usage/cms/netlify/).

- I created an "admin" folder under the root of my project
- Copied and pasted the index.html code into a file of the same name
- Configured my "config.yml" as follows

```yaml
backend:
  name: github-api
  repo: nickeblewis/headforcode # owner/repo
  branch: master # master

public_folder: "content"
media_folder: "content/assets"

collections:
  - name: "post"
    label: "Post"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime"}
```
- I also set up my webpack file as instructed too

**- What is the current behavior?**

Having set up my authentication, I committed my changes and pushed them to Netlify. The first time I visited [https://headforcode.netlify.com](https://headforcode.netlify.com) it displayed the user interface but was unable to load my posts.

Strangely now when I try, the CMS doesn't load at all??? Weird

**- Please mention your node.js, and operating system version.**

6.9.3

**Comment by MoOx** [comment]
Poke @xuopled

**Comment by cassiozen** [comment]
Hi @nickeblewis & @MoOx. 

Your config looks perfect. 
This doc you mentioned is pointing to the Ember's version of the CMS. We're currently porting it over to React, and we're publishing the assets right now. 

As soon as I get them, I'll ask you to change the URLs and try again.

**Comment by cassiozen** [comment]
We're now publishing the Netlify to npmjs and unpkg. Unpkg is a CDN for javascript modules, and it let's you point to semantic versions of files (so backwards-compatible bug fixes will loaded as they're made available).

Please point change the asset URLs in your HTML file for:
https://unpkg.com/netlify-cms@^0.1.1/dist/cms.css
https://unpkg.com/netlify-cms@^0.1.1/dist/cms.js

**Comment by nickeblewis** [comment]
Ok thanks @cassiozen - going to give that a go now and shall let you know how I get on.

**Comment by nickeblewis** [comment]
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Content Manager</title>
    <link rel="stylesheet" href="https://unpkg.com/netlify-cms@^0.1.1/dist/cms.css" />
  </head>
  <body>
    <script src="//cms.netlify.com/assets/vendor.js"></script>
    <script src="https://unpkg.com/netlify-cms@^0.1.1/dist/cms.js"></script>
  </body>
</html>
```

I have now changed it to the above, do I still require the vendor.js file?

**Comment by nickeblewis** [comment]
@cassiozen thanks for this, still having some teething problems. I do now see a spinner with loading configuration message. My browser console reports that the vendor.js file cannot be found, so guessing that I can probably do away with that. It also reports:

Uncaught (in promise) Backend not found: github-api

Please advise...

**Comment by cassiozen** [comment]
Humm, try changing github-api to simply "github". I guess this was misspelled in the porting...

**Comment by cassiozen** [comment]
Oh, and you don't need this vendor asset: 

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Content Manager</title>
    <link rel="stylesheet" href="https://unpkg.com/netlify-cms@^0.1.1/dist/cms.css" />
  </head>
  <body>
    <script src="https://unpkg.com/netlify-cms@^0.1.1/dist/cms.js"></script>
  </body>
</html>
```

**Comment by nickeblewis** [comment]
Progress!! I now can see the CMS UI, it prompted me to authenticate with Github and that worked. The UI shows with a spinner in the middle and a message stating that it may take several minutes.... however it never finishes, just gets stuck in a loop... 

Anything else I can try?

**Comment by cassiozen** [comment]
Is your content really big? Like, hundreds and hundreds of files of content? 
On the console, does it show any errors?

**Comment by nickeblewis** [comment]
Yes it does, we are seeing a 404 error and it's because it is trying to find - https://api.github.com/repos/nickeblewis/headforcode/contents/content/blog?ref=master

Now the problem has to be the "contents" part of the URL, if I took that out, I think this will then work

**Comment by nickeblewis** [comment]
and nope, my content isn't too large yet, less than 100 pages

**Comment by cassiozen** [comment]
The "/contents" is part of the git api, so it should be there. 

Is this the Repo you're using? https://github.com/nickeblewis/headforcode

I'll try running it here...

**Comment by nickeblewis** [comment]
Yes - that is the correct repo

**Comment by cassiozen** [comment]
Oh, wait a minute. I guess It's a configuration problem  -  You're pointing to a `/content/blog` folder, but there isn't such folder. 

Maybe it should be `/content/posts` instead?

**Comment by nickeblewis** [comment]
Ah yes - you are right - Ok, we have moved on now, the error no longer occurs but in the browser console a new error is being trapped:

cms.js:68 Uncaught (in promise) TypeError: Cannot read property 'split' of undefined(…)

**Comment by cassiozen** [comment]
We have a "card" interface in place. It tries to infer what content to show, but it is filing for some use cases (including yours).

Please try adding a "card" configuration. I got it working with this config for your project:

```yaml
backend:
  name: github
  repo: nickeblewis/headforcode # Path to your Github repository
  branch: master # Branch to update (master by default)

public_folder: "content"
media_folder: "content/assets" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
    card: {type: "alltype", text: "title"}

```
