### ISSUE TITLE
[Bug] CMS on Gitlab not displaying photos in media assets

### ISSUE THREAD

**Issue by namzo** [netlify/netlify-cms#1436]
I just setup Netlify CMS on my site on Gitlab, I noticed that in the admin, the media page doesn't show my pictures.
<img width="672" alt="screen shot 2018-06-14 at 6 56 22 am" src="https://user-images.githubusercontent.com/1392665/41392404-9aff9e54-6fa0-11e8-9e00-229b26e058f5.png">

When I try to view the image, I noticed the url isn't encoded properly:
<img width="500" alt="screen shot 2018-06-14 at 6 56 35 am" src="https://user-images.githubusercontent.com/1392665/41392473-effce718-6fa0-11e8-973f-b7f8caf38c4e.png">

Steps to reproduce:
- Add Netlify CMS to existing Gitlab site (Not using NPM)
- View the Media assets

**CMS Version**
Netlify CMS version: 1.9.0
Browser version: Chrome 67

**Here's my config file**
```yaml
backend:
  name: gitlab
  repo: namzo/ernestojeh.com
  branch: master
  site_domain: ernestojeh.com

display_url: https://ernestojeh.com
media_folder: "img/post" # Media files will be stored in the repo under images/uploads

collections:
  - name: "writing" # Used in routes, e.g., /admin/collections/blog
    label: "Writing" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
```
Thanks.
