### ISSUE TITLE
Edit translations files from netlify-cms admin

### ISSUE THREAD

**Issue by xuopled** [netlify/netlify-cms#144]
For my translations, I have some `YAML` files with this format : 

``` yml
locale: "en"

messages:
  homepage:
    netlify-cms: "Netlify CMS is promising !"

```

Do you think it could be possible to edit translations directly from `netlify-cms` ?

Thank you

**Comment by cassiozen** [comment]
Hi,

The Netlify CMS does support something we call "Single File Collections", which means multiple data on a single `yaml` or `json` file.  This is really well suited for things like settings. You could try using it for your locale files, but you need to define all fields in your configuration.

You can read more about the config file on the README, but I drafted here a possible configuration for a locale file:

```yaml

collections: 
  - ... # All your collections. Omitted for brevity
  - name: "translations"
    label: "Translations"
    files:
      - name: "english"
        label: "English"
        file: "_locales/en.yaml"
        fields:
          - label: "Messages"
            name: "messages"
            widget: "object"
            fields:
               - {label: "Netlify CMS Header", name: "netlify-cms", widget: "string"}
```
