### ISSUE TITLE
Issue seeing the admin interface when building a sample site and deploying on gitlab 

### ISSUE THREAD

**Issue by marcos-abreu** [netlify/netlify-cms#1440]
**- Do you want to request a *feature* or report a *bug*?**
BUG

**- What is the current behavior?**

I can't see the admin interface after creating a sample site using the 'Deploy to Netlify' button available on the documentation for Netlify CMS, and choosing to deploy to Gitlab. 

**- If the current behavior is a bug, please provide the steps to reproduce.**
- access the Netlify CMS Docs (https://www.netlifycms.org/docs/start-with-a-template/)
- click on the `Deploy to Netlify` button under `Gatsby Site Starter`
- on the first screen click on the `connect to Gilab`
- on the second step (after authenticating with gitlab) choose the repo name and click on the `Save & Deploy` button
- After the project is deployed, I got an email with the invitation link to create a user for the project. And then clicked on the `Accept Invite` link on the email
- when prompted create a password for the account, create one and click on the `Sign up` button
- instead of seeing the admin interface, the screen keeps the `Login with Netlify Identity` and briefly shows an error message `undefined`

**- What is the expected behavior?**
- I should see the admin interface for the website.

**- Please link or paste your `config.yml` below if applicable.**

```
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
```
