### ISSUE TITLE
 Cannot read property 'src' of undefined in CMS

### ISSUE THREAD

**Issue by Dwaxy** [netlify/netlify-cms#1461]
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
I'm making a simple blog with Gatsby and was tinkering around with image paths for my posts and ran into some knowin problems (see [this](https://github.com/netlify/netlify-cms/issues/843)). I was trying to make Gatsby process the images used with Netlify CMS with the help of some [plugins](https://www.gatsbyjs.org/packages/gatsby-remark-relative-images/?=images). I also implemented [feature images](https://codebushi.com/gatsby-featured-images/). I ran into some bugs, and after reverting the file structure down to the default paths, those bugs still persisted. They are:

> Failed to load entries: TypeError: Cannot read property 'src' of undefined (cms.js:791 in the console)

> Failed to persist entry: TypeError: Cannot read property 'src' of undefined (after I published a post)

Both of these were error popups in the CMS, but the build on Netlify still ran and gave me

> error gatsby-node.js returned an error 
   GraphQLError: Cannot query field "allMarkdownRemark" on type "RootQueryType".

The errors in the console let me to code that seemed to have something to do with image caching. I'm new to all this so its probably a simple problem but the paths in my config should be fine.

My admin config

```
backend:
  name: git-gateway
  branch: master

# media_folder: src/pages/blog/img
# public_folder: src/pages/blog/img

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featurte Image", name: "feature image", widget: image}

```
package.json

```
 "name": "gatsby-starter-netlify-cms",
  "description": "Example Gatsby, and Netlify CMS project",
  "version": "1.1.3",
  "author": "Austin Green",
  "dependencies": {
    "gatsby": "^1.9.272",
    "gatsby-image": "^1.0.54",
    "gatsby-link": "^1.6.44",
    "gatsby-plugin-netlify": "^1.0.19",
    "gatsby-plugin-netlify-cache": "^0.1.0",
    "gatsby-plugin-netlify-cms": "^1.0.12",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-sass": "^1.0.26",
    "gatsby-plugin-sharp": "^1.6.48",
    "gatsby-remark-images": "^1.5.67",
    "gatsby-remark-relative-images": "^0.1.2",
    "gatsby-source-filesystem": "^1.5.39",
    "gatsby-transformer-remark": "^1.7.44",
    "gatsby-transformer-sharp": "^1.6.27",
    "lodash": "^4.17.5",
    "lodash-webpack-plugin": "^0.11.4",
    "netlify-cms": "^1.7.0",
    "prop-types": "^15.6.2",
    "react": "^16.4.1",
    "react-helmet": "^5.2.0",
    "uuid": "^3.2.1"
  },
```

Gatsby config

```
module.exports = {
  siteMetadata: {
    title: 'Gatsby + Netlify CMS Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sass',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/img`,
        name: 'images',
      },
    },
    'gatsby-plugin-sharp',
    'gatsby-transformer-sharp',
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
        
           // go before gatsby-remark-images
          {
            resolve: `gatsby-remark-relative-images`,
          },
          {
            resolve: `gatsby-remark-images`,
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 590,
            },
          },
        
        ],
      },
    },
    {
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
        modulePath: `${__dirname}/src/cms/cms.js`,
      },
    },
    'gatsby-plugin-netlify-cache',
    'gatsby-plugin-netlify', // make sure to keep it last in the array
  ],
}
```

graphQL query

```
export const pageQuery = graphql`
  query IndexQuery {
    allMarkdownRemark(
      sort: { order: DESC, fields: [frontmatter___date] },
      filter: { frontmatter: { templateKey: { eq: "blog-post" } }}
    ) {
      edges {
        node {
          excerpt(pruneLength: 400)
          id
          fields {
            slug
          }
          frontmatter {
            title
            templateKey
            date(formatString: "MMMM DD, YYYY")
            tags
            featuredImage {
               childImageSharp{
                    sizes(maxWidth: 1000) {
                        ...GatsbyImageSharpSizes
                    }
                }
            }
            
          }
        }
      }
    }
  }
`
```

Hopefully this is just me not knowing what I'm doing. Its likely. I would appreciate some help, as I love your services and want to know how to use them right <3

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
I can make new blog posts in the CMS without errors and have it build fine

**- Please mention your versions where applicable.**

Netlify CMS version: 1.9.2
Browser version: Google Chrome 67.0.3396.87

Node.JS version: 8.6.0
Operating System: macOS Sierra 10.12.6

**- Please link or paste your `config.yml` below if applicable.**

**Comment by ButterBridge** [comment]
`
# media_folder: src/pages/blog/img
# public_folder: src/pages/blog/img
`

Should these be as they would appear in the public folder after the build, i.e.
`
# media_folder: blog/img
# public_folder: blog/img
`

?

**Comment by tomrutgers** [comment]
@ButterBridge 
`media_folder` is the location of the folder within the repo, in this case `src/pages/blog/img`. 
`public_folder` is where the image folder is located after the build: `blog/img`

**Comment by tulsileathers** [comment]
@Dwaxy I'm having the same problem. Did you have figure out a solution?

**Comment by tech4him1** [comment]
@tulsileathers If you can, try upgrading to Gatsby v2 and Natlify CMS v2.

**Comment by lol-russo** [comment]
I'm having the same problem with Gatsby v2 and Netlify CMS v2

**Comment by Dwaxy** [comment]
Hello everyone, sorry to keep you waiting. I solved this somewhere along the line. Here is what I have now and its working fine. Note that I am using the plugin mentioned above, and have followed its instructions. 

config (used as is): 
```
backend:
  name: git-gateway
  branch: master

# media_folder: static/img
# public_folder: /img

media_folder: src/pages/img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Type", name: "type", widget: "string"}
      # - {label: "FeaturedImage", name: "featuredImage", widget: "image"}
      - label: "FeaturedImage"
        name: "featuredImage"
        widget: "custompathimage"
        customMediaPath: "../img/"
        rawMediaPath: "https://github.com/Dwaxy/my-blog/tree/master/src/pages/img"
```

versions & dependencies:
```
"dependencies": {
    "autoprefixer": "^9.1.0",
    "browserslist": "^4.0.1",
    "gatsby": "^1.9.272",
    "gatsby-image": "^1.0.54",
    "gatsby-link": "^1.6.44",
    "gatsby-plugin-feed": "^1.3.25",
    "gatsby-plugin-google-analytics": "^1.0.31",
    "gatsby-plugin-mailchimp": "^2.2.3",
    "gatsby-plugin-netlify": "^1.0.19",
    "gatsby-plugin-netlify-cache": "^0.1.0",
    "gatsby-plugin-netlify-cms": "^1.0.12",
    "gatsby-plugin-postcss-sass": "^1.0.22",
    "gatsby-plugin-purify-css": "^2.2.1",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-robots-txt": "^1.1.0",
    "gatsby-plugin-sass": "^1.0.26",
    "gatsby-plugin-sharp": "^1.6.48",
    "gatsby-plugin-sitemap": "^1.2.25",
    "gatsby-remark-images": "^1.5.67",
    "gatsby-remark-relative-images": "^0.1.2",
    "gatsby-source-filesystem": "^1.5.39",
    "gatsby-transformer-remark": "^1.7.44",
    "gatsby-transformer-sharp": "^1.6.27",
    "lodash": "^4.17.5",
    "lodash-webpack-plugin": "^0.11.4",
    "netlify-cms": "^1.9.3",
    "prop-types": "^15.6.2",
    "react": "^16.4.1",
    "react-helmet": "^5.2.0",
    "uuid": "^3.3.2"
  },
```

From this making a query was straightforward. Hurt my head and my desk a bit though. Hope this is helpful to someone. 

(I have another project using Gatsby & Netlify v2, this setup solved the issue which is still there)
