### ISSUE TITLE
Generated commit messages do not use label_singular

### ISSUE THREAD

**Issue by papandreou** [netlify/netlify-cms#1473]
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

When publishing a new item in a collection that has a `label_singular` defined, the `label` is used to generate the commit message, even though only one item is being created or updated.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Define a collection with a `label_singular` in config.yml:

```yaml
collections:
  -
    name: foobars
    label: Foobars
    label_singular: Foobar
    folder: foobars
    create: true
```

2. Create a new Foobar and publish it.

Observe that the resulting commit message is `Create Foobars "...the id..."`

**- What is the expected behavior?**

That the commit message uses `label_singular` so the commit message ends up as `Create Foobar "...the id..."`

**- Please mention your versions where applicable.**

Netlify CMS version: 1.9.2
Browser version: Chrome 67.0.3396.87/OSX

Node.JS version: 10.4.1
Operating System: Mac OSX 10.13.5 (High Sierra)
