### ISSUE TITLE
Can't choose date by mouse when Firefox accessibility tools enabled

### ISSUE THREAD

**Issue by renestalder** [netlify/netlify-cms#1505]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When Firefox's accessibility feature to navigate via keyboard is enabled, using `datetime` widget, date is not always consistent selectable with the mouse cursor in Firefox. When clicking a date, sometimes the current date is included into the text box, sometimes nothing is included in the text box.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a collection folder type that has two datetime fields.

Example:

```yml
collections:
  - label: "Veranstaltungen"
    name: "veranstaltungen"
    folder: "content/_veranstaltungen"
    slug: "{{slug}}-{{minute}}{{year}}{{second}}"
    create: true
    extension: "md"
    fields:
      - {label: "Name der Veranstaltung", name: "title", widget: "string", required: true}
      - {label: "Beginnt am", name: "datetimeStart", widget: "datetime"}
      - {label: "Endet am", name: "datetimeEnd", widget: "datetime"}
      - {label: "Kurzbeschreibung", name: "description", widget: "text", pattern: ['.{1,250}', "1 bis 250 Zeichen. Wird auf Social Media Platformen angezeigt."], required: true}
      - {label: "Beschreibung", name: "body", widget: "markdown", required: true}
      - {label: "Vorschaubild (optional)", name: "image", widget: "image"}
      - label: "Wiederkehrend (optional)"
        name: "repeat"
        widget: "object"
        fields:
          - label: "Nach Regel"
            name: "rule"
            widget: "select"
            options:
              - {label: "Keine", value: "none"}
              - {label: "Wöchentlich", value: "weekly"}
```
2. Open Firefox and activate accessibility helper via F7. More Info:  
  https://support.mozilla.org/en-US/kb/accessibility-features-firefox-make-firefox-and-we#w_using-a-keyboard-to-navigate-within-webpages
3. Try create a entry in the collection by selecting the dates in Firefox with mouse only.

**- What is the expected behavior?**

Should be possible to select.

This might mostly be caused by the inaccessible and in this case non-semantic markup of the calendar picker, which is using table elements for interactive elements, where it should use buttons or other form elements for the interactive date elements.

**- Please mention your versions where applicable.**

Netlify CMS version: ^1.0.0 via CDN
Browser version: Firefox 61.0.1

## Notes
I didn't go deep in the code and didn't check if this is a built in picker or an external add-on, but if you're interested in the topic accessibility and willing to make the CMS more accessible, I would love to help you here since that is my main focus as front-end developer.

Also, you could blame the person using navigation by keyboard but then actually using the cursor for this, but the datetime picker is clearly not built as it should be to be semantically correct and I believe, with a semantic correct markup that takes care of accessibility, the same functional and visual result would not make this bug happen.
