### ISSUE TITLE
Error logging in with gitlab.com

### ISSUE THREAD

**Issue by flacito** [netlify/netlify-cms#1508]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**- Do you want to request a *feature* or report a *bug*?**
*bug*

**- What is the current behavior?**
Trying to login with GitLab client side implicit grant. It worked fine in my browser once and authorize it, but subsequent logins display an unable to fetch with a very cryptic log message in the console.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. access static site admin page (I'm using VuePress)
1. click `Login with Gitlab`
1. "failed to fetch" is displayed
1. `unsentRequest.js:30 OPTIONS https://gitlab.com/api/v4/user?ts=1532218269984 ` is displayed in the console
1. that GitLab api link works fine for me when I enter it in another tab

**- What is the expected behavior?**

Admin app should login fine.

**- Please mention your versions where applicable.**
Netlify CMS version: 1.0.0
Browser version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

Node.JS version:
Operating System: Mac OS 10.13.6 (17G65)

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: gitlab
  branch: master
  repo: kingsland-academy/mgmt
  auth_type: implicit
  app_id: 216349029c6648c5549a3e81a774855cdc56585d50dadffb8ece3563d7c7db16

media_folder: "/"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
```
![netlify_cms_error](https://user-images.githubusercontent.com/5777368/43041089-e2b338fa-8d23-11e8-8dbd-cd98e0de8d2d.png)
[netlify_cms_error.log](https://github.com/netlify/netlify-cms/files/2216620/netlify_cms_error.log)
