### ISSUE TITLE
Roles authentication not working

### ISSUE THREAD

**Issue by kennedyrose** [netlify/netlify-cms#1518]
I have my site set up to only allow users with the "admin" role to be able to use the CMS. However, anyone seems to be able to sign in regardless of role. My config looks like this:

```yml
backend:
  name: git-gateway
  branch: gatsby
  accept_roles:
    - admin
```

I'm using Netlify Identity. I've signed up for new accounts with no roles whatsoever, but they can still sign in.
