### ISSUE TITLE
Adding a list of files doesn't appear to work correctly

### ISSUE THREAD

**Issue by mryanb** [netlify/netlify-cms#1520]
**- Do you want to request a *feature* or report a *bug*?**
Bug, trying to add a list of files

**- What is the current behavior?**
The fields don't render correctly.
![2018-07-25_17-11-18](https://user-images.githubusercontent.com/3656391/43230535-3d54e94a-902e-11e8-9eb8-50c36122b341.gif)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Add the following field to the example config.yml
```yml
- label: "Files"
        name: "files"
        widget: "list"
        field:
          - {label: "File", name: "file", widget: "file"}
```
**- What is the expected behavior?**
I would expect to see the file upload option within each box.

**- Please mention your versions where applicable.**

Netlify CMS version: Netlify CMS version 1.9.4
Browser version: Chrome 67.0.3396.99

**- Please link or paste your `config.yml` below if applicable.**
```yml
backend:
  name: test-repo

display_url: https://example.com
media_folder: "assets/uploads"

publish_mode: editorial_workflow # optional, enables publishing workflow

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Files"
        name: "files"
        widget: "list"
        field:
          - {label: "File", name: "file", widget: "file"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}

  - name: "faq" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "FAQ" # Used in the UI
    folder: "_faqs"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Question", name: "title", widget: "string", tagname: "h1"}
      - {label: "Answer", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "_data/settings.json"
        description: "General Site Settings"
        fields:
          - {label: "Global title", name: "site_title", widget: "string"}
          - label: "Post Settings"
            name: posts
            widget: "object"
            fields:
              - {label: "Number of posts on frontpage", name: front_limit, widget: number}
              - {label: "Default Author", name: author, widget: string}
              - {label: "Default Thumbnail", name: thumb, widget: image, class: "thumb"}

      - name: "authors"
        label: "Authors"
        file: "_data/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}

  - name: "kitchenSink" # all the things in one entry, for documentation and quick testing
    label: "Kitchen Sink"
    folder: "_sink"
    create: true
    fields:
      - label: "Related Post"
        name: "post"
        widget: "relationKitchenSinkPost"
        collection: "posts"
        displayFields: ["title", "date"]
        searchFields: ["title", "body"]
        valueField: "title"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Boolean", name: "boolean", widget: "boolean", default: true}
      - {label: "Text", name: "text", widget: "text"}
      - {label: "Number", name: "number", widget: "number"}
      - {label: "Markdown", name: "markdown", widget: "markdown"}
      - {label: "Datetime", name: "datetime", widget: "datetime"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "File", name: "file", widget: "file"}
      - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
      - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden"}
      - label: "Object"
        name: "object"
        widget: "object"
        fields:
          - label: "Related Post"
            name: "post"
            widget: "relationKitchenSinkPost"
            collection: "posts"
            searchFields: ["title", "body"]
            valueField: "title"
          - {label: "String", name: "string", widget: "string"}
          - {label: "Boolean", name: "boolean", widget: "boolean", default: false}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Number", name: "number", widget: "number"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Datetime", name: "datetime", widget: "datetime"}
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "File", name: "file", widget: "file"}
          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
      - label: "List"
        name: "list"
        widget: "list"
        fields:
          - {label: "String", name: "string", widget: "string"}
          - {label: "Boolean", name: "boolean", widget: "boolean"}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Number", name: "number", widget: "number"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Datetime", name: "datetime", widget: "datetime"}
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "File", name: "file", widget: "file"}
          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
          - label: "Object"
            name: "object"
            widget: "object"
            fields:
              - {label: "String", name: "string", widget: "string"}
              - {label: "Boolean", name: "boolean", widget: "boolean"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Number", name: "number", widget: "number"}
              - {label: "Markdown", name: "markdown", widget: "markdown"}
              - {label: "Datetime", name: "datetime", widget: "datetime"}
              - {label: "Date", name: "date", widget: "date"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "File", name: "file", widget: "file"}
              - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
              - label: "List"
                name: "list"
                widget: "list"
                fields:
                  - label: "Related Post"
                    name: "post"
                    widget: "relationKitchenSinkPost"
                    collection: "posts"
                    searchFields: ["title", "body"]
                    valueField: "title"
                  - {label: "String", name: "string", widget: "string"}
                  - {label: "Boolean", name: "boolean", widget: "boolean"}
                  - {label: "Text", name: "text", widget: "text"}
                  - {label: "Number", name: "number", widget: "number"}
                  - {label: "Markdown", name: "markdown", widget: "markdown"}
                  - {label: "Datetime", name: "datetime", widget: "datetime"}
                  - {label: "Date", name: "date", widget: "date"}
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "File", name: "file", widget: "file"}
                  - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
                  - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden"}
                  - label: "Object"
                    name: "object"
                    widget: "object"
                    fields:
                      - {label: "String", name: "string", widget: "string"}
                      - {label: "Boolean", name: "boolean", widget: "boolean"}
                      - {label: "Text", name: "text", widget: "text"}
                      - {label: "Number", name: "number", widget: "number"}
                      - {label: "Markdown", name: "markdown", widget: "markdown"}
                      - {label: "Datetime", name: "datetime", widget: "datetime"}
                      - {label: "Date", name: "date", widget: "date"}
                      - {label: "Image", name: "image", widget: "image"}
                      - {label: "File", name: "file", widget: "file"}
                      - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
```
