### ISSUE TITLE
Angular: local files not added / updated

### ISSUE THREAD

**Issue by shyamal890** [netlify/netlify-cms#1525]
**- Do you want to request a *feature* or report a *bug*?**
- Not sure

**- What is the current behavior?**
I have added Netlify `index.html` and `config.yml` to assets folder. The `admin/` route works as expected. I am able to post blog article upload images. Images are synced with Github repo but local files are not modified to include the new post or image.

**- Please mention your versions where applicable.**
Netlify CMS version: 1.9.4
Browser version:

Node.JS version: 8+
Operating System: Windows 10

**- Please link or paste your `config.yml` below if applicable.**

```
backend:
  name: github
  repo: ....some repo link

publish_mode: editorial_workflow

media_folder: "assets/images/uploads"
public_folder: "assets/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "assets/posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

```
