### ISSUE TITLE
Error: Backend not found: bitbucket

### ISSUE THREAD

**Issue by pointyfar** [netlify/netlify-cms#1535]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Bitbucket backend does not seem to work? Accessing /admin displays the following error:

`Error: Backend not found: bitbucket`

**- If the current behavior is a bug, please provide the steps to reproduce.**
Follow the tutorial to set up Netlify CMS as written [here](https://www.netlifycms.org/docs/add-to-your-site/)
following the instructions to [Bitbucket Backend configuration](https://www.netlifycms.org/docs/authentication-backends/#bitbucket-backend)

**- What is the expected behavior?**
Bitbucket backend to work [as announced](https://www.netlifycms.org/blog/2018/07/netlify-cms-2-0-launches-with-bitbucket-support-and-a-new-monorepo-architecture)

**- Please mention your versions where applicable.**
Netlify CMS version:
Included with `<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>`:
console.log reports: `netlify-cms 2.0.4`

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: bitbucket
  repo: "my-bitbucket/my-repo" # Path to your Bitbucket repository
  
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "test" # Used in routes, e.g., /admin/collections/blog
    label: "Test" # Used in the UI
    folder: "content/test" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Publish Status", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
```

Just from digging around: might it be the absence of Bitbucket here `packages/netlify-cms/src/backends.js`?

PS I also tried to build locally, adding Bitbucket lines in the above-mentioned file. 
The `Backend not found` error is gone, and I now see the netlify-cms logo and a 
`Login with Bitbucket` button. Not sure I'm doing it right though, as I'm not 
really familiar with the code.
