### ISSUE TITLE
Github backend throws errors when using git-gateway backend

### ISSUE THREAD

**Issue by ascorbic** [netlify/netlify-cms#1536]
**- Do you want to request a *feature* or report a *bug*?**

Bug. (version 2, regression)

**- What is the current behavior?**

When running with the git-gateway backend, after logging-in the page gives the error "The GitHub backend needs a "repo" in the backend configuration." I am assuming this is a bug, as I am not using the Github backend. I am using Netlify CMS in a Gatsby project, which worked fine before upgrading to Netlify CMS 2. After upgrade I started getting this error, which I have reproduced in a minimal static site.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Minimal repo: https://github.com/ascorbic/netlify-cms-test

**- What is the expected behavior?**

No error

**- Please mention your versions where applicable.**

Netlify CMS version: netlify-cms 2.0.4

**- Please link or paste your `config.yml` below if applicable.**
```yml
backend:
  name: git-gateway

media_folder: static

collections:
  - name: "clients" 
    label: "Clients"
    label_singular: "Client"
    folder: "src/pages/clients"
    create: true
    extension: json
    slug: "{{slug}}"
    fields:
- {label: "Path", name: "path", widget: "string"}
```
