### ISSUE TITLE
Set up with Vuepress can't upload images to Media

### ISSUE THREAD

**Issue by Adam-Collier** [netlify/netlify-cms#1551]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
Trying to use Netlify CMS with Vuepress. Currently having an issue when uploading media files. I keep getting this issue 

<img width="1280" alt="screen shot 2018-07-30 at 10 50 44" src="https://user-images.githubusercontent.com/20065745/43390691-b432aadc-93e6-11e8-8db3-8e703a386f7b.png">

in the console it errors out with:

<img width="1280" alt="screen shot 2018-07-30 at 10 53 50" src="https://user-images.githubusercontent.com/20065745/43390761-e1000fb4-93e6-11e8-8d70-f4aa2342971f.png">

Here is a link to the repo: https://github.com/Adam-Collier/netlify-cms-vuepress 

I thought it might be an issue with the public and media folder paths in config.yml but after trying out a few different paths I have had no luck

**- If the current behavior is a bug, please provide the steps to reproduce.**
clone repo, add to netlify, create an identity (instructions in the repo's readme) and then try uploading an image.
**- What is the expected behavior?**
An image uploads successfully.

**- Please mention your versions where applicable.**

Netlify CMS version: netlify-cms 2.0.6
Browser version: Chrome version 68.0.3440.75

Operating System: Mac OS High Sierra 10.13.4

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "docs/.vuepress/public/images"
public_folder: "images"

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
```
