### ISSUE TITLE
Korean letters are not typed properly in markdown widget fields

### ISSUE THREAD

**Issue by DaleSeo** [netlify/netlify-cms#1559]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Korean letters are not typed properly in markdown widget fields. Letter disappear when the editor UI blinks. This issue doesn't occur with either string widget or text widget.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Just try to type any Korean letters in a markdown widget field.

**- What is the expected behavior?**
Korean letters are expected to be entered properly in markdown widget fields without losing any letters.

**- Please mention your versions where applicable.**

Netlify CMS version: 2.0.6
Browser version: Chrome 67.0.3396.99

Node.JS version: v8.11.3
Operating System: Windows

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "source/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "source/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "select", options: ['Java', 'JavaScript', 'Python']}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
```
