### ISSUE TITLE
Writing posts with GitLab as backend is broken

### ISSUE THREAD

**Issue by Kavakuo** [netlify/netlify-cms#1564]
**- Do you want to request a *feature* or report a *bug*?**
Bug, see below for a detailed analysis. Pull request is coming too.

**- What is the current behavior?**
Using GitLab as backend doesn't work. Creating or editing posts is not possible.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Use the config.yml above and try to create new posts for a static website. No error is shown by netlify-cms, but there are no new commits in the repository.

**- What is the expected behavior?**
It should be possible to create and edit posts with netlify-cms.

**- Bug analysis**
If you try to publish a new post, a POST request with the following body is sent to the GitLab API.

```json
{
    "branch": "master",
    "commit_message": "Update Pentest “2017-03-01-Hooking”",
    "actions": [{
        "action": "update",
        "file_path": "Pentest/_posts/2017-03-01-Hooking.md",
        "content": {},
        "encoding": "base64"
    }]
}
```
The problem is the empty `content` property inside the request body of the POST request. The response has a status code 500. I don't know why the frontend doesn't show any error but instead shows a message that everything went well. I think the request promise is not rejected although the status code is 500.

I could track down the bug. It is introduced by @erquhart ([Blame](https://github.com/netlify/netlify-cms/blame/4d6a1ebf8d171ec81f18a0558b5e2423383ea736/packages/netlify-cms-backend-gitlab/src/API.js#L188))
The problem is that the `content` constant is a Promise and not the value of `item.raw`. I will make a Pull request to fix this.

Please take a look at the GitHub implementation as well. I didn't test it, but I think it is working, because the Promise is handled correctly.([Relevant GitHub code](https://github.com/netlify/netlify-cms/blame/master/packages/netlify-cms-backend-github/src/API.js#L714))

**- Please mention your versions where applicable.**

Netlify CMS version: 2.0.6
Browser version: Chrome 66, Firefox 61

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: gitlab
  branch: master # Branch to update (optional; defaults to master)
  repo: [repository]
  auth_type: implicit # Required for implicit grant
  app_id: [applicationId] # Application ID from your GitLab settings
  api_root: https://gitlab.lan/api/v4
  base_url: https://gitlab.lan
  auth_endpoint: oauth/authorize
```
