### ISSUE TITLE
Uploading images with GitLab as backend is broken

### ISSUE THREAD

**Issue by Kavakuo** [netlify/netlify-cms#1565]
**- Do you want to request a *feature* or report a *bug*?**
Bug, see below for the bugfix. Pull request is coming.

**- What is the current behavior?**
Uploading images with GitLab as backend is broken.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Use GitLab as backend and try to upload a new image.

**- What is the expected behavior?**
The image is uploaded and commited by the cms.

**- Bugfix**
Use the `result` function instead of `get` in the `uploadAndCommit` function (see [here](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-backend-gitlab/src/API.js#L188)). I will create a pull request to fix this issue.

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: gitlab
  branch: master # Branch to update (optional; defaults to master)
  repo: [repository]
  auth_type: implicit # Required for implicit grant
  app_id: [applicationId] # Application ID from your GitLab settings
  api_root: https://gitlab.lan/api/v4
  base_url: https://gitlab.lan
  auth_endpoint: oauth/authorize
```
