### ISSUE TITLE
Can the relationship widget link to filtered folder collections?

### ISSUE THREAD

**Issue by aaronaustin** [netlify/netlify-cms#1577]
I have two filtered collections in the same folder.  I would like to use the relationship widget to connect to those but it's not pulling any items.  Is this possible?

```yaml
collections:
  - name: "bulletin"
    label: "Bulletins"
    folder: "src/pages/bulletin"
    create: true
    slug: "{{year}}-{{month}}-{{day}}:{{time}} {{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Elements", name: elements, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Presenter, name: presenter, widget: text}, {label: "Resource Link", name: "resourceLink", widget: "relation", collection: "element", searchFields: ["title"], valueField: "title", displayFields: ["title"]}, {label: "Show Title", name: "showTitle", widget: "boolean", default: false}, {label: "Show Text", name: "showText", widget: "boolean", default: false}, {label: "Stand", name: "stand", widget: "boolean", default: false}]}

  - name: "song_element"
    label: "Songs"
    folder: "src/pages/element"
    filter: {field: "type", value: "song"}
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Type", name: "type", widget: "select", options: ["song", "reading"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Text", name: "text", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "reading_element"
    label: "Readings"
    folder: "src/pages/element"
    filter: {field: "type", value: "reading"}
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Type", name: "type", widget: "select", options: ["song", "reading"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Text", name: "text", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list"}
```
