### ISSUE TITLE
Cannot render custom preview template for file collection

### ISSUE THREAD

**Issue by runandrew** [netlify/netlify-cms#1625]
**Describe the bug**
Adding a custom preview template for a file collection does not override the default template. The default template is still shown, no errors in the console. Note: I tried the same template for a folder collection and it is successful there.

**To Reproduce**
1. Create a file collection
2. Add template code:
```
const PagePreview = createClass({
      render: function () {
        return h('div', {},
          h('h1', {}, "test"),
        );
      }
    });

CMS.registerPreviewTemplate("pages", PagePreview);
```

**Expected behavior**
The preview for a file within the collection to render the `h1` element with the text of `test`.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: ^2.0.0
 - Git provider: Github
 - OS: OSX 10.13
 - Browser version: latest Chrome

 - Node.JS version: 8.11.1

**CMS configuration**
A sample of the `Pages` file collection

```
collections:
  - label: Pages
    name: pages
    files:
      - label: "Home Page"
        name: home
        file: src/data/pages/home.yml
        path: /
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: "Subtitle"
                name: subtitle
                widget: text
              - label: "Call to Action Link"
                name: link
                widget: string
```

**Additional context**
