### ISSUE TITLE
Remove 'Quick Add' if there is no config option that allows creating new content

### ISSUE THREAD

**Issue by MitchellCash** [netlify/netlify-cms#1643]
**Describe the bug**
When you create a CMS configuration where all collections use `create: false` then the `Quick Add` button up the top right of the CMS does not need to appear as it does nothing.

**To Reproduce**
1. Create a new CMS configuration
2. Mark all `collections` as `create: false`
3. Start instance
4. Navigate to CMS
5. Note the appearance of `Quick Add` at the top right and the fact it does nothing

**Expected behavior**
That the button does not appear when all ability to create new items is set to `false`

**Screenshots**
![netlify-cms-quick-add](https://user-images.githubusercontent.com/8009243/44448856-d9a5de00-a62f-11e8-92b9-3e3b4e1c87a7.gif)

**Applicable Versions:**
 - Netlify CMS version: 2.0.9
 - Git provider: GitHub
 - OS: macOS 10.13.6
 - Browser version: Firefox 61.0.2 (64-bit)

**CMS configuration**
```
backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "assets/img/uploads" # Media files will be stored in the repo under assets/img/uploads

# A list of collections the CMS should be able to edit
collections:
    # PAGES
    - name: "pages"             # Used in routes, e.g., /admin/collections/pages
      label: "Pages"            # Label used in the UI
      label_singular: "Page"    # Singular label used in the UI
      folder: "pages"           # The path to the folder where the documents are stored
      create: false             # Do not allow users to create new items in this collection
      delete: false             # Prevents users from deleting items in a collection
      extension: md             # Determines the file extension used when finding existing entries
      format: yaml-frontmatter  # Parses files and saves files with data frontmatter
      fields:                   # The fields for each document, usually in front matter
          - {name: "title", label: "Title", widget: "string", tagname: "h1"}
          - {name: "intro_paragraph", label: "Intro Paragraph", widget: "text", required: false}
          - {name: "body", label: "Body", widget: "markdown", required: false}
      editor:
          preview: true         # Enable the preview pane for this collection
```
