### ISSUE TITLE
Allow required fields in list and object widget

### ISSUE THREAD

**Issue by MitchellCash** [netlify/netlify-cms#1649]
**Is your feature request related to a problem? Please describe.**
When I use the list widget I lose the ability to set a field as required. Possibly also the same problem on object widget, but have not tested.

**Describe the solution you'd like**
I would like to be able to set fields as required when using the list and object widgets.

**Describe alternatives you've considered**
N/A

**Additional context**
E.g.

```
      - label: "Team Information"
        name: "team_information"
        file: "_data/team.yml"
        fields:
          - label: "Team Member"
            name: "team_member"
            widget: list
            fields:
              - {label: Name, name: name, widget: string, required: true}
              - {label: Position, name: position, widget: string, required: true}
              - {label: Avatar, name: avatar, widget: image, required: true}
              - {label: Description, name: description, widget: text, required: true}
```

In the above example the fields in the list widget do not honour the `required: true` values.
