### ISSUE TITLE
Support Hugo Page Bundles

### ISSUE THREAD

**Issue by yani-** [netlify/netlify-cms#1697]
**Is your feature request related to a problem? Please describe.**
My content is organized in page bundles:
```
/content/posts/my-cool-article/index.md
/content/posts/my-other-cool-article/index.md
```
I would like that NetlifyCMS can handle content organized this way.

**Describe the solution you'd like**
In config.yml, I should be able to do something like this:
```
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    slug: "{{slug}}/index.md"
```

**Describe alternatives you've considered**
-

**Additional context**
-
