### ISSUE TITLE
Request: Add Mechanism For Sharing Fields

### ISSUE THREAD

**Issue by Undistraction** [netlify/netlify-cms#1701]
**Is your feature request related to a problem? Please describe.**
There is currently no way to share fields between different collections, different files, or files and collections. For example, my data model includes a Projects collection, an Articles collection and numerous Pages. All need to include a series of fields that will be used to generate metadata: the `title` which is already present, `description`, and `image`. It would be nice if I could abstract these shared fields and include them into an collections or files that need them. This would result in less duplication, and therefore more consistency and less room for errors.

**Describe the solution you'd like**
An additional section in `config.yaml` for defining groups of fields:
```yaml
sharedFieldsGroups: 
  - name: metadata
    fields: 
       - label: Title
          name: title
          widget: string
       - label: Description
          name: description
          widget: string
       - label: Image
          name: image
          widget: image
```
Then a mechanism to use a group in the `fields` of a collection or file:
```yaml
    fields: 
       - include: metadata
```

**Describe alternatives you've considered**
The alternative is to perform some kind of preprocessing on the `config.yaml`, but this feels to me like something that should be handled by netlify-cms. 

**Additional context**
Other thoughts:
- Should be reasonably easy to validate that the included fields are present.
