### ISSUE TITLE
Permission denied to access property "nodeType" on Alt Text (image) editing 

### ISSUE THREAD

**Issue by idiazroncero** [netlify/netlify-cms#1709]
**Describe the bug**
Error when uploading an image using the WYSIWG editor (widget:markdown, body field).
The error happens when you click on the ALT field of the image, (the image uploads correctly).
The error happens using both a gitlab and github backend.
The error is: Error: Permission denied to access property "nodeType""

**To Reproduce**

- Install a template based on a GitLab / GitHub back-end (I tried both) I used this:
https://templates.netlify.com/template/eleventy-netlify-boilerplate/
- Login to the admin and edit/create a new post.
- Add an image to the markdown field. Upload a new image and select it.
- Click on the Alt field
- The error happens. Blank screen and message:

"Sorry!
There's been an error - please report it!
Error: Permission denied to access property "nodeType""

**Expected behavior**
Error doesn't happen.

**Applicable Versions:**
 - Netlify CMS version: 2.0.11
 - Git provider: Tried github and gitlab
 - OS: macOS Hight Sierra
 - Browser version: Firefox 61.0.2
 - Node.JS version: 8.11.4

**CMS configuration**
```yaml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  media_folder: 'static/img' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'blog'
    label: 'Post'
    folder: 'posts'
    create: true
    slug: '{{slug}}'
    fields: 
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Page'
    folder: 'pages'
    create: false
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Navigation Title', name: 'navtitle', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'hidden', default: 'nav' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
```

It's the original from the repo
