### ISSUE TITLE
Default empty datetime not honored when the field is absent in an existing entry

### ISSUE THREAD

**Issue by papandreou** [netlify/netlify-cms#1745]
**Describe the bug**

I want to introduce a `publicationDate` field that uses the `datetime` widget, but doesn't get auto-filled with the current time when an entry is first created. To accomplish that I've followed [the documentation](https://www.netlifycms.org/docs/widgets/#datetime) and specified `default: ''` to prevent the default behavior of inserting "now". However, that doesn't work for the collection entries that were present before I added the field. When I edit one of those, the absence of the `publicationDate` field in the frontmatter of the .md file makes netlify-cms insert the current time anyway. I don't want that -- the publication date is not supposed to be added until the entry is actually ready for publication.

(Also, as a side note, it's kinda ugly that a non-existent datetime value for new entries gets persisted as `publicationDate: ''`. I'd rather that the field didn't get added at all. This is somewhat related to https://github.com/netlify/netlify-cms/issues/1449)

Maybe `date` and `datetime` widgets should have a separate config option to control whether the field gets populated with the "now" value instead of the `default: ''` thing?

**To Reproduce**

1. Define a collection with a `datetime` field with `default: ''` and `required: false` (see **CMS configuration** for an example)
2. Add a new entry to the collection, leaving the publication date blank
3. Delete the `publicationDate: ''` line from the markdown file in the repository, simulating an existing entry that existed before the `publicationDate` field was defined.
4. Reload the CMS and edit the entry

Observe that the publication date field is now filled with the current date.

**Expected behavior**

That the publication date field was left blank when starting to edit the entry

**Applicable Versions:**

 - Netlify CMS version: 2.0.11
 - Git provider: GitHub
 - OS: OSX High Sierra (10.13.6)
 - Browser version: Chrome 68

 - Node.JS version: 10.9.0

**CMS configuration**

```
collections:
  -
    name: things
    label: Things
    label_singular: thing
    folder: things
    create: true
    slug: "{{id}}"
    fields:
      -
        label: Title
        name: title
        widget: string
      -
        label: Id
        name: id
        widget: string
      -
        label: Publication Date
        name: publicationDate
        default: ""
        required: false
        widget: datetime
```
