### ISSUE TITLE
undefined in the branch name

### ISSUE THREAD

**Issue by steverandy** [netlify/netlify-cms#1748]
**Describe the bug**
netlifty-cms created new branch with `undefined` word instead of `cms`. The branch name looks like: `undefined/20180915-post-title`. Because of this issue, the newly create entry will not appear in the draft section on Workflow page.

**Expected behavior**
The branch name should be `cms/20180915-post-title`

**Applicable Versions:**

 - Netlify CMS version: 2.1.1
 - Git provider: GitHub
 - OS: macOS
 - Browser version Chrome 69
 - Node.JS version: 10

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master
  squash_merges: true
publish_mode: editorial_workflow
media_folder: "static/uploads"
collections:
  - name: "news"
    label: "News"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
```
