### ISSUE TITLE
Form splitting

### ISSUE THREAD

**Issue by ciokan** [netlify/netlify-cms#1759]
I propose a form splitting technique into tabs. Maybe some setting in the collection that allows me to send one field to a different tab.

I have a `Posts` collection and it contains a lot of fields (meta description & keywords, excerpt, content, title, tags. category, publish date etc.).

Example yaml:

```
- name: posts
  label: Posts
  label_singular: Post
  folder: static/content/collections/posts
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}/"
  fields:
  - {label: "Title", name: "title", widget: "string"}
  - {label: "Publish Date", name: "date", widget: "datetime"}
  - label: "Meta"
    name: "meta"
    widget: "object"
    form_stack: "Meta"
    fields:
    - label: Meta keywords
      name: meta_keywords
      widget: string
      required: false
    - label: Meta description
      name: meta_description
      widget: string
      required: false
      hint: "If left empty we will use the excerpt instead"
```

Notice the `form_stack: "Meta"` field. In admin this will form a separate tab named "Meta" and add there all the fields under this stack. Everything without a `form_stack` field will be sent to `Main` or something.  This would allow us to let that form breathe a little.
