### ISSUE TITLE
Folder names containing whitespace (GitLab)

### ISSUE THREAD

**Issue by Kavakuo** [netlify/netlify-cms#1798]
**Describe the bug**
Using Netlify CMS with GitLab where folder paths containing a white space character, results in a bug. The cms is unable to show posts inside the particular folder. The problems that the request to the GitLab API contains a URL encoded '+' character (instead of the white space) for every white space in the URL, this includes the path to the folder inside the `path` query argument of the URL. Because of that the request fails.

The URL of the request to the GitLab API, which fetches a list of the files inside the folder, is taken from a `HEAD` request sent before, where the response contains a `Link` field inside the HTTP-Header ([src](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-backend-gitlab/src/API.js#L118-L124)). Inside this field are two URLs listed where white spaces are encoded as `+` instead of `%20`. 

**To Reproduce**
1. Configure Netlify CMS with GitLab as backend.
2. Use something like in the config.yml
```yaml
- create: true
  fields:
  - default: docs
    label: Layout
    name: layout
    widget: hidden
  - label: Title
    name: title
    widget: string
  - label: Body
    name: body
    widget: markdown
  folder: Folder with whitespace/_posts
  label: Folder with whitespace
  name: folder with whitespace
  slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
```
3. Start Netlify CMS and try to create or edit the posts inside the folder.

**Expected behavior**
The posts inside the folder are shown by Netlify CMS.

**Applicable Versions:**

 - Netlify CMS version: 2.1.2-dev
 - Git provider: GitLab

**CMS configuration**

```yaml
backend:
  api_root: https://gitlab.lan/api/v4
  app_id: ***
  auth_endpoint: oauth/authorize
  auth_type: implicit
  base_url: https://gitlab.lan
  branch: master
  name: gitlab
  repo: ***
collections:
- create: true
  fields:
  - default: docs
    label: Layout
    name: layout
    widget: hidden
  - label: Title
    name: title
    widget: string
  - label: Publish Date
    name: date
    widget: datetime
  - label: Body
    name: body
    widget: markdown
  folder: Folder with white space/_posts
  label: Folder with white space
  name: folder with white space
  slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
```

**Additional context**
Pull Request is coming.
