### ISSUE TITLE
Remove requirement for 'title' field in folder collections

### ISSUE THREAD

**Issue by hnspn** [netlify/netlify-cms#1802]
I'm not sure if this should be considered as a feature request or as a bug.

## General

The 'title' field seems to be required in folder collections according to the [documentation](https://www.netlifycms.org/docs/collection-types/#folder-collections)

The config file checks that requirement at initialization ever since  [release 2.0](https://github.com/netlify/netlify-cms/pull/1203).

This requirement was put in place because the generated slug uses the 'title' field.

## My problem
My particular use case of the cms would require me having a folder collection that references JSON files. I don't want to add a title property for in my files.
I already have a field that could be used as an identifier 'uid'

### config.yml
here is my configuration for the affected folder collection

```yml
  - name: "author"
    label: "Authors"
    folder: "content/authors"
    create: true
    slug: "{{uid}}.json"
    fields:      
      - {label: "UID", name: "uid", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Profile picture", name: "image", widget: "image"}
      - {label: "Website", name: "url", widget: "string"}
      - {label: "Bio", name: "bio", widget: "string"}
      - {label: "Social Urls", name: "social", widget: "list"}
```

As you can see, I don't have a title field.
I also have defined a custom slug that uses my own identifier.

This current configuration gives me an error message:
`Error loading the CMS configuration
Config Errors:
'collections[1]' must have a field that is a valid entry identifier
Check your config.yml file.`

### Adding a title field to my collection
I can add a title field to my collection and that would fix the error message, but it would add a field that I have no need for and that I cannot leave blank for items in my collection.
Seems like a bad practice.

### Removing the requirement for 'title' field when using cutom slug
Since this requirement is only here to ensure the slug will work (not sure if its the only reason), we could simply not check it when a custom slug is defined.

### Changing requirement for a custom identifier
The current code checks if the collection has identifier fields.
The only two identifier fields are currently 'title' and 'path' [source](https://github.com/netlify/netlify-cms/blob/b167b79fc6c05d2db52f20b471b5e88df364693e/packages/netlify-cms-core/src/constants/fieldInference.js#L3)
I could specify my own identifier field like this [feature request](https://github.com/netlify/netlify-cms/pull/1543) suggests and it would add my field to 'title' and 'path' as an indentifier.
This would fix the error.
 
### Change perspective
Maybe I'm using the cms for something it was not indented to do and I should not be able to edit these kind of files.

## Contex
netlify-cms v 2.1.2
