### ISSUE TITLE
TypeError: e.join is not a function

### ISSUE THREAD

**Issue by arifpedia** [netlify/netlify-cms#1807]
**To Reproduce**

1. Login
2. Open any post

**Screenshots**
![capture](https://user-images.githubusercontent.com/4081293/46842029-6762a600-cdf5-11e8-94b9-a363aa42df8e.PNG)

**Applicable Versions:**

 - Netlify CMS version:  2 (https://cdn.jsdelivr.net/npm/netlify-cms@2/dist/netlify-cms.min.js)
 - Git provider: Gitlab
 - Generator: Hexo

**CMS configuration**

```yml
backend:
  name: gitlab
  repo: xxxx/xxxxx # Path to your GitLab repository

display_url: https://www.xxxx.com

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "source/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
```

**Comment by tomrutgers** [comment]
Your list widgets (tags and categories) do not have `field` or `fields` defined. 

```
- label: "Tags"
  name: "tags"
  widget: "list"
  field: {label: "Tag", name: "tag_name", widget: "string"}
```

**Comment by talves** [comment]
@arifpedia thanks for the detailed issue. I am going to close and we can open if the solution @tomrutger suggested did not fix it.

**Comment by nicolasesnis** [comment]
I'm having the same problem here. Has anyone found a solution yet?

**Comment by talves** [comment]
@nicolasesnis did you check what @tomrutgers suggests as the issue here https://github.com/netlify/netlify-cms/issues/1807#issuecomment-429251896?

**Comment by barthc** [comment]
@tomrutgers  @talves  with a list widget like this:
```
- {label: "Categories", name: "categories", widget: "list"}
```
The CMS would just display a string like widget and value is split by `,`  and stored as array.

@nicolasesnis  can we see your config, if it's different from the one above.

**Comment by SixFingeredAmish** [comment]
I’m also running into this issue with a list widget in my custom widget:
```
fields: [{label: "Images", name: "id", widget: "list", field: {label: "Image", name: "galleryImage", widget: "image"}}],
```
Does anyone know a fix for this?

**Comment by theredwillow** [comment]
@steakscience I'm having this exact same issue. I'm trying to make a list of markdowns as a sub-field in a collection. Did you ever figure this out?

**Comment by shushugah** [comment]
I get same error with plural version of `fields`

```yaml
collections:
  - name: "event" # Used in routes, e.g., /admin/collections/blog
    label: "Event" # Used in the UI
    folder: "_events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", fields: [{label: "Tag", name: "tag_name", widget: "string"}] }
```
