### ISSUE TITLE
Unable to delete List Item (Image widget)

### ISSUE THREAD

**Issue by AryanJ-NYC** [netlify/netlify-cms#1810]
**Describe the bug**
When in Netlify CMS, I am unable to delete an image widget from a list.

**To Reproduce**

1. Go to `webpage.com/admin` and click on the Properties page
2. Add an image
3. Click X
4. Image will not be removed

**Expected behavior**

Clicking X should remove the image from the CMS

**Screenshots**

![screen shot 2018-10-14 at 3 46 15 pm](https://user-images.githubusercontent.com/8263430/46921361-53bb6900-cfc8-11e8-8813-62cd0768e5cb.png)

**Applicable Versions:**

 - Netlify CMS version: 2.1.1
 - Git provider: GitHub
 - OS: macOS High Sierra 10.13.6
 - Browser version: Google Chrome 69.0.3497.100
 - Node.JS version: Node 10.9.0

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "property"
    label: "Properties"
    folder: "src/pages/property"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "property"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image"}}
```

**Comment by tomrutgers** [comment]
Just tested this on @erquhart's  codepen, I get the same problem. It works when you use `fields` instead of `field`. 

```
- label: "Images"
  name: "images"
  widget: "list"
  fields:
    - {label: "Image", name: "image", widget: "image"}
```
