### ISSUE TITLE
Identity prompt for Git Gateway blocks GitLab implicit auth login

### ISSUE THREAD

**Issue by pieterdd** [netlify/netlify-cms#1824]
I really like what Netlify CMS is doing with the whole "static website with admin interface that makes Git commits" thing. But I'm hesitant to use it for real projects.

Even if you use a custom authentication backend, Netlify CMS seems dependent on Netlify. That's fine for now, I like the platform. But startups can go out of business. Or they get acquired and shut down by a big company. That's not a dependency I have when I use a more traditional CMS; I can always get a VPS somewhere else. Netlify CMS on the other hand requires a soft vendor lock-in to Netlify for the editing capabilities.

If Netlify is ever discontinued, is there a realistic way to run Netlify CMS on other infrastructure?

**Comment by Herohtar** [comment]
It's definitely possible to use without anything hosted on Netlify. The downside is that it requires a bit more configuration, and some kind of server for authentication. My current setup for my personal site is hosted entirely on Firebase, even the auth which is going through a Firebase Cloud Function that I wrote for GitHub OAuth.

The only problem is replicating git-gateway if you want to allow access without requiring GitHub accounts. Theoretically you can host that yourself, but it seems to require a more advanced server setup.

**Comment by pieterdd** [comment]
> You can use GitLab with the "Implicit Grant" option described here: https://www.netlifycms.org/docs/authentication-backends/#client-side-implicit-grant - this does not require a server-side component for authentication, so it works entirely in your browser.

Then how come I still get this prompt when authenticating against GitLab? That implies a Netlify dependency, doesn't it?

![image](https://user-images.githubusercontent.com/1407980/47451945-53da1680-d7c9-11e8-85a5-5a357755b794.png)

**Comment by pieterdd** [comment]
Here's the config. IIRC it's based on the Hugo Site Starter starter project except that I overwrote the backend.

```yaml
backend:
  name: gitlab
  repo: pdedecker/netlify-cms-test
  auth_type: implicit
  app_id: fdcf25187f4d7fa62c77bd2299c879d8be57e64d708f90e3a29f70867d5b5de5

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
```

The "Set site URL" popup opens after GitLab redirects back to the admin site.
