### ISSUE TITLE
Build fails when new field is added

### ISSUE THREAD

**Issue by runofthemill** [netlify/netlify-cms#1828]
**Describe the bug**
This appears to be the same/a similar issue as #1803; I have added a new field to the CMS, via `config.yml`, that is a sub-field named `image` under the list widget `video`, and am referencing it in a page template. The build fails, with the following error:

```
[...]
2:13:16 PM: Executing user command: gatsby build
2:13:18 PM: success open and validate gatsby-config — 0.009 s
2:13:18 PM: success load plugins — 0.260 s
2:13:19 PM: success onPreInit — 0.637 s
2:13:19 PM: success delete html and css files from previous builds — 0.096 s
2:13:19 PM: success initialize cache — 0.007 s
2:13:19 PM: success copy gatsby files — 0.013 s
2:13:19 PM: success onPreBootstrap — 0.008 s
2:13:19 PM: success source and transform nodes — 0.304 s
2:13:20 PM: success building schema — 0.334 s
2:13:20 PM: success createPages — 0.155 s
2:13:20 PM: success createPagesStatefully — 0.048 s
2:13:20 PM: success onPreExtractQueries — 0.000 s
2:13:20 PM: success update schema — 0.186 s
2:13:20 PM: error GraphQL Error Unknown field `image` on type `[video_2]`
2:13:20 PM:   file: /opt/build/repo/src/templates/state-page.js
2:13:20 PM:    6 |         title
2:13:20 PM:    7 |         deadlines
2:13:20 PM:    8 |         initiatives
2:13:20 PM:    9 |         competitive {
2:13:20 PM:   10 |           photo
2:13:20 PM:   11 |           details
2:13:20 PM:   12 |         }
2:13:21 PM:   13 |         video {
2:13:21 PM:   14 |           video_details
2:13:21 PM:   15 |           video_url
2:13:21 PM: > 16 |           image
2:13:21 PM:      |           ^
2:13:21 PM:   17 |         }
2:13:21 PM:   18 |       }
2:13:21 PM:   19 |     }
2:13:21 PM:   20 |   }
```

The commit triggering the build also includes the update to `config.yml` which adds the `image` field. The field, as well as the list it is contained in, are optional:

```
      - label: Candidates to Watch
        name: video
        widget: list
        hint: "For each candidate, please add either a video URL or an image, but not both!"
        required: false
        fields:
          - {label: Video URL, name: video_url, widget: string, required: false}
          - {label: Image, name: "image", widget: image, required: false}
          - {label: Details, name: video_details, widget: markdown}
```

**To Reproduce**
1. Add a new field to `config.yml`
2. Reference that field in a GraphQL query
3. Commit changes & trigger Netlify build

**Expected behavior**
Build to succeed, with new field available in NetlifyCMS

**Applicable Versions:**

 - Netlify CMS version: 2.1.1
 - Git provider: GitHub
 - OS: N/A
 - Browser version: N/A

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://votesaveamerica.com

collections:
  - name: states
    label: States
    folder: src/pages/statepages
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: Layout, name: templateKey, widget: hidden, default: state-page}
      - {label: Title, name: title, widget: string}
      - {label: Intro Blurb, name: body, widget: markdown}
      - {label: Important Deadlines, name: deadlines, widget: markdown}
      - {label: Ballot Initiatives, name: initiatives, widget: markdown, required: false}
      - label: Competitive
        name: competitive
        widget: list
        required: false
        fields:
          - {label: Photo, name: photo, widget: image}
          - {label: Details, name: details, widget: markdown}
          - {label: Name, name: name, widget: string}
          - {label: District, name: district, widget: string}
          - {label: Area, name: area, widget: string}
          - {label: BallotReady Link, name: ballotready_link, widget: string, required: false}
      - label: Candidates to Watch
        name: video
        widget: list
        hint: "For each candidate, please add either a video URL or an image, but not both!"
        required: false
        fields:
          - {label: Video URL, name: video_url, widget: string, required: false}
          - {label: Image, name: "image", widget: image, required: false}
          - {label: Details, name: video_details, widget: markdown}


  - name: pages
    label: Pages
    files:
      - label: What else should I know?
        name: resources
        file: src/pages/resources/index.md
        delete: false
        editor:
        preview: false
        fields:
          - {label: Layout, name: templateKey, widget: hidden, default: resources-page}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Resources
            name: resources
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Link, name: link, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Logo, name: logo, widget: image}
      - label: Thank You
        name: thankyou
        file: src/pages/thankyou/index.md
        delete: false
        editor:
        preview: false
        fields:
          - {label: Layout, name: templateKey, widget: hidden, default: thankyou-page}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: Am I registered?
        name: verify
        file: src/pages/verify/index.md
        delete: false
        editor:
          preview: false
        fields:
          - {label: Layout, name: templateKey, widget: hidden, default: register-page}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: iFrame URL, name: url, widget: string}
      - label: Get Registered
        name: register
        file: src/pages/register/index.md
        delete: false
        editor:
          preview: false
        fields:
          - {label: Layout, name: templateKey, widget: hidden, default: register-page}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: iFrame URL, name: url, widget: string}
      - label: Get Involved / Now what?
        name: takeaction
        file: src/pages/takeaction/index.md
        delete: false
        editor:
          preview: false
        fields:
          - {label: Layout, name: templateKey, widget: hidden, default: take-action-page}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Social Feed Header, name: feed_header, widget: string}
          - {label: Social Feed Description, name: feed_desc, widget: markdown}
      - label: Do Something
        name: dosomething
        file: src/pages/dosomething/index.md
        delete: false
        editor:
          preview: false
        fields:
          - {label: Layout, name: templateKey, widget: hidden, default: dosomething-page}
          - {label: Title, name: title, widget: string}
      - label: What's up with my state?
        name: states
        file: src/pages/states/index.md
        delete: false
        editor:
          preview: false
        fields:
          - {label: Layout, name: templateKey, widget: hidden, default: states-page}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: Voter Guide
        name: ballot
        file: src/pages/ballot/index.md
        delete: false
        editor:
          preview: false
        fields:
          - {label: Layout, name: templateKey, widget: hidden, default: ballot-page}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Steps Label, name: steps_label, widget: string}
          - label: Steps
            name: steps
            widget: list
            required: false
            fields:
              - {label: Step, name: step, widget: markdown}
      - label: FAQs
        name: faq
        file: src/pages/faq/index.md
        delete: false
        editor:
          preview: false
        fields:
          - {label: Layout, name: templateKey, widget: hidden, default: faq-page}
          - {label: Title, name: title, widget: string}
          - label: FAQs
            name: faqs
            widget: list
            required: false
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: markdown}
      - label: Get 3 Friends
        name: get3friends
        file: src/pages/get3friends/index.md
        delete: false
        editor:
          preview: false
        fields:
          - {label: Layout, name: templateKey, widget: hidden, default: threefriends-page}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Text Template Title, name: text_title, widget: string}
          - {label: Text Template Intro, name: text_intro, widget: markdown}
          - {label: Text Template Copy, name: text_copy, widget: markdown}
          - {label: Email Template Title, name: email_title, widget: string}
          - {label: Email Template Intro, name: email_intro, widget: markdown}
          - {label: Email Template Copy, name: email_copy, widget: markdown}
          - {label: State Deadline Table, name: state_deadlines, widget: markdown}
```
