### ISSUE TITLE
Using relation widget causes "TypeError: Cannot read property 'toJS' of undefined"

### ISSUE THREAD

**Issue by jhackett1** [netlify/netlify-cms#1833]
I'm building a Gatsby website, and using Netlify CMS to manage markdown documents.

I'm trying to use a relation widget to save a value based on another collection, but:

- I don't see any relation-specific UI, just a plain string input widget
- On save, the CMS crashes and gives me a "TypeError: Cannot read property 'toJS' of undefined" error

This only seems to happen on collections making use of the relation widget.

It looks like the markdown file does get successfully created, so the API request would appear to succeed despite the interface crashing.

**To Reproduce**
Define a config.yml collection making use of a relation widget?

**Expected behavior**
I can use the relation widget as a dropdown select menu to save a value based on fields from another collection.

**Applicable Versions:**
Gatsby v2 website
Netlify CMS v2.1.3

**CMS configuration**
The relevant part of my config.yml looks like

```
  # Speakers
  - name: "speaker"
    extension: "markdown"
    label: "Speakers"
    folder: "content/speakers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
    editor:
      preview: false

  # Event
  - name: "event"
    extension: "markdown"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Speaker", name: "speaker", widget: "relation", collection: "speaker", valueField: "title", searchField: ["title"]}
    editor:
      preview: false
```
