### ISSUE TITLE
Files not showing in collection with 404 error

### ISSUE THREAD

**Issue by gcolson** [netlify/netlify-cms#1872]
Since a few days, whenever I log in to the admin interface, only one file is loaded in a collection and an error message shows up after a few seconds :

```
Failed to persist entry: API_ERROR: {"message":"404 File Not Found"}
```

I have tried many changes in the config.yml file but did not find a solution. Here is my `config.yml` : 

```
backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)
media_folder: "assets/images" # Media files will be stored in the repo under images/uploads
collections:
  - name: "home-page" # Used in routes, e.g., /admin/collections/blog
    label: "Page d'accueil" # Used in the UI
    folder: "" # The path to the folder where the documents are stored
    filter: {field: 'layout', value: 'home'}
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
      - {label: "Show", name: "show_tile", widget: "hidden", default: "false"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Sous-titre", name: "landing-title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Actualités", name: "news", widget: "string"}
      - {label: "Image principale", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio-pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages des créations" # Used in the UI
    folder: "" # The path to the folder where the documents are stored
    filter: {field: 'layout', value: 'portfolio'}
    create: true # Allow users to create new documents in this collection
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio"}
      - {label: "Show", name: "show_tile", widget: "hidden", default: "true"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Sous-titre", name: "subtitle", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image principale", name: "image", widget: "image"}
      - {label: "Image 1", name: "image1", widget: "image", required: false}
      - {label: "Image 2", name: "image2", widget: "image", required: false}
```
Everything worked fine until a few days ago.
Did anybody experienced a similar bug ? 

Thanks !

**Comment by gcolson** [comment]
I don't know if that could help but here is the bug in the firefox dev console : 

```
API_ERROR: "{"message":"404 File Not Found"}"
	cms %5E2.0.0/dist/netlify-cms.js:14:136009
	cms %5E2.0.0/dist/netlify-cms.js:14:136324
	cms %5E2.0.0/dist/netlify-cms.js:45:25185
W/< entries.js:348:6
```

**Comment by erquhart** [comment]
Either `folder` or `file` must have a value for each collection, you have an empty `folder` value for both collections.

**Comment by gcolson** [comment]
Yep I've tried with "/" as folder value (that's where my .md files are) but I got the same issue

**Comment by tomrutgers** [comment]
Have you tried putting your markdown files in a folder instead of in your sites root?

**Comment by q-omar** [comment]
I have a somewhat similar issue. You can view my folder structure here: [https://i.imgur.com/AGOJ3h5.png](url) and the contents of my config.yml

```
#https://www.netlifycms.org/docs/add-to-your-site/

backend:
  name: github
  repo: https://github.com/jackieluc/insiight
  branch: test # Branch to update (optional; defaults to master)
  site_domain: https://test--insiight.netlify.com/#/
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
```
 and index.html are
```
<!-- https://www.netlifycms.org/docs/add-to-your-site/ -->

<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>
  <link rel="stylesheet" href="https://unpkg.com/netlify-cms@^2.0.0/dist/cms.css" />
</head>
<body>
  <!-- Include the script that builds the page and powers Netlify CMS -->
  <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
</body>
</html>
```

I've tried going to http://localhost:8080/admin/#/ via npm start and it doesn't work there. It doesn't work at http://127.0.0.1:8080/admin/#/ when doing npm build preview either. I also tried branch deploys via the Netlify console but https://test--insiight.netlify.com/admin/# (which is our site) doesn't work either.
