### ISSUE TITLE
Github Backend login for NetlifyCMS users on their own host using Netlify oauth gateway doesn't work

### ISSUE THREAD

**Issue by Mataniko** [netlify/netlify-cms#1890]
**Describe the bug**
When using the Github backend, the auth window on "api.netlify.com" never sends back the Github token to NetlifyCMS, even if authentication was successful.

**To Reproduce**
1. Create a simply netlifycms site in your own domain. Running it on netlify.com or locally doesn't reproduce the issue. A bare minimum config with a Github backend would suffice. A sample config.yml can be found below.
2. Create a GitHub oauth app (docs)
3. Connect it to your Netlify account (docs) 
4.Try to login, observe the window stuck on "Authorized"
5. Try to login on a local copy, observe login works.

**Expected behavior**
Users should be able to login outside localhost. This fails remotely because the Authentication window has a host check before deciding to send the token back or not to the Login window.

**Applicable Versions:**
 - Netlify CMS version: 2.2.0
 - Git provider: GitHub
 - OS: Any
 - Browser version: Any

**CMS configuration**
```
backend:
  name: github
  repo: mataniko/XXXXXXX
  site_domain: XXX.netlify.com

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: 'news'
    label: 'News Articles'
    extension: 'json'
    folder: 'data/news'
    create: true
    delete: false
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}"
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'X', hidden: true }
      - { label: 'Content', name: 'content', widget: 'markdown' }
```

**Additional context**
Here is the relevant code snippet from the Authentication window:
```
if ( host === "cms.netlify.com" || host == "localhost") { 
 window.opener.postMessage( 'authorization:github:success:{\"token\":\"XXXXXXXXXXXXXXXXXXXX\",\"provider\":\"github\"}', e.origin ); 
}
```
