### ISSUE TITLE
[Identify] does not show the correct form

### ISSUE THREAD

**Issue by dantehemerson** [netlify/netlify-cms#1902]
Netlify should show me this: https://festive-mccarthy-8e1933.netlify.com/admin/#/ (Example of Netlify site)
![](http://i.imgur.com/GxwfqEc.png)

instead it shows me only the github botton: https://dantecalderon.com/admin/?no-cache=1#/
![](http://i.imgur.com/YnJQHXV.png)

My repository: https://github.com/dantehemerson/dantecalderon.com

 - Netlify CMS version: 3.0.5
 - Git provider: GitHub
 - OS: Linux Debian
 - Browser version  chrome 70.0.3538.110
 - Node.JS version:8.12.0

`config.yml`
```yml
backend:
  name: github
  repo: dantehemerson/dcweb

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Model, name: model, widget: hidden, default: post }
      - { label: Title, name: title }
      - { label: Description, name: description, widget: text}
      - { label: Path, name: path }
      - { label: "Featured Image", name: thumbnail, widget: image }
      - { label: Date, name: date,  widget: datetime }
      - { label: Published, name: published, widget: boolean, default: true }
      - { label: "Header Style", name: style, widget: select, options: ["default", "normal-img", "medium-img", "full-image", "doble-column"], default: default}
      - { label: Tags (Separar con comas), name: tags, widget: list }
      - { label: Body, name: body, widget: markdown }

  - name: portfolio
    label: Projects
    folder: src/pages/projects
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: Model, name: model, widget: hidden, default: project }
      - { label: Title, name: title }
      - { label: Subtitle, name: subtitle }
      - { label: Description, name: description, widget: text}
      - { label: Path, name: path }
      - { label: "Featured Image", name: thumbnail, widget: image }
      - { label: Images, name: images, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Description, name: description}]}
      - { label: Date, name: date,  widget: datetime }
      - { label: Finished, name: finished, widget: boolean, default: true }
      - { label: Published, name: published, widget: boolean, default: true }
      - { label: "Header Style", name: style, widget: select, options: ["default", "normal-img", "medium-img", "full-image", "doble-column"], default: default}
      - { label: Tags (Separar con comas), name: tags, widget: list }

      # Datos propios de un proyecto
      - { label: Roles (Separar con comas), name: roles, widget: list }
      - { label: Stack (Separar con comas), name: stack, widget: list }
      - { label: Client, name: 'client', widget: string, default: Personal }
      - { label: Repository, name: 'repository', widget: string, required: false }
      - { label: Licence, name: licence, widget: string, default: MIT }
      - { label: Website, name: 'website', widget: string, required: false }
      - { label: Body, name: body, widget: markdown }
```
**My settings in Netlify app**
![](http://i.imgur.com/Twk0Pjx.png)
-----
![screencapture-app-netlify-sites-dantecalderon-settings-identity-2018-11-23-03_12_38](https://user-images.githubusercontent.com/18385321/48933359-fde2b680-eecd-11e8-8f65-2ed6c5dafdbf.png)
