### ISSUE TITLE
Deprecation warning in Chrome

### ISSUE THREAD

**Issue by davidkazuhiro** [netlify/netlify-cms#1909]
**Describe the bug**
Chrome is giving a deprecation warning on the collection edit page

```
[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.
```

URL: https://company.com/netlify-cms/#/collections/post/entries/my-post

**To Reproduce**
1. Open Netlify CMS in Google Chrome
2. Click on an existing post to edit it
3. View the Developer Tools page to see the Console

**Expected behavior**
There is no warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/474054/48980296-76ce5200-f10a-11e8-88e1-e15364ebf72b.png)

**Applicable Versions:**
- Netlify CMS version: 2.2.0
- Git provider: GitHub Enterprise 2.14
- OS: macOS High Sierra
- Browser version: chrome 70

**CMS configuration**
```
backend:
  name: github
  repo: test/test
  base_url: https://netlify-oauth-client.local
  api_root: https://ghe.local/api/v3

media_folder: images
publish_mode: editorial_workflow

collections:
  - name: post
    label: Post
    folder: _posts
    create: true
    fields:
      - {name: layout, label: Layout, widget: hidden, default: post}
      - {name: title, label: Title}
      - {name: cover, label: Cover, widget: image}
      - {name: date, label: Date, widget: datetime}
      - {name: categories, label: Categories, widget: hidden, default: posts}
      - {name: body, label: Body, widget: markdown}
```
