### ISSUE TITLE
Required field notification appears even on successful save

### ISSUE THREAD

**Issue by emckay** [netlify/netlify-cms#1910]
**Describe the bug**

When I enter information in all required fields (including a date and markdown widget) and hit "publish", a toaster notification that says "Oops, you've missed a required field. Please complete before saving." appears, but the entry is still published.

**To Reproduce**
1. Click "create a new page"
2. Enter data in all fields
3. Click "publish" -> "publish now"
4. Observe toaster notification saying "Oops, you've missed a required field. Please complete before saving."

**Expected behavior**
I expect no toaster notification to appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/899325/48987670-378a0c00-f0de-11e8-8b95-0682e757f2a8.png)

**Applicable Versions:**
 - Netlify CMS version: 2.2.0
 - Git provider: BitBucket
 - OS: Ubuntu
 - Browser version: Chrome 61

 - Node.JS version: 10.13.0

**CMS configuration**
```
backend:
  name: bitbucket
  repo: *omitted*

media_folder: static/assets
public_folder: assets

collections:
  - name: page
    label: Page
    folder: static/pages
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
```
**Additional context**
Another user reported this on https://github.com/netlify/netlify-cms/issues/649
