### ISSUE TITLE
Extend commit message template tags with collection values

### ISSUE THREAD

**Issue by buz-zard** [netlify/netlify-cms#1912]
**Is your feature request related to a problem? Please describe.**

When content editors do updates to already created entity, the cms creates multiple similar commits (`Update collection {{slug}}` x N ... ). We want our content editors to provide some more info in the commit messages. I'm aware of https://www.netlifycms.org/docs/beta-features/#commit-message-templates, but I'd like to pass collection data to the template.

**Describe the solution you'd like**

`commit_messages` could also be described for collections, via such API:

```
backend:
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”

collections:
  - label: Post
    name: post
    folder: src/content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{uri}}"
    fields:
      - { label: "Describe the changes", name: changes, required: true }
      - { label: Title, name: title, required: true }
      - { label: Body, name: body, widget: markdown, required: true }
    commit_messages:
      update: Update {{collection}} “{{slug}}” - {{changes}}
```

**Describe alternatives you've considered**

I tried to include the field in the slug:

```
backend:
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”

collections:
  - label: Post
    name: post
    folder: src/content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{uri}}_{{changes}}"
    fields:
      - { label: "Describe the changes", name: changes, required: true }
      - { label: Title, name: title, required: true }
      - { label: Body, name: body, widget: markdown, required: true }
```

But since the filename doesn't change, the slug passed to commit template doesn't use the latest values.

**Additional context**
