### ISSUE TITLE
Incorrect branch name with GitHub backend

### ISSUE THREAD

**Issue by KarthikBhaskara** [netlify/netlify-cms#1933]
**Describe the bug**
According to the [docs](https://www.netlifycms.org/docs/configuration-options/#publish-mode), if my backend is Github, the branch name created from the CMS should be of the form `cms/collectionName-slug`, however, when I push from the CMS, the branch name is of the form `cms/slug`. This creates issues when I am modifying multiple pages of the same name from different directories, for example, `a/intro/` and `b/intro/`.

**Applicable Versions:**

 - Netlify CMS version: 2.1.3
 - Git provider: GitHub

**CMS configuration**
```
backend:
  name: github
  repo: random/repo
  squash_merges: true

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
  - name: a
    label: a
    folder: content/a
    slug: "{{slug}}"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: b
    label: b
    folder: content/integration-guides/b
    slug: "{{slug}}"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
```
