### ISSUE TITLE
Delete Option Set to False for File Type Collection

### ISSUE THREAD

**Issue by j-brenneman** [netlify/netlify-cms#1937]
## Description
I have set `delete: false` on a collection of type `files`. When I navigate to the admin interface, I am still seeing and able to delete that collection instance.

## Reproduction
1. Set `delete:false` for a file type collection in the `config.yml`
2. Naviagte to that collection type in the Admin UI
3. Click `Delete Published Entry`
4. Confirm Deletion
5. Publish / Save (Editorial Workflow)
6. Collection is deleted

## Expected behavior
The `Delete Published Entry` should not appear, or at the very least there should be a pop up that prevents the end user from deleting the collection instance.

## Screenshots
**Admin Page Home**
<img width="1427" alt="screen shot 2018-12-05 at 11 47 52 pm" src="https://user-images.githubusercontent.com/12101361/49562128-34fe9200-f8e8-11e8-9d05-6f1fb1f50ca9.png">

**Header Edit View**
<img width="1434" alt="screen shot 2018-12-05 at 11 47 21 pm" src="https://user-images.githubusercontent.com/12101361/49562108-257f4900-f8e8-11e8-9043-6a8fb32b52e4.png">

## Applicable Versions
 - Netlify CMS version: ^1.0.0
 - Git provider: GitHub
 - OS: MacOS Sierra 10.12.6
 - Browser version Chrome  Version 70.0.3538.102
 - Node.JS version: 10.14.1

## CMS configuration
```yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - label: Landing Page
    name: landing_page
    files:
      - label: Header
        name: landing_page_header
        file: content/landing_page/header.yml
        delete: false
        fields:
          - label: Title
            name: title
            widget: string
          - label: Sub Text
            name: sub_text
            widget: string
          - label: Background Image
            name: backgroundImage
            widget: image
      - label: About
        name: landing_page_about
        file: content/landing_page/about.yml
        delete: false
        fields:
          - label: Title
            name: title
            widget: string
          - label: Paragraph One
            name: paragraph_one
            widget: markdown
          - label: Primary Image One
            name: primary_image_one
            widget: image
          - label: Primary Image Two
            name: primary_image_two
            widget: image
          - label: Highlight Text
            name: highlight_text
            widget: text
          - label: Paragraph Two
            name: paragraph_two
            widget: markdown
          - label: Secondary Image
            name: secondary_image
            widget: image
```
