### ISSUE TITLE
Select widget doesn't render options

### ISSUE THREAD

**Issue by 0x80** [netlify/netlify-cms#1939]
**Describe the bug**
When using the select widget, I have tried specifying the options as a list of strings and as a key/value object. I can see that the options are passed as props to the `SelectContainer` component and its `Control` child, however the rendered dropdown is empty. The number of options in the dropdown matches the configured number of options, but the elements are blank. Selecting a blank option also doesn't satisfy the "required" setting, so that indicates that nothing is being selected.

**Screenshots**

<img width="512" alt="screenshot 2018-12-06 21 07 51" src="https://user-images.githubusercontent.com/1193520/49609197-1a392580-f99b-11e8-8ffc-b9679e8a58d3.png">

**Applicable Versions:**

 - Netlify CMS version: 2.3.0
 - Browser version chrome 70

**CMS configuration**

```yaml
	fields:
        - {
          label: 'Building Nr',
          name: 'building',
          widget: 'select',
          options: { 'gebouw 1': 1, 'gebouw 2': 2, 'gebouw 3': 3 },
          required: false,
        }
```

**Comment by barthc** [comment]
@0x80  try something like so:
```
      - label: 'Building Nr'
        name: 'building'
        widget: 'select'
        options:
          - { label: 'gebouw 1', value: 1 }
          - { label: 'gebouw 2', value: 2 }
          - { label: 'gebouw 3', value: 3 }

**Comment by 0x80** [comment]
@barthc I am not very experienced with YAML but according to my editor (VSCode) that is not valid.

It allows me to do this:

```yaml
- {
          label: 'Building Nr',
          name: 'building',
          widget: 'select',
          options: [{ label: 'gebouw 1', value: 1 }, { label: 'gebouw 2', value: 2 }, { label: 'gebouw 3', value: 3 }],
          required: false,
        }
``` 

but that doesn't work either.

Like I said I also tried an array of strings like so:

```yaml
- {
          label: 'Building Nr',
          name: 'building',
          widget: 'select',
          options: ['1', '2', '3'],
          required: false,
        }
}
```

That didn't render the select widget either. That's matching the example in the docs...
