### ISSUE TITLE
Select widget doesn't respect "required" config option

### ISSUE THREAD

**Issue by 0x80** [netlify/netlify-cms#1940]
**Describe the bug**

Setting `required: false` in the configuration options of a select widget seems to have no effect. You will still get and error saying the value is required.

**Applicable Versions:**

 - Netlify CMS version: 2.3.0
 - Browser version chrome 70

**CMS configuration**

```yaml
      - {
          label: 'Building Nr',
          name: 'building',
          widget: 'select',
          options: { 'gebouw 1': 1, 'gebouw 2': 2, 'gebouw 3': 3 },
          required: false,
        }
```

**Additional context**
