### ISSUE TITLE
Don't prepend a hyphen when a title starts with a double quote

### ISSUE THREAD

**Issue by rdebeasi** [netlify/netlify-cms#1963]
**Describe the bug**

When a title begins with a double quote character, a hyphen is added to the beginning of the resulting slug and filename. For example, `title: '"Quote" Wall'` produces a file called `-quote-wall.md` and a branch called `cms/-quote-wall`.

See https://github.com/openpracticelibrary/openpracticelibrary/pull/569/commits/752fae1d4346e492cdc68ca62a9699d98e656b48 for an example.

Potentially related: #1698

**To Reproduce**

1. Configure Netlify CMS to use the slug for the filenames in a `post` collection.
```yaml
collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
 ```
2. Create a post in Netlify CMS.
3. Add a title with a quotation mark at the beginning, such as `"quotation" test`.
4. A file named `-quotation-test.md` should appear. (It will be in a pull request if editorial workflow is enabled. Otherwise, it will be committed to master.)

**Expected behavior**

I would expect the steps above to produce a file called `quotation-test.md`

**Applicable Versions:**

 - Netlify CMS version: 2.3.1
 - Git provider: GitHub
 - OS: Fedora 29
 - Browser version: Firefox 63

**CMS configuration**

https://github.com/openpracticelibrary/openpracticelibrary/blob/staging/static/admin/config.yml
