### ISSUE TITLE
Login Fails With Self-hosted Gitlab instance

### ISSUE THREAD

**Issue by Undistraction** [netlify/netlify-cms#1966]
**Describe the bug**
Logging in to a self-hosted Gitlab instance results in an error popup with the message:

> Failed to load settings from `/.netlify/identity`

![caps](https://user-images.githubusercontent.com/161489/50286559-ac3f3480-0457-11e9-9896-da663fdaa15f.jpeg)

This is despite the configuration using Gitlab as the backend.

**To Reproduce**

1. Deploy application that uses Github self-hosted backend with the config below

2. Navigate to `example.com/admin`

3. Click 'Login With Github'

![capss](https://user-images.githubusercontent.com/161489/50286725-3be4e300-0458-11e9-8038-a5696dcd5f26.jpeg)

**Expected behavior**
Successful login to CMS

**Applicable Versions:**

 - Netlify CMS version: 2.3.1
 - Git provider: Self-hosted Gitlab
 - OS: OSX 10.13.6
 - Browser version Chrome 71
 - Node.JS version: 8.11.3/

**CMS configuration**
```
backend:
  name: gitlab
  repo: company/repo-name # Path to your GitLab repository
  auth_type: implicit # Required for implicit grant
  app_id: XXXXXXXXXXXXXXXXXXXXX # Application ID from your GitLab settings
  api_root: https://gitlab.company.com/api/v4
  base_url: https://gitlab.company.com
  auth_endpoint: oauth/authorize
```
