### ISSUE TITLE
Securing cloudinary credentials

### ISSUE THREAD

**Issue by kishaningithub** [netlify/netlify-cms#1967]
To integrate cloudinary, the [official documentation here](https://www.netlifycms.org/docs/cloudinary/#connecting-cloudinary-to-netlify-cms) asks one to put in `api_key` and `cloud_name` inside `config.yml`.

Aren't these secure parameters? IMHO these 2 values should probably come into the application via environment variables and should never be checked in inside the `config.yml` file.

What are your views on this from a security perspective ?

**Comment by levibuzolic** [comment]
`cloud_name` is definitely not considered secret and `api_key` is generally somewhat safe to be exposed, given your Cloudinary permissions are set up to disallow unsigned uploads.

Previously I've used Netlify functions + Netlify identity to generate authentication signatures for Cloudinary to allow uploads to my users without them requiring Cloudinary credentials.

**Comment by pdkn** [comment]
Is it possible to the config.yml to access Netlify build Environment Variables? i.e 
```
media_library:
  name: cloudinary
  config:
    cloud_name: ${CLOUDINARY_CLOUD_NAME}
    api_key: ${CLOUDINARY_API_KEY}
```

(not working)
