### ISSUE TITLE
Fields not editable with an html extension in a file collection

### ISSUE THREAD

**Issue by wyhaines** [netlify/netlify-cms#1992]
**Describe the bug**

With a file collection, with an `html` extension, fields in the front matter aren't editable. Changing nothing other than the file extension, from `html` to `md`, makes everything work as expected.

**To Reproduce**

```
      - label: "index.html documents"
        name: "index_documents"
        file: "src/_includes/documents.html"
        format: "frontmatter"
        extension: "html"
        description: "The documents navigation column on the left of the index.html page."
        fields:
          - {label: Title, name: title, default: "FUND DOCUMENTS", widget: string}
          - {label: Body, name: body, widget: markdown}
```

The `title` field will not appear when one tries to edit this content.

Change the file to have a `.md` ending, though, with corresponding changes in the above configuration, and everything works as expected.

**Applicable Versions:**
This is with Netlify CMS version 2.3.2
