### ISSUE TITLE
Cloudinary per field configuration doesn't work

### ISSUE THREAD

**Issue by matuzo** [netlify/netlify-cms#2001]
Hi!

**Describe the bug**
I'm using Cloudinary as my media library. I want to set `output_filename_only: false` for all fields globally and enable it on specific fields but it only works globally.

With the config below I always get the full url.

**Expected behavior**
I would expect to define a global value for how the output of files should look like and change it on specific fields. At least thats how I understand the documentation.

> The Cloudinary media library integration can be configured in two ways: globally and per field
https://www.netlifycms.org/docs/cloudinary/#cloudinary-configuration-options

In my example I'd expect a full url in the body field and only the file name in the image field

**Applicable Versions:**

 - Netlify CMS version: netlify-cms 2.3.3
 - Git provider:GitHub
 - OS: macOS High Sierra
 - Browser version Firefox Nightlx

**CMS configuration**
```
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: my_name
    api_key: 1234567890

collections:
  - name: 'til' 
    label: 'TIL' 
    folder: 'til' 
    create: true
    slug: '{{slug}}' 
    fields:
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - { label: 'Image', name: 'image', widget: 'image', required: false, media_library: { output_filename_only: true }  }
```

Thank you!
