### ISSUE TITLE
number widget saving as string with valueType int

### ISSUE THREAD

**Issue by zanona** [netlify/netlify-cms#2007]
**Describe the bug**

I have a field set to the number widget where it's taking an initially set integer value but saving it as a string.

**To Reproduce**

**config.yml**
```yaml
collections:
  - name: product
    label: Products
    extension: yml
    format: yml
    fields:
      - name: price
        label: price
        widget: number
        valueType: int
        default: 0
```

**document.yml**
```yaml
price: 264
```

After changing the product price to `265`  through Netlify CMS, the updated document looks like:

```yaml
price: '265'
```

**Expected behavior**

Save output as integer

**Applicable Versions:**

https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js
