### ISSUE TITLE
identifier_field doesn't use field value if field has a widget type of hidden

### ISSUE THREAD

**Issue by Undistraction** [netlify/netlify-cms#2016]
**Describe the bug**
Using `identifier_field` for a collection fails to use the field value if that field has its `widget` type set to `hidden`.

**To Reproduce**
```
  - name: forms
    label: Forms
    folder: src/settings/forms/
    identifier_field: name
    fields: 
      - name: name
        label: Name
        widget: hidden
      - name: id
        label: Id
        widget: string
```

**Expected behavior**
The collection item's `name` field is used in the list of collection items.

**Actual behavior**
Netlify CMS falls back to using the item's `id` instead.

**Applicable Versions:**
```
Netlify CMS version: netlify-cms 2.3.2
Git provider: Gitlab
OS: OSX
Browser version: 71.0.3578.98
Node.JS version: 8.11.3
```

**Additional context**
