### ISSUE TITLE
Error when creating preview

### ISSUE THREAD

**Issue by jakegore** [netlify/netlify-cms#2057]
**Describe the bug**
I am trying to use a react component as a live preview with gatsby and the netlify-cms npm package. I think I have set it all up correctly, but in the preview window, it doesn't display the template and it says:
```
Sorry!
There's been an error - please report it!
TypeError: Cannot read property 'get' of undefined
```

**To Reproduce**

Make a new gatsby project with my files and try to edit a 'page' collection in the netlify cms admin panel.

**Expected behavior**
It would put the values into the react component and display it in the live preview.

**Screenshots**

![error](https://i.ibb.co/M7fRT3N/2019-02-03-183313-1920x1080-scrot.png)

**Applicable Versions:**

 - Netlify CMS version: 2.3.3
 - Git provider: Gitlab
- OS: Arch Linux
 - Browser version Chromium 72
 - Node.JS version: 6.7.0

**CMS configuration**

```yml
backend:
  name: git-gateway

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Index"
        name: "index"
        file: "src/pages/index/index.md"
        fields:
          - { label: "Path", name: "path", widget: "hidden" }
          - { label: "Main", name: "main", widget: "object", fields: [
              { label: "Heading", name: "heading", widget: "string" },
              { label: "Description", name: "description", widget: "markdown" }
            ]}
```

**Additional context**

src/cms/cms.js
```javascript
import CMS from "netlify-cms"
import IndexPreview from "./preview-templates/index"

CMS.registerPreviewTemplate('index', IndexPreview)
```

src/cms/preview-templates/index.js
```javascript
import React from "react"
import { IndexPageTemplate } from "../../templates/index.js"

const IndexPreview = ({ entry, widgetFor }) => {
  return (
    <IndexPageTemplate
      heading={entry.getIn(['data', 'heading'])}
      description={widgetFor('description')}
    />
  )
}

export default IndexPreview
```

src/templates/index.js
```javascript
import React from "react"
import { graphql } from "gatsby"
import Markdown from "react-markdown"
import Layout from "../components/layout"

export const IndexPageTemplate = ({
  heading,
  description
}) => (
  <>
    <h1>{ heading }</h1>
    <Markdown source={ description } />
  </>
)

const IndexPage = ({ data }) => {
  const fm = data.markdownRemark.frontmatter

  return (
    <Layout>
      <IndexPageTemplate
        heading={fm.main.heading}
        description={fm.main.description}
      />
    </Layout>
  )
}

export default IndexPage

export const mainQuery = graphql`
  query MainQuery($path: String!) {
    markdownRemark(frontmatter: { path: { eq: $path } }) {
      frontmatter {
        main {
          heading
          description
        }
      }
    }
  }
`
```
