### ISSUE TITLE
Relation with valueField: title looses relation on update

### ISSUE THREAD

**Issue by FredrikSigvartsen** [netlify/netlify-cms#2063]
**Describe the bug**

I'm using NetlifyCMS and GatsbyJS. I'm having a problem to make it easy for the customer to make relations through other pages with the relation-widget in Netlify CMS. The problem appears when the customer is updating the title field: 
`- {label: "Product category", hint: "Search category name", name: "productCategory", widget: "relation", collection: "categories", searchFields: ["title"], valueField: "title", displayFields: ["title"]}`

**To Reproduce**
1. Map "productCategory" with markdown.frontmatter.title in gatsby-config-js. 
2. Make a Product that has a relation to a category. E.g. the product "Candybar" to category "Chocolate". 
3. Change category title from "Chocolate" to "Cocoa". 
4. Error: Then the relation between the product Candybar and Cocoa/Chocolate is lost, and then the user would need to update all products with a relation to Cocoa-category.  

**Expected behavior**
I would expect the relation to be preserved even though the title is changed. There are multiple ways to handle this, as far as my knowledge goes:

1. When changing the **_title_** the **slug** is not updated, and therefore it could be use as a valueField in the relation-widget. Is this possible? I have seen: #445 , but will this include this possibility? 
2. Using a generated ID of some kind. How to make this possible?

Please suggest other solutions to this issue. 

**Applicable Versions:**
 - Netlify CMS version: 2.3.2 
 -  Gatsby: ^2.0.85
 - Git provider: Github
 - OS: MacOS Mojave 10.14.2

**CMS configuration**
```
collections:
  - name: "products"
    label: "Products"
    folder: "src/pages/produkter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-item"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Product category", name: "productCategory", widget: "relation", collection: "kategorier", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
      - {label: "Produkt ID", name: "productId", widget: "string", default: "000000"}
      - {label: "ELNR", name: "ELNR", widget: "string", default: "000000"}
      - {label: "Packaging", name: "packaging", widget: "string", default: "1 stk"}
  - name: "kategorier"
    label: "Produkt kategorier"
    description: "Her kan du legge til/fjerne produktkategorier."
    folder: "src/pages/kategorier"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category-item"}
      - {label: "Tittel", name: "title", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
      - label: "Parent category (if any)"
        name: "parentCategory"
        widget: "relation"
        required: false
        collection: "kategorier"
        searchFields: ["title"]
        valueField: "title"
        hint: "Hvis denne er tom, er denne kategorien på høyeste nivå. Hvis den har en forelderkategori, er dette en subkategori"
      - {label: "SEO Beskrivelse", name: "seoDescription", required: false, widget: "text"}
```

**Additional context**

Thank you in advance, and thank you for providing Netlify CMS! I really enjoy it as a developer.
