### ISSUE TITLE
Modify field in config after creation

### ISSUE THREAD

**Issue by tonymwaruka** [netlify/netlify-cms#2066]
**Describe the bug**

I originally created a list widget for images (repeatable). Everything worked as expected. I then realized that I needed to add an `alt` tag so I went back to the `list` widget and modified it. Here is what I had before:

```
-
 label: 'Awards Section'
 name: awards
 widget: object
 fields:
  -
   label: Blurb
   name: blurb
   widget: object
   fields:
    -
     label: Title
     name: title
     widget: string
    -
     label: 'Company Name'
     name: ptext
     widget: string
    -
     label: Logos
     name: image
     widget: list
     field:
      label: Image
      name: image
      widget: image
  -
   label: Image
   name: dashimage
   widget: image

```
I updated `Logos` to:

```
-
 label: 'Awards Section'
 name: awards
 widget: object
 fields:
  -
   label: Blurb
   name: blurb
   widget: object
   fields:
    -
     label: Title
     name: title
     widget: string
    -
     label: 'Company Name'
     name: ptext
     widget: string
    -
     label: Logos
     name: logos
     widget: list
     fields:
      -
       label: Logo
       name: image
       widget: image
      -
       label: Alt
       name: alt
       widget: string
     required: false
  -
   label: Image
   name: dashimage
   widget: image
  -
   label: Alt
   name: alt
   widget: string
```
**Error**

`TypeError: e.get is not a function`

**Expected behavior**

After running local dev, the cms should have the new fields available in existing collections. Right now, you can add a new `collection` (this is of type `folder`) and the above, modified config works (i.e the images now have `alt` properties). But all existing collections just throw the error when you click to open.

**Screenshots**

![image](https://user-images.githubusercontent.com/7131552/52437738-de265c00-2ad4-11e9-99e7-b45bdd48cd0b.png)
![image](https://user-images.githubusercontent.com/7131552/52437750-e7afc400-2ad4-11e9-83e0-e86c85abcfc3.png)
![image](https://user-images.githubusercontent.com/7131552/52437784-00b87500-2ad5-11e9-8577-8c2cb9e037be.png)

**Applicable Versions:**

 - netlify-cms 2.3.2
 - Git provider: GitHub
 - OS: Mojave (Mac)
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version: v11.6.0

**Additional context**
Question is: Can you modifying an existing collection's widget without breaking existing entries on the `cms` admin area or is this a bug? I'm very new to this so it might be something minor I'm missing.
