### ISSUE TITLE
Errors in setting up basic middleman site

### ISSUE THREAD

**Issue by bdougie** [netlify/netlify-cms#207]
**- BUG in setup**

**- What is the current behavior?**
My netlify-cms cannot parse my config.yml. I am user middleman and added the admin folder to my source directory, as well as noted the public folder name in my config.yml.

https://github.com/bdougie/blog/pull/3

**- If the current behavior is a bug, please provide the steps to reproduce.**
Visit https://cms-setup--developingjourney.netlify.com/admin#/ to see the error

![default](https://cloud.githubusercontent.com/assets/5713670/21693714/d40988de-d336-11e6-9022-9e11d6b9fad9.png)

```
// current state of my admin/config/yml
backend:
  name: github
  repo: bdougie/blog # Path to your Github repository
  branch: live-blog # Branch to update (master by default)

media_folder: "source/img/uploads" # Folder where user uploaded files should go
public_folder: "source" # CMS now knows 'source' is the public folder and will strip this from the path

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "." # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Foo", name: "foo", widget: "foo"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
```

**- What is the expected behavior?**
I was expecting to see the GitHub login button.

**- Please mention your node.js, and operating system version.**
node v6.8.0
ruby v2.3
OSX 10.11.6
middleman v3.3.11
