### ISSUE TITLE
Some API calls fail with the BitBucket backend when using a branch that contains a slash

### ISSUE THREAD

**Issue by OscarBarrett** [netlify/netlify-cms#2105]
**Describe the bug**

When using `bitbucket` as the backend with a branch that contains a slash (e.g. `feature/netlify`) some API calls to [repositories/{username}/{repo_slug}/src/{node}/{path}](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/src/%7Bnode%7D/%7Bpath%7D) will 404 and content is not listed or editable. It appears that the BitBucket API expects a single path parameter to describe the node.

Everything works fine if we reference a branch on the same commit that does not contain a slash.

**To Reproduce**

1. Push a branch with a slash in it (e.g. `feature/netlify`)
2. Set up the BitBucket backend to use this branch:
```yml
backend:
  name: bitbucket
  repo: user/repo
  branch: feature/netlify
```

**Expected behavior**

The API calls shouldn't fail. They may need to be made with the commit hash of the branch head instead.

**Applicable Versions:**

 - Netlify CMS version: 2.4.2
 - Git provider: BitBucket
 - OS: MacOS 10.13
 - Browser version: Firefox 65

**CMS configuration**

```yml
backend:
  name: bitbucket
  repo: <repo>
  branch: feature/netlify

media_folder: 'static/img/uploads'
public_folder: '/img/uploads'

collections:
  - name: pages
    label: Pages
    folder: content
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Image, name: image, widget: image, allow_multiple: false }
      - { label: Body, name: body, widget: markdown }
```
