### ISSUE TITLE
lists within lists of variable type

### ISSUE THREAD

**Issue by speexy** [netlify/netlify-cms#2110]
**Is your feature request related to a problem? Please describe.**
Feature. As far as I understand each field in a list of variable types has to be an object. It would be nice if it could also be a simple list. My usecase: I want to have a type "Image Slider". The field needs to be an image with the option to add more images. My workaround right now is to wrap a list in an object. From the user perspective this creates noise in the CMS for no apparent reason.

**Describe the solution you'd like**
Under types I want to have a field with a list-widget and let the user append items to that list.

**Comment by erquhart** [comment]
You can use the `field` property in place of `fields` to accomplish this.

```yaml
collections:
  - name: pages
    fields:
      - name: images
        label: Images
        widget: list
        field: {name: image, label: Image, widget: image}
```
