### ISSUE TITLE
Draft cannot be saved when collection folder property has a leading slash

### ISSUE THREAD

**Issue by sddaniels** [netlify/netlify-cms#2115]
**Describe the bug**
If the `config.yml` file contains leading slashes in the `folder` property of a collection, it becomes impossible to save changes to a draft when that branch gets behind commits made on master. The root cause of this is that GitHub does not accept a leading slash on the `path` property when POSTing to the `/trees` endpoint. The following request is being attempted in that scenario:

`{"base_tree":"c1a16b0874e83ef25562c71bce9eb090f300d1b1","tree":[{"path":"/_pages/frequently-asked-questions.md","mode":"100644","type":"blob","sha":"b06e563e4d74960b131676daec515dbeb25b4c9a","size":2643,"url":"https://api.github.com/repos/Dwolla/monetery-jekyll/git/blobs/b06e563e4d74960b131676daec515dbeb25b4c9a"}]}`

This request results in a 422 error, and the editor sees the error in the screenshot below.

**To Reproduce**
1. Configure a site with editorial workflow enabled and leading slash in a collections folder property, similar to the config file below
2. Save a draft change in the collection you set up in Step 1
3. Publish a change to a separate page, or do anything that adds a commit to master such as merging a manual PR
4. Go back to the page you edited in Step 2. Attempt to make another change and save the draft
5. You should see the "Failed to persist entry" error in the screenshot

**Expected behavior**
The leading slash in the collections folder should be trimmed before using that value in a POST to the GitHub `/trees` endpoint.

**Screenshots**
![screen shot 2019-02-20 at 12 59 15 pm](https://user-images.githubusercontent.com/1263925/53135049-4c403980-353f-11e9-9518-f4a4986f9e6d.png)

**Applicable Versions:**
Netlify CMS 4.2.2/GitHub/Git Gateway

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master
  identity_url: "https://monetery.com/.netlify/identity"
  gateway_url: "https://monetery.com/.netlify/git"
  squash_merges: true

publish_mode: editorial_workflow
media_folder: "assets/img/uploads"

site_url: https://monetery.com
logo_url: https://monetery.com/assets/img/monetery-logo-color.svg

collections:
  - label: "Sitewide Options"
    name: options
    editor:
      preview: false
    files:
      - label: "Navigation Menu"
        name: nav
        file: "_data/nav.yml"
        fields:
          - {label: "Additional Header Text", name: headerText, widget: string, required: false}
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: topLevelItems
            widget: list
            fields:
              - {label: "Display Text", name: displayText, widget: string}
              - {label: URL, name: url, widget: string}
              - label: "Item Type"
                name: itemType
                widget: select
                options: ["Link", "Button"]
              - label: "Nav Items"
                label_singular: "Nav Item"
                name: childItems
                widget: list
                fields:
                  - {label: "Display Text", name: displayText, widget: string}
                  - {label: "URL", name: url, widget: string}
                  - {label: "Icon", name: icon, widget: image}
      - label: "Footer"
        name: footer
        file: "_data/footer.yml"
        fields:
          - {label: "Blurb", name: blurb, widget: text}
          - label: "Footer Logo"
            name: logo
            widget: object
            fields:
              - {label: "Alt Text", name: altText, widget: string}
              - {label: "Image", name: path, widget: image}
              - {label: "URL", name: url, widget: string}
          - label: "Social Links"
            label_singular: "Social Link"
            name: social
            widget: list
            fields:
              - {label: "Alt Text + Title", name: altText, widget: string}
              - {label: "Image", name: path, widget: image}
              - {label: "URL", name: url, widget: string}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - { label: "Default", value: "" }
                  - { label: "Skinny", value: "footer__social-item--skinny" }
      - label: "Defaults"
        name: defaults
        file: "_data/defaults.yml"
        fields:
          - {label: "Page Title", name: title, widget: string}
          - {label: "Meta Description", name: metaDescription, widget: text}
          - label: "Social Sharing"
            name: social
            widget: object
            required: false
            fields:
              - {label: "OpenGraph Image", name: ogImage, widget: image}
              - {label: "Twitter Image", name: twitterImage, widget: image}
      - label: "404 Page"
        name: notfound
        file: "_data/notfound.yml"
        fields:
          - {label: "Content", name: content, widget: markdown}
  - label: "Pages"
    label_singular: "Page"
    name: pages
    folder: "/_pages"
    create: true
    slug: "{{slug}}"
    preview_path: "{{permalink}}"
    editor:
      preview: false
    fields:
      - {label: "Title", name: title, widget: string}
      - {label: "Permalink", name: permalink, widget: string}
      - label: "Layout Template"
        name: "layout"
        widget: "select"
        default: "blocks"
        options:
          - { label: "Default", value: "blocks" }
          - { label: "Home Page", value: "home" }
      - {label: "Meta Description", name: metaDescription, widget: text, required: false}
      - label: "Social Sharing"
        name: social
        widget: object
        required: false
        fields:
          - {label: "OpenGraph Image", name: ogImage, widget: image, required: false}
          - {label: "Twitter Image", name: twitterImage, widget: image, required: false}
      - label: "Content Blocks"
        label_singular: "Content Block"
        name: blocks
        widget: list
        types:
          - label: "Hero"
            name: hero
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string}
              - {label: "Sub-heading", name: boxHeading, widget: string, required: false, hint: "Appears above main heading in all caps."}
              - {label: "Content", name: content, widget: markdown, buttons: ["bold", "italic", "link"]}
          - label: "Hero - Homepage"
            name: homeHero
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string}
              - {label: "Content", name: content, widget: markdown, buttons: ["bold", "italic", "link"]}
              - {label: "Arrow Link URL", name: arrowUrl, widget: string}
          - label: "Rich Text Block"
            name: textBlock
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string, required: false}
              - {label: "Sub-heading", name: subHeading, widget: string, required: false, hint: "Appears in all caps."}
              - {label: "Content", name: content, widget: markdown}
          - label: "Logo Block"
            name: logoBlock
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string}
              - label: "Style"
                name: "altStyle"
                widget: select
                default: ""
                required: false
                options:
                  - {label: "Default", value: ""}
                  - {label: "Gray Background", value: "content-block--alternate"}
                  - {label: "Hex Background", value: "hex-block"}
              - label: "Logos"
                label_singular: "Logo"
                name: logos
                widget: list
                fields:
                  - {label: "Org Name", name: altText, widget: string}
                  - {label: "URL", name: url, widget: string}
                  - {label: "Logo", name: path, widget: image}
                  - label: "Logo Width"
                    name: "logoStyle"
                    widget: select
                    default: "sponsors__logo"
                    options:
                      - {label: "Default", value: "sponsors__logo"}
                      - {label: "Full Width", value: "sponsors__logo--expand"}
                      - {label: "80% Width", value: "sponsors__logo--shrink-80"}
                      - {label: "70% Width", value: "sponsors__logo--shrink-70"}
                      - {label: "60% Width", value: "sponsors__logo--shrink-60"}
                      - {label: "50% Width", value: "sponsors__logo--shrink-50"}
          - label: "Contact Us"
            name: contactUs
            widget: object
            fields:
              - {label: "iFrame URL", name: iframeUrl, widget: string}
              - {label: "Legal Link Text", name: legalLinkText, widget: string}
              - {label: "Legal URL", name: legalUrl, widget2: string}
              - {label: "HTML ID", name: id, widget: string, required: false, hint: "Set an ID to link directly to this block."}
          - label: "Two Col with CTA"
            name: twoColCta
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - { label: "Default", value: "" }
                  - { label: "Extra Top Margin", value: "content-block--spaced" }
              - {label: "HTML ID", name: id, widget: string, required: false, hint: "Set an ID to link directly to this block."}
              - label: "Left Col"
                name: leftCol
                widget: list
                types:
                  - label: "Text with Icon"
                    name: textWithIcon
                    widget: object
                    fields:
                      - {label: "Sub-heading", name: subHeading, widget: string, required: false}
                      - {label: "Content", name: content, widget: markdown}
                      - {label: "Link Text", name: linkText, widget: string, required: false}
                      - {label: "Link URL", name: linkUrl, widget: string, required: false}
                  - label: "Expandable List"
                    name: expandableList
                    widget: object
                    fields:
                      - {label: "Sub-heading", name: subHeading, widget: string, required: false}
                      - {label: "Content", name: content, widget: markdown}
                      - label: "Items"
                        name: items
                        widget: list
                        fields:
                          - {label: "Term", name: term, widget: string}
                          - {label: "Definition", name: definition, widget: markdown}
              - label: "Right Col"
                name: rightCol
                widget: list
                types:
                  - label: "CTA"
                    name: cta
                    widget: object
                    fields:
                      - {label: "Title", name: title, widget: string}
                      - {label: "Content", name: content, widget: markdown}
                      - {label: "Link Text", name: linkText, widget: string, required: false}
                      - {label: "Link URL", name: linkUrl, widget: string, required: false}
                  - label: "Twitter Feed"
                    name: twitterFeed
                    widget: object
                    fields:
                       - {label: "Title", name: title, widget: string}
                       - {label: "Feed URL", name: feedUrl, widget: string}
                       - {label: "Max Number of Tweets", name: tweetLimit, widget: number, default: 20, valueType: int, min: 1, max: 20}
                       - {label: "Alternate Text", name: altText, widget: string, hint: "Displays when the Feed isn't enabled, such as when an ad blocker is enabled."}
          - label: "Benefits"
            name: benefits
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string, required: false}
              - {label: "Sub-heading", name: subHeading, widget: string, required: false}
              - {label: "Content", name: content, widget: markdown, required: false}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - {label: "Default", value: ""}
                  - {label: "Gray Background", value: "content-block--alternate"}
                  - {label: "Hex Background", value: "hex-block"}
              - label: "Column Layout"
                name: "layout"
                widget: "select"
                default: "col-md-6"
                options:
                  - {label: "Two Cols", value: "col-md-6"}
                  - {label: "Four Cols", value: "col-sm-6 col-lg-3 benefits__item--vertical"}
              - label: "Columns"
                name: cols
                widget: list
                fields:
                  - {label: "Heading", name: heading, widget: string}
                  - {label: "Content", name: content, widget: markdown, buttons: ["bold", "italic", "link"]}
                  - {label: "Icon", name: icon, widget: image}
              - {label: "Additional Content", name: additionalContent, widget: markdown, required: false}
          - label: "Pricing"
            name: pricing
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string, required: false}
              - {label: "Sub-heading", name: subHeading, widget: string, required: false}
              - {label: "Content", name: content, widget: markdown, required: false}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - {label: "Default", value: ""}
                  - {label: "Gray Background", value: "content-block--alternate"}
                  - {label: "Hex Background", value: "hex-block"}
                  - {label: "Hex Background - Bottom of Page", value: "hex-block hex-block--bottom"}
              - label: "Prices"
                label_singular: "Price Option"
                name: cols
                widget: list
                fields:
                  - {label: "Heading", name: heading, widget: string}
                  - {label: "Dates", name: dates, widget: string}
                  - {label: "Price Amount", name: amount, widget: string}
                  - {label: "Link Text", name: linkText, widget: string}
                  - {label: "Link URL", name: linkUrl, widget: string}
                  - {label: "Icon", name: icon, widget: image, required: false}
                  - label: "Is this Price Currently Available?"
                    name: "isEnabled"
                    widget: "select"
                    default: "enabled"
                    options:
                      - {label: "Yes", value: "enabled"}
                      - {label: "No", value: "disabled"}
              - {label: "Additional Content", name: additionalContent, widget: markdown, required: false}
          - label: "Expandable List"
            name: expandableList
            widget: object
            fields:
              - {label: "Content", name: content, widget: markdown, required: false}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - {label: "Default", value: ""}
                  - {label: "Gray Background", value: "content-block--alternate"}
              - label: "Items"
                label_singular: "Item"
                name: items
                widget: list
                fields:
                  - {label: "Term", name: term, widget: string}
                  - {label: "Definition", name: definition, widget: markdown}
          - label: "Speakers Block"
            name: speakers
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - {label: "Default", value: ""}
                  - {label: "Gray Background", value: "content-block--alternate"}
              - label: "Speakers"
                label_singular: "Speaker"
                name: speakers
                widget: list
                fields:
                  - label: "Name"
                    name: title
                    widget: relation
                    collection: speakers
                    searchFields: ["title", "id"]
                    valueField: id
                    displayFields: ["title"]
                    hint: "Start typing to find a speaker by name (at least three chars)."
  - label: "Speakers"
    label_singular: "Speaker"
    name: speakers
    folder: "/_speakers"
    create: true
    slug: "{{slug}}"
    preview_path: "/speakers/{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Full Name", name: title, widget: string}
      - {label: "Speaker ID", name: id, widget: string, hint: "Enter a short text ID that will be unique for this speaker and never change. Used internally for relation fields."}
      - {label: "Headshot", name: headshot, widget: image}
      - {label: "Title", name: jobTitle, widget: string}
      - {label: "Organization", name: organization, widget: string, required: false}
      - label: "Biography"
        name: bio
        widget: object
        fields:
          - {label: "Full Bio", name: full, widget: markdown}
          - {label: "Excerpt", name: excerpt, widget: text, required: false, hint: "Potentially used in places where the full bio is too long."}
      - label: "Social Media"
        name: social
        widget: object
        fields:
          - {label: "LinkedIn", name: linkedIn, widget: string, required: false}
          - {label: "Twitter", name: twitter, widget: string, required: false}
```

**Additional context**
I'm hoping this issue can be worked around by manually trailing the leading slash in the config. There is no guidance to do so in the docs, however.
