### ISSUE TITLE
Number type is not supported in slug template

### ISSUE THREAD

**Issue by bentranmyriota** [netlify/netlify-cms#2118]
**Describe the bug**
I am trying to create new file with order suffix after slug. I get the error "r.get().trim is not a function" when save new document. I think number type is not supported

**Screenshots**

![image](https://user-images.githubusercontent.com/23440697/53207778-94b53f80-3684-11e9-84d0-e4c74b5e1271.png)

**Applicable Versions:**
 - Netlify CMS version: 2.4
 - Git provider: GitHub
 - OS: Ubuntu 18.04
 - Browser version:72.0.3626.96 (Official Build) (64-bit)

**CMS configuration**
```
identifier_field: "name"
    slug: "{{slug}}_{{order}}"
    fields:
      - label: "Id"
        name: "id"
        hint: "Referencing id"
        pattern: ['^\w+$', "Only alphanumeric and _ characters"]

      - label: "Name"
        name: "name"
        hint: "Display name"
        widget: "string"

      - label: "Order"
        name: "order"
        hint: "Order of the section on the side navigation menu"
        widget: "number"
        min: 0
        max: 100
```
