### ISSUE TITLE
Allow multiple images in image widget.

### ISSUE THREAD

**Issue by mgrandl** [netlify/netlify-cms#213]
Is there any way to view images in the upload directory and upload new ones directly to it?

**Comment by cassiozen** [comment]
Currently there is no way to view images on the upload directory, but we do have plans for a "media viewer/explorer" in the future. 

You can upload multiple images by using the list widget together with the image widget, like this:

```yaml
      - {label: "Title", name: "title", widget: "string"}
      - label: "Images"
        name: "images"
        widget: "list"
        field: {label: "Image", name: "image", widget: "image"}
```
