### ISSUE TITLE
Can't parse date in front matter

### ISSUE THREAD

**Issue by cetra3** [netlify/netlify-cms#2144]
**Describe the bug**

NetlifyCMS breaks trying to parse dates of the format `YYYY-MM-DD` in the front-matter.

**To Reproduce**

Have a collections config like this:

```

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    format: toml-frontmatter
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Body", name: "body", widget: "markdown"}
```

Have a blog article with the following front matter:
```
+++
title = "An Example Blog"
date = 2018-12-14
+++

This is an example blog
```

You will see this in the console:

```
Object { message: "Expected \"T\" but \"\\n\" found.", line: 3, column: 18, stack: "" }
```

**Expected behavior**

The collection date is parsed correctly.
