### ISSUE TITLE
[Cloudinary] Support for "folder" option?

### ISSUE THREAD

**Issue by SachaG** [netlify/netlify-cms#2209]
Cloudinary has a [`folder` option](https://cloudinary.com/documentation/media_library_widget) that lets you open the upload widget to a specific subdirectory:

> Object. Instructs the widget to open in browse mode, displaying the contents of the specified folder, and optionally filtered to a specific asset type These options are specified with a folder object as follows: `{folder: {path: "folder", resource_type: "video"}}`

Is this option currently supported by NetlifyCMS? With Gatsby, I tried the following config but it didn't seem to work:

```
media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: foo
    api_key: 1234foobar
    folder: { path: blog }
```

If this is not currently supported, would a PR be welcome? What would be the best place to get started with that?
