### ISSUE TITLE
Collection items shows "UNSAVED CHANGES" while nothing is changed (when custom editor components are used inside a markdown field))   

### ISSUE THREAD

**Issue by bert-bruggeman** [netlify/netlify-cms#2211]
**Describe the bug**
Collection items shows "UNSAVED CHANGES" while nothing is changed (when custom editor components are used inside a markdown field))

**To Reproduce**
Create a collection with a body field and add content with a custom editor widget like "button", publish, go back to the overview and open the item again, while nothing is changed the top left "back button" message says "UNSAVED CHANGES".

**Editor component**
```
CMS.registerEditorComponent({
    id: "button",
    label: "Button",
    pattern: '^{% button(.*)',
    fields: [
      {
        name: 'text',
        label: 'Text',
        widget: 'string',
        required: true,
      },
      {
        name: 'href',
        label: 'href',
        widget: 'string',
        required: true,
      },
      {
        name: 'icon',
        label: 'Icon',
        widget: 'select',
        default: 'none',
        options: [
          'none',
          'more',
          'info',
        ],
      }
    ],

    fromBlock: function(match) {

      function getAttribute(attribute, defaultValue) {
        var val = match[1].match(attribute + '="(.*?)"');
        return val ? val[1] : defaultValue;
      }

      return {
        text: getAttribute("text",""),
        href: getAttribute("href",""),
        icon: getAttribute("icon","none"),
      };
    },

    toBlock: function(obj) {
      return '{% button text="' + obj.text + '" href="' + obj.href + '" icon="' + obj.icon + '" %}';
    },

    toPreview: function(obj) {
      if (obj.icon && obj.icon != "none") {
        obj.text = '<span>' +  obj.text + '</span>';
        var icon = '<svg width="16" height="16" class="sym icon-' + obj.icon + '"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/symbols.svg#' + obj.icon + '"></use></svg>';
      }
      else icon = "";

      if (obj.text) {
        return (
          '<div class="button-container"><a href="' + obj.href + '" class="btn">' + icon + obj.text + '</a></div>'
        );
      }
    }

});
```

**Content - markdown file (see content type below)**
```
---
title: Lorem ipsum
order: 1
image: /media/image.jpg
---

Lorem ipsum **dolor sit amet**, consectetuer adipiscing elit.
Aenean commodo ligula eget dolor. Aenean massa.
Cum sociis natoque **penatibus** et magnis dis parturient montes, nascetur ridiculus mus.
Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.

{% button text="Read more" href="/about-us" icon="more" %}
```

**Config (cards content type)**
```
  - name: "cards"
    label: "Frontpage"
    label_singular: "Card"
    folder: "_content/_cards"
    create: true
    fields:

      - label: Title
        name: title
        widget: string
        hint: Een herkenbare titel met enkele kernwoorden.

      - label: Order
        name: order
        widget: number
        default: 1
        valueType: "int"
        min: 1
        max: 99
        hint: De plaats van dit item op de frontpage.

      - label: Image
        name: image
        widget: image

      - label: Body
        name: body
        widget: markdown
```
**Browsers:** Firefox, Chrome *(current versions)*
**CMS:** *current* 2.8.0
