### ISSUE TITLE
public_folder forces leading /

### ISSUE THREAD

**Issue by Larsklopstra** [netlify/netlify-cms#2238]
**Describe the bug**
Using `public_folder: "../uploads"` I'd assume it would return `../uploads/image.png` but the result is `./../uploads/image.png` thus resulting in a 404. 

The forced leading slash will prevent [Gridsome](https://gridsome.org) from optimizing the images.

**Expected behavior**
Using `public_folder: "../uploads"` should return `../uploads/image.png` **NOT** `./../uploads/image.png`.

**CMS configuration**
```
backend:
  name: github
  repo: Larsklopstra/gridsome-starter-netlify-cms

media_folder: "uploads"
public_folder: "../uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
```

**Additional context**
Using Gridsome as static site generator.
