### ISSUE TITLE
Hints for collection types

### ISSUE THREAD

**Issue by bert-bruggeman** [netlify/netlify-cms#2240]
It would be nice to provide a hint per collection type, this could be visible as a tooltip by adding a title attribute to the collection link in the sidebar or/and below the collection title... 

**example config:**
```
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "_pages"
    create: true
    hint: "More information about this content type with some guidelines, tips, or other additional information."
    fields:

      - label: Title
        name: title
        widget: string
        hint: "More information about this field"

        ...
```

![collection-tooltips](https://user-images.githubusercontent.com/15092474/54886004-1e724b80-4e83-11e9-8290-fb2cac025c2f.jpg)
