### ISSUE TITLE
Upload fails if media folder does not exist

### ISSUE THREAD

**Issue by filkortamas** [netlify/netlify-cms#2264]
I can not upload files in the content manager. I use Bitbucket and get an error:

![Screenshot from 2019-04-02 21-14-52](https://user-images.githubusercontent.com/37575454/55429788-ca025680-557b-11e9-8369-e5348758e65c.png)

**Comment by erquhart** [comment]
We need more info.

**Comment by arminnaimi** [comment]
I am having the same issue. Below is a detailed bug report:

**Describe the bug**

Every time I try to upload an image in the editor and from the top navigation. I received the error in the screenshot:

![](https://user-images.githubusercontent.com/37575454/55429788-ca025680-557b-11e9-8369-e5348758e65c.png)

**To Reproduce**

Open the media gallery
Upload image

**Expected behavior**

When uploading an image, the image should appear in the media gallery.

**Applicable Versions:**

netlify-cms 2.9.0
Safari, Chrome
OS X Mojave
Node v10.15.3 on Netlify (using Netlify Large Media)

**CMS configuration:**

```yaml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/media/uploads"
public_folder: "/media/uploads"
logo_url: https://redacted.com/image.png


collections:
  - name: "aktuelles" # Used in routes, e.g., /admin/collections/blog
    label: "Aktuelles Artikel" # Used in the UI
    file: "markdown"
    folder: "/src/posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "DD. MMMM YYYY"}
      - {label: "Description", name: "description", widget: "string", required: false }
      - {label: "Featured Image", name: "feature_image", widget: "image", required: false }
      - {label: "Categories", name: "categories", widget: "select", multiple: true, options: ["Redacted"], required: false }
      - {label: "Body", name: "body", widget: "markdown"}
```

**Comment by arminnaimi** [comment]
I just figured what the issue is. In my case the media folder did not exist, as I did not add any images. After adding a single image to the media folder and pushing to the repo, it all works as expected.

**Comment by filkordev** [comment]
Sorry for I did not wrote any details and my late response, but here is my config.yml file:
```
backend:
  name: bitbucket
  repo: filkordev/beresautosiskola

media_folder: static/assets
public_folder: assets

site_url: https://blissful-carson-3f4906.netlify.com

collections:
  - name: home
    label: Főoldal szöveg
    folder: content/home
    create: false
    fields:
      - { name: title, label: Cím }
      - { name: body, label: Szöveg, widget: markdown }
  - name: about
    label: Iskolánkról
    folder: content/about
    create: false
    fields:
      - { name: title, label: Cím }
      - { name: body, label: Szöveg, widget: markdown }
  - name: course
    label: Tanfolyam
    folder: content/course
    create: true
    fields:
      - { name: title, label: Név, widget: string }
      - { name: date, label: Dátum, widget: date }
  - name: teachers
    label: Oktatók
    folder: content/teachers
    create: true
    identifier_field: phone
    fields:
      - { name: name, label: Név, widget: string }
      - { name: phone, label: Telefonszám, widget: string }
      - { name: car, label: Autó, widget: string }
  - name: prices
    label: Árak
    folder: content/prices
    create: true
    identifier_field: name
    fields:
      - {
          name: category,
          label: Kategória,
          widget: select,
          options: ['A', 'B'],
          default: 'B',
        }
      - {
          name: type,
          label: Típus,
          widget: select,
          options: ['normál', 'hatósági vizsgadíj'],
          default: 'normál',
        }
      - { name: name, label: Név, widget: string }
      - { name: price, label: Ár, widget: number }
  - name: documents
    label: Jogi Dokumentumok
    folder: content/documents
    create: true
    fields:
      - { name: title, label: Név, widget: string }
      - label: 'Manual PDF'
        name: 'manual_pdf'
        widget: 'file'
        default: '/assets/general-manual.pdf'
        media_library:
          config:
            multiple: true
```
I have assets folder in my root folder and have the static/assets media folder.
I tried it in macos mojave and in linux mint tessa.

**Comment by bekahmcdonald** [comment]
> I just figured what the issue is. In my case the media folder did not exist, as I did not add any images. After adding a single image to the media folder and pushing to the repo, it all works as expected.

This worked for me too.

**Comment by erquhart** [comment]
I see you're using Git Gateway, where is your repo hosted?

**Comment by arminnaimi** [comment]
Mine is hosted on GitLab.

**Comment by erquhart** [comment]
We should be creating a new folder if the it doesn't exist, sounds like that isn't happening in the Bitbucket backend.

**Comment by davidlower8** [comment]
Hi everyone. 

I am having trouble uploading and registering images with netlify CMS. It would be great to know what the progress of this issue is and if there is a solution to fix the problem. I simply get 'no assets found'. I don't even get empty thumbnails.  

I am not sure if you need the entire yml file but here it is. 

```
backend:
  name: github
  repo: of-the-spirit/philip-website # Path to your GitHub repository

media_folder: "img/uploads"
  
collections:
  - name: "home-page"
    label: "Home page"
    files:
    - label: "Introduction area"
      name: "site"
      file: "_data/home.yml"
      fields:
        - label: "Title"
          name: "title"
          widget: "string"
        - label: "Subtitle"
          name: "subtitle"
          widget: "text"
  - name: "sidebar"
    label: "Sidebar"
    files:
    - label: "About section"
      name: "site"
      file: "_data/about.yml"
      fields:
        - label: "Portrait picture"
          name: "about-img"
          widget: "image"
        - label: "About info"
          name: "about-info"
          widget: "markdown"
  - name: "footer"
    label: "Footer"
    files:
    - label: "Introduction area"
      name: "site"
      file: "_data/footer.yml"
      fields:
        - label: "Title"
          name: "title"
          widget: "string"
        - label: "Subtitle"
          name: "subtitle"
          widget: "text"
  - name: "blog-posts"
    label: "Blog posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "default-layout"
      - label: "Featured image"
        name: "img"
        widget: "image"
      - label: "Image alt tag (image description)"
        name: "img-alt"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Excerpt"
        name: "meta"
        widget: "text"
      - label: "Body"
        name: "body"
        widget: "markdown"

```

If it also helps. I use gulp to take my src img folder to my _site folder. My uploads folder is inside of the img folder. I use Jekyll.

<img width="1030" alt="Screenshot 2019-08-01 at 23 23 46" src="https://user-images.githubusercontent.com/29481254/62331609-52eeb780-b4b4-11e9-9c76-dc7efdc4f738.png">
