### ISSUE TITLE
Cannot unselect value for Relation widget marked not required

### ISSUE THREAD

**Issue by sddaniels** [netlify/netlify-cms#2284]
**Describe the bug**
In our config file, we have defined a relation widget and specified `required: false`. In the UI, this widget displays a gray `x`, indicating that the selection can be removed. However, clicking on the `x` only opens the drop down, it does not return the field to an empty value.

The following error appears in the browser console:
```
Uncaught TypeError: Cannot read property 'data' of null
    at Object.onChange (RelationControl.js:91)
    at n.value (stateManager.js:138)
    at stateManager.js:75
    at t.onChange (Select.js:214)
    at t.clearValue (Select.js:340)
    at Select.js:485
    at Object.<anonymous> (react-dom.production.min.js:14)
    at f (react-dom.production.min.js:15)
    at react-dom.production.min.js:15
    at O (react-dom.production.min.js:17)
```

**Expected behavior**
When click the the `x` in the relation widget, the selected value should be cleared out.

**Screenshots**
![Screen Shot 2019-04-10 at 2 11 22 PM](https://user-images.githubusercontent.com/1263925/55906726-89699500-5b9a-11e9-9df8-8aef1afb11b8.png)

**Applicable Versions:**
 - Netlify CMS version: 2.9.0
 - Git provider: GitHub
 - OS: OSX
 - Browser version: Chrome  73.0.3683.103

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master
  identity_url: "https://monetery.com/.netlify/identity"
  gateway_url: "https://monetery.com/.netlify/git"
  squash_merges: true

publish_mode: editorial_workflow
media_folder: "assets/img/uploads"

site_url: https://monetery.com
logo_url: https://monetery.com/assets/img/monetery-logo-color.svg

collections:
  - label: "Sitewide Options"
    name: options
    editor:
      preview: false
    files:
      - label: "Navigation Menu"
        name: nav
        file: "_data/nav.yml"
        fields:
          - {label: "Additional Header Text", name: headerText, widget: string, required: false}
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: topLevelItems
            widget: list
            fields:
              - {label: "Display Text", name: displayText, widget: string}
              - {label: URL, name: url, widget: string}
              - label: "Item Type"
                name: itemType
                widget: select
                options: ["Link", "Button"]
              - label: "Nav Items"
                label_singular: "Nav Item"
                name: childItems
                widget: list
                fields:
                  - {label: "Display Text", name: displayText, widget: string}
                  - {label: "URL", name: url, widget: string}
                  - {label: "Icon", name: icon, widget: image}
      - label: "Footer"
        name: footer
        file: "_data/footer.yml"
        fields:
          - {label: "Blurb", name: blurb, widget: text}
          - label: "Footer Logo"
            name: logo
            widget: object
            fields:
              - {label: "Alt Text", name: altText, widget: string}
              - {label: "Image", name: path, widget: image}
              - {label: "URL", name: url, widget: string}
          - label: "Social Links"
            label_singular: "Social Link"
            name: social
            widget: list
            fields:
              - {label: "Alt Text + Title", name: altText, widget: string}
              - {label: "Image", name: path, widget: image}
              - {label: "URL", name: url, widget: string}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - { label: "Default", value: "" }
                  - { label: "Skinny", value: "footer__social-item--skinny" }
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: navItems
            widget: list
            fields:
              - {label: "Display Text", name: displayText, widget: string}
              - {label: "URL", name: url, widget: string}
      - label: "Defaults"
        name: defaults
        file: "_data/defaults.yml"
        fields:
          - {label: "Page Title", name: title, widget: string}
          - {label: "Meta Description", name: metaDescription, widget: text}
          - label: "Social Sharing"
            name: social
            widget: object
            required: false
            fields:
              - {label: "OpenGraph Image", name: ogImage, widget: image}
              - {label: "Twitter Image", name: twitterImage, widget: image}
      - label: "404 Page"
        name: notfound
        file: "_data/notfound.yml"
        fields:
          - {label: "Content", name: content, widget: markdown}
  - label: "Pages"
    label_singular: "Page"
    name: pages
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    preview_path: "{{permalink}}"
    editor:
      preview: false
    fields:
      - {label: "Title", name: title, widget: string}
      - {label: "Permalink", name: permalink, widget: string}
      - label: "SEO Meta Tags"
        name: seoMeta
        widget: select
        multiple: true
        required: false
        options: ["noindex", "nofollow"]
      - label: "Layout Template"
        name: "layout"
        widget: "select"
        default: "blocks"
        options:
          - { label: "Default", value: "blocks" }
          - { label: "Home Page", value: "home" }
      - {label: "Meta Description", name: metaDescription, widget: text, required: false}
      - label: "Social Sharing"
        name: social
        widget: object
        required: false
        fields:
          - {label: "OpenGraph Image", name: ogImage, widget: image, required: false}
          - {label: "Twitter Image", name: twitterImage, widget: image, required: false}
      - label: "Content Blocks"
        label_singular: "Content Block"
        name: blocks
        widget: list
        types:
          - label: "Hero"
            name: hero
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string}
              - {label: "Sub-heading", name: boxHeading, widget: string, required: false, hint: "Appears above main heading in all caps."}
              - {label: "Content", name: content, widget: markdown, buttons: ["bold", "italic", "link"], required: false}
          - label: "Hero - Homepage"
            name: homeHero
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string}
              - {label: "Content", name: content, widget: markdown, buttons: ["bold", "italic", "link"], required: false}
              - {label: "Arrow Link URL", name: arrowUrl, widget: string}
          - label: "Rich Text Block"
            name: textBlock
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string, required: false}
              - {label: "Sub-heading", name: subHeading, widget: string, required: false, hint: "Appears in all caps."}
              - {label: "Content", name: content, widget: markdown}
          - label: "Logo Block"
            name: logoBlock
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string}
              - label: "Style"
                name: "altStyle"
                widget: select
                default: ""
                required: false
                options:
                  - {label: "Default", value: ""}
                  - {label: "Gray Background", value: "content-block--alternate"}
                  - {label: "Hex Background", value: "hex-block"}
              - label: "Number of Columns"
                name: "logoColumns"
                hint: "Controls desktop view. Tablet/Mobile views have columns set based on screen size."
                widget: select
                default: "sponsors--columns-5"
                required: false
                options:
                  - {label: "One Column", value: "sponsors--columns-1"}
                  - {label: "Two Columns", value: "sponsors--columns-2"}
                  - {label: "Three Columns", value: "sponsors--columns-3"}
                  - {label: "Four Columns", value: "sponsors--columns-4"}
                  - {label: "Five Columns", value: "sponsors--columns-5"}
                  - {label: "Six Columns", value: "sponsors--columns-6"}
              - label: "Logos"
                label_singular: "Logo"
                name: logos
                widget: list
                fields:
                  - {label: "Org Name", name: altText, widget: string}
                  - {label: "URL", name: url, widget: string}
                  - {label: "Logo", name: path, widget: image}
                  - label: "Logo Width"
                    name: "logoStyle"
                    widget: select
                    default: "sponsors__logo"
                    options:
                      - {label: "Default", value: "sponsors__logo"}
                      - {label: "Full Width", value: "sponsors__logo--expand"}
                      - {label: "80% Width", value: "sponsors__logo--shrink-80"}
                      - {label: "70% Width", value: "sponsors__logo--shrink-70"}
                      - {label: "60% Width", value: "sponsors__logo--shrink-60"}
                      - {label: "50% Width", value: "sponsors__logo--shrink-50"}
          - label: "Contact Us"
            name: contactUs
            widget: object
            fields:
              - {label: "iFrame URL", name: iframeUrl, widget: string}
              - {label: "Legal Link Text", name: legalLinkText, widget: string}
              - {label: "Legal URL", name: legalUrl, widget2: string}
              - {label: "HTML ID", name: id, widget: string, required: false, hint: "Set an ID to link directly to this block."}
          - label: "Two Col with CTA"
            name: twoColCta
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - { label: "Default", value: "" }
                  - { label: "Extra Top Margin", value: "content-block--spaced" }
              - {label: "HTML ID", name: id, widget: string, required: false, hint: "Set an ID to link directly to this block."}
              - label: "Left Col"
                name: leftCol
                widget: list
                types:
                  - label: "Text with Icon"
                    name: textWithIcon
                    widget: object
                    fields:
                      - {label: "Sub-heading", name: subHeading, widget: string, required: false}
                      - {label: "Content", name: content, widget: markdown}
                      - {label: "Link Text", name: linkText, widget: string, required: false}
                      - {label: "Link URL", name: linkUrl, widget: string, required: false}
                  - label: "Expandable List"
                    name: expandableList
                    widget: object
                    fields:
                      - {label: "Sub-heading", name: subHeading, widget: string, required: false}
                      - {label: "Content", name: content, widget: markdown}
                      - label: "Items"
                        name: items
                        widget: list
                        fields:
                          - {label: "Term", name: term, widget: string}
                          - {label: "Definition", name: definition, widget: markdown}
              - label: "Right Col"
                name: rightCol
                widget: list
                types:
                  - label: "CTA"
                    name: cta
                    widget: object
                    fields:
                      - {label: "Title", name: title, widget: string}
                      - {label: "Content", name: content, widget: markdown}
                      - {label: "Link Text", name: linkText, widget: string, required: false}
                      - {label: "Link URL", name: linkUrl, widget: string, required: false}
                  - label: "Twitter Feed"
                    name: twitterFeed
                    widget: object
                    fields:
                       - {label: "Title", name: title, widget: string}
                       - {label: "Feed URL", name: feedUrl, widget: string}
                       - {label: "Max Number of Tweets", name: tweetLimit, widget: number, default: 20, valueType: int, min: 1, max: 20}
                       - {label: "Alternate Text", name: altText, widget: string, hint: "Displays when the Feed isn't enabled, such as when an ad blocker is enabled."}
          - label: "Benefits"
            name: benefits
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string, required: false}
              - {label: "Sub-heading", name: subHeading, widget: string, required: false}
              - {label: "Content", name: content, widget: markdown, required: false}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - {label: "Default", value: ""}
                  - {label: "Gray Background", value: "content-block--alternate"}
                  - {label: "Hex Background", value: "hex-block"}
              - label: "Column Layout"
                name: "layout"
                widget: "select"
                default: "col-md-6"
                options:
                  - {label: "Two Cols", value: "col-md-6"}
                  - {label: "Four Cols", value: "col-sm-6 col-lg-3 benefits__item--vertical"}
              - label: "Columns"
                name: cols
                widget: list
                fields:
                  - {label: "Heading", name: heading, widget: string}
                  - {label: "Content", name: content, widget: markdown, buttons: ["bold", "italic", "link"]}
                  - {label: "Icon", name: icon, widget: image}
              - {label: "Additional Content", name: additionalContent, widget: markdown, required: false}
          - label: "Pricing"
            name: pricing
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string, required: false}
              - {label: "Sub-heading", name: subHeading, widget: string, required: false}
              - {label: "Content", name: content, widget: markdown, required: false}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - {label: "Default", value: ""}
                  - {label: "Gray Background", value: "content-block--alternate"}
                  - {label: "Hex Background", value: "hex-block"}
                  - {label: "Hex Background - Bottom of Page", value: "hex-block hex-block--bottom"}
              - label: "Prices"
                label_singular: "Price Option"
                name: cols
                widget: list
                fields:
                  - {label: "Heading", name: heading, widget: string}
                  - {label: "Dates", name: dates, widget: string}
                  - {label: "Price Amount", name: amount, widget: string}
                  - {label: "Link Text", name: linkText, widget: string}
                  - {label: "Link URL", name: linkUrl, widget: string}
                  - {label: "Icon", name: icon, widget: image, required: false}
                  - label: "Is this Price Currently Available?"
                    name: "isEnabled"
                    widget: "select"
                    default: "enabled"
                    options:
                      - {label: "Yes", value: "enabled"}
                      - {label: "No", value: "disabled"}
              - {label: "Additional Content", name: additionalContent, widget: markdown, required: false}
          - label: "Agenda"
            name: agenda
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string, required: false}
              - {label: "Sub-heading", name: subHeading, widget: string, required: false, hint: "Appears in all caps."}
              - {label: "Content", name: content, widget: markdown, required: false}
              - label: "Date Tables"
                label_singular: "Event Date"
                name: tables
                widget: list
                fields:
                  - {label: "Table Heading", name: tableHeading, widget: string, hint: "Date you're entering times for."}
                  - label: "Timeframes"
                    label_singular: "Timeframe"
                    name: timeframes
                    widget: list
                    fields:
                      - {label: "Time", name: time, widget: string}
                      - {label: "Heading", name: contentHeading, widget: string, required: false}
                      - label: "Sub-heading with Link"
                        name: subHeadingLink
                        widget: object
                        fields:
                          - {label: "Sub-heading Text", name: subHeadingText, widget: string, required: false}
                          - label: "Speaker Link"
                            name: speakerLink
                            widget: "relation"
                            collection: "speakers"
                            searchFields: ["title"]
                            valueField: speakerId
                            displayFields: ["title"]
                            required: false
                            hint: "Link will open Speaker Popup Modal for that speaker."
                          - {label: "Other Link URL", name: otherLinkUrl, widget: string, required: false, hint: "Link will take user directly to the URL."}
                      - {label: "Content", name: content, widget: markdown, required: false}
                      - label: "Style"
                        name: "altStyle"
                        widget: "select"
                        default: ""
                        required: false
                        options:
                          - {label: "Default", value: ""}
                          - {label: "Narrow Gray Background", value: "agenda__content--gray"}
          - label: "Expandable List"
            name: expandableList
            widget: object
            fields:
              - {label: "Content", name: content, widget: markdown, required: false}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - {label: "Default", value: ""}
                  - {label: "Gray Background", value: "content-block--alternate"}
              - label: "Items"
                label_singular: "Item"
                name: items
                widget: list
                fields:
                  - {label: "Term", name: term, widget: string}
                  - {label: "Definition", name: definition, widget: markdown}
          - label: "Speakers Block"
            name: speakers
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string}
              - label: "Style"
                name: "altStyle"
                widget: "select"
                default: ""
                required: false
                options:
                  - {label: "Default", value: ""}
                  - {label: "Gray Background", value: "content-block--alternate"}
              - label: "Speakers"
                label_singular: "Speaker"
                name: speakers
                widget: list
                fields:
                  - label: "Name"
                    name: title
                    widget: relation
                    collection: speakers
                    searchFields: ["title", "speakerId"]
                    valueField: speakerId
                    displayFields: ["title"]
                    hint: "Start typing to find a speaker by name (at least three chars)."
              - label: "Announcement Card"
                name: announcement
                widget: object
                fields:
                  - label: "Show/Hide"
                    name: isVisible
                    widget: boolean
                    default: false
                    hint: "Displays an additional card at the end of the list of speakers with an image and text."
                  - {label: "Image", name: img, widget: image, required: false}
                  - {label: "Image Alt Text", name: altText, widget: string, required: false}
                  - {label: "Content", name: content, widget: markdown, required: false}
  - label: "Speakers"
    label_singular: "Speaker"
    name: speakers
    folder: "_speakers"
    create: true
    slug: "{{slug}}"
    preview_path: "/speakers/{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Full Name", name: title, widget: string}
      - {label: "Speaker ID", name: speakerId, widget: string, hint: "Enter a short text ID that will be unique for this speaker and never change. Used internally for relation fields."}
      - label: "SEO Meta Tags"
        name: seoMeta
        widget: select
        multiple: true
        required: false
        options: ["noindex", "nofollow"]
      - {label: "Headshot", name: headshot, widget: image}
      - {label: "Title", name: jobTitle, widget: string}
      - {label: "Organization", name: organization, widget: string, required: false}
      - label: "Biography"
        name: bio
        widget: object
        fields:
          - {label: "Full Bio", name: full, widget: markdown}
          - {label: "Excerpt", name: excerpt, widget: text, required: false, hint: "Potentially used in places where the full bio is too long."}
      - label: "Social Media"
        name: social
        widget: object
        fields:
          - {label: "LinkedIn", name: linkedIn, widget: string, required: false}
          - {label: "Twitter", name: twitter, widget: string, required: false}

```

**Additional context**
Discussed in Gitter channel on 4/10/2019
