### ISSUE TITLE
Select widget default value is not being applied

### ISSUE THREAD

**Issue by vai0** [netlify/netlify-cms#2291]
**Describe the bug**
Select widget default value is not being applying when options are objects of label/value pairs

```
- label: "Feature on /resources homepage"
  name: "mainFeatured"
  widget: "select"
  default: '0'
  options:
    - {label: "Not Featured", value: '0'}
    - {label: "Primary", value: '1'}
    - {label: "Secondary", value: '2'}
    - {label: "Tertiary", value: '3'}
```

Result:
![image](https://user-images.githubusercontent.com/1195698/56175974-4fd7c600-5fae-11e9-8368-bff829b1667c.png)

**Expected behavior**
When a default is set, the field should visually be initialized with the default value - in this case "Not Featured", and with a value of "0"

**Applicable Versions:**
 - Netlify CMS version: 2.9.0
 - Git provider: Gitlab
 - OS: Mac OS 10.14 Mojave
 - Browser version: Chrome 73.0.3683.75 
 - Node.JS version: v10.15.3

**Comment by barthc** [comment]
@vai0  your widget config works for me, I can see the default set. Also, note that the widget default option only works for new entry.

**Comment by madikarizma** [comment]
I believe this is worth re-opening, as I experience the same issue. Take a look with the following fields configuration:

```
fields:
      - label: "Select"
        name: "Select"
        widget: "select"
        default: "default"
        options:
          - label: "Default"
            value: "default"
          - label: "Not Default"
            value: "not default"
      - label: "List"
        name: "list"
        widget: "list"
        fields:
          - label: "Select"
            name: "Select"
            widget: "select"
            default: "default"
            options:
              - label: "Default"
                value: "default"
              - label: "Not Default"
                value: "not default"
      - label: "Variable List"
        name: "variableList"
        widget: "list"
        types:
          - label: "List Type (Object)"
            name: "listTypeObject"
            widget: "object"
            fields:
              - label: "Select"
                name: "Select"
                widget: "select"
                default: "default"
                options:
                  - label: "Default"
                    value: "default"
                  - label: "Not Default"
                    value: "not default"
```

What I've noticed so far is that the default select widget setting stops working whenever involved in creating a **new** list item/variable list object.

![netlify-cms-issue-select-widget-default](https://user-images.githubusercontent.com/498069/58754480-cec18900-849e-11e9-9c53-85712e40e8ca.png)

- Netlify CMS version: 2.9.0 via unpkg
- Git provider: GitHub
- OS: Mac OS 10.14.5 Mojave
- Browser version: Chrome 74.0.3729.169
- Node.JS version: v12.1.0
