### ISSUE TITLE
Relation widget behaves unexpectedly with lists of values

### ISSUE THREAD

**Issue by dawaltconley** [netlify/netlify-cms#2306]
**Describe the bug**

The `relation` widget treats lists of values as a single item (a list), rather than multiple items.

I believe this is a bug because:
- it doesn't seem like intended or useful behavior.
- the widget allows the user to select a list of items as an option, but will not update the display to show that it is selected.
- a list of items can be selected and added to a multi-select, even though it does not update the widget's display—_but_ selecting another item after that, even with `multiple: true`, will clear the list-items from the selection. This makes them more-or-less incompatible with multi-select relation widgets.

**To Reproduce**

Given some `posts` with front matter like:

```
---
categories:
  - foo
  - bar
---
```
```
---
categories:
  - bar
  - baz
---
```

And a collection with the following field:

```
- label: Categories
  name: categories
  widget: relation
  collection: posts
  searchFields: categories
  valueField: categories
```

You get a widget that lets you select between the list `foo,bar` and the list `bar,baz`.

![relation-widget-bugged](https://user-images.githubusercontent.com/20374950/56834284-fccc0180-683e-11e9-97a0-cd8652d06add.png)

**Expected behavior**

A widget that lets you select between the strings `foo`, `bar`, and `baz`.

![relation-widget-expected](https://user-images.githubusercontent.com/20374950/56834292-0190b580-683f-11e9-92fa-a54a8a1c0b66.png)

**Applicable Versions:**

 - Netlify CMS version: 2.9.1
 - Git provider: GitHub
 - OS: macOS 10.13.6
 - Browser version: Safari 12.1

**CMS configuration**

In this case the relations widget references itself (which may not make much sense), but it doesn't have to. In these cases though, a widget with `multiple: true` will always cause this problem, since it outputs items as a list.

```
...
collections:
  - label: Videos
    label_singular: Video
    name: videos
    folder: _posts
    extension: md
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: date
        format: YYYY-MM-DD hh:mm:ss
      - label: URL
        name: link
        widget: string
      - label: Categories
        name: categories
        widget: relation
        collection: videos
        searchFields: categories
        valueField: categories
        multiple: true
```

**Additional context**
Not the main issue, I don't think, but here's the result of trying to add list values with `multiple` set to true (in this example, `Category 1` and `Category 2` are single-item lists and the rest are strings):

![relation-widget-bugged-2](https://user-images.githubusercontent.com/20374950/56836373-1112fd00-6845-11e9-9a74-d074bbd99070.gif)
