### ISSUE TITLE
Build fails after deleting entry in admin portal

### ISSUE THREAD

**Issue by LouiseReid** [netlify/netlify-cms#2314]
**Describe the bug**
Production build fails after deleting a collection entry from admin portal.  In my app I have a collection called gigs, this is the error I get from the deploy logs:

```
9:10:19 PM: Module build failed (from ./node_modules/gridsome/lib/webpack/loaders/page-query.js):
9:10:19 PM: Error: Cannot query field "event" on type "Gigs".
9:10:19 PM: GraphQL request (43:9)
9:10:19 PM: 42:         date,
9:10:19 PM: 43:         event,
9:10:19 PM:             ^
```
Deleting an entry seems to delete the whole folder where the entries are added to.

**Expected behavior**
I expect just that entry to be deleted and the production build to succeed with the deleted entry no longer showing on the site.

**Applicable Versions:**

 - Netlify CMS version: 2.9.2
 - Git provider: Github
 - OS: High Sierra
 - Browser version chrome 73

 - Node.JS version: 11.13

**CMS configuration**
```
backend:
  name: git-gateway
  repo: https://github.com/***
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: "src/images"
media_library:
  name: uploadcare


collections:
  - label: "Gigs"
    name: "gigs"
    folder: "api/gigs"
    create: true
    format: json
    extension: json
    identifier_field: date
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "gigs"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Event", name: "event", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Tickets", name: "tickets", widget: "string"}
```
