### ISSUE TITLE
Can't connect with self-hosted Gitlab repository

### ISSUE THREAD

**Issue by EliotBerriot** [netlify/netlify-cms#2316]
**Describe the bug**

I'm currently trying to self-host Netlify CMS, Gotrue and Git-Gateway to deploy a Jenkyll site, for which the git repo will be hosted on a private GitLab instance.

I'm following [this guide](https://github.com/hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway), which is working great so far (i'm using Docker for the deployment though).

I can load the admin, connect using my own identity server, however, problem aries when Netlify-CMS tries to talk to Gitlab through my own Git-Gateway.

As I understand, the CMS is trying to fetch Git repository data to get a list of posts, medias, etc. This is done by triggering requests such as:

```
https://gitgateway/gitlab/repository/files/.lfsconfig/raw?ref=master&ts=1557050043139
```

The requests is successfully received by my Git Gateway, and I can see the following log emitted by Git Gateway:

```
time="2019-05-05T09:49:24Z" level=info msg="Proxying to GitLab: https://mygitlab/projects/my/project/repository/files/.lfsconfig/raw?ref=master&ts=1557050043139" component=api method=GET path=/gitlab/repository/files/.lfsconfig/raw referer="http://127.0.0.1:4000/admin/" 
```

However, GitLab doesn't actually answer this request with the file content. Instead, it issues a 302 redirect to `/user/sign_in`.

I initially thought I had an issue with my auth tokens, but I can successfully reproduce the issue. Considering the following variables:

```
export TOKEN="gitlab_oauth_token"
export FILE="index.md"
```

This works:
```
curl -H "Authorization: Bearer $TOKEN" "https://mygitlab/api/v4/projects/my%2Fproject/repository/files/$FILE?ref=master"

# Outputs a json payload with file info
```

But this doesn't:

```
curl -H "Authorization: Bearer $TOKEN" "https://mygitlab/projects/my/project/repository/files/$FILE/raw?ref=master"
# triggers a redirection to /user/sign_in
```

Apparently, [fetching raw content using a private or oauth token is not supported anymore](https://gitlab.com/gitlab-org/gitlab-ce/issues/55081) by GitLab, which could explain the current behaviour. It's always possible I'm doing something wrong of course ;)

**To Reproduce**

Steps to reproduce the behavior. For example:
1. Setup a selfhosted git-gateway with a self-hosted Gitlab (v11.10.4)
1. Go to `/admin/`
2. Login
3. Open the browser console
4. See that requests for raw files returns 302 redirects when send to Git Gateway

**Expected behavior**

Netlify-CMS should retrieve repository data without issue.

netlify-cms-app 2.9.1 index.js:25:12
netlify-cms-core 2.11.0 bootstrap.js:52:12
netlify-cms 2.9.1
**Applicable Versions:**
 - Netlify CMS version:netlify-cms-app 2.9.1 index.js:25:12, netlify-cms-core 2.11.0 bootstrap.js:52:12, netlify-cms 2.9.1
 - Git provider: Gitlab (self hosted)
 

**CMS configuration**

```yml

backend:
  name: git-gateway
  branch: master
  identity_url: "https://gotrue/identity"
  gateway_url:  "https://gitgateway/git"
  
media_folder: assets
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
```

**Additional context**

I'm not sure if the issue should be solved at Netlify CMS level (by querying the API directly instead of Gitlab raw URL), or at Git-Gateway level.

Feel free to ask if you need more info :)
