### ISSUE TITLE
Issue with Uploadcare widget

### ISSUE THREAD

**Issue by smashercosmo** [netlify/netlify-cms#2318]
**Describe the bug**
When I add 
````
media_library:
  name: uploadcare
  config:
    publicKey: my_real_public_key
````
to my config.yaml and then open /admin page, Uploadcare widget doesn't show up and I see
````
netlify-cms-app.js:255 Uncaught (in promise) TypeError: Cannot read property 'init' of undefined
    at netlify-cms-app.js:255
````
in devtools console. If I remove media_library option, error goes away.

**Expected behavior**
There shouldn't be an error in console and widget should show  up

**Applicable Versions:**

 - Netlify CMS version: 2.9.1
 - Git provider: GitHub
 - OS: MacOS Sierra 10.12
 - Browser: Chrome 74
 - Node.JS version: 11.9.0

**CMS configuration**
````
backend:
  name: git-gateway
  accept_roles:
    - admin
  branch: master
  repo: name/my_real_repo

public_folder: /img
media_folder: static/img
media_library:
  name: uploadcare
  config:
    publicKey: my_real_public_key

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: string
      - label: "Publish Date"
        name: "date"
        widget: datetime
      - label: "Description"
        name: "description"
        widget: string
      - label: "Body"
        name: "body"
        widget: markdown
      - label: "Image"
        name: "image"
        widget: image
````

**Additional context**
I'm using netlify-cms with Gatsby
