### ISSUE TITLE
Nested validation failing silently

### ISSUE THREAD

**Issue by axelboc** [netlify/netlify-cms#2320]
**Describe the bug**
After upgrading Netlify CMS, I'm no longer able to publish or save changes. When I hit the _Publish Now_ button (or the _Save_ button when the editorial workflow is enabled), nothing happens; there's no progress bar at the top and the content is not published/saved. The following error appears in the console:

```
Uncaught (in promise) undefined
  (anonymous) @ netlify-cms-app.js:227
  async function (async)
  (anonymous) @ netlify-cms-app.js:227
  (anonymous) @ netlify-cms-app.js:227
  onSelection @ netlify-cms-app.js:59
  (anonymous) @ netlify-cms-app.js:180
  o.selectItem @ netlify-cms-app.js:180
  (anonymous) @ react-dom.production.min.js:14
  d @ react-dom.production.min.js:15
  [... some more calls in react-dom here]
```

I was able to narrow down the version of Netlify CMS that introduced the regression: [v2.4](https://github.com/netlify/netlify-cms/compare/netlify-cms@2.3.3...netlify-cms@2.4.0). The problem is still present in v2.9.1.

**Applicable Versions:**
 - Netlify CMS version: **2.4.2**
 - Git provider: **git-gateway** (GitHub)
 - OS: Windows 10
 - Browser version: Firefox 66, Chrome 74

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"
site_url: "https://..."

collections:
  - name: "pages"
    label: "Pages"
    files:
      - ...
      - ...
```

My config only has a single `files` collection, so the problem occurs when editing individual "pages". I've tried setting the following config options without success:

- `publish-mode: editorial_workflow`
- `show_preview_links: false`

**Additional context**
Thinking it was a permission issue with GitHub, I re-linked my repository in Netlify and requested a new access token for Netlify Identity, but the problem remained.
