### ISSUE TITLE
Workflow throws "TypeError: e.filter is not a function"

### ISSUE THREAD

**Issue by jschill** [netlify/netlify-cms#2331]
**Describe the bug**

When enabling the editorial workflow and clicking "Workflow" I get "TypeError: e.filter is not a function" pointing to this line: https://github.com/netlify/netlify-cms/blob/8e1556f9083d8d673f5f1f7de4bf68fbe0eb003a/packages/netlify-cms-core/src/backend.js#L508

**To Reproduce**

**Expected behavior**
I have never got this working so I don't know.

**Screenshots**
![Screenshot 2019-05-16 09 45 26](https://user-images.githubusercontent.com/224493/57835987-0ef6eb00-77c0-11e9-8d45-90c89cb35620.png)

**Applicable Versions:**

 - Netlify CMS version: 2.9.1
 - Git provider: Github
 - OS: macOS 10.14.4
 - Browser version: chrome 74

 - Node.JS version: n/a

**CMS configuration**

Repo removed
```
backend:
  name: github
  repo: my/repo
  branch: cms # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/assets/img/blog/uploads"
public_folder: "/assets/img/blog/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"} # Fix widget
      - {label: "Publish Date", name: "date", widget: "date", format: "MMM Do YY"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Cover image", name: "cover_image", widget: "image"}
      - {label: "Cover opacity", name: "cover_opacity", widget: "number", default: 0.4, valueType: "float", min: 0.1, max: 1.0, step: 0.1}
      - {label: "Cover blur", name: "cover_blur", widget: "string", default: "1px"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

```

**Additional context**

Seems like it has been up before: https://github.com/netlify/netlify-cms/issues/1320
