### ISSUE TITLE
Invariant Violation: Minified React error #31

### ISSUE THREAD

**Issue by ademilter** [netlify/netlify-cms#2338]
**Describe the bug**

Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Fri%20May%2031%202019%2015%3A06%3A17%20GMT%2B0300%20(GMT%2B03%3A00)&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Screenshots**

![Screen Shot 2019-05-21 at 16 39 51](https://user-images.githubusercontent.com/187922/58100830-17e42400-7be7-11e9-9b1e-f753b3fcdcd4.png)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

```yml
backend:
  name: git-gateway
  branch: netlify-cms

media_folder: static/img
public_folder: /img
site_url: https://sad-jackson-bece43.netlify.com

collections:
  - name: 'note'
    label: 'Note'
    folder: 'src/notes'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}'
    identifier_field: date
    fields:
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
```

**Additional context**

source code https://github.com/ademilter/notes/tree/netlify-cms

new note insert page works

![Screen Shot 2019-05-21 at 16 47 08](https://user-images.githubusercontent.com/187922/58101436-4adae780-7be8-11e9-9a8b-b515640f44a2.png)
