### ISSUE TITLE
Nested Fields for Search/Filtering in Relation Widget

### ISSUE THREAD

**Issue by WJXHenry** [netlify/netlify-cms#2356]
**Is your feature request related to a problem? Please describe.**

Feature request.

I was using the [Relation Widget](https://www.netlifycms.org/docs/widgets/#relation) and noticed that there doesn't seem to be a way to have nested search/display fields.

**Describe the solution you'd like**

I'd like to be able to use nested fields in the `displayFields` and `searchFields` options. Something like:
```
displayField: ['name.en', ...]
searchField: ['name.en', ...]

or

displayField: {name.en}
searchField: {name.en}
```
so it would be able to filter on objects.

Here is the structure of my collection:
```yaml
- name: "myCollection"
  label: "My Collection"
  ...
  fields:
    - name: "name"
      label: "Name"
      widget: "object"
      fields:
        - name: "en"
          label: "En"
          widget: "string"
        - name: "fr"
          label: "Fr"
          widget: "string"
          ...
```
which would produce this structure:
```yaml
# myCollection

name:
  en: "English Name"
  fr: "French Name"
...
```

It'd be ideal to be able to reference the English name (`name.en`) in the `displayFields` or `searchFields` options.

**Describe alternatives you've considered**

I have tried flattening the structure of my collection to something like:

```yaml
name_en: "English Name"
name_fr: "French Name"
```

but it becomes messy with deeply nested objects.

**Additional context**

To prevent breaking changes, the input to the `displayFields` or `searchFields` options could be an object-like string (E.g. `'{name.en}'`) so it can be differentiated from regular string/list inputs.
