### ISSUE TITLE
 self-referential / circular data structures cause "RangeError: Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by sempostma** [netlify/netlify-cms#2360]
**Describe the bug**
The bug comes up when referencing data using yaml.

**To Reproduce**
YAML allows for circular data structures but netlify-cms can't handle this. referential mostly works find fine but self-referential causes a RangeError: Maximum call stack size exceeded error.

```yaml
collections:
  - name: "pages"
    label: "Pagina's"
    folder: "src/pages"
    create: true
    preview_path: "{{slug}}"
    editor:
      preview: false
    fields:
      &a1
      - { type: string, label: "Title", name: "title", widget: "string" }
      - { type: hidden, label: "Layout", name: "layout", widget: "hidden", default: "BlogPost"}
      - { type: datetime, label: "Publish Date", name: "date", widget: "datetime" }
      - { type: string, label: "Description", name: "description", widget: "string" }
      - { type: markdown, label: "Body", name: "body", widget: "markdown" }      
      - { type: object, label: Nested Example, name: nestedExample, widget: list, fields: *a1 }
```

**Expected behavior**
The cms should allow for circular data up to a specific depth or it should step through the circular data only when the user expands a specific section of the UI.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/34186586/59138067-30945e00-898b-11e9-9b77-88b5a8b48cf6.PNG)
![Capture2](https://user-images.githubusercontent.com/34186586/59138068-30945e00-898b-11e9-98b5-6f1ebedeed8b.PNG)

**Applicable Versions:**

 - Netlify CMS version: 2.9.1

**CMS configuration**

```yaml
backend:
  name: bitbucket
  branch: master
  repo: ###############
  accept_roles:
    - admin
    - editor


media_folder: src/uploads
public_folder: /uploads

collections:
  - name: "pages"
    label: "Pagina's"
    folder: "src/pages"
    create: true
    preview_path: "{{slug}}"
    editor:
      preview: false
    fields:
      &a1
      - { type: string, label: "Title", name: "title", widget: "string" }
      - { type: hidden, label: "Layout", name: "layout", widget: "hidden", default: "BlogPost"}
      - { type: datetime, label: "Publish Date", name: "date", widget: "datetime" }
      - { type: string, label: "Description", name: "description", widget: "string" }
      - { type: markdown, label: "Body", name: "body", widget: "markdown" }      
      - { type: list, label: Nested Example, name: nestedExample, widget: list, fields: *a1, default: [] }

  - name: "posts"
    label: "Posts"
    folder: "src/pages/posts"
    create: true
    preview_path: "{{slug}}"
    editor:
      preview: false
    fields:
      *a1 
```
