### ISSUE TITLE
How to enable netlify identity widget on jekyll hosted on gitlab

### ISSUE THREAD

**Issue by sandhyadevadas** [netlify/netlify-cms#2365]
Let me say I am not hosting jekyll with netlify but hosting on gitlab and added two files  
1. admin/index.html
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>
</head>
<body>
  <!-- Include the script that builds the page and powers Netlify CMS -->
  <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
</body>
</html>
```
and
2. admin/config.yml
```
backend:
  name: gitlab
  repo: bpmottathai/news # Path to your GitLab repository
  auth_type: implicit # Required for implicit grant
  app_id: b09bdfef685a87474xxxxxxxxxxxxxxxxxxxxxxx # Application ID from your GitLab settings
media_folder: "images/uploads"
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
```
I can login with my gitlab login details. Can I allow someone to login to add/edit content through netlify cms by using identity widget or else?

I added 
```
<script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
<script>
  if (window.netlifyIdentity) {
    window.netlifyIdentity.on("init", user => {
      if (!user) {
        window.netlifyIdentity.on("login", () => {
          document.location.href = "/admin/";
        });
      }
    });
  }
</script>
```
to admin/index.html `</head>` portion but when login from other account I get error like   

![](https://i.ibb.co/BG64XpL/netlify.png)
