### ISSUE TITLE
how to disable netlify editor preview icon

### ISSUE THREAD

**Issue by sandhyadevadas** [netlify/netlify-cms#2366]
I used 
```
editor:
  preview: false
```
in admin/config.yml of jekyll
Still the preview icon is showing in admin page.

**Comment by erquhart** [comment]
That setting is currently per collection - so you would do:

```yaml
collections:
  - name: posts
    editor:
      preview: false
```
