### ISSUE TITLE
List of object is not editable.

### ISSUE THREAD

**Issue by danielstaleiny** [netlify/netlify-cms#2375]
Hi, when I create list of objects, fields are not editable. 
Not working with `field: Object`
```
      - label: "Sections"
        name: "sections"
        widget: "list"
        field:
          label: "Author"
          name: "author"
          widget: "object"
          fields:
            - { label: "Navigation text", name: "navtitle", widget: "text" }
            - label: "Type"
              name: "type_ref"
              widget: "select"
              options:
                - { label: "Title", value: "string" }
                - { label: "Text", value: "text" }
                - { label: "Checker", value: "boolean" }
            - {label: "Value", name: "value", widget: "string"}

```
If used `fields: - Object`. everything works as desired. I believe this is an bug how the field: is proccessed by cms. 
```
      - label: "Sections"
        name: "sections"
        widget: "list"
        fields:
         - label: "Author"
           name: "author"
           widget: "object"
           fields:
             - { label: "Navigation text", name: "navtitle", widget: "text" }
             - label: "Type"
               name: "type_ref"
               widget: "select"
               options:
                 - { label: "Title", value: "string" }
                 - { label: "Text", value: "text" }
                 - { label: "Checker", value: "boolean" }
                 - {label: "Value", name: "value", widget: "string"}

```
