### ISSUE TITLE
Wrong collection settings used on create

### ISSUE THREAD

**Issue by smakinson** [netlify/netlify-cms#238]
**- Do you want to request a *feature* or report a *bug*?**
Bug report

**- What is the current behavior?**
Incorrect collection settings used when creating a new item. This was the first thing I created from the admin.

**- If the current behavior is a bug, please provide the steps to reproduce.**
* I am running the admin locally using the victor-hugo server script.
* I have the base folders in site for hugo committed.
* I clicked the pencil icon and chose the second collection ( Event Type ) in the config
* I was taken to a proper form.
* I filled in its title field ( the only field ) and clicked save.
* I was taken to the edit form for the first collection in the config ( it has more fields )
* I saw that the .md file on github had the incorrect fields. ( though title was in both collections )

I am using: 
`publish_mode: editorial_workflow`

Here are the collections from the config _( I did notice afterwards that I should have had site/ in the folder paths, but I don't think that should have caused the issue )_:

```
collections:
  - name: "event"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
       - { label: "Title", name: "title", widget: "string", default: "" }
       - { label: "Main Image", name: "main-image", widget: "image", default: "" }
       - { label: "Event Type", name: "event-type", widget: "string", default: "" }
       - { label: "Start Date", name: "start-date", widget: "datetime", default: "" }
       - { label: "Audience", name: "audience", widget: "string", default: "" }
       - { label: "Cost", name: "cost", widget: "string", default: "Free" }

       - { label: "Description", name: "description", widget: "markdown", default: "" }
  - name: "event-type"
    label: "Event Type"
    folder: "content/event-types"
    create: true
    slug: "{{slug}}"
    fields:
       - { label: "Title", name: "title", widget: "string", default: "" }
```

The problem did not occur on creating a second Event Type.

I do have this as my last line in the config for copy paste. I assume comments will be ignored:
`#- { label: "", name: "", widget: "", default: "" }`

Also as I'm typing this I noticed I had left a blank line between the Cost and Description when I reordered them.

**- What is the expected behavior?**
The proper collection fields to be used for creating the .md file and the proper form to be shown.

**- Please mention your node.js, and operating system version.**
node v6.9.4 
osx 10.11.6
