### ISSUE TITLE
List widget populates default/empty entry by default

### ISSUE THREAD

**Issue by madikarizma** [netlify/netlify-cms#2380]
**Describe the bug**
List widget populates default/empty entry by default

**To Reproduce**
Use configuration below / see screenshot

**Expected behavior**
When considering UX for a content editor, especially when a list field is configured to be *not required*, forcing the user to remove the default list entry is an unnecessary step. It is better behavior for a user to add list items when they want them vs. removing the default/empty list item when they don't want them. This is also a more educational experience for a user who may be getting acquainted with Netlify CMS. The empty gray block you see by default is not intuitive and could confuse the user. In my opinion, fields should not be populated with a default value unless it is configured to have a default value.

**Screenshots**
<img width="836" alt="Screen Shot 2019-06-12 at 2 58 06 PM" src="https://user-images.githubusercontent.com/498069/59378671-df85c080-8d22-11e9-91f4-c81de2a1a2b8.png">

**Applicable Versions:**
- Netlify CMS version: 2.9.0 via unpkg
- Git provider: GitHub
- OS: Mac OS 10.14.5 Mojave
- Browser version: Chrome 74.0.3729.169
- Node.JS version: v12.1.0

**CMS configuration**
```
fields:
- label: List
  name: list
  widget: list
  required: false
  fields:
  - label: Test
    name: test
    widget: text
```

**Comment by barthc** [comment]
@madikarizma  PR #2374 will fix this issue.

**Comment by Undistraction** [comment]
@barthc This is still a problem in 2.9.5 if any of the fields of the list widget have default values.

**Comment by Undistraction** [comment]
@barthc this is still a problem as of 2.9.5 if any fields have a default value, for example:

```
fields:
- label: List
  name: list
  widget: list
  required: false
  fields:
  - label: Test
    name: test
    widget: text
    default: 'test'
```

**Comment by barthc** [comment]
@Undistraction the OP says a config like this:
```
fields:
- label: List
  name: list
  widget: list
  required: false
  fields:
  - label: Test
    name: test
    widget: text
```
should not force an empty UI input, your config have a default set `default: 'test'`.

**Comment by Undistraction** [comment]
@barthc I said this in my post:
> if any fields have a default value

I'm pretty sure this is not intended behaviour and it seems related to this issue. If a list is marked as `required: false`, the required-ness of its own fields shouldn't force it to be required. They should only apply if it has been added.

If this is indeed not the intended behaviour and you think this is an unrelated issue I'm happy to write up a new issue.

**Comment by barthc** [comment]
> If a list is marked as required: false,

https://github.com/netlify/netlify-cms/issues/2103#issuecomment-468389785

> I'm pretty sure this is not intended behaviour and it seems related to this issue.

It's indeed the way the list default behaviour was implemented. Or another approach I can think of is to handle all `list` widget default behavior only onclick of the `add +` button

**Comment by Undistraction** [comment]
@barthc Thanks for the link. This is definitely unexpected behaviour (at least to me). Good to see it is being discussed though.

**Comment by DamengRandom** [comment]
Set default: 'Text', then . No test will disappear, thanks @Undistraction, the solution works for me

like this: 
```
fields:
- label: List
  name: list
  widget: list
  required: false
  fields:
  - label: Test
    name: test
    widget: text
    default: 'test'
```
