### ISSUE TITLE
[Bug] __PATH_PREFIX__ is not defined

### ISSUE THREAD

**Issue by derevandal** [netlify/netlify-cms#2400]
**Describe the bug**
When I log in my **Netlify CMS** with **Netlify Identity**, I got the error **`__PATH_PREFIX__ is not defined`** and the *cms* doen'st redirect me to cms's page. 

**To Reproduce**
1. Only install and try to use

**Expected behavior**
Redirect to `/admin/ ` page

**Screenshots**
![image](https://user-images.githubusercontent.com/1340508/59968644-656bed80-9513-11e9-8d60-c3806e0bd5a9.png)

**Applicable Versions:**
 - Netlify CMS version: 2.9.3
 - Git provider: Git Gateway (Netlify Identity + Gitlab)
 - OS: Windows 10
 - Browser version: 75.0.3770.100 (Versão oficial) 64 bits (cohort: Stable)
 - Node.JS version: 10.15.3

**CMS configuration**
```yml
backend:
  name: git-gateway
site_url: https://institutoalves.com.br
media_folder: "static/uploads"
public_folder: "/uploads"
show_preview_links: false

collections:
  - name: "talks"
    label: "Palestras"
    folder: "content/talks"
    create: true
    slug: "palestras/{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string" }
      - {label: "Link", name: "link", widget: "string", default: "/contato" }
      - {label: "Imagem", name: "image", widget: "image" }
      - {label: "Descrição", name: "description", widget: "string" }
      - {label: "Rascunho", name: "draft", widget: "boolean", default: true}
      - {label: "Conteúdo", name: "body", widget: "markdown" }
    editor:
      preview: false
  - name: "store"
    label: "Produtos"
    folder: "content/store"
    create: true
    slug: "{{type}}/{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - label: "Preço"
        name: "price"
        widget: "object"
        fields:
          - {label: "De:", name: "from", widget: string }
          - {label: "Por:", name: "to", widget: string }
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - label: "Tipo"
        name: "type"
        widget: "select"
        options:
          - {label: "Brinquedos Pedagógicos", value: "brinquedos-pedagogicos" }
          - {label: "Livros", value: "livros" }
          - {label: "Outros", value: "outros" }
      - {label: "Rascunho", name: "draft", widget: "boolean", default: true}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
    editor:
      preview: false
  - name: "blog"
    label: "Publicações"
    folder: "content/posts"
    create: true
    slug: "blog/{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Rascunho", name: "draft", widget: "boolean", default: true}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
  - label: "Páginas"
    name: "pages"
    create: false
    files:
      - label: "Página Inicial"
        name: "home"
        file: "content/settings/home.yml"
        fields:
          - {label: "Youtube URL", name: "homeYoutubeURL", widget: "string"}
      - label: "Contato"
        name: "contact"
        file: "content/settings/contact.yml"
        fields:
          - {label: "WhatsApp URL", name: "contactWhatsappUrl", widget: "string"}
      - label: "Sobre Nós"
        name: "about-us"
        file: "content/settings/about-us.yml"
        fields:
          - {label: "Conteúdo", name: "body", widget: "markdown"}
    editor:
      preview: false
```

**Additional context**
I'm using **Gridsome**, this is my configs:
```js
// gridsome.config.js
module.exports = {
  plugins: [
    /*  ... */
    {
      use: `gridsome-plugin-netlify-cms`,
      options: {
        htmlTitle: 'Editor'
      }
    }
  ]
}
```
