### ISSUE TITLE
Filter items in relation field by default

### ISSUE THREAD

**Issue by austincondiff** [netlify/netlify-cms#2405]
I'd like the ability to filter a relation field to only display items that match a certain field.

**Comment by erquhart** [comment]
Can you give an example?

**Comment by austincondiff** [comment]
I have two folder collections called Products and Product Categories. I have a few product categories, two of which are "electronics" and "accessories". I have a relation field to choose the product category but I also have another relation field to select multiple accessories for that product. 

I want to be able to limit or filter the products that you can select in the accessories relation field to only products that have the category relation field set to "accessories". 

I'd like to display a section at the bottom of my product page that lists the accessories available for that product. Because these accessories are also products, the user can click any of them to view these products using the products template just like any other product.

Here is a snippet in my admin config.yml.

```yml
collections:
  - name: "productCategories"
    label: "Product Categories"
    folder: "src/pages/product-categories"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Product Category Name", name: "title" }
      - { label: "Slug", name: "slug", required: true, pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Cannot contain spaces, capital letters, or special characters. You may separate words with dashes and numbers are allowed."], hint: "This will be used in the URL." }
  - name: "products"
    label: "Products"
    folder: "src/pages/products"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Product Name", name: "title" }
      - { label: "Slug", name: "slug", required: true, pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Cannot contain spaces, capital letters, or special characters. You may separate words with dashes and numbers are allowed."], hint: "This will be used in the URL." }
      - { label: "Category", name: "category", widget: "relation", collection: "productCategories", searchFields: ["title"], valueField: "slug", displayFields: ["title"] }
      - { label: "Overview", name: "overview", widget: "markdown" }
      - { label: "Price", name: "price" }
      - { label: "Accessories", name: "accessories", widget: "relation", collection: "products", searchFields: ["title"], valueField: "slug", displayFields: ["title"], multiple: true, required: false }
      - { label: "Related Products", name: "relatedProducts", widget: "relation", collection: "products", searchFields: ["title"], valueField: "slug", displayFields: ["title"], multiple: true, required: false }
```

Let me know if you need any clarification.

**Comment by tomrutgers** [comment]
Sounds like it’s related to https://github.com/netlify/netlify-cms/issues/565

**Comment by erquhart** [comment]
Yep, this is a duplicate of #565, please thumb that issue up and subscribe to get updates 👍

**Comment by austincondiff** [comment]
@erquhart @tomrutgers I think you might be misunderstanding what I am saying. From what I can tell this is a separate issue from #585 which advocates for conditional fields. 

I am proposing a relation field displaying a filtered collection based on fields in each item in the collection being referenced. 

In this context, I only want to display products in the relation field dropdown that are associated with the accessory category (where categories are its own folder collection). Are you following me?

**Comment by erquhart** [comment]
Right - if we have conditional fields, you can set up two relation fields and display only one based on the value of the first relation field.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by austincondiff** [comment]
That is not what I am saying at all. Let me try to explain better.

In product edit screen, I want to have a relation field called accessories that lists other products, but only lists the products in the accessory product category.

Product Categories is a folder collection, each category is an item within that collection.

Consider the following...

Categories:
- Electronics
- Clothing
- Accessories

Products:
- iPhone (category: Electronics)
- iPhone Case (category: Accessories)
- T-shirt (category: Clothing)

If I go to edit the iPhone product, I see the following fields:
- Title
- Category (relation to Product Categories collection)
- Price
- Description
- Accessories (relation to self - Products)

When I click on the accessories drop down, I only want to see iPhone case because this product has a category of accessories. I don’t want to see iPhone and Tshirt as they do not have accessories set as their associated product category. Does that make more sense?

**Comment by erquhart** [comment]
Ah you're totally right, I was thinking you had different collections for each product category rather than a single product collection. We could add filtering to the relation widget with the same approach taken for the `filter` property on collections themselves: https://www.netlifycms.org/docs/collection-types#filtered-folder-collections

We would just need to treat the filter value as a template, so you could do:

```yaml
  - label: "Related Products"
    name: "relatedProducts"
    widget: "relation"
    collection: "products"
    searchFields: ["title"]
    valueField: "slug"
    displayFields: ["title"]
    filter:
      field: category
      value: "{{category}}"
    multiple: true
    required: false
```

Thoughts?

**Comment by austincondiff** [comment]
You are on the right track! I’d do something like this...
```yml
  - label: "Related Products"
    name: "relatedProducts"
    widget: "relation"
    collection: "products"
    searchFields: ["title"]
    valueField: "slug"
    displayFields: ["title"]
    filters:
      - field: category
        values: ["accessories", "add-ons"]
      - field: colors
        values: ["red", "blue"]
    multiple: true
    required: false
```

This allows multiple filters and values to allow more flexibility.

**Comment by erquhart** [comment]
Allowing multiple filters could work, but keeping it simple and using existing logic makes this low hanging fruit. You'll want to use template strings rather than hardcoding, hence my use of `{{category}}` rather than "accessories", as you need the current value of the field _as_ the filter.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Niek** [comment]
Related to this, it would be great if it'd be possible to filter on the existence of a field, so something like ``filter: {field: "myfield"}`` means "any value".

**Comment by miguelt1** [comment]
this feature would be awesome, so we could filter a relation by language for example

**Comment by JimmyOei** [comment]
I was also looking for a feature like this, but it was not implemented yet even after so many years. I then created my own custom relation widget a couple weeks ago, which works exactly as @austincondiff mentioned, using: 
```
filters:
  - field: category
    values: ["accessories", "add-ons"]
  - field: colors
    values: ["red", "blue"]
```

But I think this feature would be really nice to have in the relation widget by default. Could I pick this up?
