### ISSUE TITLE
Invariant Violation error - Git Gateway

### ISSUE THREAD

**Issue by bsde1245** [netlify/netlify-cms#2416]
I am hosting jekyll site on netlify forked from github(gh-pages).
I am trying to add netlify cms feature.
My admin/index.html
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>
</head>
<body>
  <!-- Include the script that builds the page and powers Netlify CMS -->
  <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
</body>
</html>
```
admin/config.yml
```
backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
site_url: https://optimistic-poitras-148d9a.netlify.com
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    editor:
      preview: false
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "select", multiple: true, options: ["kerala", "india", "world", "business", "movie", "tech", "job", "sports", "health", "auto", "she", "travel", "homestyle", "index"]}
      - {label: "Audio File", name: "speech", widget: "file", required: false}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Youtube Video Id", name: "youtubeId", widget: "string", required: false}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
```
When going to  mysite/admin, I get a login screen like below,
![image](https://i.ibb.co/BjwPRCr/netli.png)
On sign in with my netlify account, I get
```
Error
There's been an error - please report it.

Details
Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=t%3A%20invalid_grant%3A%20No%20user%20found%20with%20this%20email&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

Note: I signed in to netlify.com using github.
