### ISSUE TITLE
`accept_roles` not working as expected

### ISSUE THREAD

**Issue by lewnelson** [netlify/netlify-cms#2418]
**Describe the bug**
When allowing users to sign up to the CMS via the identity widget if you have configuration to only accept certain roles these do not work by default.

Example:

```
backend:
  name: git-gateway
  branch: staging
  accept_roles:
    - admin
    - editor
```

* New user signs up with Google oAuth provider
* By default they have no roles as a new user
* Expected behaviour is they should not have access, however they do have access

**To Reproduce**

See above

**Expected behavior**
Expecting users without appropriate roles to have no access to the CMS

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: 2.9.5
 - Git provider: GitHub
 - OS: Mac 10.14.5
 - Browser version: Chrome 75.0.3770.100

 - Node.JS version:

**CMS configuration**
```
backend:
  name: git-gateway
  branch: staging
  accept_roles:
    - admin
    - editor
media_folder: static/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
show_preview_links: true
collections:
  - name: meta_data
    label: Meta data
    folder: resources/content/meta
    create: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - name: head
        label: SEO <head /> data
        widget: object
        fields:
          - name: title
            label: Site title tag value
            widget: string
          - name: meta
            label: Meta tags
            label_singular: Meta tag
            widget: list
            fields:
              - name: name
                label: name attribute
                widget: string
              - name: content
                label: Content attribute, if no value is given then value will be taken from "File"
                widget: string
                required: false
                default: ""
              - name: file
                label: File
                description: Used instead of content where the meta tag is a URL to a file such as image etc.
                required: false
                default: ""
                widget: file
                allow_multiple: false

```

**Additional context**
