### ISSUE TITLE
not able to add a new pic in gallery using netlify cms

### ISSUE THREAD

**Issue by TenSketch** [netlify/netlify-cms#2420]
I get error when i try to upload using netify CMS,
![Screenshot_23](https://user-images.githubusercontent.com/23096153/60509337-4aa33100-9cea-11e9-8242-13a483375b4c.png)
```yml
backend:   
  name: git-gateway   
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
- name: "gallery" # Used in routes, e.g., /admin/collections/gallery
  label: "Gallery" # Used in the UI
  folder: "content/gallery" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - label: "Image"
      name: "image"
      required: true
      widget: "image"
    - label: "Picture Title"
      name: "title"
      widget: "string"
      required: true
    - label: "Upload Date"
      name: "date"
      required: false
      widget: "datetime"
    - label: "Draft"
      name: "draft"
      widget: "boolean"
      default: false
      required: false
    - label: "Categories"
      name: "categories"
      default: "gallery"
      required: false
      widget: "list"
```

**Comment by TenSketch** [comment]
![Screenshot_23](https://user-images.githubusercontent.com/23096153/60509128-d8325100-9ce9-11e9-8a41-6c0c62da4003.png)

my config.yml code

`backend:   
  name: git-gateway   
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
- name: "gallery" # Used in routes, e.g., /admin/collections/gallery
  label: "Gallery" # Used in the UI
  folder: "content/gallery" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - label: "Image"
      name: "image"
      required: true
      widget: "image"
    - label: "Picture Title"
      name: "title"
      widget: "string"
      required: true
    - label: "Upload Date"
      name: "date"
      required: false
      widget: "datetime"
    - label: "Draft"
      name: "draft"
      widget: "boolean"
      default: false
      required: false
    - label: "Categories"
      name: "categories"
      default: "gallery"
      required: false
      widget: "list"
`

**Comment by tomrutgers** [comment]
Your indentation is a bit off. Can you check if this works?
```yml
backend:   
  name: git-gateway   
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "gallery" # Used in routes, e.g., /admin/collections/gallery
    label: "Gallery" # Used in the UI
    folder: "content/gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Image"
        name: "image"
        required: true
        widget: "image"
      - label: "Picture Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Upload Date"
        name: "date"
        required: false
        widget: "datetime"
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
        required: false
      - label: "Categories"
        name: "categories"
        default: "gallery"
        required: false
        widget: "list"
```
