### ISSUE TITLE
Better way to add global settings

### ISSUE THREAD

**Issue by austincondiff** [netlify/netlify-cms#2427]
Currently the best way to add settings is to add a file collection called settings and add files to that collection for each setting/setting category. While this works, I propose we add a `settings` attribute alongside `collections` where you can add global settings.

This is what I mean in config.yml...

```yml
backend:
  name: git-gateway
  branch: master

site_url: https://my-site.netlify.com
media_folder: static/images
public_folder: images

collections: ...

settings:
    file: "src/data/settings.yml"
    fields:
      - label: Navigation
        name: navigation
        widget: object
        fields:
          - { label: "Links", label_singular: "Link", name: "links", widget: "list", fields: [
              { label: "Label", name: "label", widget: string, required: false },
              { label: "Path", name: "path", widget: string, required: false },
              { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false },
              { label: "Links", label_singular: "Link", name: "links", widget: "list", fields: [
                { label: "Label", name: "label", widget: string, required: false },
                { label: "Path", name: "path", widget: string, required: false },
                { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false },
                { label: "Links", label_singular: "Link", name: "links", widget: "list", fields: [
                  { label: "Label", name: "label", widget: string, required: false },
                  { label: "Path", name: "path", widget: string, required: false },
                  { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false }
                ]}
              ]}
            ]}
      - label: Footer
        name: footer
        fields:
          - label: Footer
            name: footer
            widget: object
            fields:
              - { label: "Copyright text", name: "copyrightText", widget: "string" }
              - { label: "Links", label_singular: "Link", name: "links", widget: "list", fields: [
                  { label: "Label", name: "label", widget: string, required: false },
                  { label: "Path", name: "path", widget: string, required: false },
                  { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false }
                ]}
      - label: "Social Media"
        name: social-media
        fields:
          - label: "Social Media"
            name: social-media
            widget: object
            fields:
              - { label: "Links", label_singular: "Link", name: "links", widget: "list", fields: [
                  { label: "Type", name: "type", widget: "select", options: [
                    { label: "Facebook", value: "facebook" },
                    { label: "Instagram", value: "instagram" },
                    { label: "LinkedIn", value: "linkedin" },
                    { label: "Pinterest", value: "pinterest" },
                    { label: "Tumblr", value: "tumblr" },
                    { label: "Twitter", value: "twitter" },
                    { label: "YouTube", value: "youtube" }
                  ]},
                  { label: "URL", name: "url", widget: string, required: false }
                ]}
```
