### ISSUE TITLE
Metadata not found for a Relation widget in a Custom Preview

### ISSUE THREAD

**Issue by chriddell** [netlify/netlify-cms#2434]
**Describe the bug**

Metadata for a relation widget can't be found in a Custom Preview Template.

**To Reproduce**

```javascript
const ArticlePreview = ({ entry, widgetFor, fieldsMetaData }) => {
  const data = entry.get('data').toJS()
  const author = fieldsMetaData.getIn(['authors', data.author])

  console.log(data.author) // returns value of author field (title)
  console.log(author) // returns undefined

  return (
    /* A view is returned here. */
  )
}
```

**Screenshots**

![BCB39D2E-26A8-4E6A-81D5-CEA138A36517](https://user-images.githubusercontent.com/8282383/60963341-69b44b00-a308-11e9-9b52-eea2a455fe09.jpg)

**Expected behavior**

`console.log(author)` returns the metadata for the 'related' author.

**Applicable Versions:**
 - Netlify CMS version: 2.9.5
 - Git provider: BitBucket

**CMS configuration**
```yml
- name: articles
  label: Articles
  folder: data/articles
  create: true
  fields:
    - label: "TemplateKey"
      name: templateKey
      widget: hidden
      default: "templates/ArticleTemplate"
    - label: "Title"
      name: title
      widget: string
    - label: "Author"
      name: author
      widget: relation
      collection: "authors"
      searchFields: ["title"]
      valueField: "title"
      displayFields: ["title", "twitterHandle"]
    - label: "Body"
      name: body
      widget: markdown

- name: authors
  label: Authors
  folder: data/authors
  create: true
  fields:
    - label: "TemplateKey"
      name: templateKey
      widget: hidden
      default: "templates/AuthorTemplate"
    - label: "Name"
      name: title
      widget: string
    - label: "Twitter Handle"
      name: twitterHandle
      widget: string
      required: false
```

**Additional context**

Have also tried using a Class Component instead of a Function Component, but no luck.
