### ISSUE TITLE
Support for simple widget types within List

### ISSUE THREAD

**Issue by cunneen** [netlify/netlify-cms#2436]
**Is your feature request related to a problem? Please describe.**

I'm trying to create / edit a data collection, but there doesn't seem to be a way to have a *list* widget of multiple *simple* data types (e.g. string, number).

I want the resulting data to be like this:

```json
items: [ "one", "two", "three" ]
```

**Describe the solution you'd like**

Maybe a `list_item_widget` property or something similar, which would allow this:

```yaml
  - name: "test"
    label: "test"
    folder: "site/data/test"
    create: true
    delete: true
    extension: json
    format: json
    fields:
      - label: "title"
        name: "title"
        widget: "string"
      - label: "items"
        name: "items"
        allow_add: true
        widget: "list"
        list_item_widget: "string"

```

Please forgive me if there's already a way to do this.

Edit: Just to clarify, I know that the editor-user can separate list items with commas in the plain text input, but with a lot of items the UI looks awful and a non-technical user is likely to mess this up.
