### ISSUE TITLE
"Cannot read property 'hits' of undefined" when using relation widget

### ISSUE THREAD

**Issue by promozoo** [netlify/netlify-cms#2458]
**Describe the bug**
Getting "Cannot read property 'hits' of undefined" in console when using the relation widget. Not getting any results, whether I click on the widget or type characters in it to search. Confused by example in documentation, as it mixes the use of collection 'name' , and an 'author' subfield also called 'name'... https://www.netlifycms.org/docs/widgets/relation/#relation

**Expected behaviour**
When I click on the 'previewImage' dropdown menu I should be able to select any of the four images I've previously uploaded in the 'caseStudyInfo' section.

**Screenshots**
<img width="1440" alt="Screenshot 2019-07-19 at 15 26 28" src="https://user-images.githubusercontent.com/35098605/61542551-b4853f80-aa39-11e9-8fda-6c08701bc1d7.png">

**Applicable Versions:**
 - Netlify Cms App: 2.9.6
 - Gatsby version: 2.13.28

**CMS configuration**
```
      - label: Case Study Info
        name: caseStudyInfo
        widget: object
        fields:
          - label: Case Study 1st Section
            name: caseStudyFirstSection
            widget: object
            fields:
              - label: What was the campaign?
                name: text
                widget: text
              - label: Image
                name: image
                widget: image
          - label: Case Study 2nd Section
            name: caseStudySecondSection
            widget: object
            fields:
              - label: What was the creative brief?
                name: text
                widget: text
              - label: Image
                name: image
                widget: image
          - label: Case Study 3rd Section
            name: caseStudyThirdSection
            widget: object
            fields:
              - label: What did we do?
                name: text
                widget: text
              - label: Image
                name: image
                widget: image
          - label: Case Study 4th Section
            name: caseStudyFourthSection
            widget: object
            fields:
              - label: How did it go?
                name: text
                widget: text
              - label: Image
                name: image
                widget: image
      - label: Preview Image
        name: previewImage
        widget: relation
        collection: caseStudyInfo
        searchFields:
          [
            caseStudyFirstSection.image,
            caseStudySecondSection.image,
            caseStudyThirdSection.image,
            caseStudyFourthSection.image,
          ]
        valueField: image
```
