### ISSUE TITLE
Dropdown menu widget not populating when running gatsby build

### ISSUE THREAD

**Issue by vickylance** [netlify/netlify-cms#2460]
**Describe the bug**

I have configured 2 dropdown menus as widget select. But the dropdown menu is not populating if run `gatsby build` and `gatsby serve`. But it is getting populated if I run `gatsby develop`

**To Reproduce**

Add the above config to a new gatsby project and then 

**Expected behavior**

The dropdown menu to be populated even after `gatsby build`.

**Screenshots**

<img width="814" alt="Screen Shot 2019-07-21 at 5 27 35 PM" src="https://user-images.githubusercontent.com/5861833/61590942-65780f80-abdd-11e9-8d93-fa6663bc91c4.png">
<img width="824" alt="Screen Shot 2019-07-21 at 5 27 30 PM" src="https://user-images.githubusercontent.com/5861833/61590943-69a42d00-abdd-11e9-9aa3-27b4c99a72f9.png">

**Applicable Versions:**

 - netlify-cms-app: 2.9.6,
 - Git provider: GitHub
 - OS: Mac OS Mojave 10.14.5 (18F132)
 - Browser version: Chrome 75.0.3770.142 (Official Build) (64-bit)
 - Node.JS version: v10.13.0

**CMS configuration**

```
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Author", name: "author", widget: "string", default: 'Vignesh S' }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Language", name: "language", widget: "select", options: ["en", "es"] }
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["reactjs", "gatsbyjs", "nextjs", "nuxtjs", "phaser3", "python", "scikit-learn", "anaconda", "spyder", "matplotlib", "bokeh", "pandas"]
      - { label: "Body", name: "body", widget: "markdown" }
```
