### ISSUE TITLE
Widget for Sequence of Strings

### ISSUE THREAD

**Issue by Kasuko** [netlify/netlify-cms#248]
**- Do you want to request a *feature* or report a *bug*?**

feature

**- What is the current behavior?**

I am interested in using Netlify CMS to manage a Hexo blog. I have it working except for one pretty major issue. Hexo expects the tags and categories in the front matter to be a sequence of strings.

There is no widget, as far as I can tell that will allow me to create a sequence of strings. I found the (previously documented, though now undocumented) List widget and attempted to use that. However, that appears to make a sequence of objects. Is it possible to use that widget to make a sequence of string?

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

There should be a widget that allows you to make a variable sized list of strings that aren't part of an object.

**- Please mention your node.js, and operating system version.**

hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.9.4
v8: 5.1.281.89
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j

**Comment by biilmann** [comment]
I think the list widget should work as you want if you leave out the "fields" attribute

**Comment by Kasuko** [comment]
It doesn't seem to. When I set the widget to list as in

```yaml
collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "source/_posts/blog" # The path to the folder where the documents are stored
    sort: "date:desc"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", class: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}

```

I get really odd list behaviour as shown in
<img width="292" alt="screen shot 2017-03-01 at 3 10 57 pm" src="https://cloud.githubusercontent.com/assets/86419/23479140/78d58112-fe91-11e6-8c5b-ef44353fc0e3.png">


Where I can not seem to click and edit the values in the list anywhere.
