### ISSUE TITLE
segregation of content to another repo

### ISSUE THREAD

**Issue by haxmax** [netlify/netlify-cms#2490]
I have a web application "MyNotes" which is a gatsby application. I am trying to use netlify-cms on it. On github, I have following structure.
 - MyNotes Repository(private)
 - MyNotesContent Repository(public)
**I am pulling data to MyNotes using gatsby-source-github-api.**

**Is your feature request related to a problem? Please describe**
I would like to add Netlify-cms on MyNotes Application with backend repo as MyNotesContent.
```
backend:
  name: git-gateway
  repo: username/MyNotesContent 
  branch: master
```
**However, I am not able to write to MyNotesContent repo.**
