### ISSUE TITLE
Error: The Field title is missing for the collection

### ISSUE THREAD

**Issue by TidyIQ** [netlify/netlify-cms#2491]
Using Gatsby, all I did was install `"netlify-cms-app": "^2.9.7"` and `"gatsby-plugin-netlify-cms": "^4.1.6"`, added the plugin to `gatsby-config.js`, then created the following file at `static/admin/config.yml`:

```
backend:
  name: test-repo
media_folder: static/img
public_folder: img
collections:
  - name: "navbar"
    label: "Navigation Bar"
    folder: "navbar"
    create: true
    fields:
      - name: "links"
        label: "Links"
        widget: "list"
        fields:
          - { name: "label", label: "Label", widget: "string" }
          - { name: "path", label: "Path", widget: "string" }
```

When I run `gatsby develop` and go to `http://localhost:8000/admin` I get the following error message in console:

```
 ⛔ The Field title is missing for the collection “navbar”
Netlify CMS tries to infer the entry title automatically, but one couldn't be found for entries of
the collection “navbar”. Please check your site configuration.
```

That's literally all I've done so it should be easy enough to reproduce the issue. No idea what I've done wrong.
