### ISSUE TITLE
Editor types over last word on mobile (andorid)

### ISSUE THREAD

**Issue by Jackbennett** [netlify/netlify-cms#2510]
Hi, tried to have a look around but I didn't see this in another issue. Tho I can't be the first to come across this surely.

**Describe the bug**

Typing in the editor (full or markdown) isn't possible on androids chrome. Typing overwrites the last word when hitting space, generally just making gibberish output if you manage any at all. Clicking into text areas moves the viewport around unhelpfully. Clicking the top of a post moves the cursor under the controls bar (I think).

**To Reproduce**
Steps to reproduce the behaviour.
1. Go to admin, create or edit a collection
2. Start typing in the body for content

**Expected behavior**

Write post content, in markdown or the ritch editor.

**Applicable Versions:**
 - Netlify CMS version: [e.g. 2.9.7]
 - Git provider: gitlab
 - OS: Andorid 9, tried on 2 phones
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

```yml
backend:
  name: gitlab
  auth_type: implicit
  app_id: ...
media_folder: "media"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sidebar", name: "sidebar",  widget: "select", multiple: false, options: ["false", "auto"]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Stack", name: "stack", widget: "select", multiple: true, options: [
        "design",
        "applications",
        "development",
        "operations",
        "network",
        "hardware"
      ]}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
```
