### ISSUE TITLE
Getting TypeError: e.join is not a function when pressing "New Blog" Button

### ISSUE THREAD

**Issue by robwelan** [netlify/netlify-cms#2513]
**Describe the bug**

I have not received this error previously. The problem does not occur on existing blog posts.

My YML file content
**To Reproduce**
Click the "New Blog" button.

**Expected behavior**
New Blog button is supposed to open a form allowing the ability to enter a new blog entry.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: 2.9.6
 - Git provider: GitLab
 - OS: Windows 10
 - Browser version: Chrome 76.0.3809.87

**CMS configuration**

```yaml
backend:
  name: gitlab
  repo: *******************

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    delete: true
    identifier_field: title
    slug: '{{slug}}'
    preview_path: 'blog/{{slug}}'
    show_preview_links: true
    fields:
      - {label: "Publish?", name: publish, widget: boolean, default: false, required: true}
      - {label: "Include In Full-Text-Index", name: include_in_fti, widget: boolean, default: true, required: true}
      - {label: Path, name: path, default: 'blog'}
      - {label: Author, name: author, default: '@_WealthierYou', widget: string}
      - {
          label: 'Publish Date',
          name: 'publish_date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - {label: Title, name: title, required: true, widget: string, tagname: 'h1'}
      - {label: Body, name: body, widget: markdown }
      - {label: Categories, name: categories, required: true, widget: 'list'}
      - {label: Tags, name: tags, required: true, widget: 'list'}
      - {label: Keywords, name: 'meta_keywords', required: true, widget: 'list'}
      - {label: 'SEO Description', name: 'meta_description', widget: 'text' }
      - {label: 'Show Disclaimer', name: 'show_disclaimer', widget: 'list', default: 'standard', required: false }
      - {label: 'Twitter Tags', name: twitter_tags, widget: list, default: '#wealthieryou, #livefinanciallyconfident, #resilientwomen', required: true }
      - name: 'featured_image'
        label: 'Featured Image'
        widget: object
        fields:
          - {label: Image, name: src, required: true, widget: image}
          - {label: Alt text, name: alt, required: true, widget: string}
          - {label: Title, name: title, required: false, widget: string}

```

**Additional context**

Please note that this issue has materialised recently. I have added two boolean fields. To try to resolve, I reverted to an earlier version of my YML, but no luck. So, back to the above version.
