### ISSUE TITLE
Show image widget in preview template directly after uploading to repo

### ISSUE THREAD

**Issue by blauwhelm** [netlify/netlify-cms#2516]
**Is your feature request related to a problem? Please describe.**
I'm using GatsbyJS in combination with Netlify CMS. If you add an Image widget to Netlify CMS and try to render this in a preview template it won't show the image right away, but only after a rebuild of the site. This is because the image needs to be stored in the specified public_folder, which will be done after a rebuild. This results in a broken image.

**Describe the solution you'd like**
I was wondering if it's possible to show a preview right away, just like in the markdown widget, when you add an image inside. Maybe by linking it to the repo instead of the public folder? Or using the same technique as the markdown widget?

**Example of config.yml**
```yaml
media_folder: static/assets
public_folder: assets
collections:
  - name: pages
    label: Pagina's
    folder: src/pages/
    create: true
    fields:
      - label: "Rechter zijkant"
        name: "aside"
        widget: "object"
        fields:
          - label: "Afbeelding(en)"
            name: "images"
            widget: "list"
            required: false
            fields:
              - {
                label: "Afbeelding",
                name: "image",
                widget: "image",
                required: false,
              }
```

**Example of corresponding preview template**
```javascript
const PagePreview = ({ widgetsFor }) => {
  const images = widgetsFor("aside").getIn(["data", "images"]).toJS();

  return (
    <>
      {images
        ? images.map(({ image }, i) => {
            return <img key={i} alt="image" src={image} />;
          })
        : null}
    </>
  );
};
```
