### ISSUE TITLE
Collection items not appearing in CMS colection listing

### ISSUE THREAD

**Issue by darranmorris** [netlify/netlify-cms#2518]
**Describe the bug**
Netlify CMS is not listing items in a collection. If I add a new file using the CMS, it appears in the listing. If I refresh the page, then the new item also disappears. The items appear fine on the built website. This site uses Bitbucket. I have a very similar config for another site which uses GitHub and the collection items display fine in the CMS. 

**To Reproduce**
1. Select a collection. 
2. Collection contains no items. 
3. Add a new file and save it. 
4. The item appears in the collection. 
5. Refresh the browser window. 
6. Collection contains no items. 

**Expected behavior**
Collection should contain the list of all items in the collection folder. 

**Screenshots**
<img width="406" alt="Screenshot 2019-08-05 at 13 43 20" src="https://user-images.githubusercontent.com/98928/62466242-317e1c00-b791-11e9-8576-6d3f75d48033.png">

**Applicable Versions:**
 - Netlify CMS version: 2.9.7
 - Git provider: BitBucket
 - OS: Mac OS 10.14
 - Browser version: Chrome 75

**CMS configuration**
```
backend:
  name: bitbucket
  repo: darranmorris/xxxxxxxx

media_folder: "source/images/posts/"
public_folder: "/images/posts/"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
  
collections: # A list of collections the CMS should be able to edit
  - label: "Website"
    name: "website"
    files:
      - label: "Home Page"
        name: "home"
        file: "data/cms/home.yml"
        fields:
          - {label: "Hero Title", name: hero_title, widget: string, default: "AUTOMATE<br /> YOUR OIL & GAS<br /> CONTROL ROOM<br /> OPERATIONS"}
          - {label: "Hero Subtitle", name: hero_subtitle, widget: string, default: "Operate flow rate transitions and facility re-starts up to 40% faster."}
          - {label: "Hero CTA", name: hero_cta, widget: string, default: "Get in touch"}
          - {label: "Intro Title", name: introtitle, widget: string, default: "What is CruxOCM?"}
          - {label: "Intro Paragraph", name: intro_para, widget: markdown}
          - {label: "Intro Method Title", name: intro_method_title, widget: string}
          - {label: "Intro Method Paragraph", name: intro_method_para, widget: string}
          - {label: "Intro Block Pullout", name: intro_pullout, widget: string}
      - label: "About Page"
        name: "about"
        file: "data/cms/about.yml"
        fields:
          - {label: "Main Title", name: main_title, widget: string}
          - {label: "Main Intro", name: main_intro, widget: string}
          - {label: "Main Block Pullout", name: main_pullout, widget: string}
          - {label: "Partner Logos Title", name: logos_title, widget: string}
      - label: "Contact Page"
        name: "contact"
        file: "data/cms/contact.yml"
        fields:
          - {label: "Main Title", name: main_title, widget: string}
          - {label: "Main Title", name: main_title, widget: string}
  - name: news
    label: News
    folder: source/news/
    extension: .html.md
    format: frontmatter
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - {label: "Title", name: title, widget: string}
      - {label: "Date", name: date, widget: datetime}
      - {label: "Layout", name: layout,, widget: hidden, default: "blog-layout"}
      - {label: "Nav Item", name: nav_item,, widget: hidden, default: "news"}
      - {label: "Blog Image", name: image, widget: image, default: "https://cruxocm.netlify.com/images/posts/default.jpg"}
      - {label: "Body", name: body,, widget: markdown}
```
