### ISSUE TITLE
TypeError: e.join is not a function

### ISSUE THREAD

**Issue by mugas** [netlify/netlify-cms#2540]
**Describe the bug**

I create a list widget and gives that error when I am in admin. I check others errors similar but their solutions don't work on my code. I add the field label, don't work and the default and still gives the same error.
Any ideas

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

```yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "json"
    sort: "date:desc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "date",
          format: "Do MMM YYYY",
        }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["javascript"] }
```
**Additional context**
