### ISSUE TITLE
Md files with JSON frontmatter not displaying content in CMS

### ISSUE THREAD

**Issue by alexearnshaw** [netlify/netlify-cms#2572]
**Describe the bug**
Markdown files with JSON frontmatter are not displayed correctly in the CMS UI.

I am using Netlify CMS with Hugo. In my Hugo content folder I have several collections of markdown files, some with YAML frontmatter and others with JSON frontmatter.

I have defined these collections in my netlify config file and have specified `format: "frontmatter"` for the collections with YAML frontmatter and `format: "json-frontmatter"` for those with JSON frontmatter.

The markdown files with YAML frontmatter are displayed fine in CMS, while the files with JSON frontmatter are listed (with no titles) and when you click to edit one the content is blank:

The following animation shows what displays for files with JSON frontmatter and then with files with YAML frontmatter:

![netifycmsjsonfrontmatter](https://user-images.githubusercontent.com/29064556/63433374-faf40280-c41a-11e9-8d73-6a21ed605ba6.gif)

This is an extract of one of my markdown files with JSON frontmatter
```
{"title":"Additional configuration","linkTitle":"Additional configuration","weight":"9","date":"2019-08-09","description":"Perform additional configuration after installation."}

## Change API Portal look and feel

For details on how to configure the look and feel of your API Portal end-user interface, see the [API Portal Administrator Guide](/bundle/APIPortal_77_AdministratorGuide_allOS_en_HTML5) .

```

This is an extract of my Netlify config for files in this collection:
```
collections: # A list of collections the CMS should be able to edit
 ...
  - name: "apipinstall"
    label: "Install API Portal"
    label_singular: "API Portal installation"
    description: "All pages relating to installing API Portal."
    folder: "content/en/docs/apiportal_install"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "apipha"
...
```

The entire project is here https://github.com/Axway/axway-open-docs
The URL for the Netlfiy CMS on the project is https://axway-open-docs.netlify.com/admin/

**Expected behavior**
The documentation says that JSON frontmatter is supported using the `format: "json-frontmatter"` so I would expect the CMS to display the file correctly. I've also tried using `format: "frontmatter"` with these files and in that case the files still have no heading and when I click to open them they show only the unparsed JSON in the body field and no other content.

**Screenshots**
see above animation

**Applicable Versions:**
 - netlify-cms-app 2.9.8-beta.0 (we are using open authoring beta but I don't think this is related to open authoring?)
 - Git provider: Github
 - OS: Windows 10 Enterprise version 1803
 - Browser version Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**CMS configuration**
https://github.com/Axway/axway-open-docs/blob/master/static/admin/config.yml

**Additional context**
We are using open authoring beta version but I don't think this is related to open authoring?
