### ISSUE TITLE
Image widgets in lists have media folder set to 'null'

### ISSUE THREAD

**Issue by colophonemes** [netlify/netlify-cms#26]
Image widgets used normally prepend the correct path to the uploaded image, based on the `media_folder` and `public_folder` keys in `config.yml`. However, if you use the image widget as part of a list widget, then the media folder is set to `null`. I presume that this is something to do with how the image widget is inheriting properties from the list widget.

The code I'm using to generate the list looks like this:

``` yaml
## config.yml
...
media_folder: "src/images/uploads" # Folder where user uploaded files should go
public_folder: "src" # strip this from the media_folder

collections:
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "src/content/posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection  
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle (optional)", name: "Subtitle (optional)", widget: "string", tagname: "h3", optional: true}
      - {label: "Featured Image (optional)", name: "featuredImage", widget: "image", optional: true}
      - {label: "Content", name: "body", widget: "markdown"}
      - label: "Image Attachments"
        name: "imageAttachments"
        widget: "list"
        fields: 
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}

```

The image widget used for featuredImage gets the path fine (i.e. `images/uploads/filename.jpg`), but the image widget used in `imageAttachments` gets `null` (i.e. `null/filename.jpg`).

I note that on the [TODO page](https://github.com/netlify/netlify-cms/blob/master/TODO.md#gallery-widget) there's a suggestion that you could make a gallery widget by using an image widget in a list (which is where I got the idea) so I assume that this use case has been tested — am I just missing something in the config?

Cheers,
Sam
