### ISSUE TITLE
Relation widget misbehaviour when searched elements have identical value in valueField

### ISSUE THREAD

**Issue by Mayaela** [netlify/netlify-cms#2600]
**Describe the bug**
The relation widget doesn't allow the user to select an element in the dropdown result list if there is one element higher up with the same value in its valueField. It will display the first element with the same value instead of the one you clicked on.
Then, if you open the dropdown list again, all the options with the same value in valueField appeared as selected (blue background, cf. screenshot below).
If you use the multiple choices configuration and repeat the same process, it doesn't work either: if you click on a project at the bottom of the list, if there was another project above with the same value, the widget will select the highest in the list. If you click again on the drop-down, your initial choice will not show at all. It won't be offered as an option. Only the other projects with values that are different from the one already selected will show in the list.

**To Reproduce**
1. Create a collection with a least two fields like these :
ex: 
```
- name: "projects"
  label: "Projects"
  label_singular: "Project"
  folder: "content/project"
  create: true
  extension: json
  identifier_field: title
  fields:
    - { label: "Project name", name: "title", widget: "string"}
    - label: "Project's rating"
      name: "rating"
      widget: "number"
      valueType: "float"
      min: 0
      max: 5
      step: 0.1
      default: 0
```

2. Go to your netlify cms admin dashboard and add at least two projects to your projects collections. Make sure to set the same rating for two of the projects. ex: 4,6

3. Create a collection with a field that uses the relation widget like this : 
```
- name: "projectPage"
  label: "Project Pages"
  folder: "content/projectPage"
  create: true
  extension: json
  identifier_field: project1logo
  fields:
    - label: "Project 1 Logo"
      name: "project1Logo"
      widget: "image"
    - label: "Project 1 Rating"
      name: "project1Rating"
      widget: "relation"
      collection: "projects"
      searchFields: ["title"]
      valueField: "rating"
      displayFields: ["title", "rating"]
```
4. Save your config changes and go back to netlify cms admin dashboard.
Create a new project page in your Project Pages Collection.
Go to the relation widget "Project 1 Rating" and try to select a project that has the same rating value as one above it in the dropdown list (cf. screenshot).
The widget will display the name and rating of the project with the same rating (valueField) that was the highest in the list.
Click again to show the dropdown list and you'll see that several projects are selected instead of the one you clicked on.

5. If you change your config file and add "multiple: true" to your Relation widget and then go back to the admin dashboard, you will be able in theory to select several projects in the "Project 1 Rating" widget. If you try again to click on a project at the bottom of the list, if there was another project above with the same value, the widget will still display the highest in the list. If you click again on the drop-down, your initial choice won't be offered as an option. Only the other projects with values that are different from the one already selected will show in the list.

6. You can use React Dev Tools to  check the metadatafields of the relation widget React component, you can see that the project's data that you first selected is well registered in there. But the children of the component have the highest project data registered as value and display it.

**Expected behavior**
The relation widget should allow the user to select and display any element listed even if several elements have the same value in their valueField.

**Screenshots**
<img width="675" alt="netlify cms relation widget bug" src="https://user-images.githubusercontent.com/36012265/63690448-ee055380-c80c-11e9-9f93-a48394a306a5.png">

**Applicable Versions:**
 - Netlify CMS version: 2.9.7
 - Git provider: Gitlab
 - OS: MacOs Mojave
 - Browser version : Chrome 76.0.3809.100
 - Node.JS version: v10.15.1
- gatsby: 2.13.83
- gatsby-plugin-netlify-cms: 4.1.11

**Additional context**
Using Gatsby
