### ISSUE TITLE
Overwriting occurs in editor when adding the same slug post with multiple collections

### ISSUE THREAD

**Issue by semigura** [netlify/netlify-cms#2620]
**Describe the bug**
I use NetlifyCMS with GatsbyJS.
When I try to save a post that has an existing slug in one collection to another collection, the edit screen of the same slug post in the first collection is overwritten by the one added later.
This is a problem only on the CMS and there is no problem with the display of the website.

**To Reproduce**
1. Enable editorial_workflow
2. Add and publish a post in one collection where slug can be entered in field
3. Add the same slug post in another collection and save it in draft state
4. View the edit screen of the post added in 2

**Expected behavior**
The same slug post in different collections should be editable without overwriting one.

**Screenshots**
After 2:
This screen's URL is `/admin/#/collections/one-posts/entries/001`
<img width="1438" alt="スクリーンショット 2019-08-29 15 36 03" src="https://user-images.githubusercontent.com/37991437/63922741-3bd5c200-ca80-11e9-89ba-4295be250a2a.png">

After 3:
This screen's URL is `/admin/#/collections/another-posts/entries/001`
<img width="1440" alt="スクリーンショット 2019-08-29 15 37 56" src="https://user-images.githubusercontent.com/37991437/63922740-3bd5c200-ca80-11e9-981d-d1df64abd18b.png">

After 4:
This screen's URL is `/admin/#/collections/one-posts/entries/001`
<img width="1440" alt="スクリーンショット 2019-08-29 15 38 20" src="https://user-images.githubusercontent.com/37991437/63922737-3bd5c200-ca80-11e9-94ca-243279d0bc91.png">

**Applicable Versions:**
- Netlify CMS version: 2.9.7
- GatsbyJS version: 2.13.50
- Git provider: GitHub
- OS: macOS Mojave 10.14
- Browser version: Chrome 75
- Node.JS version: 10.13.0

**CMS configuration**
```yaml
backend:
  name: git-gateway
  branch: develop

publish_mode: editorial_workflow

collections:
  - name: "one-posts"
    label: "One posts"
    folder: "src/pages/one-posts"
    create: true
    slug: '{{fields.slug}}'
    fields:
      - {
          label: 'Template type',
          name: 'type',
          widget: 'hidden',
          default: 'one-posts',
        }
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
        default: '001'
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: "another-posts"
    label: "Another posts"
    folder: "src/pages/another-posts"
    create: true
    slug: '{{fields.slug}}'
    fields:
      - {
          label: 'Template type',
          name: 'type',
          widget: 'hidden',
          default: 'another-posts',
        }
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
        default: '001'
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
```

**Additional context**
If I publish the post I added later, the problem will be solved.
However, I would like to be able to edit either of them in draft state.
Is there any good solution?
Because I am not an English speaker, I apologize for the ugly translation.
