### ISSUE TITLE
GitHub GraphQL: media library assets 404 for private repos

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2633]
**Describe the bug**

Images in the media library are not loaded (404) for private repos.

**To Reproduce**

1. Run the CMS locally (`yarn start`)
2. Create a **private** GitHub repo to use for test purposes
3. Enable the GraphQL API:
```yml
backend:
  name: github
  repo: repo-owner/repo-name # replace with your repo info
  use_graphql: true
```
4. Upload an image to the media library
5. Refresh the CMS
6. Open the media library and view the image

**Expected behavior**

Image should be shown.

**Screenshots**

<img width="949" alt="Screen Shot 2019-09-03 at 2 39 54 PM" src="https://user-images.githubusercontent.com/2112202/64199622-bb84d780-ce58-11e9-9976-0e3f37ea08d3.png">

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]

**Additional context**

Related to #2456.
