### ISSUE TITLE
GitHub GraphQL: workflow subject to race conditions

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2634]
**Describe the bug**

When saving, setting status, and publishing, operations can fail causing changes to be lost.

**To Reproduce**

1. Run the CMS locally (`yarn start`)
2. Create a GitHub repo to use for test purposes
3. Enable the GraphQL API and editorial workflow:
```yml
backend:
  name: github
  repo: repo-owner/repo-name # replace with your repo info
  use_graphql: true

publish_mode: editorial_workflow
```
4. Create a new post and save
5. Make an edit to the post, and then quickly do the following:
  1. Save
  2. Update status to "Ready"
  3. Publish

**Expected behavior**

Operations should happen sequentially and in order to avoid race conditions, all operations should succeed.

**Screenshots**

<img width="804" alt="Screen Shot 2019-09-03 at 2 51 24 PM" src="https://user-images.githubusercontent.com/2112202/64200362-57631300-ce5a-11e9-89bc-2d297b7e5d0e.png">

**Applicable Versions:**

 - Netlify CMS version: 2.9.8-beta.3

**Additional context**

Related to #2456.
