### ISSUE TITLE
Unable to add editorial_workflow to the example 

### ISSUE THREAD

**Issue by americool** [netlify/netlify-cms#264]
Currently trying to address issue #252. I'm trying to use the sample set-up while running the project locally. However by default editorial_workflow is not available. When I attempt to add (publish_mode: editorial_workflow) in example/config.yml, after running npm start, pretty much everything breaks. It asks for my email as a login then clears the form after it's entered but never does anything. As soon as I delete the publish_mode info in the config file, the example works again.

```
backend:
  name: test-repo
  delay: 0.1

publish_mode: editorial_workflow

media_folder: "assets/uploads"

collections: # A list of collections the CMS should be able to edit

...
```
https://github.com/netlify/netlify-cms/tree/master/example
