### ISSUE TITLE
Wrapped image/file widget does not call onChange callback.

### ISSUE THREAD

**Issue by dagatsoin** [netlify/netlify-cms#2700]
**Describe the bug**

Context:
I am creating a custom widget to be able to put an image inside a H.
To not reimplement the image widget, I wrap it inside my new component.
My issue is that, when choosing a new image, my component did not update the thumbnail.
This is because the file widget does not call the onChange callback. I don't understand how the original widget update it self though.
So is there a way to wrap the file/image widget into a new one and keeping the updating mechanism ?

**To Reproduce**
1- Clone https://github.com/dagatsoin/wizar-pro-website/tree/af1ae8607a51d55f11b2c5a60a2984a99e5d1303
2- `$npm develop`
3- go to `http://localhost:8000/admin`
4- create a new Section
5- in field Image, choose/upload a new image

The image does not appear into the controller widget.
To make it appears you need to trigger a sibling value change: hit a key in the field below.
The image now appears.

**Expected behavior**
The image should appear into the controller widget

**Screenshots**
1 -The current image
![image](https://user-images.githubusercontent.com/3670794/65591608-16f44200-df8d-11e9-823f-f60be45c6acd.png)
2- I choose a new image
![image](https://user-images.githubusercontent.com/3670794/65591675-2ffcf300-df8d-11e9-877b-15b5749ba457.png)
3- The thumbnail did not change
![Capture d’écran 2019-09-25 à 12 08 42](https://user-images.githubusercontent.com/3670794/65592129-45bee800-df8e-11e9-976a-6e1ee127bbd8.png)
4- I need to trigger a change to make it appear
![Capture d’écran 2019-09-25 à 12 09 35](https://user-images.githubusercontent.com/3670794/65592144-4c4d5f80-df8e-11e9-83ec-95586fccb6bc.png)

**Applicable Versions:**

netlify-cms-app 2.9.1
netlify-cms-core 2.11.0
netlify-cms-app 2.9.1
netlify-cms-core 2.11.0
netlify-cms 2.9.1

Git provider: Github
OS: OSX Sierra
Browser version : Chrome 76.0.3809.132 

 - Node.JS version: v11.5.0

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: dagatsoin/wizar-pro-website

publish_mode: editorial_workflow

media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "sections"
    label: "Sections"
    folder: "content/sections"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["hero", "left", "right", "vertical"]}
      - {label: "CTA", name: "cta", widget: cta}
      - {label: "Title", name: "title", widget: "string"}
      - {label: Image, name: image, widget: imageInHeader}
      - {label: "Image position", name: "imagePosition", widget: "select", options: ["left", "right"]}
      - {label: "Contrast text", name: "contrastText", widget: "boolean", default: true}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Background Image", name: backgroundImage, widget: image}

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
```

**Additional context**
[Here is the code of my custom widget.](https://github.com/dagatsoin/wizar-pro-website/blob/af1ae8607a51d55f11b2c5a60a2984a99e5d1303/src/cms/ImageControl.tsx)
