### ISSUE TITLE
Can't see "Deploy Preview Links"

### ISSUE THREAD

**Issue by 5509** [netlify/netlify-cms#2721]
**Describe the bug**

Can't see "Deploy Preview Links" though I meet requirements.

https://www.netlifycms.org/docs/deploy-preview-links/#using-deploy-preview-links

**To Reproduce**

1. Meet requirements (Using GitHub, editorial workflow, have a CI
2. Create new content with future date
3. Click "Save"
4. Then link won't appear

**Expected behavior**

"Deploy Preview Links" are available on my Netlify CMS.

**Screenshots**

<img width="1173" alt="スクリーンショット 2019-10-03 12 30 32" src="https://user-images.githubusercontent.com/521075/66097523-a9be5d80-e5d9-11e9-819f-27a3a5a64da4.png">

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version: 2.9.1
 - Git provider: GitHub
 - OS: macOS High Sierra
 - Browser version: Google Chrome 76.0.3809.132

**CMS configuration**

```
backend:
  name: github
  repo: xxx/xxx
  preview_context: deploy-preview
  branch: dev

publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"
show_preview_links: true
site_url: "https://xxxxxxxx.com/"

collections:
  - name: seminars
    label: live/seminars
    folder: src/pages/live/seminars
    create: true
    slug: "{{permalink}}"
    preview_path: live/seminars/{{slug}}
    fields:
      - { label: Title, name: title, widget: string, default: "" }
      - { label: Category, name: category, widget: hidden, default: live }
      - { label: Taxonomy, name: taxonomy, widget: hidden, default: seminars }
      - { labe;: "Date", name: date, widget: datetime, format: "YYYY-MM-DDTHH:mm:ss+09:00" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: Cover, name: cover, widget: image, required: false }
      - { label: Description, name: description, widget: string, required: false }
      - { label: "og:image", name: ogImage, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
```

**Additional context**
