### ISSUE TITLE
Ignore files from collection

### ISSUE THREAD

**Issue by panakour** [netlify/netlify-cms#2727]
I have a hugo site in which I have a content called "project". 
My config file:
```
collections:
  - name: "project" 
    editor:
      preview: false
    label: "Project"
    folder: "site/content/project"
    create: true
    fields:
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Project Date", name: "project_date", widget: "datetime"}
      - {label: "Head Image (Recommended 1920x1080)", name: "head_image", widget: "image", required: false}
      - {label: "Thumbnail Image (Recommended 360x560)", name: "thumb_image", widget: "image", required: false}
      - {label: "Images", name: "images", widget: list, field:
        {label: "Image (Recommended 800x500)", name: "image", widget: "image"}}
      - {label: "Description", name: "body", widget: "markdown"}
```

The admin is working fine and I can create/edit my projects. The issue is that the admin also show the _index.md file which is used from hugo for the list page. Also this file has different front-matter (I have a file collection for this to edit from the cms).

**The solution you'd like**
For hugo site should automatically excludes this file from the collection.

**alternatives you've considered**
Maybe a better and more generic solution for all SSGs is to have a [config option](https://www.netlifycms.org/docs/configuration-options/#collections) to let us give an array from some of the files to be ignored

**Comment by erquhart** [comment]
Should be possible, agreed.

**Comment by panakour** [comment]
maybe this issue #1472 would minimize the needed of this feature

**Comment by GabriFila** [comment]
Hi everyone!
Have there been any updates on this issue? I've looked at #1472 but I didn't find any solution or talk related to this. I'm interested in this feature to show only the actual collection content with a Hugo site and not "collection metadata" files.
I'd be happy to help implement this

**Comment by erezrokah** [comment]
Hi @GabriFila, the current workaround is to use https://www.netlifycms.org/docs/collection-types#filtered-folder-collections
e.g. have a `show` field on entries and add a filter entries with that value set to `true`.
Also related https://github.com/netlify/netlify-cms/issues/1000

**Comment by GabriFila** [comment]
Thank you @erezrokah, I'll try that.
Is there an interest to implement this without a workaround but with an actual `ignore` field, maybe with a regex inside or a glob pattern? Would it create problems?

**Comment by erezrokah** [comment]
I'm going to have a look at the suggested addition to add a `type: exclude/include` to `filter` and also to support entry meta data like filename.
Feels like it shouldn't be much of an effort, but I'll have to verify it.

**Comment by GabriFila** [comment]
Thank you! I have little experience with React, I don't know if I could help but if you need me I'd be happy to do it!

**Comment by OdairTrujillo** [comment]
> Hi @GabriFila, the current workaround is to use https://www.netlifycms.org/docs/collection-types#filtered-folder-collections
> e.g. have a `show` field on entries and add a filter entries with that value set to `true`.
> Also related #1000

I used this workaround, it's easy and clean. Just do something like this in your collection config and your md files to be ignored or included:

Front matter of a file to be included (I removed some lines from your example for clarity):
```
---
featured: true
title: Some title
date: 2020-07-14T22:49:10.427Z
visible: true
---
```
Front matter of a file to be excluded or filtered:
```
---
featured: true
title: A title for an _index.md
date: 2020-07-14T22:49:10.427Z
visible: false
---
```
Option and fields to use into your collection config:
```
collections:
  - name: "project" 
    editor:
       preview: false
    label: "Project"
    folder: "site/content/project"
    create: true
    filter: {field: "visible", value: true}
    fields:
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Visible", name: "visible", widget: hidden, default: true}
```
Pay attention to the Visible label, and the visible fields in the frontmatter of the files. Now all your new files created with the CMS will include the visible label, hiding the files with visible: false for the CMS, and without any interaction with the user.
