### ISSUE TITLE
Unsaved changes alert when nothing changed

### ISSUE THREAD

**Issue by danielkellyio** [netlify/netlify-cms#2743]
**Describe the bug**
When i open an existing entry in a collection after about a second the words in the top left corner turn red and report I have unsaved changes even when I haven't changed anything. Also when I try to leave the page without making any changes I get an alert "Are you sure you want to leave this page?".  

It seems to be related somehow to the relation widget because:
1. As soon as the upper left hand text reports unsaved changes the selected options in a relation widget appear
2. I have a different collect that does not use the relation widget and does not have said issue

**To Reproduce**
1. Visit the edit view of a collection with a relation widget
2. See upper left hand corner report unsaved changes
3. Navigate away from the page
4. See popup

**Expected behavior**
Unsaved changes should only be reported and alert should fire only when I've made changes. 

**Screenshots**
https://drive.google.com/file/d/1NXe4X3kZ63IWrULOyIowU7CroTDBji55/view?usp=sharing

**Applicable Versions:**
 - Netlify CMS version: 2.9.7
 - Git provider: GitHub
 - OS: Mac Mojave 10.14.6
 - Browser version: Chrome 77.0.3865.90

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://awake-template.netlify.com
logo_url: https://awake-template.netlify.com/logo-frames/logo-f0.svg
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    preview_path: "{{slug}}"
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Category", name: "category", widget: "relation", collection: "categories", searchFields: "name", valueField: "name", multiple: true}
      - {label: "Author", name: "author", widget: "string", default: "Daniel Kelly"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featureImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}

```
