### ISSUE TITLE
Use the relation widget to select a file of any type by filename

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2756]
**Is your feature request related to a problem? Please describe.**

If I have a directory of templates, I want to be able to select one by name. There is no need to process the file contents, I just want to see the names, select one, and have that filename be the value output by the relation widget.

**Describe the solution you'd like**

The relation widget can list files and allow me to search by name.

**Comment by erquhart** [comment]
cc/ @cmaxw

**Comment by erezrokah** [comment]
This is available now via templating:

```yaml
- label: "Templates"
  name: "template"
  widget: "relation"
  collection: "templates"
  searchFields: ["{{filename}}}"]
  valueField: "{{filename}}.{{extension}}"
  displayFields: ["{{filename}}.{{extension}}"]
```
