### ISSUE TITLE
Collection files are ignored

### ISSUE THREAD

**Issue by Keized** [netlify/netlify-cms#2775]
Hi, i have a little issue, all my collection files are ignored
I created 2 collections: 
- Post collection where i can add posts
- Pages collection where i can edit existing files (homepage, contact, etc...)

When I'm using the 'test-repo' backend : 

- Existing posts do not appear
- Pages appears but without content
- When I create a new message, it is not registered at all (neither in the browser memory)

When I'm using the 'test-repo' backend : 

- I can not see my existing pages (I cannot edit them)
- I can show my existing posts

My gatsby-config
```
module.exports = {
  siteMetadata: {
    title: `blog`,
  },
  plugins: [
    `gatsby-plugin-netlify-cms`,

    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/blog`,
        name: `blog`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/pages`,
        name: `pages`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/assets`,
        name: `assets`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 590,
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          `gatsby-remark-prismjs`,
          `gatsby-remark-copy-linked-files`,
          `gatsby-remark-smartypants`,
        ],
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-feed`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Gatsby Starter Blog`,
        short_name: `GatsbyJS`,
        start_url: `/`,
        background_color: `#ffffff`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `content/assets/gatsby-icon.png`,
      },
    },
    `gatsby-plugin-offline`,
    `gatsby-plugin-react-helmet`
  ],
}

```
My /static/admin/config.yml
```
backend:
  name: test-repo
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - label: "Homepage"
        name: "homepage"
        file: "/site/content/pages/homepage.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "/site/content/pages/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Showroom"
        name: "showroom"
        file: "/site/content/pages/showroom.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
```

 - Git provider: GitHub,
 - OS: Linux mint
 - Browser version chrome 77
 - Node.JS version: 11.13.0
