### ISSUE TITLE
Jekyll layout template

### ISSUE THREAD

**Issue by nifl** [netlify/netlify-cms#28]
Specifying a layout template per content type isn't clear in the README. For example, Jekyll frontmatter for a post should include `layout: post`. This isn't being generated with new posts. How should this configuration be made?

**Comment by biilmann** [comment]
There's two ways to do it.

One is Jekyll specific and consists of setting a global layout for the post collection, you can see an example of that here:

https://github.com/netlify/netlify-home/blob/master/_config.yml#L33

The other option works for any hidden field, and it's based on adding a hidden widget with a default value to the fields:

```yml
collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
```
