### ISSUE TITLE
Relation field value return more than one value.

### ISSUE THREAD

**Issue by mrshannonyoung** [netlify/netlify-cms#2800]
With the relation field, it would be good to return more than one value from the document.

The following does _not_ work, but would be ideal to pull more than one `  valueField` from the collection.

```
- label: "Post Author"
  name: "author"
  widget: "relation"
  collection: "people"
  searchFields: ["firstname", "lastname"]
  displayFields: ["firstname", "lastname"]
  valueField: "firstname lastname"
  multiple: true
```
The following _does_ work:
```
- label: "Post Author"
  name: "author"
  widget: "relation"
  collection: "people"
  searchFields: ["firstname", "lastname"]
  displayFields: ["firstname", "lastname"]
  valueField: "firstname"
  multiple: true
```

You can search for more than one value, but not return more than one 🤷🏻‍♂️

Keep up the great work on Netlify CMS 🥳

**Comment by erquhart** [comment]
Typically you want to return a value that can serve as a key to uniquely link back to the related entry, so one field is the typical need. Accepting a string template that can access other field values would make sense for this.

**Comment by Chevindu** [comment]
> a string template that can access other field values would make sense for this

@erquhart  I'm not sure how that can be used to achieve what the OP suggested (bind to more than one value field). [Documentation](https://www.netlifycms.org/docs/widgets/#relation) reads:

> `value_field`: (required) name of the field from the referenced collection whose value will be stored for the relation. For nested fields, separate each subfield with a `.` (e.g. `name.first`). For list fields use a wildcard `*` to target all list items (e.g. `categories.*`)

I still feel lost on how to implement something like `value_field: ["firstname", "lastname"]`.

My use case is that, if the CMS could support binding 2 fields of the selected relation, relevant template has access to 2 field values. I'm not sure if I'm making any sense. Thanks to you either way!

**Comment by erezrokah** [comment]
Hi @Chevindu, you could use `value_field: {{fields.firstname}}____{{fields.lastname}}` to create a value based on more than one field.

**Comment by tim-at-topos** [comment]
I see how https://github.com/decaporg/decap-cms/pull/3659 allows for string template support, but I'm interested in what (I think) the title of the issue suggests: is it possible to return e.g. a list of values?

For example, I'm using a relation widget for the authors of blog posts. Each author page (pulled from a collection) has a `name` and a `website`. I would like the relation widget to return something of the form

```
author:
  - name: "Firstname Lastname"
    website: "www.example.com"
```

**Comment by martinjagodic** [comment]
@tim-at-topos as was said above, the relation widget is intended to get a key with which you can get more fields in your SSG.

This would be a more correct approach also in your case because I assume that the website can be edited. And if you edit it on the authors page, it will not update on the blog post.

**Comment by lucasayb** [comment]
For anyone looking for a solution, you can achieve something like this:

```yaml
value_field: "{{name}}__{{color}}",
```

Being `name` and `color` two fields presents in my `categories` collection:

```yaml
  - name: "categories"
    label: "Categories"
    folder: "_categories"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        } # The fields for each document, usually in front matter
      - { label: "Color", name: "color", widget: "color", allowInput: true }
```

The reason why I needed this is because recently, I built my own SSG and didn't want to make something too complex, like grabbing the color info from some other folder and processing that markdown that I don't want to use to anything else besides this relationship. By doing this way, I can just store my category name and color in the same field and avoid things like this, and through the front end, I can just split between the `__` and handle the color and the name of the category separately.
