### ISSUE TITLE
image with cloudinary injects ">-" + "newline" + "image"

### ISSUE THREAD

**Issue by pixelass** [netlify/netlify-cms#2825]
**Describe the bug**

When injecting images via cloudinary the src string is prepended by a `>- \n`

This causes `null` to be returned instead of the actual string

```md
---
templateKey: blog-post
title: Just a test
date: 2019-08-05T14:20:26.289Z
description: this is a test
featuredpost: true
featuredimage: >-
  https://res.cloudinary.com/kellerkind/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1572457475/CD6V0159_pfywad.jpg
---

some text content
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version:
  netlify-cms-app 2.9.7
   netlify-cms-core 2.12.2
 - Git provider: github

**CMS configuration**

```yml
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
media_library:
  name: cloudinary
  config:
    cloud_name: **********
    api_key: ****************

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "gallery"
    label: "Gallery"
    folder: "src/pages/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: "image"}
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          fields: [{label: "Image", name: "image", widget: "image"}, {label: "Text", name: "text", widget: "text"}],
        }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Subheading", name: "subheading", widget: "string"}
          - {
              label: "Mainpitch",
              name: "mainpitch",
              widget: "object",
              fields:
                [
                  {label: "Title", name: "title", widget: "string"},
                  {label: "Description", name: "description", widget: "text"},
                ],
            }
          - {label: "Description", name: "description", widget: "string"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}

```
