### ISSUE TITLE
Can't uplaud image or save a draft or publish an article : "Failed to persist entry: API_ERROR: Not Found"

### ISSUE THREAD

**Issue by GoulvenC** [netlify/netlify-cms#2826]
Hi everyone !
I'm stuck for a while with this problem, everything works otherwise I was able to add the different collaborators on the CMS but they have the same error.
Can not save a draft, publish an article or upload an image. On the first two I get an error "Failed to persist entry: API_ERROR: Not Found" and on the third an blank error but the console says "API_ERROR: Not Found" so I guess it's related...

**When I try to save a draft**
The famous error : 
![image](https://user-images.githubusercontent.com/35667800/67967508-feb7b880-fc05-11e9-939a-a96d08cab4d6.png)
and the console : 
![Capture d’écran de 2019-10-31 17-21-56](https://user-images.githubusercontent.com/35667800/67967091-425df280-fc05-11e9-9449-21dfb2e1c6ff.png)

**When I try to upload an image**
The blank error : 
![image](https://user-images.githubusercontent.com/35667800/67966944-0f1b6380-fc05-11e9-9936-491d554fba45.png)
and the console : 
![Capture d’écran de 2019-10-31 17-13-14](https://user-images.githubusercontent.com/35667800/67967083-3ffb9880-fc05-11e9-966c-df94ad3fdaaa.png)

**Config.yml**
```
backend:
  name: git-gateway
  accept_roles:
    - Editeurs
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/couvertures/"
public_folder: "/images/couvertures/"
collections:
  - name: "Articles"
    label: "Articles"
    folder: "content/articles/"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Brouillon", name: "draft", widget: "boolean", default: false}
      - {label: "Couverture", name: "image", widget: "image"}
      - {label: "Miniature", name: "bgImage", widget: "image"}
      - {label: "description", name: "description", widget: "string"}
      - {label: "Auteur·e·s", name: "author", widget: "string"}
      - {label: "type", name: "type", widget: "hidden", default: "post"}
      - {label: "Article", name: "Body", widget: "markdown"}
  - name: "AilleursSurLeWeb"
    label: "AilleursSurLeWeb"
    folder: "content/ailleurssurleweb/"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Titre", name: "Title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Brouillon", name: "draft", widget: "boolean", default: false}
      - {label: "Couverture", name: "image", widget: "image"}
      - {label: "Miniature", name: "bgImage", widget: "image"}
      - {label: "description", name: "description", widget: "string"}
      - {label: "Auteur·e·s", name: "author", widget: "string"}
      - {label: "type", name: "type", widget: "hidden", default: "post"}
```

**And here you have the [Github Repo](https://github.com/Alt-rev-com/site)**

Thank you all for reading, I hope not to have missed the solution in Github Issues and the doc :/
