### ISSUE TITLE
Prevent publishing if duplicate identifier_field

### ISSUE THREAD

**Issue by TidyIQ** [netlify/netlify-cms#2829]
**Is your feature request related to a problem? Please describe.**

Identifier fields should be unique. Duplicates should not be allowed to be published.

**Describe the solution you'd like**

Throw error if attempting to publish with an identifier field value that already exists.

**Describe alternatives you've considered**

There are no easy to use alternatives.

**Additional context**

I'm using a relation widget in a collection where the display/search/value field is set to the identifier_field of the collection it's related to. If a user has duplicate identifier_fields in that collection then the relation widget is useless as I can't lookup the correct field (since I have no idea which duplicate is the correct one).

Also, I'm unable to access the value of a field with duplicate identifier_fields as I have no idea which one is correct.

ID fields should always be unique. It doesn't make sense to allow duplicates.

**Comment by vai0** [comment]
@TidyIQ have you found a solution to this? I'm experiencing the same issue - it doesn't stop me from publishing another entry with the same identifier field value. I'm using a gitlab backend

**Comment by erquhart** [comment]
I thought we fixed this in the past, might be a regression.

cc/ @erezrokah

**Comment by erezrokah** [comment]
@TidyIQ, @vai0 can you share your `config.yml` so I can try to create a reproduction?
The CMS should generate a unique slug for each entry (postfixing an index in case of collisions).

**Comment by vai0** [comment]
@erezrokah 

Here is my config.yml
```
- label: "LP Event Activity"
    name: "lp-event-activity"
    folder: "frontend/src/content/lp-event-activity"
    create: true
    description: "Create an activity event landing page"
    extension: "yml"
    identifier_field: slug
    fields:
      - label: "slug"
        name: "slug"
        widget: "string"
        hint: "/events/[slug]. e.g., strata-2019"
      - ...
...
backend:
  name: "gitlab"
  branch: "production"
  repo: "engineering/bifrost"
  auth_type: "implicit"
  app_id: ...
  api_root: .../api/v4
  base_url: ...
  auth_endpoint: "oauth/authorize"
```
### Steps to reproduce
1. Click on an existing entry in folder collection
2. Click "duplicate" in submenu
![image](https://user-images.githubusercontent.com/1195698/72854478-5ac03500-3c69-11ea-88e0-9fc064f94665.png)
3. Entry is successfully duplicated, with a unique filename - however the `slug`, which is set as the `identifer_field` is same across both entries in gitlab. Below is a screenshot of the duplicated entry in gitlab.
![image](https://user-images.githubusercontent.com/1195698/72854581-9eb33a00-3c69-11ea-8bce-33ef2c5d39bf.png)
 
What should ideally happen is the slug field should change after duplication (e.g., [original-slug]-1), and if the user attempts to publish, it should prevent the commit and instead throw an error, something like `Entry could not be published - [slug-field-value] already exists, [identifier_field-value] must be unique`
