### ISSUE TITLE
After changing branch in config.yml Netlify-cms still commits to the old branch

### ISSUE THREAD

**Issue by prakashsanker** [netlify/netlify-cms#2852]
My config.yml originally looked like this

```
backend:
  name: github
  # name: git-gateway
  repo: <REPO_NAME>
  branch: copy-changes
  #identity_url: https://dustinbold.netlify.com/.netlify/identity
  #gateway_url: https://dustinbold.netlify.com/.netlify/git

media_folder: static/cms/uploads
#media_folder_relative: true
public_folder: /cms/uploads
```
It now looks like this - 

```
backend:
  name: github
  # name: git-gateway
  repo: XelpmocDesignandTechPvtLtd/agebold-web
  branch: staging
  #identity_url: https://dustinbold.netlify.com/.netlify/identity
  #gateway_url: https://dustinbold.netlify.com/.netlify/git

media_folder: static/cms/uploads
#media_folder_relative: true
public_folder: /cms/uploads
```

However when I go the CMS, it still commits to the old branch rather than the new branch. I then sshed into my container and went to my build folder and checked the config.yml there...but the config.yml there has the new branch as well.

I'm not sure what's going on.
