### ISSUE TITLE
GitLab with git-gateway integration is broken 

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [netlify/netlify-cms#2881]
**Describe the bug**
When I load the content manager on my site, it runs into an error saying (in the console):

> TypeError: "i is null"
>     cms %5E2.0.0/dist/netlify-cms.js:65
>     cms %5E2.0.0/dist/netlify-cms.js:65
> mediaLibrary.js:230:117
> 07:56:48.611 uncaught exception: Object

Nothing seems to be affected at this point except for the media. When I go to look at the media, nothing is shown. I had previously been able to open the media and all of my images are shown.

Then I try to create a post. When I fill out all of the fields, and click on Publish Now, I get another error (in the console):

> API_ERROR: ""
>     cms %5E2.0.0/dist/netlify-cms.js:168
>     cms %5E2.0.0/dist/netlify-cms.js:168
>     cms %5E2.0.0/dist/netlify-cms.js:65
> entries.js:373:14
> 08:18:25.562
> TypeError: "calling a builtin Map constructor without new is forbidden"
>     cms %5E2.0.0/dist/netlify-cms.js:53
>     cms %5E2.0.0/dist/netlify-cms.js:13
>     cms %5E2.0.0/dist/netlify-cms.js:13
>     cms %5E2.0.0/dist/netlify-cms.js:53
>     cms %5E2.0.0/dist/netlify-cms.js:168
>     cms %5E2.0.0/dist/netlify-cms.js:18
>     cms %5E2.0.0/dist/netlify-cms.js:214
>     cms %5E2.0.0/dist/netlify-cms.js:227
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:160
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:143
>     cms %5E2.0.0/dist/netlify-cms.js:13
>     cms %5E2.0.0/dist/netlify-cms.js:18
>     cms %5E2.0.0/dist/netlify-cms.js:168
>     cms %5E2.0.0/dist/netlify-cms.js:168
>     cms %5E2.0.0/dist/netlify-cms.js:18
>     cms %5E2.0.0/dist/netlify-cms.js:13
> deploys.js:94:14
> 08:18:25.578
> TypeError: "e is undefined"
>     cms %5E2.0.0/dist/netlify-cms.js:18
>     cms %5E2.0.0/dist/netlify-cms.js:1
>     cms %5E2.0.0/dist/netlify-cms.js:1
>     cms %5E2.0.0/dist/netlify-cms.js:1
>     cms %5E2.0.0/dist/netlify-cms.js:18
>     cms %5E2.0.0/dist/netlify-cms.js:18
>     cms %5E2.0.0/dist/netlify-cms.js:214
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:160
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:151
>     cms %5E2.0.0/dist/netlify-cms.js:143
>     cms %5E2.0.0/dist/netlify-cms.js:13
>     cms %5E2.0.0/dist/netlify-cms.js:18
>     cms %5E2.0.0/dist/netlify-cms.js:168
>     cms %5E2.0.0/dist/netlify-cms.js:168
>     cms %5E2.0.0/dist/netlify-cms.js:18
>     cms %5E2.0.0/dist/netlify-cms.js:13
> ErrorBoundary.js:59:12
> 08:18:25.703 null 2 ErrorBoundary.js:77:14

**To Reproduce**

**Expected behavior**

I expect no errors to appear, the media to be appropriately populated, and for posts to be successfully published.
**Screenshots**

![netlify-cms-error](https://user-images.githubusercontent.com/34974905/68947010-603d6280-0782-11ea-9812-73af21e8013f.png)

**Applicable Versions:**

 - Netlify CMS version: 2.9.7
 - Git provider: GitLab
 - OS: Windows 10
 - Browser version: Firefox 70.0.1

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master
media_folder: "/img"
logo_url: /img/logo_transparent.png
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: "blog"
    label: "Blog Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "/blog/{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
```

**Additional context**
