### ISSUE TITLE
Jekyll + Netlify CMS returns 404 when deployer

### ISSUE THREAD

**Issue by ppartarr** [netlify/netlify-cms#2935]
**Describe the bug**

When deploying the https://github.com/netlify-templates/jekyll-netlify-cms template, the app returns a 404.

**To Reproduce**
Steps to reproduce the behavior.
1. Go to https://github.com/netlify-templates/jekyll-netlify-cms
2. Click on deploy to netlify
3. Visit app & see error

**Expected behavior**

Jekyll template home page should be displayed

**Screenshots**

**CMS configuration**

```yaml
---
title: Jekyll Netlify CMS
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: This is the basic Jekyll starter site, with Netlify CMS integrated and
  using Netlify Identity for authentication.
baseurl: ''
url: xxx
theme: minima
show_excerpts: false
minima:
  date_format: "%b %-d, %Y"
twitter_username: jekyllrb
github_username: jekyll
rss: rss
```

**Additional context**
