### ISSUE TITLE
Uploadcare media library not showing existing files

### ISSUE THREAD

**Issue by floo51** [netlify/netlify-cms#2966]
**Describe the bug**

With uploadcare, already uploaded images don't show in the upload widget.
It means than if we want to add one new image, it will replace all already existing images.
For now, I reupload the whole set every time I want to add a single image.

**To Reproduce**

1. Install and configure uploadcare following [this documentation](https://www.netlifycms.org/docs/uploadcare/).

2. Set an image field in one of the collections:
```
      - label: Images de la construction
        name: images
        widget: image
        media_library:
          config:
            multiple: true
            imagesOnly: true
            imageShrink: 1200x1200
```

3. Add an image A
4. Publish
5. Try to add a second image B
6. B replaces A

**Expected behavior**

Both B and A should be on the field.

**Screenshots**

![netlifycms](https://user-images.githubusercontent.com/2562270/70861015-e3400d00-1f28-11ea-80a4-12fa701cf024.gif)

**Applicable Versions:**
netlify-cms-app 2.9.7
netlify-cms-core 2.12.2
netlify-cms-media-library-uploadcare 0.5.5

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master

media_library:
  name: uploadcare
  config:
    publicKey: xxx
public_folder: /img
site_url: xxx

collections:
  - name: "projects"
    label: "Projets"
    folder: "src/pages/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Titre
        name: title
        widget: string
      - label: Images de couverture
        name: covers
        widget: image
        media_library:
          config:
            multiple: true
            multipleMax: 4
            imagesOnly: true
            imageShrink: 1200x1200
```

**Additional Notes**

I'm willing to help fix this and would love some directions
