### ISSUE TITLE
Nested widget validation in custom widget

### ISSUE THREAD

**Issue by MatthewWilson24** [netlify/netlify-cms#2979]
I have been building custom widgets that are derived from the default object and list widgets provided by Netlify, e.g:

```
const ObjectControl = CMS.getWidget("object").control

export class AccessibleImageControl extends React.Component {
    render() {
        const fields = new Map({
            fields: [
                new Map({
                    label: "Description",
                    name: "alt",
                    widget: "string",
                    required: true
                }),
                new Map({
                    label: "Image File",
                    name: "src",
                    widget: "image",
                    required: true
                }),
            ]
        })

        return <ObjectControl {...this.props} field={fields} />
    }
}
```

I believed then that the following nodes in my config.yml file would produce essentially identical widgets:

```
- {label: Widget1, name: Widget1, widget: accessibleImage}
- label: Widget2
   name: Widget2
   widget: object
   fields:
      - {label: Description, name: alt, widget: string, required: true}
      - {label: Image File, name: src, widget: image, required: true}
```

However, it turns out that while Widget2 (defined exclusively in the config.yml file) validates the presence of its subfields, Widget1 does not. I have tried looking through the source code, but am none the wiser why this is the case. The docs are certainly silent on validating nested widgets within custom widgets -- although admittedly it is a complex use case.

I'm not entirely sure if this is a bug, an error on my part, or intentional behaviour? It would certainly be useful to be able to customise existing widgets without losing the default functionality Netlify provides. And, from a UX point of view, it would be really helpful if widgets nested within a custom widget could perform their own validation. Perhaps there is already a way of doing this that I just can't work out?
