### ISSUE TITLE
Copy from markdown editor copies all editor content to clipboard

### ISSUE THREAD

**Issue by danielkellyio** [netlify/netlify-cms#3017]
**Describe the bug**
When markdown mode is on for a markdown type widget, I highlight a particular line or 2 that I want to copy but the whole content of the widget is copied to clipboard

**To Reproduce**
1. Type a paragraph or 2 into a markdown widget
2. Turn it to markdown edit mode (as opposed to Rich Text)
3. Copy a single line by highlighting and pressing cmd + c
4. Paste contents of clipboard anywhere
5. All of the widget content will be pasted not just the selected text

**Expected behavior**
I expect only selected text to be copied to clipboard

**Applicable Versions:**

 - Netlify CMS version: 2.10.2
 - Git provider: Github
 - OS: MacOS 10.14.6
 - Browser version: Chrome 79.0.3945.88

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master
site_url: http://localhost:3000
display_url: http://localhost:3000
media_folder: assets/uploads
public_folder: uploads
collections:
  - name: pages
    name_singular: page
    label: Pages
    label_singular: Page
    preview_path: "{{slug}}"
    folder: content/pages
    create: true
    slug: "{{slug}}"
    identifier_field: title
    fields:
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
      - label: Feature Image
        name: image
        widget: image
      - label: Layout
        name: layout
        widget: select
        default: sidebar-left
        options:
          - Right Sidebar
          - Left Sidebar
          - One Column
      - label: Hero Size
        name: heroSize
        widget: select
        default: medium
        options:
          - Large
          - Medium
          - Small
      - label: Content
        name: body
        widget: markdown
      - label: Side Bar Content (if sidebar layout)
        name: sidebar
        widget: markdown
  - name: posts
    name_singular: post
    label: Posts
    label_singular: Post
    preview_path: "{{slug}}"
    folder: content/posts
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
      - label: Category
        name: category
        widget: select
        options:
          - Third Party Integrations
          - About Awake
          - Test Category
        multiple: true
      - label: Author
        name: author
        widget: string
        default: Daniel Kelly
      - label: Publish Date
        name: date
        widget: datetime
      - label: Featured Image
        name: featureImage
        widget: image
      - label: Body
        name: body
        widget: markdown
  - name: categories
    name_singular: category
    label: Categories
    label_singular: Category
    preview_path: categories/{{slug}}
    folder: content/categories
    create: true
    slug: "{{slug}}"
    identifier_field: name
    editor:
      preview: false
    fields:
      - label: Name
        name: name
        widget: string
      - label: Image
        name: image
        widget: image
      - label: Description
        name: description
        widget: markdown
  - name: videos
    name_singular: video
    label: Videos
    label_singular: Video
    preview_path: videos/{{slug}}
    folder: content/videos
    create: true
    slug: "{{slug}}"
    identifier_field: name
    editor:
      preview: false
    fields:
      - label: Name
        name: name
        widget: string
      - label: Source
        name: src
        widget: text
      - label: Notes
        name: notes
        widget: markdown
      - label: Publish Date
        name: date
        widget: datetime
      - label: Author
        name: author
        widget: string
        default: Daniel Kelly
  - name: products
    name_singular: product
    label: Products
    label_singular: Product
    preview_path: products/{{slug}}
    folder: content/products
    create: true
    slug: "{{slug}}"
    identifier_field: name
    editor:
      preview: false
    fields:
      - label: Name
        name: name
        widget: string
      - label: Feature Image
        name: image
        widget: image
      - label: Features
        name: features
        widget: list
        field:
          label: Feature
          name: feature-item
          widget: string
      - label: Summary
        name: summary
        widget: text
      - label: Description
        name: description
        widget: markdown
      - label: Price
        name: price
        widget: string
      - label: Preview URL
        name: preview_url
        widget: string
      - label: File GUID
        name: file_guid
        widget: string
logo_url: /logo-frames/logo-f0.svg
```

Thanks!
