### ISSUE TITLE
images are not uploaded in default image widget

### ISSUE THREAD

**Issue by aditya81070** [netlify/netlify-cms#3019]
**Describe the bug**

I am trying to upload an image from the admin panel. It shows the dialogue to upload the image but it just shows `Loading..` text. I have also tried to push buggy code to Github and tried to upload the image from the published website but it doesn't work. 

**To Reproduce**
Steps to reproduce the behavior. For example:
1. Go to admin panel and create a new blog(I am using gatsby-starter-hello-world and netlify-cms)
2. Click on `create blog`
3. Scroll down to `Cover` field and try to upload an image
4. See following error in the console-
```
netlify-cms-app.js:28 API_ERROR: Not Found
    at new t (http://localhost:8000/admin/netlify-cms-app.js:60:77455)
    at new o (http://localhost:8000/admin/netlify-cms-app.js:60:77821)
    at u.handleRequestError (http://localhost:8000/admin/netlify-cms-app.js:98:139449)
    at http://localhost:8000/admin/netlify-cms-app.js:40:152654
    at async Promise.all (index 0)
(anonymous) @ netlify-cms-app.js:28

Uncaught (in promise) TypeError: Cannot read property 'find' of undefined
    at netlify-cms-app.js:28
    at netlify-cms-app.js:60
    at netlify-cms-app.js:28
    at netlify-cms-app.js:91
    at Object.Bi (react-dom.production.min.js:175)
    at Ai (react-dom.production.min.js:14)
    at Di (react-dom.production.min.js:14)
    at wf (react-dom.production.min.js:14)
    at Ei (react-dom.production.min.js:176)
    at zd (react-dom.production.min.js:15)
```

**Expected behavior**

I should be able to select and upload an image from the `image` widget. After uploading the image, it should be stored in the folder specified as `media_folder`.

**Screenshots**

![Screenshot from 2019-12-31 15-25-22](https://user-images.githubusercontent.com/30300772/71617692-3630ea00-2be2-11ea-9b3c-69ceffef839a.png)
![Screenshot from 2019-12-31 15-26-19](https://user-images.githubusercontent.com/30300772/71617700-3df08e80-2be2-11ea-9357-d0c225368e89.png)

**Applicable Versions:**

 - Netlify CMS version: "netlify-cms-app": "^2.10.1",
 - Git provider: Github
 - OS: Ubuntu 18.04.3 LTS x86_64
 - Browser version: Google Chrome | 79.0.3945.88

 - Node.JS version:
I am using yarn. 
yarn: 1.21.1
**CMS configuration**

```
# backend:
#   name: github
#   repo: aditya81070/gatsby-with-netlify-cms-learn
backend:
  name: git-gateway
# media_folder: static/assets
publish_mode: editorial_workflow
media_folder: static/images/uploads
# public_folder: assets
# media_library:
#   name: uploadcare
#   config:
#     publicKey: 46afd475684287af5b68
#     imagesOnly: true
#     imageShrink: 480x480
collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: cover, label: Cover Image, widget: image }
```

**Additional context**

I tried to find a solution to this problem in previous issues. Some issues advised enabling `git-gateway` but I already enabled it. 
Additionally, I tried to use Uploadcare to store my images/files and it worked perfectly. But I want to store my images in my repository.
