### ISSUE TITLE
Unsaved changes state recurring after saving Markdown including new line characters

### ISSUE THREAD

**Issue by marcveens** [netlify/netlify-cms#3039]
**Describe the bug**

I keep getting the "Unsaved Changes" status even after actually saving it and not changing anything. It's probably caused by a new line in the Markdown editor. This character is represented as "\" when I look at the Markdown viewer within the editor.

**To Reproduce**

1. Go to an edit page with a Markdown editor included
2. Type some text into the editor
3. Press Shift+Enter (on Windows) to create a new line
4. Type some more text after the new line
5. Save changes
6. For a second, the "Saved Changes" message is showing but is immediately replaced by "Unsaved Changes" again.

**Expected behavior**

Expected was to maintain the Saved Changes state since nothing was changes after pressing the save button

**Screenshots**

![netlify-cms-bug](https://user-images.githubusercontent.com/1115616/71885120-ffa32400-3139-11ea-8bb8-1868d4376d35.gif)

**Applicable Versions:**

 - Netlify CMS version: netlify-cms-app@2.10.1 and netlify-cms-core@2.13.1
 - Git provider: Github
 - OS: Windows 10
 - Browser version: Chrome 79.0.3945.88

 - Node.JS version: 12.14.0

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master
  use_large_media_transforms_in_media_library: false
media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: contentpages
    label: Content pages
    files:
      - label: Homepage
        name: homepage
        file: src/pages/contentpages/homepage.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: url
            name: url
            widget: hidden
            default: /
          - label: Body
            name: body
            widget: markdown
```
