### ISSUE TITLE
BitBucket media API returns error 500

### ISSUE THREAD

**Issue by ymslavov** [netlify/netlify-cms#3058]
**Describe the bug**
I'm using a precompiled Netlify CMS version from https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js with a BitBucket implicit grant and client-only login (i.e. no backend of my own).

I was loading all content and images fine until yesterday, when I started receiving error 500 on the calls trying to list all my media uploads.

**To Reproduce**
1. GET request to https://api.bitbucket.org/2.0/repositories/[MY REPOSITORY]/src/149e401b14719eae74ae3fc2d849e97bfd2d0354/static/img/blog/uploads?sort=-path&max_depth=undefined&ts=1578561460229 
2. Get the following console error trace for the request:
```
API_ERROR: Expected an ok response, but received an error status: 500.
    at new t (https://unpkg.com/netlify-cms@2.10.3/dist/netlify-cms.js:114:111695)
    at new r (https://unpkg.com/netlify-cms@2.10.3/dist/netlify-cms.js:114:112061)
    at https://unpkg.com/netlify-cms@2.10.3/dist/netlify-cms.js:68:58616
    at async t.default.listFiles (https://unpkg.com/netlify-cms@2.10.3/dist/netlify-cms.js:68:60374)
    at async t.default.listAllFiles (https://unpkg.com/netlify-cms@2.10.3/dist/netlify-cms.js:68:60895)
```

**Expected behavior**
The images are successfully fetched from BitBucket.

**Applicable Versions:**

 - Netlify CMS version:
netlify-cms-app 2.11.0
netlify-cms-core 2.14.0
netlify-cms 2.10.3
 - Git provider: BitBucket
 - OS: Linux Mint 18.3
 - Browser version Chrome 73.0.3683.86

**CMS configuration**
```
backend:
  name: bitbucket
  repo: [MY REPO HERE]
  branch: master
  auth_type: implicit
  app_id: [MY APP ID HERE]

media_folder: "static/img/blog/uploads"
public_folder: "/img/blog/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "store/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "json"
    fields:
      - {label: "Published", name: "published", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "markdown"}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "Auto Keywords", name: "autoKeywords", widget: "boolean", default: false}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Header Image", name: "image", widget: "image"}
      - {label: "Thumbnail Image", name: "thumb", widget: "image"}
      - {label: "Featured Article", name: "featured", widget: "boolean", default: false}
```
