### ISSUE TITLE
Custom Preview: this.props.getAsset(image) is returning a promise after version 2.10.0

### ISSUE THREAD

**Issue by hesstobi** [netlify/netlify-cms#3062]
**Describe the bug**
I followed the docs to create a custom image. But the 

```
<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
<script>
var MyPreview = createClass({
  render: function() {
    var entry = this.props.entry;
    var image = entry.getIn(['data', 'image']);
    var bg = this.props.getAsset(image);
    return h('div', {},
      h('img', {src: bg.toString()})
    );
  }
});

CMS.registerPreviewTemplate("test", MyPreview);
</script>
```

But the `this.props.getAsset` is returning a pending promise and the `toString()` will then give `[object promise]` thus the image is not displayed in the Preview.

**Expected behavior**
The result of the promises is needed to preview the image

**Applicable Versions:**

 - Netlify CMS version: 2.10.3, 2.10.4

Is is working a expected until version 2.10.0

**CMS configuration**
```
collections:
  - name: "test"
    folder: "site/content/test/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - label: "image"
       name: "src"
       widget: "image"
```

**Additional context**
