### ISSUE TITLE
UNPUBLISHED_ENTRY_PERSIST_FAILURE - API_ERROR: Reference already exists

### ISSUE THREAD

**Issue by borisschapira** [netlify/netlify-cms#3065]
Hi you’ll. 

I’m using NetlifyCMS on a website for several months now. Today, I no longer have access to editorial functions: my drafts no longer appear in “Workflow”, I am unable to save changes, and the buttons allowing to set statuses (Draft, Review, Ready) when making a change have disappeared. I don’t know where to start the debug to understand where the problem comes from…

Steps to reproduce the behavior. For example:
1. Open an item from a collection
2. Modify an item content
3. Click on "Save"
4. See error:

```
{type: "UNPUBLISHED_ENTRY_PERSIST_FAILURE", payload: {…}, optimist: {…}, error: API_ERROR: Reference already exists
```

**Expected behavior**

Access to editorial features, allowing to save the file in a specific status (draft, in review…)

**Applicable Versions:**

 - netlify-cms-app 2.11.1
 - netlify-cms-core 2.14.1
 - netlify-cms 2.10.4
 - Git provider: GitHub
 - Authentification provider: GitHub
 - Browser version: Chrome & Firefox evergreen

**CMS configuration**

```
backend:
  name: github
  repo: myorg/private-repo
  branch: master
publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "pages_fr"
    label: "Pages FR"
    description: >
      Pages en français du site
    folder: "pages/fr/"
    create: true
    fields:
      - {label: "Gabarit", name: "layout", widget: "hidden", default: "default"}
      - {label: "Titre", name: "title", widget: "string", default: "Bienvenue"}
      - {label: "I18n", name: "i18n-key", widget: "string", default: "home"}
      - {label: "Contenu", name: "body", widget: "markdown" }
  - name: "pages_en"
    label: "Pages EN"
    description: >
      Pages en anglais du site
    folder: "pages/en/"
    fields:
      - {label: "Gabarit", name: "layout", widget: "hidden", default: "default"}
      - {label: "Titre", name: "title", widget: "string", default: "Welcome"}
      - {label: "I18n", name: "i18n-key", widget: "string", default: "home"}
      - {label: "Contenu", name: "body", widget: "markdown" }
```
