### ISSUE TITLE
Media manager does not load media

### ISSUE THREAD

**Issue by SergioMendolia** [netlify/netlify-cms#3093]
**Describe the bug**
Media manager does not display any image. 
Thumbnails are still displayed when editing an element
Uploading an image makes the commit with the image, but the path is not updated in the element
There is an error in the console

**To Reproduce**
Try to add an image.

If necessary, I can give access to the repository

**Expected behavior**
Be able to add an image

**Screenshots**
![Capture d’écran 2020-01-15 à 14 25 01](https://user-images.githubusercontent.com/4610317/72439188-bd678b80-37a6-11ea-86ac-d507c26d7422.png)
![Capture d’écran 2020-01-15 à 14 27 21](https://user-images.githubusercontent.com/4610317/72439189-bd678b80-37a6-11ea-9f75-cd5982f1370d.png)

**Applicable Versions:**
 - Netlify CMS version: 2.10.4
 - Git provider: GitHub
 - OS: MacOS
 - Browser version Latest Firefox and latest safari, not tried on chrome

**CMS configuration**

```yml
backend:
  name: git-gateway
  branch: master
  use_large_media_transforms_in_media_library: false
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "articles"
    label: "Articles"
    extension: json
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Texte", name: "body", widget: "markdown", required: true}
    summary: "{{date}} - {{title}}"
    editor:
      preview: false
```

**Additional context**
I have 116 images for about 50Mb and they are stored using netlify large media
