### ISSUE TITLE
Duplicate Entry should not be an option for File Collections 

### ISSUE THREAD

**Issue by vai0** [netlify/netlify-cms#3124]
**Describe the bug**
The "Duplicate" submenu option should not exist when viewing an entry in a file collection, since unlike folder collections, file collections do not have the option to create new entries in the collection.
![image](https://user-images.githubusercontent.com/1195698/72853867-7a565e00-3c67-11ea-8505-4847d35348d3.png)

**Applicable Versions:**

 - Netlify CMS version: 2.10.1
 - gatsby-plugin-netlify-cms: 4.1.33
 - Git provider: gitlab

**CMS configuration**
```
 - label: "Events Center"
    name: "events"
    extension: "yml"
    editor:
      preview: false
    files:
      - ...
```
