### ISSUE TITLE
[uploadcare] Multiple images and JSON cause TypeError: Cannot convert object to primitive value 

### ISSUE THREAD

**Issue by caseykey** [netlify/netlify-cms#3128]
**Describe the bug**
When using the Uploadcare media_library, you can upload multiple images. However, when I attempt to add multiple images to an entry which is saved as JSON, I encounter:
`TypeError: Cannot convert object to primitive value`
I tried to fix this by moving the image widget into an object and a list, neither fixed the issue. The error I encounter tells  me to save this before navigating away:
```
{
  "project": "whatspython",
  "image": "images/whatspython.png",
  "start": "May 2018",
  "end": {
    "date": "July 2018"
  },
  "title": "Python Curriculum & Blog",
  "subtitle": "Curriculum Development",
  "icons": {
    "fa": [
      "FaWordpress",
      "FaPhp",
      "FaPython",
      "FaGamepad"
    ]
  },
  "description": "textual description of project"
}
``` 

**To Reproduce**
Setup NetlifyCMS with Gatsby and then add Uploadcare support as described [here](https://stackoverflow.com/questions/59834384/netlifycms-unable-to-select-multiple-images-using-uploadcare-image-widget)
Configure a config.yml for NetlifyCMS to use JSON, similar to this:
```
backend:
  name: github
  repo: repoName/gituser
  branch: source
  site_domain: netlify-url

public_folder: "/src/images/"
media_folder: "/src/images/"
media_library:
  name: uploadcare
  config:
    publicKey: 4ba0a13b1abc6d2ff0f4

collections:
  - label: "Projects" # Used in the UI
    name: "projects" # Used in routes, e.g., /admin/collections/blog
    label_singular: 'Project'
    folder: "src/data/projects" # The path to the file where projects are defined
    media_folder: 'images' # Should save images in same directory as the project, to make referencing easier
    create: true
    extension: json
    format: json
    fields: # The fields for each document, usually in front matter
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        field:
        - {label: "Image", name: "image", widget: "image"
 
```

**Expected behavior**
I expect for multiple images to be added to the UI afterwards as URLs and available in the JSON as
```
{
  ...
  "galleryImages": {[image1url, image2url, image3url]},
  ...
}
```
Although, I would like these files uploaded as files to my github repo.

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.11.5]
 - Git provider: Github
 - OS: Windows 10 running project under WSL (Ubuntu)
 - Browser version [e.g. chrome 22, safari 11] Chrome Version 79.0.3945.117 

 - Node.JS version: 6.9.0

**CMS configuration**
```
backend:
  name: github
  repo: caseykey/caseykey.github.io
  branch: source
  site_domain: quirky-bassi-7f760a.netlify.com

public_folder: "/src/images/"
media_folder: "/src/images/"
media_library:
  name: uploadcare
  config:
    publicKey: 4ba0a13b1abc6d2ff0f4

collections:
  - label: "Projects" # Used in the UI
    name: "projects" # Used in routes, e.g., /admin/collections/blog
    label_singular: 'Project'
    folder: "src/data/projects" # The path to the file where projects are defined
    media_folder: 'images' # Should save images in same directory as the project, to make referencing easier
    create: true
    extension: json
    format: json
    fields: # The fields for each document, usually in front matter
      - {label: "Project Name", name: "project", widget: "string", hint: "A project name used for files and folders", pattern: ['^[\w\-]+$', "Accepted characters are alphanumeric, _, and -."]}
      - {label: "Image", name: "image", widget: "image", allow_multiple: false}
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        field:
        - {label: "Image", name: "image", widget: "image"
      - {label: "Start Date", name: "start", widget: "datetime", timeformat: false, dateFormat: "MMMM YYYY", format: "MMMM YYYY"}
      - label: "End Date"
        name: "end"
        widget: "object"
        fields:
        - {label: "Present", name: "present", widget: "boolean", default: false, hint: "Toggle on if project's in development.", required: false}
        - {label: "Completed", name: "date", widget: "datetime", timeformat: false, dateFormat: "MMMM YYYY", format: "MMMM YYYY"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - label: "Icons"
        name: "icons"
        widget: "object"
        fields:
          - {label: "Font Awesome", name: "fa", widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
          - {label: "Devicons", name: "di", widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
          - {label: "Ionicons", name: "io", widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Link", name: "link", widget: "string", required: false}
```
