### ISSUE TITLE
Workflow doesn't load when integrated with GitHub

### ISSUE THREAD

**Issue by caiofbpa** [netlify/netlify-cms#3129]
**Describe the bug**
We cannot open the workflow page on the CMS due to a `401 Unauthorized` error in a GitHub request.

**To Reproduce**
1. Log in with email and password
2. Click on the Workflow tab

**Expected behavior**
The Workflow page should load showing all pending posts

**Screenshots**
![Screen Shot 2020-01-22 at 16 19 22](https://user-images.githubusercontent.com/507356/72926498-4b0d2300-3d33-11ea-8aa1-f011fe18cfe7.png)

**Applicable Versions:**

 - Netlify CMS version: 2.10.9
 - Git provider: GitHub
 - OS: MacOS 10.15 Catalina
 - Browser version: Safari 13.0.4

**CMS configuration**
```
backend:
  name: git-gateway
  repo: mercos/site-blog
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: 'public/uploads' # Media files will be stored in the repo under public/uploads
public_folder: '/uploads' # Folder path where uploaded files will be accessed, relative to the base of the built site

site_url: https://mercos.com
logo_url: https://mercos.com/images/site/logo-mercos-colored.png

slug:
  encoding: 'ascii'
  clean_accents: true
```
> _config.yml continues after this with out `collections` definitions

(cc @xrafs)
