### ISSUE TITLE
Collection media_folder ignored for absolute paths

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#3132]
**Describe the bug**

If an image has an absolute path, the **media_folder** for the collection is ignored. Collection level media folders are assumed to only be used for relative paths.

Consider the following markdown snippets:

**content/docs/getting-started/with-github.md**
```markdown
![](/Images/docs/getting-started/authenticate-with-github-step-1.jpg)
```

**content/docs/extending/overview.md**
```markdown
![](/Images/docs/extending/overview-feature.jpg)
```

The relevant configuration would look like:

```yml
media_folder: /static/Images
public_folder: /Images

collections:
  - name: getting-started
    media_folder: /static/Images/docs/getting-started
    public_folder: /Images/docs/getting-started

    # global media_folder/public_folder should also work
  - name: extending
    media_folder: '{{media_folder}}/docs/extending'
    public_folder: '{{public_folder}}/docs/extending'
```

Note the leading slash in **media_folder** - this should indicate that its an absolute path, and that all media in this collection use this path without the collection path prepended.

Related to #3053.
