### ISSUE TITLE
Fields marked optional are still required

### ISSUE THREAD

**Issue by techpeace** [netlify/netlify-cms#315]
**- Do you want to request a *feature* or report a *bug*?**

Report a *bug*.

**- What is the current behavior?**

Marking a field as optional in the `config.yml` does not make the field optional.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Add `optional: true` to a field for a collection in `config.yml`:

```yaml
collections:
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "The Voxable Voice" # Used in the UI
    folder: "source/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.html.markdown" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Header Image", name: "header_image", widget: "image"}
      - {label: "Twitter Image", name: "twitter_image", widget: "image", optional: true}
      - {label: "Share Description", name: "share_description", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
```

**- What is the expected behavior?**

The field should be optional when creating a post.

**- What is the actual behavior?**

The field is still required:

![image](https://cloud.githubusercontent.com/assets/2220/24169663/54e258c8-0e4c-11e7-8b7f-f3a2e47448b9.png)

**- Please mention your node.js, and operating system version.**

node version: 6.9.5
OS: Mac OS X 10.12.3

Using Middleman
