### ISSUE TITLE
Error in AssetProxy causing empty media browser (Bitbucket + LFS)

### ISSUE THREAD

**Issue by wslaghekke** [netlify/netlify-cms#3151]
**Describe the bug**
When you add an image and refresh the page the CMS will try to restore the state from localStorage, however it has saved invalid images to localstorage (with Path, but no URL or FileObj)
Im not entirely sure how that scenario is meant to work, should the CMS only save concept images in local storage or should it save a blob for remote images too?

**To Reproduce**
1. Open the CMS and go to an entry
2. Clear application storage so the indexedDB is empty
3. Refresh the page and login
4. Add an image
5. Refresh the page
6. See an error in the console as follows:
AssetProxy.js:25 Uncaught (in promise) TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at new i (AssetProxy.js:25)
    at t.createAssetProxy (AssetProxy.js:61)
    at entries.js:405
    at Array.map (<anonymous>)
    at entries.js:405

**Expected behavior**
No error

**Applicable Versions:**
CMS Version 2.10.12
Chrome 79 on Linux

**CMS configuration**
```
backend:
  name: bitbucket
  repo: <>
  branch: master
  auth_type: implicit
  app_id: <>
locale: "nl"
media_folder: public/images
public_folder: /images
collections:
  - name: "pages"
    label: "Pagina's"
    label_singular: "pagina"
    folder: "data"
    create: true
    format: json
    fields:
      - label: "Titel"
        name: "title"
        widget: "string"
      - label: "favicon"
        name: "favicon"
        widget: "image"
        required: false
      - label: "Header"
        name: "header"
        widget: "object"
        fields:
          - { label: "Applicatie afbeelding", name: "applicationImage", widget: "image"}
          - { label: "Logo", name: "logoImage", widget: "image" }
          - { label: "Beschrijving", name: "description", widget: "text"}
      - label: "Intro"
        name: "intro"
        widget: "object"
        fields:
          - { label: "Titel", name: "title", widget: "string"}
          - { label: "Beschrijving", name: "description", widget: "text" }
      - label: "Content blokken"
        name: "contentBlocks"
        widget: "list"
        types:
          - label: "Extra info"
            name: "extraInfo"
            widget: "object"
            fields:
              - {label: "Titel", name: "title", widget: "string", required: false}
              - {label: "Beschrijving", name: "description", widget: "string", required: false}
              - label: "Achtergrondkleur"
                name: "background"
                widget: "select"
                options:
                  - { label: "Grijs", value: "grey" }
                  - { label: "Wit", value: "white" }
              - label: "Afbeeldingen"
                name: "infoImages"
                widget: "list"
                fields:
                  - {label: "Afbeelding", name: "image", widget: "image"}

          - label: "Slider links"
            name: "sliderLeft"
            widget: "object"
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Beschrijving", name: "description", widget: "text"}
              - label: "Rotatie"
                name: "rotation"
                widget: "select"
                options:
                  - { label: "Omhoog", value: "up" }
                  - { label: "Omlaag", value: "down" }
              - label: "Afbeelding-formaat"
                name: "typeImage"
                widget: "select"
                options:
                  - {label: "Afbeelding 1/3", value: "30-percent"}
                  - {label: "Afbeelding 1/2", value: "50-percent"}
                  - {label: "Afbeelding 2/3", value: "70-percent"}
              - {label: "Type", name: "type", widget: "hidden", default: "sliderRight"}
              - label: "Slider links"
                name: "sliderList"
                widget: "list"
                fields:
                  - {label: "id", name: "id", widget: "number"}
                  - {label: "Beschrijving", name: "description", widget: "string"}
                  - {label: "Afbeelding", name: "image", widget: "image"}
          - label: "Slider rechts"
            name: "sliderRight"
            widget: "object"
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Beschrijving", name: "description", widget: "text"}
              - label: "Rotatie"
                name: "rotation"
                widget: "select"
                options:
                  - { label: "Omhoog", value: "up" }
                  - { label: "Omlaag", value: "down" }
              - label: "Afbeelding-formaat"
                name: "typeImage"
                widget: "select"
                options:
                  - {label: "Afbeelding 1/3", value: "30-percent"}
                  - {label: "Afbeelding 1/2", value: "50-percent"}
                  - {label: "Afbeelding 2/3", value: "70-percent"}
              - {label: "Type", name: "type", widget: "hidden", default: "sliderRight"}
              - label: "Slider right"
                name: "sliderList"
                widget: "list"
                fields:
                  - {label: "id", name: "id", widget: "number"}
                  - {label: "Beschrijving", name: "description", widget: "string"}
                  - {label: "Afbeelding", name: "image", widget: "image"}
      - label: "Faq"
        name: "faqList"
        widget: "list"
        fields:
          - { label: "id", name: "id", widget: "number" }
          - { label: "Vraag", name: "question", widget: "string" }
          - { label: "Antwoord", name: "answer", widget: "markdown" }
      - label: "Gegevens"
        name: "footer"
        widget: "object"
        fields:
          - { label: "Adres", name: "address", widget: "string" }
          - { label: "Telefoonnummer", name: "phone", widget: "string" }
          - { label: "E-mail", name: "email", widget: "string" }
          - { label: "Afbeelding tekst", name: "imageText", widget: "string", required: false }
          - label: "Afbeeldingen"
            name: "images"
            widget: "list"
            fields:
              - {label: "Afbeelding", name: "image", widget: "image"}
```

**Additional context**
Git attributes as follows:
public/images/** filter=lfs diff=lfs merge=lfs -text
