### ISSUE TITLE
NetlifyCMS not working when too many unpublished articles in editorial workflow

### ISSUE THREAD

**Issue by dcastil** [netlify/netlify-cms#3169]
**Describe the bug**

NetlifyCMS fails to display content in the workflow page when there are more than 29 unpublished articles using GitHub.

**To Reproduce**

1. Set up NetlifyCMS for a site with editorial workflow and git-gateway backend.
2. Create at least 30 articles through NetlifyCMS, so that there are at least 30 pull requests open in the GitHub repo.
3. Navigate to workflow page in NetlifyCMS admin site

**Expected behavior**

All articles load as expected.

**Screenshots**

Workflow page in NetlifyCMS admin site when the error happens. The app stays in this state.

<img width="1440" alt="Screenshot 2020-01-29 at 10 03 56" src="https://user-images.githubusercontent.com/31006608/73490800-8cde3f00-43ad-11ea-8a22-e198bc0cb214.png">

The problem seems to be in an incorrectly executed request for GitHub pull requests. The GitHub API only sends the first 30 PRs, this first request comes back with the correct data. NetlifyCMS then tries to fetch the second page, but instead of sending the request to `/.netlify/git/github/pulls`, it is being sent directly to `https://api.github.com`.

<img width="1205" alt="Screenshot 2020-01-29 at 10 02 44" src="https://user-images.githubusercontent.com/31006608/73490897-c151fb00-43ad-11ea-8020-f329ac187ba0.png">

<img width="781" alt="Screenshot 2020-01-29 at 10 03 04" src="https://user-images.githubusercontent.com/31006608/73491224-679e0080-43ae-11ea-99d4-6aaec3d2e847.png">

**Applicable Versions:**

 - Netlify CMS version: `netlify-cms-app@2.11.0-beta.1`
 - Git provider: GitHub
 - OS: Mac OS Catalina v10.15.2
 - Browser version Chrome v79.0.3945.130

 - Node.JS version: v12.14.1

**CMS configuration**

```yml
backend:
  name: git-gateway
  squash_merges: true
  accept_roles:
    - admin
    - content-editor

media_folder: packages/nn-website/src/assets/cms
public_folder: cms
publish_mode: editorial_workflow
site_url: …

slug:
  encoding: ascii
  clean_accents: true

collections:
  - …
```
