### ISSUE TITLE
API_ERROR: Not Found

### ISSUE THREAD

**Issue by pniedzwiedzinski** [netlify/netlify-cms#3188]
**Describe the bug**
I have a git repo with posts stored in this structure: `wpisy/{{year}}/{{month}}/{{day}}/{{title}}.md`. And I wanted to add Netlify CMS to it. So I get it working but I can't add nor modify posts. When I modify an existing post I got this error:
![image](https://user-images.githubusercontent.com/19212948/73664318-7aab1c00-469f-11ea-8d4a-30276fef80b7.png)

The third error about `preview_path_date_field` is because the post I was working has invalid date field.

I was thinking that maybe it's caused by the lack of file extension - the file is `biwak-przekazaniowy.md`. I checked the encoded in base64 content and everything seems ok there.

The GitHub API returns 404
![image](https://user-images.githubusercontent.com/19212948/73666440-1b4f0b00-46a3-11ea-8754-d5e73020922c.png)

**To Reproduce**
I don't really know how to reproduce it. This is the repo I'm using https://github.com/19pdh/kronika/tree/netlify-cms.

The only way, I think is to fork it and to try to deploy it on your own.

**Expected behavior**
Update the post on GitHub

**Screenshots**
See above

**Applicable Versions:**

 - Netlify CMS version: 2.10.16
 - Git provider: GitHub
 - OS: macOs 10.14.6
 - Browser version Chrome 79

 - Node.JS version: not using npm

**CMS configuration**
```
backend:
  name: git-gateway

#publish_mode: editorial_workflow
display_url: https://puszcza.netlify.com
site_url: https://puszcza.netlify.com
locale: 'pl'

media_folder: 'static/media'
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: posts
    label: 'Wpisy'
    folder: 'wpisy'
    slug: '{{filename}}'
    path: '{{year}}/{{month}}/{{day}}/{{filename}}.{{extension}}'
    preview_path: 'kronika/{{year}}/{{month}}/{{day}}/{{filename}}'
    preview_path_date_field: 'date'
    editor:
      preview: false
    fields:
      - label: 'Tytuł'
        name: title
        widget: string
        required: true

      - label: 'Autor'
        name: author
        widget: string
        required: true

      - label: 'Data'
        name: date
        widget: datetime
        dateFormat: DD.MM.YYYY
        timeFormat: false
        required: true

      - label: 'Kategorie/Tagi'
        name: category
        widget: list
        required: false

      - label: 'Zdjęcie okładki - link'
        name: image
        widget: string
        required: false

      - label: 'Wpis'
        name: body
        widget: markdown
        required: true
```

**Additional context**

**Comment by erezrokah** [comment]
Hi @pniedzwiedzinski, `filename` and `extension` template variables are not available for `slug` and `path`. We actually use `slug` and `path` to generate the filename.

**Comment by pniedzwiedzinski** [comment]
Still not working though :/ I've got the same error

```yml
backend:
  name: git-gateway

#publish_mode: editorial_workflow
display_url: https://puszcza.netlify.com
site_url: https://puszcza.netlify.com
locale: 'pl'

media_folder: 'static/media'
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: posts
    label: 'Wpisy'
    folder: 'wpisy'
    slug: '{{title}}'
    path: '{{year}}/{{month}}/{{day}}/{{slug}}'
    preview_path: 'kronika/{{year}}/{{month}}/{{day}}/{{title}}'
    preview_path_date_field: 'date'
    editor:
      preview: false
    fields:
      - label: 'Tytuł'
        name: title
        widget: string
        required: true

      - label: 'Autor'
        name: author
        widget: string
        required: true

      - label: 'Data'
        name: date
        widget: datetime
        dateFormat: DD.MM.YYYY
        timeFormat: false
        required: true

      - label: 'Kategorie/Tagi'
        name: category
        widget: list
        required: false

      - label: 'Zdjęcie okładki - link'
        name: image
        widget: string
        required: false

      - label: 'Wpis'
        name: body
        widget: markdown
        required: true
```
