### ISSUE TITLE
Collection level media_folder needs to be entry level for file collections

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#3199]
**Is your feature request related to a problem? Please describe.**

File collections can contain groups of entries that work quite differently from one another. Some entries may source their media from dedicated folders, Eg., a file with a list of authors and their bio pics.

**Describe the solution you'd like**

- **media_folder** for individual entries (file type collections only).
- the `{{media_folder}}` variable in this case would inherit the combined value of the global and collection level **media_folder**, if either are present.
- should be accompanied by same level **public_folder** for absolute paths

**Comment by erezrokah** [comment]
Does bullet number 2 means we should join the two?
e.g.

```
media_folder: 'global'

collections:
  - name: posts
    media_folder: 'posts'
    files:
      - file: src/posts/post1.md
        media_folder: '{{media_folder}}/post1'
```
Should return in `global/posts/post1` ? Or does it mean collection level overrides global one?
