### ISSUE TITLE
Remove double slashes from media_folder/public_folder

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#3204]
**Is your feature request related to a problem? Please describe.**

There's bound to be confusion and mistakes around our cascading **media_folder**/**public_folder** string replacements. If your global value ends with a slash, and then you add a slash after including that value as a string replacement, you get an unexpected double slash:

```yaml
media_folder: /static/img/

collections:
  - name: blog
    media_folder: "{{media_folder}}/blog"
```

**Describe the solution you'd like**

This potential mistake is simple to anticipate and account for, so we should. When constructing the final value of either property, double slashes (`//`) should be replaced with a single slash. Because **media_folder**/**public_folder** are not used for complete urls, they won't be affected.
