### ISSUE TITLE
Cloudinary selected image previews not rendering in image widgets

### ISSUE THREAD

**Issue by brianzelip** [netlify/netlify-cms#3206]
**Describe the bug**

I'm using Cloudinary for media library.

The selected image previews are not showing up in the admin page's image widgets. See screenshot:

![Netlify CMS admin page showing a Cloudinary image preview that doesn't render](https://i.imgur.com/YlC6qPC.png)

The one error in the console:

```js
TypeError: Arguments to path.join must be strings 2 index.js:117:12
```

Here's my relevant `config.yml`:

```yml
media_library:
  name: cloudinary
  config:
    cloud_name: ***********
    api_key: ************
  output_filename_only: true
collections:
  - label: 'Products'
    name: 'products'
    folder: '_data/products'
    format: 'json'
    create: true
    identifier_field: name
    fields:
      - label: 'Primary photo'
        name: 'imgPrimary'
        widget: 'image'
        allow_multiple: false
        required: false
      - label: 'Secondary photos'
        name: 'imgSecondarySet'
        widget: 'list'
        allow_multiple: true
        field: { label: Image, name: image, widget: image }
        required: false
```

**To Reproduce**

See screenshot above.

**Expected behavior**

The image preview should render for selected images.

**Screenshots**

See above

**Applicable Versions:**

 - Netlify CMS version:

```
netlify-cms-app 2.11.14
netlify-cms-core 2.17.0
netlify-cms 2.10.17
```

 - Git provider: GitHub

 - OS: macOS 10.12.6
 - Browser version FF Dev Edition 73.0b12

 - Node.JS version: Not using node, just straight up src tag in html

**CMS configuration**

See above

**Additional context**
