### ISSUE TITLE
Preview pane classnames are different when CMS is built so styles are getting used

### ISSUE THREAD

**Issue by LAmango** [netlify/netlify-cms#3215]
**Describe the bug**
When I work locally on the CMS the classnames are the same as the classnames I use for my preview template but when I push to GitHub and re-deploy the site, the classnames are uglified and obviously don't match the classnames I have in my css. I use css modules but it looks like the css is loading correctly in the cms.css file. I assume the uglified classnames are because of emotion? is there a way to load my css/scss into the preview template with emotion?

**Expected behavior**
That the classnames would stay the same?

**Screenshots**
<img width="1679" alt="Screen Shot 2020-02-09 at 8 59 05 PM" src="https://user-images.githubusercontent.com/15572479/74116038-b6525400-4b7f-11ea-8576-b8c46635422e.png">

**Applicable Versions:**

 - Netlify CMS version: 2.11.14
 - Git provider: GitHub
 - OS: MAC OS
 - Browser version chrome 79

 - Node.JS version: 10.16.3

**CMS configuration**
```yaml
backend:
  #name: proxy
  name: git-gateway
  #proxy_url: http://localhost:8081/api/v1
  branch: master

media_folder: src/assets/images
public_folder: images

collections:
  - name: pages
    label: Pages
    files:
      - name: about
        label: About
        file: "src/cms/about.md"
        fields:
          - { name: "templatekey", label: "Template Key",  widget: "hidden", default: "about-page" }
          - { name: path, label: Path, widget: "hidden" }
          - { name: title, label: Title }
          - name: team
            label: Team
            widget: list
            allow_add: true
            fields:
              - { name: name, label: Name, widget: string }
              - { name: description, label: Description, widget: string }
              - { name: image, Title: Image, widget: "image", required: false}
      - name: home
        label: Home
        file: "src/cms/home.md"
        fields:
          - { name: "templatekey", label: "Template Key",  widget: "hidden", default: "about-page" }
          - { name: path, label: Path, widget: hidden }
          - { name: title, label: Title }
          - { name: subtitle, label: Subtitle }
          - { name: mainImage, label: "Main Image", widget: image, hint: "Image is not displaying correctly here but it does work on the actual site if you change the image"}
          - name: topics
            label: Topics
            widget: list
            fields:
              - { name: heading, label: Heading }
              - { name: body, label: Body, widget: markdown }
              - { name: image, label: "Background Image", widget: image }
          - { name: stepsTitle, label: "Steps Title" }
          - { name: stepsSubtitle, label: "Steps Subtitle" }
          - name: steps
            label: Steps
            widget: object
            fields:
              - { name: step1, label: "Step 1" }
              - { name: step2, label: "Step 2" }
              - { name: step3, label: "Step 3" }
```

**gatsby-config**
```javascript
var netlifyCmsPaths = {
  resolve: `gatsby-plugin-netlify-cms-paths`,
  options: {
    cmsConfig: `/static/admin/config.yml`,
    enableIdentityWidget: true,
  },
}

module.exports = {
  //pathPrefix: `/mygatsby`,
  siteMetadata: {
    title: 'Fortune Foodz',
    author: 'Lucas Albano',
    description: 'Sanitation & Food Service Consultants',
    menuLinks: [
      {
        name: 'Home',
        link: '/',
      },
      {
        name: 'About',
        link: 'about',
      },
    ],
  },
  plugins: [
    'gatsby-plugin-sass',
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'fortune-foodz',
        short_name: 'fortune',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/assets/images/ff-logo.png', // This path is relative to the root of the site.
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/assets/`,
        name: 'images',
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/`,
        name: 'cms',
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          netlifyCmsPaths,
          'gatsby-remark-relative-images',
          {
            resolve: 'gatsby-remark-images',
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 2048,
            },
          },
        ],
      },
    },
    {
      resolve: 'gatsby-plugin-html-attributes',
      options: {
        lang: 'en',
      },
    },
    'gatsby-plugin-offline',
    {
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
        modulePath: `${__dirname}/src/cms/cms.js`,
        htmlFavicon: `src/assets/images/ff-logo.png`
      },
    },
    'gatsby-plugin-netlify'
  ],
}
```

**cms.js**
```javascript
import CMS from 'netlify-cms-app'
import AboutPagePreview from './preview-templates/AboutPagePreview';
import HomePagePreview from "./preview-templates/HomePagePreview";
import "../assets/scss/main.scss"


CMS.registerPreviewTemplate('about', AboutPagePreview);
CMS.registerPreviewTemplate('home', HomePagePreview);
```

**preview template**
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import AboutPageTemplate from "../../templates/AboutPageTemplate";
import About from "../../pages/about";

class AboutPagePreview extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            images: {}
        }

    }
    componentDidMount() {
        const entryTeam = this.props.entry.getIn(['data', 'team']);
        const team = entryTeam ? entryTeam.toJS() : [];

        console.log("team: ", team);
        for(let i = 0; i < team.length; i++) {
            this.props.getAsset(team[i].image).then(value => {
                this.setState({
                    images: {
                        ...this.state.images,
                        [team[i].name] : value
                    }
                }
                )
            })
        }
    };

    render(){
        const { entry, widgetFor } = this.props;
        const entryTeam = this.props.entry.getIn(['data', 'team']);
        const team = entryTeam ? entryTeam.toJS() : [];
        return (
            <>
            {team ? team.map(member => {
                return (
                    <div style={{padding: 20}}>
                        <header className="major">
                            <h2>{this.props.entry.getIn(['data', 'title'])}</h2>
                        </header>
                        <AboutPageTemplate
                            image={this.state.images[member.name]}
                            description={member.description}
                            name={member.name}
                        />
                    </div>
                )
                }) : null}
                </>
        )

    }
}

AboutPagePreview.propTypes = {
    entry: PropTypes.shape({
        getIn: PropTypes.func,
    }),
    widgetFor: PropTypes.func,
    getAsset: PropTypes.func
};

export default AboutPagePreview
```

**Closing Thoughts**
Strangely, when I have the dev tools open and do an "Empty cache and hard reload" the classnames change to my classnames and the styles work! but then if I do a regular reload, the styles go back to the old classnames 😢 

here is a link to the repo [here](https://github.com/LAmango/fortune-foodz)
that repo is private so here is a link to a repo with the same issues thats public [here](https://github.com/LAmango/fulcrum-website)

If it's not already apparent, this is my first posting of an issue (like evar) so if I need to give more examples or explanation Ill be happy to do so. And if there is somewhere more relevant that i can post this I'm all ears too! Thanks in advance, so far I've been loving my experience with Netlify and their cms!
