### ISSUE TITLE
Default Custom Widget Starter example does not work.

### ISSUE THREAD

**Issue by guirreri** [netlify/netlify-cms#3222]
**Describe the bug**
When setting up a default [Gridsome project](https://gridsome.org/docs/#1-install-gridsome-cli-tool), adding Netlify CMS, and then adding the [default custom Netlify CMS widget starter example](https://github.com/netlify/netlify-cms-widget-starter), the user can not view the Create form.

**To Reproduce**
1. Install [Gridsome CLI](https://gridsome.org/docs/#1-install-gridsome-cli-tool) globally.
    * `npm install --global @gridsome/cli`
2. Clone https://github.com/guirreri/netlify-cms-custom-widget-issue
3. `yarn`
4. `gridsome develop`
5. Goto localhost:8080/admin, login via github auth
6. Click "New Posts"

**Expected behavior**
A form should appear with the default custom Netlify CMS widget.

**Screenshots**
User sees the following in Chrome:

```
Error
There's been an error - please report it.

Details
TypeError: Cannot read property 'validate' of undefined
```

User see the following in Firefox:
```
Error
There's been an error - please report it.

Details

TypeError: t.innerWrappedControl is undefined
```

**Applicable Versions:**
Installed packages: https://github.com/guirreri/netlify-cms-custom-widget-issue/blob/master/package.json

 - Netlify CMS version: 2.10.17
 - Git provider: GitHub
 - OS: OSX
 - Browser version: Latest Chrome, Latest Firefox
 - Node.JS version: 10.15.3
 - Yarn version: 1.19.2

**CMS configuration**
https://github.com/guirreri/netlify-cms-custom-widget-issue/blob/master/src/admin/config.yml

**Comment by smashercosmo** [comment]
Having the same issue. Tried to register custom widget and immediately got
```
TypeError: Cannot read property 'validate' of undefined
```

```
import CMS from 'netlify-cms-app'
CMS.registerWidget('customWidget', cusomWidget, customWidgetPreview)
CMS.init({ config })
```
```
media_folder: static/img
public_folder: /img
backend:
  name: git-gateway
  branch: blog

collections:
  - label: Demos
    label_singular: demo
    name: demos
    folder: content/demos
    media_folder: '/{{media_folder}}/demos/{{filename}}'
    public_folder: '{{public_folder}}/demos/{{filename}}'
    format: yaml
    create: true
    slug: demo-{{slug}}
    identifier_field: title
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Test, name: test, widget: customWidget }
```
