### ISSUE TITLE
Missing file collection labels with local backend

### ISSUE THREAD

**Issue by stefanprobst** [netlify/netlify-cms#3234]
**Describe the bug**
On initial load, the labels of file-collection entries in the overview are missing when using the local backend, but work fine with the test-repo backend (haven't checked w/ other backends).

With local backend:
![netlifycms_local_backend](https://user-images.githubusercontent.com/20753323/74266615-dcedc780-4d04-11ea-9e96-59e510a292ef.png)

With test backend:
![netlifycms_test_backend](https://user-images.githubusercontent.com/20753323/74266635-e37c3f00-4d04-11ea-8719-f0be00590b15.png)

**To Reproduce**
1. Clone repo, replace `dev-test` folder with `index.html` (with `dist/netlify-cms.js` script only), and touch `site.yml`
2. Create the following `dev-test/config.yml`:
```yaml
backend:
  name: test-repo
local_backend: true
media_folder: static/images
collections:
  - name: settings
    label: Settings
    files:
      - name: site
        label: Site Settings
        file: site.yml
        fields:
          - { name: title, label: Title, widget: string }
```
3. run `yarn develop` once with `netlify-cms-proxy-server` running, once without

**Expected behavior**
label should render correctly

**Screenshots**
See above

**Applicable Versions:**
 - Netlify CMS version: current master

**CMS configuration**
See above

**Additional context**
When logging `loadedEnties` [here](https://github.com/netlify/netlify-cms/blob/249bd7ec1ed2197106cbb01f8c05e1b8830aa5bc/packages/netlify-cms-core/src/backend.ts#L298) i get:

```js
// test-repo
{
  loadedEntries: [
    {
      file: {
        path: 'site.yml',
        label: 'Site Settings',
      },
      data: undefined,
    },
  ],
}

// with local backend
{
  loadedEntries: [
    {
      file: {
        path: 'site.yml',
        id: null
      },
      data: null
    }
  ]
}
```
