### ISSUE TITLE
Media library should show a different set of images depending on how it was opened

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#3235]
**Describe the bug**

- The media library is currently gathering all media folders from image widgets and the collection, and loading all images from those sources.
- Instead, it should be loading only images for the media_folder specified by the caller.
- Additionally, individual files in a collection should override (and optionally inherit from via `{{media_folder}}`) the file collection itself.
- The media library should only ever show a set of sibling files from a single directory - nested directories should be ignored.

**Expected behavior**

```yaml
media_folder: /static/img
collections:
  - name: general
    media_folder: "{{media_folder}}/general/"
    files:
      - name: partners
        fields:
          - name: featured_image
            widget: image
            media_folder: "{{media_folder}}/partners/"
      - name: customers
        media_folder: "{{media_folder}}/customers/"
        fields:
          - name: main_image
            widget: image
          - name: logo
            widget: image
            media_folder: "{{media_folder}}/logos/"
```
Given the previous config:
- the **feature_image** field in the **partners** entry should only show images from `/static/img/general/partners`
- the **main_image** field in the **customers** entry should only show images from `/static/img/general/customers`
- the **logo** field in the **customers** entry should only show images from `/static/img/general/customers/logos`
- directories that are nested in these resolved directories should be ignored - in the previous bullet, if `/static/img/general/customers/logos/archive` is a directory containing images, images in that directory should not be shown

Much of the path resolution logic described above for individual fields will also apply to folder collections.
