### ISSUE TITLE
Feature request: editing JSON files instead Markdown for content

### ISSUE THREAD

**Issue by MarcCoet** [netlify/netlify-cms#326]
How hard would it be to support editing JSON files instead of only Markdown?

For a portfolio for example, I would have only 1 JSON file containing all my portfolio entries instead of all the separate markdown files.

**Comment by erquhart** [comment]
The CMS already has this, actually, just needs to be documented. For an example, check out the `settings` collection in the [repo example](https://github.com/netlify/netlify-cms/blob/master/example/config.yml#L31), where a json file and a yaml file are both set up to be edited through the CMS:

```yaml
- name: "settings"
    label: "Settings"
    files:
      - name: "general"
        label: "Site Settings"
        file: "_data/settings.json"
        description: "General Site Settings"
        fields:
          - {label: "Global title", name: "site_title", widget: "string"}
          - label: "Post Settings"
            name: posts
            widget: "object"
            fields:
              - {label: "Number of posts on frontpage", name: front_limit, widget: number}
              - {label: "Default Author", name: author, widget: string}
              - {label: "Default Thumbnail", name: thumb, widget: image, class: "thumb"}

      - name: "authors"
        label: "Authors"
        file: "_data/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
```
