### ISSUE TITLE
TypeError when `config.yml` requests a missing widget: Cannot read property 'validate' of undefined

### ISSUE THREAD

**Issue by edbrannin** [netlify/netlify-cms#3283]
**Describe the bug**

Error when `config.yml` requests a missing widget

> TypeError: Cannot read property 'validate' of undefined

**To Reproduce**

1. In a working config.yml, capitalize the first letter of a stock widget.
2. Reload the page and make a new item in the collection you just updated.
3. See error.

Example: 

```
  - name: page
    label: Page
    folder: /
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: Markdown } # Danger!
```

(This also applies to `fields` in a list, etc.)

**Expected behavior**

* Replace the invalid widget with an error that says the widget could not be found
    * For bonus points, if widget.toLowercase() exists, suggest using that
* Some sort of "Invalid configuration" warning on the main page

**Applicable Versions:**

 - Netlify CMS version: 2.10.23
 - Git provider: GitHub
 - OS: macOS Mojave
 - Browser version: Chrome 79

**CMS configuration**

https://github.com/exultrochester/exultrochester.org/blob/master/admin/config.yml

**Additional context**

I first encountered this problem while adding `collections[name=conference][name=speakers][name=image]` in the above config.
