### ISSUE TITLE
Boolean is shown as required even though it has a default

### ISSUE THREAD

**Issue by hecktarzuli** [netlify/netlify-cms#3311]
**Describe the bug**
When you setup a boolean field, and have other fields that are required, the boolean shows an error message even though it has a default.

**To Reproduce**
1. Create a boolean widget
2. Create an input widget.
3. Create a new entry, fill nothing in, click Publish.
4. Notice the UI tells you both fields are required
5. Fill in the input widget
6. Press publish
7. Notice bool still shows error
8. Turn bool on, turn bool back off
9. Press publish, notice it saves now.

**Expected behavior**
I shouldn't have to turn a bool from false(default), to true, to false

**Screenshots**
![image](https://user-images.githubusercontent.com/2112282/75126810-406ee200-5681-11ea-8be9-8315e12e85a3.png)

**Applicable Versions:**

 - Netlify CMS version: 2.10.26
 - Git provider: github
 - OS: Mac
 - Browser version Chrome 80.0

 - Node.JS version: 10.17.0

**CMS configuration**
```yaml
backend:
  name: git-gateway
  branch: master

media_folder: static/img/content
public_folder: /img/content

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Published'
        name: 'isPublished'
        widget: 'boolean'
      - label: 'Icon'
        name: 'icon'
        widget: 'select'
        options: ['VUE', 'NUXT']
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
      - label: 'thumb'
        name: 'thumb'
        widget: 'object'
        fields:
          - label: 'Url'
            name: 'url'
            widget: 'image'
            media_library:
              config:
                multiple: false
          - label: 'Alt'
            name: 'alt'
      - label: 'Body'
        name: 'body'
        widget: 'list'
        types:
          - label: 'Code Block'
            name: 'codeBlock'
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
              - label: 'Style'
                name: 'style'
                widget: 'select'
                options: ['GOOD', 'BAD', 'NORMAL']
                default: 'NORMAL'
              - label: 'Code'
                name: 'code'
                widget: 'markdown'
          - label: 'Image'
            name: 'image'
            fields:
              - label: 'Url'
                name: 'url'
                widget: 'image'
              - label: 'Alt'
                name: 'alt'
                widget: 'string'
          - label: 'Markdown'
            name: 'markdown'
            fields:
              - label: 'Content'
                name: 'content'
                widget: 'markdown'
          - label: 'YouTube Video'
            name: 'youTubeVideo'
            fields:
              - label: 'ID'
                name: 'id'
                widget: 'string'
```
