### ISSUE TITLE
Create new collection entry at user-defined path (maybe in a subfolder)

### ISSUE THREAD

**Issue by zachleat** [netlify/netlify-cms#3324]
Currently I have `path: "{{slug}}"` in my collection config. I’d like to be able to do `path: "{{fields.folder}}{{slug}}"` where folder is an optional form field value that is set by the user. If they don’t specify a `folder`, it just puts the file in the top level folder of the collection.

**Comment by erezrokah** [comment]
The use case for this issue should be covered in https://github.com/netlify/netlify-cms/issues/3227 (https://www.netlifycms.org/docs/beta-features/#nested-collections)
You can use the string widget to control the entry path, or write a custom widget that takes into account other fields.
Please comment if that doesn't satisfy the feature request

**Comment by ValeriyTen** [comment]
@erezrokah 
I have a problem with this implementation.
I have my repository with Hugo content. I managed to configure Netlify CMS at self-hosted Gitlab and I'm able to see all content from repository correctly. But whenever I' trying to edit existing entry or create new one inside existing subfolder it throws error "Example path is not a valid path". 
As far as my tests go, it seems that path can't be made out of Capital letters, spaces or anything other than just lowercase letters. My configuration of collections:
```
collections:
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content/pages
    create: true
    # adding a nested object will show the collection folder structure
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
```
Could you please advice on how to correctly make configuration in this case. 
As a result I just need an ability to create entries in any subfolders by just setting a path, just as described in post topic.
Thanks!

**Comment by erezrokah** [comment]
@ValeriyTen, the string widget is quite permissive in what can go into the path.
I recommend to use a pattern to enforce a valid path https://www.netlifycms.org/docs/widgets/#common-widget-options

**Comment by ValeriyTen** [comment]
@erezrokah 

I managed to get any symbol into 'path' field to edit existing subfolders by configuring Netlify this way

```
collections:
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content
    create: true
    nested:
        depth: 100
        summary: '{{title}}'
    fields:
        - label: Path
          name: path
          widget: string
          index_file: '_index'
          pattern: ['.*', "Insert"]
        - label: Title
          name: title
          widget: string
        - label: Body
          name: body
          widget: markdown
```
But I have one more problem. Whenever I need to create a new entry in any subfolder, I specify path for that entry and after publishing it creates in root folder, in my example it's "content" folder. How do I configure it then?

**Comment by erezrokah** [comment]
> But I have one more problem. Whenever I need to create a new entry in any subfolder, I specify path for that entry and after publishing it creates in root folder, in my example it's "content" folder. How do I configure it then?

The supported way to handle nested collections and editing entries path is via the `meta` configuration as specified in the docs.

Regular fields (even if they are named `path`) won't get be regarded as fields for modifying entries path.

**Comment by ValeriyTen** [comment]
> The supported way to handle nested collections and editing entries path is via the `meta` configuration as specified in the docs.

I changed my collection config to this:
```
collections:
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content
    create: true
    nested:
        depth: 100
        summary: '{{title}}'
    fields:
        - label: Title
          name: title
          widget: string
        - label: Body
          name: body
          widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: '_index', pattern: ['.*', "Error"] } }
```
I managed to create a new entry in subfolder and to move created entry to another folder, but when I try to edit 'Body' of existing entry it fails with error ```Failed to persist entry: API_ERROR: A file with this name already exists``` plus ```pattern: ['.*', "Error"]``` parameter gets completely ignored, as it still says that 'path is not a valid path' if path contains special characters(Uppercase letters, dots etc). 

Any idea what I did wrong in configs? Because as far as my research go, I can't seem to find any info on ```meta``` parameter in Netlify docs or at Netlify forums.

Thanks in advance!
