### ISSUE TITLE
Editorial Workflow mode fails to create pull requests in GitHub

### ISSUE THREAD

**Issue by CalMlynarczyk** [netlify/netlify-cms#3407]
**Describe the bug**
When using `publish_mode` in `editorial_workflow`, we get an error when saving changes to or creating new pages. The new branch gets created, but not the pull request on top of it. This was working up until the past month or so when we noticed that we could no longer make changes via the Netlify CMS interface.

**To Reproduce**
We see that the GitHub API request to create the pull request fails with a 422 status:

**Request:**

```json
{
  "title": "Update Articles “help-us-build-a-better-retirement”",
  "body": "Automatically generated by Netlify CMS",
  "head": "unitedincome:cms/articles/help-us-build-a-better-retirement",
  "base": "develop"
}
```

**Response:**

```json
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "PullRequest",
      "field": "head",
      "code": "invalid"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"
}
```

**Expected behavior**
The changes save to a new branch with a pull request on GitHub for approving the change.

**Applicable Versions:**

 - Netlify CMS version: 2.10.30
 - Git provider: GitHub
 - OS: macOS and Windows
 - Browser version Chrome, Firefox
 - Node.JS version: 10.16

**CMS configuration**
```yaml
backend:
  name: github
  repo: unitedincome/somerepo
  branch: develop
  auth_endpoint: auth

publish_mode: editorial_workflow
```

**Additional context**
This applies to a private repository owned by an organization named **UnitedIncome**. We see this issue in all environments across different domains and configurations.

**Comment by erezrokah** [comment]
Thanks for reporting @CalMlynarczyk, I think as a workaround this should work:

```yaml
backend:
  name: github
  repo: UnitedIncome/somerepo
  branch: develop
  auth_endpoint: auth

publish_mode: editorial_workflow
```
Seems like GitHub is case insensitive in regards with URL, for not with the `head` parameter when creating a pull request.
Will submit a fix soon
