### ISSUE TITLE
Git Gateway Error when logging in

### ISSUE THREAD

**Issue by BranonConor** [netlify/netlify-cms#3408]
**Describe the bug**
When logging in to /admin using Google for an account that has been invited and has been working for weeks, I get two "Git Gateway Error {object Object}" error notifications. No changes have been made to the admin _config.yml that should affect this. 

**To Reproduce**
Go to admin log in > click log in > sign in with google > pick email > get error, and can't log in > clear cache and try again > same error

**Expected behavior**
allow log in

**Applicable Versions:**

 - Netlify CMS version: 
netlify-cms-app 2.11.27
netlify-cms-core 2.21.0
netlify-cms 2.10.30
 - Git provider: Github
 - OS: Mac OS Catalina
 - Browser version: latest version of Chrome

 - Node.JS version: latest

**CMS configuration**
```yaml
backend:
    name: git-gateway
    branch: master

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "source/_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Type", name: "type", widget: "hidden", default: "blog"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
  - name: "components" # Used in routes, e.g., /admin/collections/blog
    label: "Component" # Used in the UI
    folder: "source/_posts/components" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Type", name: "type", widget: "hidden", default: "component"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "quotes" # Used in routes, e.g., /admin/collections/blog
    label: "Testimonial Quotes" # Used in the UI
    folder: "source/_posts/quotes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "quote"}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}  
      - {label: "Initials", name: "initials", widget: "string"}
  - name: "top-level-pages"
    label: "Top Level Pages" # Used in the UI
    folder: "source/top-level-pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "index" # Filename template, e.g., YYYY-MM-DD-title.md
    path: '{{title}}/{{slug}}'
    fields: # The fields for each document, usually in front matter
      - {label: "Draft", name: "draft", widget: "boolean", default: true, requried: false}
      - {label: "Type", name: "type", widget: "hidden", default: "top-level"}
      - {label: "Child Pages", name: "children", widget: "boolean", default: "false"}
      - {label: "Menu Label", name: "menulabel", widget: "string"}
      - {label: "Menu Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "lower-level-pages" # Used in routes, e.g., /admin/collections/blog
    label: "Lower Level Pages" # Used in the UI
    folder: "source/lower-level-pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "index" # Filename template, e.g., YYYY-MM-DD-title.md
    path: '{{title}}/{{slug}}'
    fields: # The fields for each document, usually in front matter
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "lower-level"}
      - {label: "Child Pages", name: "children", widget: "hidden", default: "false"}
      - {label: "Parent Page Name", name: "parent", widget: "string"}
      - {label: "Menu Label", name: "menulabel", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

```
**Additional context**
Everything has been working as-is for weeks and is acting up seemingly out of nowhere.
