### ISSUE TITLE
Collection's public_folder is being included into pattern validation for image widget

### ISSUE THREAD

**Issue by vai0** [netlify/netlify-cms#3436]
**Describe the bug**
If a collection has the [`media_folder` / `public_folder` fields applied to a collection](https://www.netlifycms.org/docs/beta-features/#folder-collections-media-and-public-folder), an image widget field will always mark as invalid if the `pattern` field applied does not include pattern matching the `public_folder`.

e.g.,
```yml
collections:
  - name: leadership
    label: Leadership
    media_folder: ../../static/images/leadership
    public_folder: /images/leadership
    ...
    fields:
      - label: "Profile Image"
        name: "imgSrc"
        widget: "image"
        pattern: ['^blah_[a-z]+-[a-z]+\.(jpg|jpeg|png|gif|bmp)$',
          "Must match the format: blah_{firstname}-{lastname}.{format}
          without brackets and have one of the following extensions (jpg|jpeg|png|gif|bmp)"]
```
will error if provided an image filename of `blah_justin-chi.jpg`, but will be valid if you change the pattern to
```yml
  pattern: ['^/images/leadership/blah_[a-z]+-[a-z]+\.(jpg|jpeg|png|gif|bmp)$',
        "Must match the format: blah_{firstname}-{lastname}.{format}
        without brackets and have one of the following extensions (jpg|jpeg|png|gif|bmp)"]
```

**Expected behavior**
Only the image filename should be tested against the pattern, but instead it appears as if the eventual path ``${public_folder}${filename}`` is also being tested.

**Applicable Versions:**

 - Netlify CMS version: 2.11.29
 - Git provider: GitLab
 - OS: Linux Debian 9
 - Browser version chrome 80.0.3987.87 (Official Build) (64-bit)
