### ISSUE TITLE
Widget MarkdownEditor: option editorComponents has no effect

### ISSUE THREAD

**Issue by jannis701** [netlify/netlify-cms#3459]
I'm trying to get rid of the default components "image" (because i want to replace it by an own component) and "code-block" (because I don't need it).
in _config.yml_ I set
```
collections:
   - name: "page"
     ....
     fields:
         - { label: "Body", name: "body", widget: "markdown", editorComponents: [ 'youtube' ], buttons: [ "bold" ] }
```

For testing, I registered two own components "youtube" and "youtube1" (according to https://www.netlifycms.org/docs/widgets/#markdown ) because I thougt, maybe the option editorComponents affects only custom components. But it seems **editorComponents-array has no effect at all**.
All registered components are shown, no matter what I set editorComponents-array to. 
Buttons-option thus, does work as expected.

Used software-versions (from package.json):
  "name": "netlify-cms",
  "version": "2.10.15",

  "name": "netlify-cms-widget-markdown",
  "version": "2.8.2",
