### ISSUE TITLE
Can't access nested lists or objects in preview templates

### ISSUE THREAD

**Issue by jonathansgardner** [netlify/netlify-cms#3485]
**Is your feature request related to a problem? Please describe.**
I can't access the data from a nested list widget using the widgetsFor function in my preview template

**Describe the solution you'd like**
I have a list widget that is nested inside of an object widget which I am unable to access in order to display in my preview template using the widgetsFor function

i.e.
```
# config.yml

...

  - name: about
     label: About
     widget: object
     fields:
       - name: links
          label: Links
          widget: list
          fields:
            - { name: title, label: Link text, widget: string }
            - { name: url, label: URL, widget: string }
```
