### ISSUE TITLE
Request to add option for image widget to trim output to a relative path

### ISSUE THREAD

**Issue by Nixinova** [netlify/netlify-cms#3487]
**Is your feature request related to a problem? Please describe.**

All images for my content are stored in e.g. `/assets/images`, so I remove this string for the image parameter in the page's front matter, leaving just e.g. "header-image.jpg" as the parameter. However, Netlify CMS's image widget always uses the full path name in its output, creating e.g. "/assets/images/header-image.jpg" when I just wanted the former.

**Describe the solution you'd like**

I would like to request that a option be added to the image widget called something like e.g. `output_file_path` to specify where the output file name should be relative to; in my example I would set this option to "/assets/images".

**Describe alternatives you've considered**

1. Changing the widget type to string and manually inputting it, however this is annoying
2. Manually removing the path on GitHub
3. Editing my code to replace the path with "" when it exists

**Additional context**

None.

**Comment by erezrokah** [comment]
Hi @Nixinova, this is possible as a beta feature:
https://www.netlifycms.org/docs/beta-features/#folder-collections-media-and-public-folder

You can set:
```
media_folder: '' # this will result in saving the image in the same directory as the content file
public_folder: '' # this will result in outputting just image filename
```
On a collection.

Can you try this feature with the latest version?

**Comment by Nixinova** [comment]
I haven't figured out how do use that. Does the public_folder parameter go inside the collection or outside? What about the media_folder parameter?

**Comment by erezrokah** [comment]
Hi @Nixinova, the `media_folder` and `public_folder` can go at the root level, collection level, file level (for file collections) and field level.

`media_folder` tells the CMS where to save the files in the repository, `public_folder` tells the CMS how to output the file path  (e.g which value to save in the markdown) and defaults to `media_folder`.

Can you share your `config.yml`, files structure and values saved you're expecting in the repo to have? Also make sure you're using the latest CMS version.

**Comment by Nixinova** [comment]
Importing `netlify-cms@^2.0.0`

```
backend:
  name: git-gateway
  branch: news
media_folder: "assets/images/articles/banners"
public_folder: ""
collections:
  - name: "article"
    label: "Article"
    folder: "/pages/articles/2020/04"
    create: true
    slug: "{{slug}}"
    fields:
```
If I want the output from the Article collection to drop the full assets/images/etc path name from the front matter parameter where should public_folder and media_folder be?

**Comment by Nixinova** [comment]
Hm, I just found a hacky way of doing this. I made two widgets that both have the name "url" but set them to two different widgets, image and string. So I can use the image widget to choose an image, which autofills in the string widget value, and then customise the output url using the string widget, which is quite useful.

**Comment by Nixinova** [comment]
Tempted to close this issue as this method is more useful to me than if I could get public_folder to work, as if I know the filename I can just type it in instead of browsing through all the images.

**Comment by erezrokah** [comment]
using `public_folder: ""` should work at the root level but I think there is a bug there.
You can use:

```
backend:
  name: git-gateway
  branch: news
media_folder: "assets/images/articles/banners"
collections:
  - name: "article"
    label: "Article"
    folder: "/pages/articles/2020/04"
    create: true
    slug: "{{slug}}"
    public_folder: ""
    fields:
```
As a workaround or use `public_folder: "/"` if that works for you.
