### ISSUE TITLE
Page Types

### ISSUE THREAD

**Issue by liamkeily** [netlify/netlify-cms#3491]
It would be nice if users could select a type when creating a page / item, which determines the fields used for that item

The config could look like this:

```
collections:
  - name: "pages"
    label: "Pages"
    create: true
    types:
	- type: ‘markdown’
           label: ‘Markdown Page’
           fields:
		- {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-markdown"}
		- {label: "Title", name: "title", widget: "string"}
		- {label: "Description", name: "description", widget: "text"}
		- {label: "Body", name: "body", widget: "markdown"}
        - type: ‘blocks’
           label: ‘Blocks Page’
           fields:
		- {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-blocks"}
		- {label: "Title", name: "title", widget: "string"}
		- {label: “Blocks”, name: “blocks”, widget: “list”}
	- type: ‘contact’
           label: ‘Contact Page’
           fields:
		- {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-contact”}
		- {label: "Title", name: "title", widget: "string"}
		- {label: "Email", name: "email", widget: "email"}
		- {label: "Address", name: "address", widget: "text"}
		- {label: "Phone", name: "phone", widget: "text"}
```

This would offer the same flexibility as a file collection, while also allowing the user to create new page of any type.

The type could be stored in the frontmatter of the item.
