### ISSUE TITLE
Duplicate object template via GUI

### ISSUE THREAD

**Issue by bencodezen** [netlify/netlify-cms#3495]
**Is your feature request related to a problem? Please describe.**
Lists must be defined statically rather than dynamically.

Scenario: I want to create a field called “TaskItem” that can be duplicated for each page

```
- label: 'TaskItem'
  name: 'task-item'
  widget: 'object'
  fields: 
    - { label: 'Task Name', name: 'task-name', widget: 'string' }
    - { label: 'Task Status', name: 'task-status', widget: 'string' }
```

Right now if I define it in the NetlifyCMS config,yml file, it will only show up X number of times I replicate this item in the config.yml.

**Describe the solution you'd like**
I’d like to be able to use TaskItem as a template that I can replicate in NetlifyCMS so that it automatically adds new items to an array which allows for dynamic lists instead of static ones

Possible solution is to add a property like:

- `type: list`
- `repeatable: true`
- `template: true`

to the object providing the template that can be repeated.

1. Create new "TaskList" collection
2. See a field for "Task Item" with a "New" or "+" button to add a new item
3. Click on "New" or "+" button
4. See form fields generate within CMS to fill out
5. Each successive "New" or "+" duplicate the form field to allow user to fill out additional items

Resulting MD file:

```
# TaskList-1.md
---
- items:
    - task-name: 'Get milk'
       task-status: 'incomplete'
    - task-name: 'Get bread'
       task-status: 'incomplete'
---
```

**Describe alternatives you've considered**
Manually creating X number of items to have a possible list length in case we need it, but it seems wrong once the thought has been considered.

**Additional context**
