### ISSUE TITLE
TypeError: e.join is not a function

### ISSUE THREAD

**Issue by radek-daniluk** [netlify/netlify-cms#3509]
**Describe the bug**
Can't open post editor

**To Reproduce**
Click on draft post in Workflow tab.

**Expected behavior**
Open page with post editor

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.36`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0`

**CMS configuration**
```
publish_mode: editorial_workflow
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: '-'
backend:
  name: git-gateway
  branch: master
media_folder: assets
collections:
  - name: post
    label: Posts
    folder: _posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
      - label: Archived
        name: archiwum
        widget: boolean
        default: 'false'
      - label: Categories
        name: categories
        widget: list
        default:
          - ekologia
      - label: Publish Date
        name: date
        widget: datetime
      - label: Head Image
        name: head-image
        widget: image
      - label: Body
        name: body
        widget: markdown
    publish: true
public_folder: /assets

```

**Additional context**

**Comment by tomrutgers** [comment]
I think this error is raised when a list widgets default value is not configured in the right way, might be because of the YAML list syntax. Can you try setting the categories default value as an array?
```
- label: Categories
  name: categories
  widget: list
  default: ['ekologia']
```

@erezrokah Actually it would make sense to support the list syntax (not sure if this is a bug or intentional)

**Comment by radek-daniluk** [comment]
This is how my `config.yml` looks like literally:
```
# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'assets'
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Archived", name: "archiwum", widget: "boolean", default: "false"}
      - {label: "Categories", name: "categories", widget: "list", default: ["ekologia"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Head Image", name: "head-image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
```

I changed categories line to:
```
      - label: Categories
        name: categories
        widget: list
        default: ['ekologia']

```

but bug report still shows:
```
      - label: Categories
        name: categories
        widget: list
        default:
          - ekologia

```
