### ISSUE TITLE
TypeError: e.get is not a function

### ISSUE THREAD

**Issue by edsu** [netlify/netlify-cms#3522]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.2`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: '-'
backend:
  name: git-gateway
  branch: redesign
media_folder: static/images
public_folder: /images
collections:
  - identifier_field: title
    name: datasets
    slug: '{{year}}{{month}}{{day}}-{{slug}}'
    editor:
      preview: true
    folder: src/datasets
    publish: true
    sortableFields:
      - commit_date
      - title
      - commit_author
    label: Datasets
    format: yaml-frontmatter
    fields:
      - label: Added
        name: added
        widget: datetime
      - label: Creators
        name: creators
        widget: list
        fields:
          - label: Name
            name: name
            widget: string
          - label: Email
            name: email
            widget: string
            required: false
      - label: Tweet Dates
        name: dates
        widget: list
        fields:
          - label: Start
            name: start
            widget: datetime
          - label: End
            name: end
            widget: datetime
      - label: Published
        name: published
        widget: datetime
      - label: Repository
        name: repository
        widget: string
      - label: Subjects
        name: subjects
        widget: list
      - label: Title
        name: title
        widget: string
      - label: Tweets
        name: tweets
        widget: number
      - label: Dataset URL
        name: url
        widget: string
        pattern:
          - 'https?://.+'
          - Must be a URL
      - label: Description
        name: body
        widget: markdown
    create: true
    extension: md

```

**Additional context**
