### ISSUE TITLE
netlify-cms-proxy-server is not working: 422 (Unprocessable Entity)

### ISSUE THREAD

**Issue by CyriacBr** [netlify/netlify-cms#3526]
**Describe the bug**
When the proxy server is on, the CMS breaks. It cannot load anything, and can't persist anything either. Looking at the console, I see this:
```
POST http://localhost:8081/api/v1 422 (Unprocessable Entity)
index.html#/collections/posts:1 Uncaught (in promise) {type: "ENTRIES_FAILURE", error: "Failed to load entries", payload: "API_ERROR", meta: {…}}
```

**To Reproduce**

1. `npx netlify-cms-proxy-server`
2. `yarn dev` (next.js)
3. Navigate to /admin/index.html
4. Can't load any collection or persist.

**Expected behavior**
The proxy shouldn't cause any issue. It works if I don't run it.

**Applicable Versions:**
- netlify-cms-app 2.12.0
- netlify-cms-core 2.23.0
- index.js:27 netlify-cms 2.10.36
 - Git provider: None for now, just using test-repo
 - OS: Ubuntu 19.10
 - Browser version Chrome 80.0.3987.149
 - Node.JS version: 10.18.1

**CMS configuration**
It works if I don't start the proxy, so I doubt it's the problem.
```yaml
backend:
  name: test-repo #git-gateway
  branch: next
local_backend: true
media_folder: public/img
public_folder: public
collections:
  - name: "posts"
    label: "Posts"
    folder: "../../src/data/blogPosts"
    extension: md
    format: yaml-frontmatter
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Slug", name: "slug", widget: "string" }
  - name: "blogQuotes"
    label: "BlogQuotes"
    folder: "../../src/data/blogQuotes"
    extension: json
    format: json
    create: true
    fields:
      - { label: "Content", name: "content", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
```
