### ISSUE TITLE
TypeError: e.split is not a function

### ISSUE THREAD

**Issue by walton-alex** [netlify/netlify-cms#3561]
**Describe the bug**
Cannot edit a post. I get an Error screen.

**To Reproduce**
Try to edit the 'test' post.

**Expected behavior**
To be able to edit the post.

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.40`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:76.0) Gecko/20100101 Firefox/76.0`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: '-'
backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: showcase
    slug: '{{slug}}'
    editor:
      preview: false
    folder: content
    publish: true
    sortableFields:
      - commit_date
      - title
      - commit_author
      - content
    label: Showcase
    fields:
      - label: Title
        name: title
        widget: string
      - label: Content
        name: content
        widget: markdown
    create: true

```

**Additional context**
I'm building a website using Hugo, and I want to be able to edit the Front Matter in some of my markdown files. I believe this is causing an issue with Netlify CMS.
