### ISSUE TITLE
netlify-cms@2.10.41 started wrapping datetime with quotes in yaml

### ISSUE THREAD

**Issue by nvreez** [netlify/netlify-cms#3568]
**Describe the bug**
We use Netlify CMS with the unpkg link set to version `^2.0.0`, and since yesterday copy changes failed our build. I discovered Netlify CMS started wrapping datetime values in doublequotes. Our parses then parsed them as strings instead. Using the Netlify CMS version `2.10.40` fixed the issue for us. We're using the github backend and have no format set on the datetime field.

**To Reproduce**
Using `2.10.41` save a markdown page with datetime widget. The yaml has added quotes around the field. 

**Expected behavior**
The datetime value should be saved without quotes. 

**Applicable Versions:**
 - Netlify CMS version: 2.10.41
 - Git provider: GitHub
 - OS: Mac OS 10.14.6
 - Browser version: Firefox 74.0.1

 - Node.JS version:

**CMS configuration**
```yaml
backend:
  name: github
  repo: org/our-repo
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'resources/public/uploads'
public_folder: '/uploads'
publish_mode: editorial_workflow
logo_url: '/images/logo.svg'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    preview_path: blog/{{slug}}
    create: true
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "author"
        searchFields: ["title", "role"]
        valueField: "title"
        displayFields: ["title", "role"]
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
```

Also found this issue from 2018 with similar problem #1271
