### ISSUE TITLE
Content Manager does not indicate config.yml parsing error.

### ISSUE THREAD

**Issue by jaredwolff** [netlify/netlify-cms#357]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
When a `config.yml` file has a parsing error in it, the admin page spins without letting the user know what's wrong. 

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a new site
1. Set the configuration file to the below snippet _Note:_ The error occurred on the 'Title' definition line. 

```
backend:
  name: github
  repo: <repo address> # Path to your Github repository
  branch: master # Branch to update
  
media_folder: "/static/img"
public_folder: "/dist/img"

collections:
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Draft", name: "draft", widget: "string", default: "true"}
      - {label: "Type", name: "type", widget: "hidden", default: "blog"}
      - {label: "Author", name: "author", widget: "string", default: "Jared"}
      - {label: "Publish Date", name: "publishdate", widget: "datetime"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Topics", name: "topics", widget: "list"}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Title", name: "title", widget: "string", pattern: [".{10,}", "Should have more than 30 characters and less than 160"]}
      - {label: "Description", name: "description", widget: "text", pattern: [".{30,160}", "Should have more than 30 characters and less than 160"]}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Image Alt", name: "image_alt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
```

1. Spin up a local machine server and attempt to navigate to it. (In my case it was Hugo so http://localhost:1313/admin/)

The diff after fixed.

```
-      - {label: "Title", name: "title", widget: "string", pattern: [".{10,}", "Should have more than 30 characters and less than 160}
+      - {label: "Title", name: "title", widget: "string", pattern: [".{10,}", "Should have more than 30 characters and less than 160"]}
```

To avoid playing where's Waldo, I was missing `"]` toward the end of the JSON string for the pattern key.

**- What is the expected behavior?**

The expected error would be to notify the end user that there is a parsing error in the YAML file. Something similar to the 'Error loading the CMS configuration.' page. 

![content_manager](https://cloud.githubusercontent.com/assets/1015795/24994415/4da66162-205d-11e7-8369-010b5b562d28.jpg)

**- Please mention your node.js, and operating system version.**
El Capitan 10.11.6 
Node v7.8.0
