### ISSUE TITLE
Save bar gets stuck in the middle of the screen. 

### ISSUE THREAD

**Issue by jaredwolff** [netlify/netlify-cms#358]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
When the content preview is shut off, the 'Save' & 'Cancel' buttons **don't** scroll with the rest of the screen. (i.e. stays static) See my screenshot below:

![content_manager](https://cloud.githubusercontent.com/assets/1015795/24996177/726d347e-2064-11e7-9f38-e11b3a43b1ed.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**

Using Safari 10.1

1. Login to Content Manager
1. Open a 'blog' collection
1. Open a single entry
1. Turn off the Post Preview
1. Scroll down

Site config as follows:

```
backend:
  name: github
  repo: <Site address> # Path to your Github repository
  branch: master # Branch to update
  
media_folder: "/static/img"
public_folder: "/dist/img"

collections:
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Draft", name: "draft", widget: "string", default: "true"}
      - {label: "Type", name: "type", widget: "hidden", default: "blog"}
      - {label: "Author", name: "author", widget: "string", default: "Jared"}
      - {label: "Publish Date", name: "publishdate", widget: "datetime"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Topics", name: "topics", widget: "list"}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Title", name: "title", widget: "string", pattern: [".{10,}", "Should have more than 30 characters and less than 160"]}
      - {label: "Description", name: "description", widget: "text", pattern: [".{30,160}", "Should have more than 30 characters and less than 160"]}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Image Alt", name: "image_alt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
```

**- What is the expected behavior?**

I expect the bar to stay in place when I scroll to lower form elements.

**- Please mention your node.js, and operating system version.**
node v7.8.0
El Capitan 10.11.6
