### ISSUE TITLE
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&a...

### ISSUE THREAD

**Issue by cardamonchai** [netlify/netlify-cms#3585]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.3`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36`

**CMS configuration**
```
publish_mode: editorial_workflow
collections:
  - name: article
    slug: '{{year}}-{{month}}---{{slug}}'
    folder: content/articles
    publish: true
    sortableFields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    label: Artikel
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: article
      - label: Titel
        name: title
        widget: string
      - label: Untertitel
        name: subtitle
        widget: string
      - label: Exzerpt
        name: description
        widget: text
      - label: GoLive
        name: date
        widget: datetime
      - label: Bild
        name: image
        widget: image
      - label: Text
        name: body
        widget: markdown
      - label: Labels
        name: labels
        widget: list
      - label: Type
        name: type
        widget: select
        default: Standard
        options:
          - Standard
          - Galerie
          - Galerie mit Bild
    create: true
    preview_path: '{{year}}/{{month}}/{{slug}}'
  - name: pages
    slug: '{{slug}}'
    folder: content/pages
    publish: true
    sortableFields:
      - commit_date
      - title
      - commit_author
      - description
    label: Seiten
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: page
      - label: Titel
        name: title
        widget: string
      - label: Untertitel
        name: subtitle
        widget: string
      - label: Exzerpt
        name: description
        widget: text
      - label: Bild
        name: image
        widget: image
      - label: Text
        name: text
        widget: markdown
    create: true
    preview_path: '{{slug}}'
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'cms: Create “{{slug}}”'
    update: 'cms: Update “{{slug}}”'
    delete: 'cms: Delete “{{slug}}”'
    uploadMedia: 'cms media: [skip ci] Upload “{{path}}”'
    deleteMedia: 'cms media: [skip ci] Delete “{{path}}”'
media_folder: static/img
public_folder: /img
editor:
  preview: false
slug:
  encoding: ascii
  clean_accent: true
  clean_accents: false
  sanitize_replacement: '-'

```

**Additional context**
