### ISSUE TITLE
Only partial relation metadata available on list previews

### ISSUE THREAD

**Issue by lmcorreia** [netlify/netlify-cms#359]
**- Do you want to request a *feature* or report a *bug*?**
* BUG

**- What is the current behavior?**
* When adding a field with the `relation` widget to a `list`, the metadata available (see https://github.com/netlify/netlify-cms/blame/7aa77baea9e64aaaf3f1a610543263426dc661b4/docs/customization.md#L181) from the list field is not complete, the only metadata available at any given time refers to the last child updated.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Add a "collection1" with a field that can be referenced and some content in its directory.
2. Add a "collection2" with a `list` field, whose children refer to "collection 1" through `relation`, like:
```
- label: "People"
        name: "people"
        widget: "list"
        fields:
          - label: "Person"
            name: "person"
            widget: "relation"
            collection: "collection1"
            searchFields:
              - "title"
            valueField: "title"
```
3. Add a custom preview class through `CMS.registerPreviewTemplate` for "collection2" and monitor the values of `this.props.fieldsMetadata.get('people')` - there is only 1 entry, the last child edited on the `list` field.

**- What is the expected behavior?**
* On step 3 above, that metadata for every child of the `list` field is available, i.e., that for every item in `this.props.entry.getIn(['data', fieldName])` there is a corresponding item in `this.props.fieldsMetadata.get('fieldName')` filled with metadata.

**- Please mention your node.js, and operating system version.**
v6.9.5 on OS X 10.11.6
