### ISSUE TITLE
Unable to enable multiple image selection with Cloudinary

### ISSUE THREAD

**Issue by gusbmurphy** [netlify/netlify-cms#3620]
Hi everyone, thanks in advance for your attention on what has been a very obnoxious problem for me, that I'd imagine has a simple solution that I've just been managing to overlook. I'm pretty new to using NetlifyCMS, and am struggling to integrate Cloudinary in the way I intend to. The only behavior that I'm trying to introduce is to allow multiple selection for an image widget. At first it seems to be working: I'm able to select multiple images and "Insert" them, but then when I go to hit publish, nothing happens. I don't see any activity bar, I only get this error in my console:

```
Uncaught TypeError: e.replace is not a function
    at i (path.js:12)
    at t.basename (path.js:37)
    at t.getValidateValue (withFileControl.js:185)
    at Object.imageGallery (Widget.js:75)
    at EditorControlPane.js:48
    at it.__iterate (immutable.js:2206)
    at it.forEach (immutable.js:4381)
    at f.validate (EditorControlPane.js:46)
    at EditorInterface.js:144
    at Object.onSelection (Dropdown.js:79)
```

Of course, I expected to be able to publish! This only happens when I introduce the `media_library` configuration of `allow_multiple`. I'll include my various version and `config.yml` file here, and thanks again for your time!

 - Netlify CMS version: gatsby-plugin-netlify-cms@4.2.2
 - Git provider: GitHub
 - MacOS Catalina: 10.15.4 (19E264b)
 - Google Chrome: 81.0.4044.113
 - Node.JS version: v12.13.0

**CMS configuration**
(The problem comes up with the `imageGallery` field.)
```
backend:
  name: github
  repo: gusbmurphy/Personal-Site

media_folder: static/assets
public_folder: assets

media_library:
  name: cloudinary
  config:
    cloud_name: dtc0i7udk
    api_key: 234775223881751

collections:
  - name: writing
    label: Writing
    folder: content/writing
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: tags, label: Tags, default: ["news", "games"], widget: "list" }
      - { name: body, label: Body, widget: markdown }
      - { name: "templateKey", widget: "hidden", default: "writing" }
  - name: work
    label: Work
    folder: content/work
    create: true
    fields:
      - { name: date, label: Date, widget: date, dateFormat: "MM.YYYY" }
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: "list" }
      - { name: shortDesc, label: Short Description, widget: "string" }
      - { name: description, label: Full Description, widget: "text" }
      - name: previewImage
        label: PreviewImage
        widget: "image"
        media_library:
          config:
            allow_multiple: false
      - name: imageGallery
        label: ImageGallery
        widget: "image"
        media_library:
          config:
            allow_multiple: true
      - { name: "templateKey", widget: "hidden", default: "work" }
```
