### ISSUE TITLE
Collection entry sorting preference gets deleted

### ISSUE THREAD

**Issue by lbischof** [netlify/netlify-cms#3647]
**Describe the bug**
The sort preference for a collection is lost when switching collections

**To Reproduce**
1. Delete localstorage key `netlify-cms.entries.sort`
1. Refresh page
2. Sort current collection
4. Check localstorage (`netlify-cms.entries.sort` is there)
3. Switch to other collection
4. Check localstorage (`netlify-cms.entries.sort` is gone)
5. Sort the current collection
6. Check localstorage (`netlify-cms.entries.sort` is there again, **with the preferences of both collections included**)
7. Switch to other collection
8. Check localstorage (`netlify-cms.entries.sort` is gone)
.
.
.

**Workaround**
If all collections are sorted manually (before refreshing), then the localstorage value is not deleted anymore. 

**Expected behavior**
The localstorage value is not deleted and the sort preference doesn't get lost.

**Applicable Versions:**
 - Netlify CMS version: 2.10.47
 - Git provider: GitLab
 - OS: Ubuntu 19.10
 - Browser version Firefox 75

**CMS configuration**
```
backend:
  name: gitlab
  repo: xxxx/website
  auth_type: implicit
  app_id: xxxx
media_folder: static/images
public_folder: /images
collections:
- name: posts
  label: Post
  folder: content/posts
  create: true
  extension: markdown
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
  - label: Title
    name: title
    widget: string
  - label: "Publish Date"
    name: "date"
    required: false
    widget: "datetime"
  - label: "Post Author"
    name: "author"
    widget: "relation"
    collection: "team"
    searchFields: ["title"]
    valueField: "author"
    displayFields: ["title"]
  - label: "Draft"
    name: "draft"
    required: false
    widget: "boolean"
    default: true
  - label: "Categories"
    name: "categories"
    required: false
    widget: "list"
  - label: "Tags"
    name: "tags"
    required: false
    widget: "list"
  - label: "Featured Image"
    name: "featured_image"
    required: false
    widget: "image"
  - label: URL
    name: url
    widget: hidden
  - label: Type
    name: type
    widget: hidden
    default: post
  - label: "Body"
    name: "body"
    widget: "markdown"
- name: team
  label: Team
  folder: content/team
  create: true
  fields:
  - label: Title
    name: title
    widget: string
  - label: "Kürzel"
    name: "author"
    widget: string
  - label: "Citation"
    name: "citation"
    widget: string
  - label: "Job Titles"
    name: "job_titles"
    required: false
    widget: "list"
  - label: "Qualifications"
    name: "qualifications"
    required: false
    widget: "list"
  - label: "Featured Image"
    name: "featured_image"
    required: false
    widget: "image"
  - label: "Body"
    name: "body"
    widget: "markdown"
```

**Additional context**
Also happens with using git-gateway instead of implicit auth.
