### ISSUE TITLE
List widget with variable types should allow hints or descriptions for each type

### ISSUE THREAD

**Issue by boygirl** [netlify/netlify-cms#3650]
I'm making extensive use of variable types in the list widget, and it has been extremely useful! One thing I would like to see would be the ability to add a hint or description for the whole type. My current work around is adding a dummy boolean widget and giving it a hint, but that feels kind of hacky.  The ideal solution would be to support a hint or description for the entire type that would show at the top of the control for each type. 

For example: 
```
label: 'Home Section'
  name: 'sections'
  widget: 'list'
  types:
    - label: 'Carousel'
      name: 'carousel'
      widget: object
      hint: 'this is a description of the carousel type. This description should render above any fields for this type",
      fields:
        - { label: Header, name: header, widget: string, default: 'Image Gallery' }
        ...
```

Another possibly easier change would be to allow hidden fields to display hints if they have any.
