### ISSUE TITLE
custom widget preview doesn't refresh when `onChange` is called from widget

### ISSUE THREAD

**Issue by andycmaj** [netlify/netlify-cms#3657]
**Describe the bug**

I have a custom widget (based on select widget/react select). I also have a custom preview that makes an apollo query based on the widget value.

When i change the value using the widget, the preview does not re-render.

I'd expect the widget to be re-rendered because it consumes the `value` state from the redux store.

**To Reproduce**

custom widget code:

```js
import React from 'react';
import ApolloClient from 'apollo-boost';
import { useQuery, ApolloProvider } from '@apollo/react-hooks';
import { reactSelectStyles } from 'netlify-cms-ui-default/dist/esm/styles';
import Select from 'react-select';
import { toClass } from 'recompose';
import getCollections from './getCollections';
import getProducts from './getProducts';

const shopifyConfig = {
  shopName: process.env.SHOPIFY_SHOP_NAME,
  accessToken: process.env.SHOPIFY_ACCESS_TOKEN,
};

const client = new ApolloClient({
  uri: `https://${shopifyConfig.shopName}.myshopify.com/api/2019-07/graphql.json`,
  headers: {
...
  },
});

const getSelectedValue = (value, options) => {
  if (!value) {
    return '';
  }

  const maybeOption = options.find(option => option.value === value);
  return maybeOption || '';
};

const SelectComponent = ({
  field,
  value,
  forID,
  classNameWrapper,
  setActiveStyle,
  setInactiveStyle,
  onChange,
}) => {
  const { loading, error, data } = useQuery(getCollections);

  if (loading) return <p>Loading collections...</p>;
  if (error) return <p>Error :(</p>;

  const options = data.collections.edges.map(
    ({ node: { id, title, description } }) => ({
      label: title,
      value: id,
    })
  );

  const changeHandle = selected => {
    if (!selected) onChange([]);
    onChange(selected.value);
  };

  const selected = getSelectedValue(value, options);

  return (
    <div>
      <Select
        inputId={forID}
        isMulti={false}
        onChange={changeHandle}
        className={classNameWrapper}
        onFocus={setActiveStyle}
        onBlur={setInactiveStyle}
        styles={reactSelectStyles}
        name="categories"
        isClearable={false}
        value={selected}
        options={options}
        placeholder="select..."
      />
    </div>
  );
};

// custom CMS widgets have to export class components...
// see: https://github.com/netlify/netlify-cms/issues/1346
export const CollectionSelect = toClass(fieldProps => (
  <ApolloProvider client={client}>
    <SelectComponent {...fieldProps} />
  </ApolloProvider>
));

const PreviewComponent = ({ value }) => {
  const { loading, error, data } = useQuery(getProducts);

  if (loading) return <p>Loading collections...</p>;
  if (error) return <p>Error :(</p>;

  const {
    products: { edges: products },
  } = data;

  return (
    <div>
      {products.map(({ node: { title } }) => (
        <div>{title}</div>
      ))}
    </div>
  );
};

export const CollectionPreview = toClass(fieldProps => (
  <ApolloProvider client={client}>
    <PreviewComponent {...fieldProps} />
  </ApolloProvider>
));
```

cms.js
```js
import CMS from 'netlify-cms-app';
import { CollectionSelect, CollectionPreview } from './CollectionSelect';
import BlogPreview from './preview-templates/BlogPreview';
import withEmotionCss from './withEmotionCss';

CMS.registerPreviewStyle('/fonts/fonts.css');

CMS.registerPreviewTemplate('blog', withEmotionCss(BlogPreview));

CMS.registerWidget('collectionSelect', CollectionSelect, CollectionPreview);
```

**Expected behavior**

`PreviewComponent` gets rendered when `onChange` is called from `SelectComponent`. This seems to not happen.

**Applicable Versions:**
netlify-cms-app 2.12.9 index.js:8:12
netlify-cms-core 2.24.4
osx
firefox/chrome
nodejs 12

**CMS configuration**

```yaml
backend:
  name: git-gateway
  branch: master

# when using the default proxy server port
# uncomment for local dev
local_backend: true

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: 'productPicks'
    label: 'Picks from the Bottle Shop'
    files:
      - label: 'Picks'
        name: 'picks'
        file: 'src/pages/index.md'
        fields:
          - {
              label: Collection Id,
              name: featuredCollectionId,
              widget: collectionSelect,
            }
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    extension: md
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Category'
        name: 'category'
        widget: 'select'
        options: ['wine', 'bar']
      - {
          label: 'Author',
          name: 'author',
          widget: 'string',
          default: 'The ThirstyNest Editors',
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Hero Image', name: 'heroImage', widget: 'image' }
      - {
          label: 'Sponsored Post Contributor',
          name: 'sponsoredPostContributor',
          widget: 'string',
        }
      - label: 'Home Page Feature Position'
        name: 'homePageFeature'
        widget: 'select'
        options: ['none', 'left', 'rightTop', 'rightBottom']
      - { label: 'Body', name: 'body', widget: 'markdown' }
```

**Additional context**
widget and widget preview both use apollo hooks
