### ISSUE TITLE
Collection Capabilities / Tying a collection to a data source

### ISSUE THREAD

**Issue by austincondiff** [netlify/netlify-cms#3683]
## What is a collection capability

Collection capabilities are like presets in that the collection would be configured a certain way without having to specify everything implicitly in your `config.yml`. 

For example (warning: pseudo code), this….
```yml
{
  name: "posts",
  label: "Posts",
  capabilities: ["category", "tag"]
}
```
would be the same thing as this…
```yml
{
  name: "posts",
  label: "Posts",
  fields: [
    { name: "category", label: "Category", widget: "relation" ... },
    { name: "category", label: "Tags", widget: "relation" ... }
  ]
}
```

## Beyond simplified collection config

Of course these capabilities could be much more complex in that they are more than simply shortcuts to adding more config but they also add additional functionality such as tie the collection to an external data source via an API.

For example…
```yml
{
  name: "authors",
  label: "Authors",
  capabilities: ["users"]
}
```
The authors collection would then mirror the users you have given access to access your CMS. Any additional information associated with that user can be stored in the CMS without having to store sensitive information such as passwords in your git repo.

## Configuring the capability

We could take this a step further and add some config to these capabilities, for example. a products capability with the option to tie it to a third party api like Shopify (could also be a third-party plugin to reduce config further). This way you can store data that is site specific while letting shopify manage titles, images, checkout, etc.

```yml
{
  name: "products",
  label: "Products",
  capabilities: [{ name: "products", api: "https://api.shopify.com/34rq234f3rwev/products", netlifyApiKeyId: "SHOPIFY_API_KEY" }]
}
```
Disclosure: not super familiar with Shopify's API or Netlify API keys, but you get the idea.
In this case we’d need to trigger a rebuild using webhooks whenever a new product is added to Shopify so that the product entries stay up to date. At that point the product id would be added as a preconfigured hidden field via the product capability and can be used by the developer in the site.

This collection may be classified as a folder collection type but it is synced with a data source so adding via the Netlify CMS UI may not be desired at that point.

I'd imagine that some of the configuration could be overwritten as well in consideration of things like this.

Thoughts about this approach?

**Comment by erquhart** [comment]
I'm still having a hard time seeing this doing more than shortening configuration for specific use cases. That's certainly worth doing, but I've generally expected the configuration UI to be the place where we provide those abstractions. This allows the "just works" experience we want coupled with only doing things one way under the hood (everything in the control panel is a widget). Not trying to shut down the idea here, just providing context on why we haven't done this sort of thing in our config so far.

**Comment by austincondiff** [comment]
Think of it like configuration templates. This provides additional ways to help simplify and avoid duplication of code in your config file.

There would be two types of collection capabilities. 
1. Provided capabilities - capabilities Netlify CMS ships with.
2. Developer defined capabilities - capabilities defined for use by the developer in their config file.

This allows a developer to define a capabilities array then they can use these capabilities later in the config file.

Example
```yml
capabilities: [
  { 
    name: "categories", 
    collections: [{ 
      name: "{{collectionName}}Categories", 
      label: "{{collectionSingularLabel}} Categories", 
      fields: [{ name: "category", label: "Category", widget: "text" }] 
    }],
    fields: [{ 
      name: "category", 
      label: "Category", 
      widget: "relation", 
      collection: "{{collectionName}}Categories" 
    }]
  },
  { 
    name: "tags", 
    collections: [{ 
      name: "{{collectionName}}Tags", 
      label: "{{collectionSingularLabel}} Tags", 
      fields: [{ name: "tag", label: "Tag", widget: "text" }] 
    }],
    fields: [{ 
      name: "tags", 
      label: "Tags", 
      widget: "relation", 
      collection: "{{collectionName}}Categories",
      multiple: true
    }]
  }
],
collections: [
  { name: "posts", label: "Posts", capabilities: ["categories", "tags"], fields: [...] },
  { name: "products", label: "Posts", capabilities: ["categories", "tags"], fields: [...] }
]
```

This cuts my config file in half and makes it much more readable.
