### ISSUE TITLE
How to Create Blog Categories?

### ISSUE THREAD

**Issue by emmadigital** [netlify/netlify-cms#3685]
How should I create blog categories in Netlify CMS? Is the below code in config.yml file is the right way to create categories? How should I deal with Site URLs, do I need to define that in config.yml file:
Category
    - Category 1
    - Category 2
    - Category 3

 - name: "uncategorized"
    label: "Uncategorized"
    folder: "src/pages/blog/uncategorized"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "hidden", default: "src/img/steve-smith-ardalis-200x200.jpg"}
      - {label: "Header Image", name: "image", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Commenting", name: "comments", widget: boolean, default: true}
      - {label: "Type", name: "type", widget: hidden, default: post}
      - {label: "Sharing", name: "share", widget: boolean, default: true}   

I want to have below Url structure for blog category:

List of posts in Category Url: www.sitedomain.com/category/category-name
Single Blog Post Url: www.sitedomain.com/post-name

**Comment by buxzee** [comment]
I want to create below categories for my blog posts, how should I achieve this please advise.

Uncategorized
Productivity
Security
Personal

**Comment by emmadigital** [comment]
Error loading the CMS configuration
Config Errors:
YAMLSyntaxError: Document is not valid YAML (bad indentation?) at line 68, column 1:

- name: "categories"
^^^^^^^^^^^^^^^^^^^^…
Check your config.yml file.

**Comment by emmadigital** [comment]
Please advise what I am doing wrong? how should I create categories for my blog.

```
- name: "categories"
    label: "Categories"
    identifier_field: slug
    folder: "src/pages/blog/"
    create: true
    fields:
      - {label: "Category", name: "category_name", widget: "string"}
      - {label: "Category Image", name: "category_img", widget: "image"}
      - {label: "Slug", name: "slug", widget: "string"} 

    - name: "personal"
    label: "Personal"
    identifier_field: slug
    folder: "src/pages/blog/personal"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "hidden", default: "src/img/steve-smith-ardalis-200x200.jpg"}
      - {label: "Header Image", name: "image", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Commenting", name: "comments", widget: boolean, default: true}
      - {label: "Type", name: "type", widget: hidden, default: post}
      - {label: "Sharing", name: "share", widget: boolean, default: true}
```

**Comment by barthc** [comment]
@emmadigital  you file indentations are off. You can use this online tool to validate your file http://www.yamllint.com/.  Update your config file like so:
```yaml
collections:
  - name: "categories"
    label: "Categories"
    identifier_field: slug
    folder: "src/pages/blog/"
    create: true
    fields:
      - {label: "Category", name: "category_name", widget: "string"}
      - {label: "Category Image", name: "category_img", widget: "image"}
      - {label: "Slug", name: "slug", widget: "string"} 

  - name: "personal"
    label: "Personal"
    identifier_field: slug
    folder: "src/pages/blog/personal"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "hidden", default: "src/img/steve-smith-ardalis-200x200.jpg"}
      - {label: "Header Image", name: "image", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Commenting", name: "comments", widget: boolean, default: true}
      - {label: "Type", name: "type", widget: hidden, default: post}
      - {label: "Sharing", name: "share", widget: boolean, default: true}
```

**Comment by barthc** [comment]
> I want to have below Url structure for blog category:
List of posts in Category Url: www.sitedomain.com/category/category-name
Single Blog Post Url: www.sitedomain.com/post-name

Not sure I understand the OP of the issue. The cms cannot control the url structure of the site. If the we talking about implementing a tag feature, then the relation widget or a simple list widget.

**Comment by emmadigital** [comment]
I checked my config.yml file on http://www.yamllint.com/ I get this error:https://prnt.sc/sals5v whats wrong with my code: Please advise

```
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
 - name: "iraq"
    label: "Iraq"
    identifier_field: slug
    folder: "src/pages/blog/iraq"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "hidden", default: "src/img/steve-smith-ardalis-200x200.jpg"}
      - {label: "Header Image", name: "image", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Commenting", name: "comments", widget: boolean, default: true}
      - {label: "Type", name: "type", widget: hidden, default: post}
      - {label: "Sharing", name: "share", widget: boolean, default: true}
  
```
