### ISSUE TITLE
Netlify CMS Content Manager Admin access denied

### ISSUE THREAD

**Issue by emmadigital** [netlify/netlify-cms#3686]
I am unable to access my Netlify CMS Content Manager. Yesterday after creating a new accoutn I was able to enter blogs but today I changed my Netlify random site name and this problem started. Reset password didn't help also as it says no user found. Netlify CMS is not connected with Netlify If I change site name, it should not automatically recognise the new site name. Please advise I am totally stuck. 

Secondly, the auto-generated Github repo by Netlify CMS is not locatable. I made few changes to my template and when push the updates to repo it says Repository not found what could be the issue am i not authorised or whatsgoing on. I tried changing repo settings with both public and private but no success. Please help me resolve this issue.

**Comment by emmadigital** [comment]
I have resloved the second issue of Github Repo, kindly help me resolve the first issue of accessing Netlify CMS Content Manager.

**Comment by barthc** [comment]
@emmadigital  Assuming are you using `git-gatway` backend and `netlify-identity` to authenticate, you would also need to change the site url stored in your browser's `localStorarge`.

**Comment by emmadigital** [comment]
I used Get Start button available on Netlify CMS home page and then
selected theme it asks me to authorize github and then it generated repo on
github and hosted site on Netlify..  everything was automated so I don't
know how it authenticate my access. I am not using git-gateway, can I
access with my email ID and password that would be better.

**Comment by barthc** [comment]
What UI or console error are you seeing, If your site and repo are public can you share them, please.

Also trying login into your site on your browser incognito mode so we can exclude the `localStorarge` site url issue.

**Comment by erezrokah** [comment]
Hi @emmadigital, do you mind following the issue template? It makes it a lot easier to understand and solve the issue. As @barthc mentioned possibly share a repo with the issue.

**Comment by emmadigital** [comment]
> What UI or console error are you seeing, If your site and repo are public can you share them, please.
> 
> Also trying login into your site on your browser incognito mode so we can exclude the `localStorarge` site url issue.

I am using incongnito mode here is my repo https://github.com/emmadigital/ardalis-newsite Url: https://ardalis.netlify.app/

I got an email to reset my password and I reset my password and I think it logged me in but got some Configuration Error message, which I don't know how to solve it. I would really appreciate If you can assist me.

**Comment by barthc** [comment]
> I think it logged me in but got some Configuration Error message

When I go here  https://ardalis.netlify.app/admin/#/ I see the below error 
```
Config Errors:
YAMLSyntaxError: Document is not valid YAML (bad indentation?) at line 68, column 1:

- name: "categories"
^^^^^^^^^^^^^^^^^^^^…
Check your config.yml file.
```
`config.yml` Indentation issue, fixed the indentation for you below

```yaml
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
  - name: "categories"
    label: "Categories"
    identifier_field: slug
    folder: "src/pages/blog/"
    create: true
    fields:
      - {label: "Category", name: "category_name", widget: "string"}
      - {label: "Category Image", name: "category_img", widget: "image"}
      - {label: "Slug", name: "slug", widget: "string"} 

  - name: "iraq"
    label: "Iraq"
    identifier_field: slug
    folder: "src/pages/blog/iraq"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "hidden", default: "src/img/steve-smith-ardalis-200x200.jpg"}
      - {label: "Header Image", name: "image", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Commenting", name: "comments", widget: boolean, default: true}
      - {label: "Type", name: "type", widget: hidden, default: post}
      - {label: "Sharing", name: "share", widget: boolean, default: true}
            
  - name: "personal"
    label: "Personal"
    identifier_field: slug
    folder: "src/pages/blog/personal"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "hidden", default: "src/img/steve-smith-ardalis-200x200.jpg"}
      - {label: "Header Image", name: "image", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Commenting", name: "comments", widget: boolean, default: true}
      - {label: "Type", name: "type", widget: hidden, default: post}
      - {label: "Sharing", name: "share", widget: boolean, default: true}

  - name: "productivity"
    label: "Productivity"
    identifier_field: slug
    folder: "src/pages/blog/productivity"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "hidden", default: "src/img/steve-smith-ardalis-200x200.jpg"}
      - {label: "Header Image", name: "image", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Commenting", name: "comments", widget: boolean, default: true}
      - {label: "Type", name: "type", widget: hidden, default: post}
      - {label: "Sharing", name: "share", widget: boolean, default: true}

  - name: "security"
    label: "Security"
    identifier_field: slug
    folder: "src/pages/blog/security"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "hidden", default: "src/img/steve-smith-ardalis-200x200.jpg"}
      - {label: "Header Image", name: "image", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Commenting", name: "comments", widget: boolean, default: true}
      - {label: "Type", name: "type", widget: hidden, default: post}
      - {label: "Sharing", name: "share", widget: boolean, default: true}

  - name: "software-development"
    label: "Software Development"
    identifier_field: slug
    folder: "src/pages/blog/software-development"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "category", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "hidden", default: "src/img/steve-smith-ardalis-200x200.jpg"}
      - {label: "Header Image", name: "image", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Commenting", name: "comments", widget: boolean, default: true}
      - {label: "Type", name: "type", widget: hidden, default: post}
      - {label: "Sharing", name: "share", widget: boolean, default: true}   

  - name: "uncategorized"
    label: "Uncategorized"
    identifier_field: slug
    folder: "src/pages/blog/uncategorized"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "hidden", default: "src/img/steve-smith-ardalis-200x200.jpg"}
      - {label: "Header Image", name: "image", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Commenting", name: "comments", widget: boolean, default: true}
      - {label: "Type", name: "type", widget: hidden, default: post}
      - {label: "Sharing", name: "share", widget: boolean, default: true}  
```
