### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by shloksomani** [netlify/netlify-cms#3690]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.11`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/img
public_folder: /img
collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Landing Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: SEO & Meta
            name: seo
            widget: object
            fields:
              - label: Browser Tab Title
                name: browserTitle
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: string
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Heading
            name: heading
            widget: string
          - label: Subheading
            name: subheading
            widget: string
          - label: Main
            name: main
            widget: object
            fields:
              - label: Body
                name: body
                widget: markdown
    publish: true
    sortableFields:
      - commit_date
      - commit_author

```

**Additional context**
