### ISSUE TITLE
Collections on same folder not appearing on first load

### ISSUE THREAD

**Issue by PedroOndh** [netlify/netlify-cms#3696]
**Describe the bug**
I am working with a page done with Jekyll and hosted on Bitbucket.
I have some different collections on the same folder that I get through a filter, being “blog, event, etc.” on the same _posts/ folder

Lately posts obtained by filtering don’t appear on first load on the admin panel, excepting the case of “blog” posts that constitute most of the files on this folder. If I click on “Sort by” and select an option it loads everything on the collection without any problem. 

I’ve realize that this is because it is always getting 20 first entries of folder _posts/ on first load. As there is no “events” on these first 20 it dismiss it as “No entries” until "Sort by" is used. 

**To Reproduce**
1. Have various collections on same folder, differentiated by filter field
2. Enter in the admin panel and click on a collection
3. See "No entries" message (error)
4. Click on "Sort by" and select any filter
5. Obtain entries.

**Expected behavior**
Obtaining filtered entries on first load

**Screenshots**
![01_folder-collections-no-results](https://user-images.githubusercontent.com/45435602/80951119-81a90e00-8df7-11ea-87b9-58964427812a.png)
![02_folder-collections-results](https://user-images.githubusercontent.com/45435602/80951127-85d52b80-8df7-11ea-8383-82b8f444853d.png)

**Applicable Versions:**
 - Netlify CMS version: 2.10.47
 - Git provider: Bitbucket
 - OS: macOS Catalina 10.15.4
 - Browser version: Observed on Chrome, Firefox and Safari

**CMS configuration**
```

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Blog post"
    description: "Entries sortable by Publish Date or title on 'Sort by' button"
    folder: "collections/_posts"
    filter:
      field: "categories"
      value: "blog"
    sortableFields: ['publish-date', 'title']
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Post Category", name: "categories", widget: "hidden", default: "blog"}
      - {label: "Post Author", name: "author", widget: "relation", collection: "team-members", searchFields: ["name","email"], valueField: "email", displayFields: ["name"], required: false}
      - {label: 'Cover Image', name: 'image', widget: 'image', tagname: '', hint: "File type: PNG / File size: as small as possible (Ask designer)"}
      - {label: "Publish date", name: "publish-date", widget: "datetime", format: "YYYY-MM-DD HH:mm a", default: ""}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h3", required: false}
      - {label: "Permalink", name: "slug", widget: "string", hint: "The URL of this post. WARNING: IF YOU EDIT THIS FIELD YOU CANNOT LEAVE IT BLANK", pattern: ["^[a-zA-Z\\-0-9]+$", "Must not have whitespaces and not being empty"], required: false}
      - {label: 'Meta Description', name: 'description', widget: 'string', required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags",  widget: select, options: ['Products', 'Engineering', 'Customers', 'empathy.co', 'News', 'Retail', 'Insights', 'Search', 'UX'], multiple: true}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "external-reference"
    label: "External Reference"
    label_singular: "'External Reference' post"
    description: "If entries don't appear on first load use 'Sort by' button"
    folder: "collections/_posts"
    filter:
      field: "categories"
      value: "external-reference"
    sortableFields: ['publish-date', 'title']
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Post Category", name: "categories", widget: "hidden", default: "external-reference"}
      - {label: "Post Author", name: "author", widget: "relation", collection: "team-members", searchFields: ["name","email"], valueField: "email", displayFields: ["name"], required: false}
      - {label: 'Cover Image', name: 'image', widget: 'image', tagname: '', hint: "File type: PNG / File size: as small as possible (Ask designer)"}
      - {label: "Publish date", name: "publish-date", widget: "datetime", format: "YYYY-MM-DD HH:mm a", default: ""}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: 'URL', name: 'link', widget: 'string', hint: "The external url of the publication" }
      - {label: 'Meta Description', name: 'description', widget: 'string', required: false }
      - {label: "Tags", name: "tags",  widget: select, options: ['Products', 'Engineering', 'Customers', 'empathy.co', 'News', 'Retail', 'Insights', 'Search', 'UX'], multiple: true}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "event"
    label: "Event"
    description: "If entries don't appear on first load use 'Sort by' button"
    folder: "collections/_posts"
    filter:
      field: "categories"
      value: "event"
    sortableFields: ['publish-date', 'title']
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Post Category", name: "categories", widget: "hidden", default: "event"}
      - {label: "Post Author", name: "author", widget: "relation", collection: "team-members", searchFields: ["name","email"], valueField: "email", displayFields: ["name"], required: false}
      - {label: 'Cover Image', name: 'image', widget: 'image', tagname: '', hint: "File type: PNG / File size: as small as possible (Ask designer)"}
      - {label: "Publish date", name: "publish-date", widget: "datetime", format: "YYYY-MM-DD HH:mm a", default: ""}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h3", required: false}
      - {label: "Permalink", name: "slug", widget: "string", hint: "The URL of this post. WARNING: IF YOU EDIT THIS FIELD YOU CANNOT LEAVE IT BLANK", pattern: ["^[a-zA-Z\\-0-9]+$", "Must not have whitespaces and not being empty"], required: false}
      - {label: 'Meta Description', name: 'description', widget: 'string', required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags",  widget: select, options: ['Products', 'Engineering', 'Customers', 'empathy.co', 'News', 'Retail', 'Insights', 'Search', 'UX'], multiple: true}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}


```
