### ISSUE TITLE
Cannot complete image selection workflow

### ISSUE THREAD

**Issue by j00bar** [netlify/netlify-cms#3701]
When trying to choose an image to add to a markdown field, after selecting the image from the Images dialog, even though "Choose selected" appears to be active, it does not hint with the cursor that it is clickable and clicking it does nothing. The "Delete selected" button does work as advertised, but not the "Choose selected".

**To Reproduce**
1. Edit a document with a markdown field.
2. In the markdown field, from the RTE, select the + and choose Image.
3. In the resulting rich text widget for image/alt-text/title entry, click "Choose an image"
4. In the modal that comes up titled "Image", select an image and watch the "Choose selected" button go from grey to green.
5. Click the "Choose selected" button.

**Expected behavior**
I expect the modal dialog to close and the RTE widget to indicate the image selected. Instead, nothing happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/166664/81015594-f34f7f00-8e2c-11ea-9aa8-fb3d0f6588e1.png)

**Applicable Versions:**

  - netlify-cms-app 2.12.12
  - netlify-cms-core 2.26.0
  - netlify-cms 2.10.48
 - GitHub
 - OS: Fedora 32
 - Browser version: Chrome 81.0.4044.129 (Official Build) (64-bit)

**CMS configuration**
```
backend:
  name: github
  branch: master
  repo: j00bar/platform-docs
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "root"
    label: "Docs root"
    folder: "content/docs"
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
  - name: "intro"
    label: "Introduction"
    folder: "content/docs/intro"
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
```

**Additional information**

I'm a total netlify-cms n00b and am probably doing something stupid.
