### ISSUE TITLE
Date and datetime persisted values may not conform to specified format

### ISSUE THREAD

**Issue by guillett** [netlify/netlify-cms#3702]
Hi folks many thanks for your great work.

**Describe the bug**

Date and datetime can be improperly persisted.

**To Reproduce**
- Add the following section to a config file
```yaml
  - name: test
    label: Tests
    create: true
    folder: "content/_tests"
    fields:
      - name: title
        widget: string
      - name: date
        widget: date
        format: YYYY-MM-DD
        dateFormat: YYYY-MM-DD
        default: ''
      - name: datetime
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: false
        default: ''
```
- Create a new entry with title and dates (pick 2020-05-06 for dates)
- Persist entry
- Check persisted data, it is OK (values in the file are `2020-05-06`)
- Refresh admin site
- Update title **only**
- Save
- Check persisted data  (values in the file are now **`2020-05-07T00:00:00.000Z`**)

**Applicable Versions:**
```
netlify-cms-app 2.12.12 index.js:25:12
netlify-cms-core 2.26.0 bootstrap.js:83:12
netlify-cms 2.10.48 index.js:27:12
```

**CMS configuration**

https://github.com/betagouv/beta.gouv.fr/blob/master/admin/config.yml

https://github.com/betagouv/beta.gouv.fr/

**Additional context**

In my specific context, I found a hack to prevent that inappropriate behavior.

```js
    var fixDateSerialization = {
      deserialize: function() {
        throw 'Not implemented' // Not used, deserialize is never called
      },
      serialize: function(value) {
        // Hack to ensure only the date part is persisted
        // Force format to YYYY-MM-DD
        return CMS.moment(value).format('YYYY-MM-DD')
      }
    }
    CMS.registerWidgetValueSerializer('date', fixDateSerialization)
```
