### ISSUE TITLE
{{media_folder}} {{public_folder}} incorrect behaviour?

### ISSUE THREAD

**Issue by codenitpicker** [netlify/netlify-cms#3706]
**Describe the bug**
I am using the new [Collections Media and Public Folder](https://www.netlifycms.org/docs/beta-features/#folder-collections-media-and-public-folder) to create posts with the following path structure:
```yaml
path: '{{slug}}/index'
```

I know that this will default the media_folder and public_folder to an empty string
```yaml
media_folder: '' 
public_folder: ''
```
This allows for images to be stored with posts in the same folder. 
```
src
  pages
    services
      service-1
        index.md
        test.jpg
```
However I would like to retain the previous default behaviour so I have a config file that looks like this:

```yaml
backend:
  name: git-gateway
  branch: master

local_backend: true 
publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "services"
    label: "Services"
    label_singular: 'Service'
    folder: "src/pages/services"
    filter: {field: "template", value: "service"}
    create: true
    path: '{{slug}}/index'
    slug: '{{slug}}'
    media_folder: '{{media_folder}}'
    public_folder: '{{public_folder}}'
```
Unfortunately this is what is created:
```
src
  pages
    services
      service-1
        static
          img
            test.jpg
        index.md
```
Is this a bug or is there anyway to keep the `path: '{{slug}}/index'` functionality while still retaining the original default location for the media folder of `static/img`?

**Applicable Versions:**
- netlify-cms-app 2.12.12
- netlify-cms-core 2.26.0
- Generator: Gatsby
