### ISSUE TITLE
Add summary option to list widget

### ISSUE THREAD

**Issue by magomimmo** [netlify/netlify-cms#3713]
**Is your feature request related to a problem? Please describe.**

When defining a file collection you generally target a file to be populated of elements (i.e. `allow_add: true`) or to read from (i.e. `allow_add: false`). Say you define the following `people` file collection inside a `editables` files collection:

```yaml
collections:
  - label: Editable Lookups
    name: editables
    files:
      - label: People
        name: people
        file: data/people.json
        fields:
          - label: People
            label_singular: person
            allow_add: true
            name: people
            widget: list
            fields:
              - label: Last
                name: last
                widget: string
              - label: First
                name: first
                widget: string
``` 

You then add few persons and your `people.json` file get populated something like this:

```json
{
  "people": [
    {
      "last": "Smith",
      "first": "Bob"
    },
    {
      "last": "Smith",
      "first": "Fred"
    },
    {
      "last": "Smith",
      "first": "Mary"
    }
  ]
}
```

In the UI visualizing people elements you can't distinguish between people with the same lastname.

![summary-feature](https://user-images.githubusercontent.com/1448905/81278863-8fa89a00-9056-11ea-9f29-66384ec03e1b.png)

**Describe the solution you'd like**

Add a `summary` option to `list` widget:

```yaml
# ....
          - label: People
            label_singular: person
            allow_add: true
            summary: '{{last}}, {{first}}' # <- summary option
            name: people
            widget: list
            fields:
              - label: Last
                name: last
                widget: string
              - label: First
                name: first
                widget: string
```

**Describe alternatives you've considered**

I don't know alternatives

**Additional context**

This new features will be a game saver in the contest of folder to file collection relationships (e.g. `ncw-file-relation` by @d4rekanguok ).
