### ISSUE TITLE
Markdown Widget editor components => "code-block" => removing new lines.

### ISSUE THREAD

**Issue by furcan** [netlify/netlify-cms#3722]
Hi,
Firstly thanks for this great CMS.

**Describe the bug**
1- When we create a post using the "code-block" editor component in the Markdown Widget; it is removing every new line in the "code-block" component when we have been save the file (MD file).

2- Also, when we have been creating or update a post using the "code-block" component on CMS; the "enter" key for the new line is not working properly for this component.

**To Reproduce**
1. Go to any Post(etc.) (It already has been created or create a new one.)
2. Click on "code-block" component. (Of course, the widget should be a Markdown widget.)
3. Type some text into it.
4. Save the Post. (or switch the Rich Text button to Markdown)
5. Then, please check the MD file to see removed lines.

---

**Expected behavior**
Not remove the new lines in the "code-block" component as expected (WYSIWYG).

---

**Screenshots**
1- Create or Update a post
<img width="805" alt="Screen Shot 2020-05-08 at 11 23 31" src="https://user-images.githubusercontent.com/49978011/81388556-1d50bc00-9121-11ea-9939-94dccd889c9f.png">

2a- Switch from Rich Text to Markdown
<img width="704" alt="Screen Shot 2020-05-08 at 11 26 03" src="https://user-images.githubusercontent.com/49978011/81388580-26da2400-9121-11ea-8d9a-3815b8c63c21.png">

2b- Or save changes to MD
<img width="1016" alt="Screen Shot 2020-05-08 at 11 26 59" src="https://user-images.githubusercontent.com/49978011/81387734-d7dfbf00-911f-11ea-8f50-28cb0a7f2565.png">

---

**Applicable Versions:**
 - Netlify CMS version: 2.9.7
 - Git provider: GitHub
 - OS: MacOS
 - Browser version: Chrome Version 81.0.4044.129 (Official Build) (64-bit)

**CMS configuration**

  ```
  - label: "YYY"
    name: "yyy"
    folder: "xxx/yyy"
    create: true
    delete: false
    identifier_field: zzz
    fields:
      - {.........}
      - { required: true, label: "Content", name: "body", widget: "markdown", buttons: ["bold","italic","link","code-block","quote","bulleted-list","numbered-list","heading-two","heading-three","heading-four"], hint: "Content of this YYY", }

```
