### ISSUE TITLE
Markdown Widget "code-block" component => "Field Settings" => "MODE" => "codemirror/..." Cannot find module.

### ISSUE THREAD

**Issue by furcan** [netlify/netlify-cms#3725]
Hi,

I just updated Netlify CMS from `v2.9.7` to `v2.10.48` to resolve this issue: #3722 

But I have another issue on Markdown Widget "code-block" component. 

**Describe the bug**
When I try to select a "mode" from "Field Settings" using the "code-block" component I am getting an error as below. (Screenshots)

**To Reproduce**
1. Go to a Markdown Widget and select a "code-block" component.
2. Click to "Settings" icon. (right-top)
3. Select a "MODE" from this "Field Settings" modal.
4. Look at the console.

**Expected behavior**
Maybe a preview as highlighted for this component but have to add the language code to file => e.g. ` ```js `

**Screenshots**
1- Select a Language
<img width="770" alt="Screen Shot 2020-05-08 at 16 08 31" src="https://user-images.githubusercontent.com/49978011/81408599-36b82f00-9146-11ea-967d-61292902ce30.png">

2- Console
<img width="702" alt="Screen Shot 2020-05-08 at 15 44 48" src="https://user-images.githubusercontent.com/49978011/81408457-f3f65700-9145-11ea-8305-a33b243bea91.png">

---

**Applicable Versions:**
 - Netlify CMS version: 2.10.48
 - Git provider: GitHub
 - OS: MacOS
 - Browser version: Chrome Version 81.0.4044.129 (Official Build) (64-bit)

**CMS configuration**

  ```
  - label: "YYY"
    name: "yyy"
    folder: "xxx/yyy"
    create: true
    delete: false
    identifier_field: zzz
    fields:
      - {.........}
      - { required: true, label: "Content", name: "body", widget: "markdown", buttons: ["bold","italic","link","code-block","quote","bulleted-list","numbered-list","heading-two","heading-three","heading-four"], hint: "Content of this YYY", }

```
