### ISSUE TITLE
TypeError: e.join is not a function. (In 'e.join(",")', 'e.join' is undefined)

### ISSUE THREAD

**Issue by gizipp** [netlify/netlify-cms#3742]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.48`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (iPad; CPU OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/80.0.3987.95 Mobile/15E148 Safari/604.1`

**CMS configuration**
```
publish_mode: editorial_workflow
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: github
  repo: gizipp/blog.gizipp.com
  branch: master
media_folder: img/uploads
collections:
  - meta: null
    name: post
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: _posts
    publish: true
    sortableFields:
      - commit_date
      - title
      - commit_author
    label: Post
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
        tagname: h1
      - label: Description
        name: desc
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: Category
        name: category
        widget: list
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Last Modifed At
        name: last_modified_at
        widget: date
        format: YYYY-MM-DD
    create: true
    sort: last_modified_at:asc
public_folder: /img/uploads

```

**Additional context**
