### ISSUE TITLE
Slow rendering in CMS

### ISSUE THREAD

**Issue by emp3ror** [netlify/netlify-cms#3752]
I have file which has a array of objects created from config.yml, the array length reached 46, now when rendering it on cms, it is slow. Here is snippet of my config.yml

```
- name: 'widgets'
    label: 'Widgets'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'hello1'
        label: 'hi hello'
        file: 'data/widgets/items.json'
        description: 'hello items'
        fields:
          - name: 'items'
            label: 'items'
            description: 'Add items'
            widget: 'list'
            fields:
              - { label: "Title", name: 'title', widget: 'string', hint: 'Title'}
              - { label: "Description", name: 'desc', widget: 'markdown', hint: 'Add description'}
              - { label: "URL", name: 'url', widget: 'string', hint: 'url', required: false}
              - name: img
                label: "Add images"
                widget: 'image'
              - { label: "Company Name", name: 'company', widget: 'string', hint: 'Title'}
              - label: "Price"
                name: "price"
                required: true
                widget: "select"
                options: ["Purchase", "Free trial","Free"]
              - label: "Client type"
                name: "plan"
                required: true
                widget: "select"
                multiple: true
                options: ["xyz","xyz"]
              - label: "tags"
                name: "tags"
                widget: relation
                collection: data_tags
                searchFields: ["title"]
                valueField: "title"
                displayFields: ["title"]
                required: true
                multiple: true
```
