### ISSUE TITLE
Getting error and losing progress when trying to save a post because token has expired (Bitbucket)

### ISSUE THREAD

**Issue by PedroOndh** [netlify/netlify-cms#3779]
**Describe the bug**
I have a web on Jekyll and hosted on Bitbucket. Sometimes when an user has been working for some time on the CMS and tries to save a post saving fails and return the message "Failed to persist entry: You must specify a provider and refresh token when calling netlify.refresh"

**To Reproduce**
1. Use CMS for some time
2. Try to save an entry
3. Get error
4. Entry is not saved, progress is lost

**Expected behavior**
Post saving, not error appearing

**Screenshots**
![image](https://user-images.githubusercontent.com/45435602/82221627-8950d280-9920-11ea-9e2c-8da7ac4c6740.png)

**Applicable Versions:**
 - Netlify CMS version: 2.10.48
 - Git provider: BitBucket
 - OS: macOS Catalina 10.15.4
 - Browser version: observed on Chrome

**CMS configuration**

```
backend:
  name: bitbucket
  repo: xxxxxx/xxx-jekyll-cms # Path to your Bitbucket repository
  branch: develop
  auth_type: implicit
  app_id: 6DxxxxxxxxC7RXhdL
  #base_url: http://localhost:3000

# for using local backend run "npx netlify-cms-proxy-server" and enter in /admin
local_backend: true

publish_mode: editorial_workflow
media_folder: "assets/media/uploads"
logo_url: https://www.xxxxx.co/assets/media/logo/logo-animated.gif
display_url: https://xxxxx.co

collections:
[...]
```
