### ISSUE TITLE
Editorial Workflow: Failed to persist entry: TypeError: r.has is not a function

### ISSUE THREAD

**Issue by franva** [netlify/netlify-cms#3795]
**Describe the bug**

I recently enabled Editorial Workflow on my blog by following [this link](https://www.netlifycms.org/docs/configuration-options/#publish-mode), once it's done, whenever I clicked the Save button on "Writing in Blog Collection" page, it throws an error:

> Failed to persist entry: TypeError: r.has is not a function
Here is the screenshot
![image](https://user-images.githubusercontent.com/5151146/82622835-17c79b80-9c22-11ea-8f23-9a59d61ecee9.png)

Also, the Big Green Publish button disappeared as well.

**To Reproduce**

Steps to reproduce the behavior. For example:
1. Go to the Publish Mode on [this page](https://www.netlifycms.org/docs/configuration-options/#publish-mode)
2. Add the `publish_mode: editorial_workflow` into your /admin/config.yml
3. Deploy to the live website
4. Go to the admin page of your website
![image](https://user-images.githubusercontent.com/5151146/82623217-f9ae6b00-9c22-11ea-99e2-83cd5f60e851.png)

5. Click the **New Blog** button
6. type anything in the new article 
7. click **Save** button
8. you will see the error message

Here is my Github Repository for my blog:
https://github.com/franva/askwinston

**Expected behavior**

I am expecting my blog is saved as a draft but not published.

**Screenshots**

![image](https://user-images.githubusercontent.com/5151146/82622835-17c79b80-9c22-11ea-8f23-9a59d61ecee9.png)

**Applicable Versions:**

 - Netlify CMS version: 2.9.6  # "netlify-cms-app": "^2.9.6",
 - netlify-cms-core 2.22.1
 - netlify-cms-app 2.11.31
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version Firefox 76.0.1 (64-bit)

 - Node.JS version: v12.14.1

**CMS configuration**
See my cms config in my [Github ](https://github.com/franva/askwinston/blob/master/static/admin/config.yml)
or here
```
backend:
  name: git-gateway
  branch: master
  repo: franva/askwinston

  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
local_backend: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Description, name: description, widget: text}]}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
```
