### ISSUE TITLE
TypeError: e.get is not a function

### ISSUE THREAD

**Issue by akaelisee** [netlify/netlify-cms#3797]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.9`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: github
  repo: akaelisee/app-stack
media_folder: static/assets
public_folder: /assets
collections:
  - name: Chaussures
    label: Chaussure
    folder: Collections/Chaussures
    create: true
    fields:
      - name: title
        required: true
        label: Titre
      - name: price
        required: true
        label: Prix
      - name: description
        required: true
        label: Description
        widget: markdown
      - name: image
        required: true
        label: Image
        widget: image
      - name: path
        required: false
        label: Path
      - name: size
        required: true
        label: Taille
      - label: Taille
        name: size
        widget: list
        fields:
          - label: taille 1
            name: s
            widget: string
    publish: true
    sortableFields:
      - commit_date
      - title
      - commit_author
      - description
  - name: blog
    label: Article
    folder: articles
    create: true
    fields:
      - name: title
        required: true
        label: Titre
      - name: price
        required: true
        label: Prix
      - name: description
        required: true
        label: Description
        widget: markdown
      - name: image
        required: true
        label: Image
        widget: image
      - label: City
        name: airport-code
        widget: object
        fields:
          - label: Address
            name: address
            widget: object
            collapsed: true
            fields:
              - label: Street Address
                name: street
                widget: string
              - label: City
                name: city
                widget: string
              - label: Postal Code
                name: post-code
                widget: string
    publish: true
    sortableFields:
      - commit_date
      - title
      - commit_author
      - description

```

**Additional context**

**Comment by HeyITGuyFixIt** [comment]
Can you post the full error? If this was a pop-up error message, can you check your browser's console for the full error and post it here?

**Comment by d4rekanguok** [comment]
Hey @akaelisee, in addition to @HeyITGuyFixIt comment above, could you describe how this error occur (on CMS startup, on publishing, etc.)? Reproducible steps will be very helpful.

**Comment by erezrokah** [comment]
Hi @akaelisee, the `config.yml` you posted has two fields which the same name:

```
- name: size
  required: true
  label: Taille
- label: Taille
  name: size
  widget: list
  fields:
    - label: taille 1
      name: s
      widget: string
```

Can you please rename one of them and try again? Closing this per more information
