### ISSUE TITLE
Removing all values from the list with empty array as default value results in array of one empty string

### ISSUE THREAD

**Issue by smashercosmo** [netlify/netlify-cms#3807]
**Describe the bug**
When list widget has empty array as default value, removing all values from it results in array of one empty string

**To Reproduce**
```yaml
  - label: Posts
    label_singular: post
    name: post
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Tags, name: tags, widget: list, allow_add: true, required: false, default: []}
      - {label: Body, name: body, widget: markdown}
```
1. Create new post
2. Don't fill the tags input
3. Publish post
4. Check the data
```md
---
title: Test
tags: []
---
test
``` 
5. Edit post by adding one tag
6. Publish and check the data
```md
---
title: Test
tags:
 - tag
---
test
``` 
5. Edit post by removing this tag
6. Publish and check the data
```md
---
title: Test
tags:
 - ""
---
test
``` 

**Expected behavior**
After removing all tags data should be the following
```md
---
title: Test
tags: []
---
test
```
