### ISSUE TITLE
Custom editor component: Markdown widget is not rendered in preview

### ISSUE THREAD

**Issue by axeleroy** [netlify/netlify-cms#3809]
**Describe the bug**
I created a new Editor Component with a title and a Markdown body.
After text has been styled, the preview displays the Markdown un-rendered.

**To Reproduce**
1. Register the following widget in `admin/index.html`
```js
CMS.registerEditorComponent({
    id: "tab",
    label: "Tab",
    fields: [
        {name: 'title', label: 'Title', widget: 'string'},
        {name: 'content', label: 'Content', widget: 'markdown'}
    ],
    pattern: /\[tab title="([^\]]*)"\]((.|\n)*)\[\/tab[^s\]]*\]/,
    fromBlock: function(match) {
        return {
            title: match[1],
            content: match[2]
        }
    },
    toBlock: function(obj) {
        return '[tab title=\"' + obj.title + '\"]\n' + obj.content + "\n[/tab]";
    },
    toPreview: function(obj) {
        return (
             obj.content
        );
    }
});
```
2. Log into CMS
3. Create new entry
4. Add Tab widget
5. Fill title and content of the widget

**Expected behavior**
The content of the widget is previewed with the markdown rendered in HTML.

**Screenshots**
![image](https://user-images.githubusercontent.com/3141536/82831895-eff26500-9eb9-11ea-8a30-d26f8b987b14.png)

**Applicable Versions:**

 - Netlify CMS version: 2.10.49
 - Git provider: GitHub, test-repo
 - OS: Ubuntu 18.04
 - Browser version Firefox 76.0.1, Chrome 81

**CMS configuration**
```yaml
backend:
  name: test-repo
locale: 'fr'
media_folder: "assets/uploads"
publish_mode: editorial_workflow
site_url: https://assomip.fr
logo_url: /assets/img/logo.png
collections:
  - name: "articles"
    label: "Articles"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "posts"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {
          label: "Catégories",
          name: "categories",
          widget: "relation",
          collection: "categories",
          displayFields: ["title"],
          searchFields: ["title"],
          valueField: "category",
          multiple: true,
          default: ["Evènements"]
        }
      - {label: "Corps", name: "body", widget: "markdown"}
      - {label: "Date et heure et l'évenement", name: "eventdate", widget: "datetime", required: false}
      - {label: "Informations sur l'évenement", name: "eventcard", widget: "event-card", required: false}
  - name: "categories"
    label: "Catégories"
    folder: "_category"
    create: true
    editor:
      preview: false
    slug: "{{title}}"
    preview_path: "category/{{slug}}"
    fields:
      - {label: "Titre", name: "title", "widget": "string"}
      - {label: "Nom", name: "category", "widget": "string"}
  - name: "pages"
    label: "Pages"
    folder: "_pages/"
    create: true
    slug: "{{title}}"
    preview_path: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "pages"}
      - {label: "Titre", name: "title", widget: "string"}
      - {
        label: "Priorité",
        hint: "Les pages avec la valeur la plus élevée seront affichées en premier dans le menu",
        name: "priority",
        widget: "number",
        valueType: "int",
        min: 0,
        max: 9,
        default: 0
      }
      - {label: "Corps", name: "body", widget: "markdown"}
  - name: "about"
    label: "À Propos"
    folder: "_about/"
    create: true
    slug: "{{title}}"
    preview_path: "a-propos/{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "pages"}
      - {label: "Titre", name: "title", widget: "string"}
      - {
        label: "Priorité",
        hint: "Les pages avec la valeur la plus élevée seront affichées en premier dans le menu",
        name: "priority",
        widget: "number",
        valueType: "int",
        min: 0,
        max: 9,
        default: 0
      }
      - {label: "Corps", name: "body", widget: "markdown"}
```
