### ISSUE TITLE
relation widget performances

### ISSUE THREAD

**Issue by magomimmo** [netlify/netlify-cms#3810]
**Describe the bug**
I switched from `ncw-file-relation` widget to the latest `relation` widget that has been recently extended to support folder to file collections relationship. Before the switch the performances were acceptable even with big JSON files. The new `relation` widget, instead, stays in waiting state forever. 
**To Reproduce**
1. Take a json file (e.g. `data/cities.json`), representing all the italian municipalities (almost 8,000) with an `id` and a `name` keys.
 
2. Define a file and a folder collections like the following:

```yaml
collections
  - label: lookups
    name: lookups
    files:
      - label: cities
        name: cities
        file: data/cities.json
        fields:
          - label: cities
            label_singular: city
            name: cities
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: id
                name: id
                widget: hidden
  - label: Folder Collection 
    name: folder_collection
    folder: content/folder_collection
    create: true
    identifier_field: id
    slug: '{{city}}'
    summary: '{{city}}'
    editor:
      preview: false
    fields:

      - label: id
        name: id
        widget: ncw-id

      - label: City
        name: city
        widget: relation
        collection: lookups
        file: cities
        searchFields: ['cities.*.name']
        displayFields: ['cities.*.name']
        valueField: cities.*.name
```
3. Create a new entry for the folder collection
4. you'll wait forever (the browser tab does not respond anymore)

**Expected behavior**

The same folder to file relationship, mutatis mutandis, implemented by using `ncw-file-relation` widget works like a charm

**Applicable Versions:**

 - netlify-cms-app 2.12.13
 - Git provider:GitHub
 - OS: Ubuntu 18.04
 - Browser version: chrome Version 83.0.4103.61 (Official Build) (64-bit)

**CMS configuration**

See above

**Additional context**

I suspect the `relation` widget has the same performance issue with folder to folder collections relationship, because I experience a very slow response time with not such a large number of entries in the referenced folder collection. 

@d4rekanguok (I added you here because you are the author of the `ncw-file-relation` widget and you collaborated a lot in adsorbing its features in the  latest `relation` widget.

[cities.zip](https://github.com/netlify/netlify-cms/files/4678461/cities.zip)
