### ISSUE TITLE
setting title field as relation causes entry titles not to appear

### ISSUE THREAD

**Issue by cdeath** [netlify/netlify-cms#3829]
**Describe the bug**

setting title field as relation causes entry titles not to appear.

**To Reproduce**

```
- name: "portfolio"
  label: "Portfolio"
  label_singular: "Investment"
  folder: "collections/_portfolio"
   create: true
  editor:
    preview: false
  fields:
    - {name: "title", label: "Title", widget: "relation", collection: "organizations", displayFields: ["title"], searchFields: ["title"], valueField: "title"}
```

**Expected behavior**

entry titles should appear, as there is no difference in the frontmatter formatting when the relation is not multiple.

**Screenshots**

![image](https://user-images.githubusercontent.com/17791147/83145862-5e6b3900-a0ed-11ea-841d-cb1cf1a76408.png)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

`https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js`

**CMS configuration**

**Additional context**

the entry itself works fine.

![image](https://user-images.githubusercontent.com/17791147/83147056-12b98f00-a0ef-11ea-9822-8bbe2850c34a.png)
