### ISSUE TITLE
TypeError: r.toJS is not a function

### ISSUE THREAD

**Issue by jkester1986** [netlify/netlify-cms#3831]
**Describe the bug**
Tried to open a page under our Admin Dashboard collection for editing, got the error in the title. Happens for all pages under this collection. Other collections are unaffected.

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.49`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: github
  repo: ZimbraOS/zm-cloudsuite-support
media_folder: src/assets/img
public_folder: assets/img
collections:
  - name: pages
    label: Pages
    extension: json
    files:
      - label: Home
        name: home
        file: content/home.json
        fields:
          - label: Title
            name: title
            widget: string
          - label: Publish Date
            name: date
            widget: datetime
          - label: Body
            name: body
            widget: markdown
          - label: Contact Support Headline
            name: contactSupportHeadline
            widget: string
            required: false
          - label: Contact Support Text
            name: contactSupportText
            widget: text
            required: false
          - label: Contact Support Button
            name: contactSupportButton
            widget: string
            required: false
      - label: Config
        name: config
        extension: json
        file: src/config.json
        fields:
          - label: MetaData
            name: metadata
            widget: object
            fields:
              - label: Site Name
                name: siteName
                widget: string
              - label: Base Url
                name: baseUrl
                widget: hidden
                default: https://support.zimbracloudsuite.com
              - label: Twitter Card
                name: twitterCard
                widget: string
    publish: true
    sortableFields:
      - commit_date
      - commit_author
  - name: integrations
    label: Integrations
    folder: content/integrations
    extension: json
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Logo
        name: logo
        widget: image
        default: assets/img/cloudsuite-icon.svg
      - label: Short Description
        name: shortDescription
        widget: text
        default: CloudSuite Integration
      - label: Body
        name: body
        widget: markdown
    publish: true
    sortableFields:
      - commit_date
      - title
      - date
      - commit_author
      - shortDescription
  - name: admin-dashboard
    label: Admin Dashboard
    folder: content/admin-dashboard
    extension: json
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
      - label: Short Description
        name: shortDescription
        widget: text
        default: CloudSuite Integration
      - label: Icon
        name: icon
        widget: relation
        collection: icons
        searchFields:
          - title
          - class
        valueField: class
        displayFields: title
    publish: true
    sortableFields:
      - commit_date
      - title
      - date
      - commit_author
      - shortDescription
  - name: icons
    label: Icons
    folder: content/icons
    extension: json
    create: true
    fields:
      - label: Type
        name: title
        widget: string
      - label: Class
        name: class
        widget: string
    publish: true
    sortableFields:
      - commit_date
      - title
      - commit_author

```

**Additional context**
