### ISSUE TITLE
TypeError: e.join is not a function

### ISSUE THREAD

**Issue by lukeocodes** [netlify/netlify-cms#3848]
**Describe the bug**

When I try to open an existing post inside CMS, I get met with the following error.

![image](https://user-images.githubusercontent.com/956290/83535391-d10f5680-a4e9-11ea-9b75-90cd4f324e16.png)

**To Reproduce**

- Login
- Click on any existing published post to edit it
- Get error

**Expected behavior**

- Login
- Click on any existing published post to edit it
- Get edit screen

**Screenshots**

![image](https://user-images.githubusercontent.com/956290/83535391-d10f5680-a4e9-11ea-9b75-90cd4f324e16.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.50`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36`

**CMS configuration**
```
publish_mode: editorial_workflow
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
  branch: master
media_folder: static/content/images/
public_folder: /content/images/
collections:
  - view_filters: []
    public_folder: /content/blog/{{slug}}/
    media_folder: ../../static/content/blog/{{slug}}/
    name: blog
    slug: "{{slug}}"
    editor:
      preview: false
    folder: content/blog
    publish: true
    sortableFields:
      - commit_date
      - title
      - author
      - description
    label: Blog
    format: frontmatter
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Featured Image
        name: thumbnail
        widget: image
        allow_multiple: false
      - label: Author
        name: author
        widget: string
      - label: Published
        name: published
        widget: boolean
        default: true
      - label: Published At
        name: published_at
        widget: datetime
      - label: Category
        name: category
        widget: list
        default:
          - new-starter
          - release
          - tutorial
      - label: Tags
        name: tags
        widget: list
      - label: Body
        name: body
        widget: markdown
    create: true
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - label: Authors
        name: authors
        file: content/authors.json
        fields:
          - label: Authors
            name: authors
            identifier_field: username
            widget: list
            fields:
              - label: Username
                name: username
                widget: string
              - label: Spotlight
                name: spotlight
                widget: boolean
                default: false
              - label: Title
                name: title
                widget: string
              - label: Name
                name: name
                widget: string
              - label: Bio
                name: bio
                widget: text
              - label: User Image
                name: image_url
                widget: image
                allow_multiple: false
              - label: Email
                name: email
                widget: string
              - label: Twitter *Username*
                name: twitter
                widget: string
              - label: Facebook Url
                name: facebook_url
                widget: string
              - label: GitHub Url
                name: github_url
                widget: string
              - label: StackOverflow Url
                name: stackoverflow_url
                widget: string
              - label: LinkedIn Url
                name: linkedin_url
                widget: string
              - label: Twitch Url
                name: twitch_url
                widget: string
              - label: YouTube Url
                name: youtube_url
                widget: string
              - label: Website Url
                name: website_url
                widget: string
    publish: true
    sortableFields:
      - commit_date
      - commit_author
    view_filters: []

```

**Additional context**
