### ISSUE TITLE
Loading editor is very slow (≥10 seconds)

### ISSUE THREAD

**Issue by JohJonker** [netlify/netlify-cms#3880]
**Describe the bug**
Clicking an item in the list view and opening the editor is slow (≥10 seconds). Looking at the Chrome DevTools network request, I can see that around 25 requests are being sent, many of which seem to be unrelated to the current item.

Context:
- I have 4 collections, with ±530, ±80, ±10 and ±10 items, respectively;
- In the one collection I have three relation widgets (see below), but no relation widgets in the others three. All of them are slow, though the one with relation widgets sometimes seems a little slower (which I assume is to be expected; I'm also aware of #3810, but that seems like an issue mainly _after_ the editor has loaded);
- I'm using the `use_graphql: true` flag (I added this yesterday to see if it would help, but I had the same issue without it);
- I am based in South Africa. I assume the long round trips to the GitHub API (which has no endpoint in Europe or Africa, as far as I could discern) compounds the issue, but it seems there is something more to this.

**To Reproduce**
1. Open Chrome DevTools
2. Go to collection list view
3. Click item title in list view
4. See loading taking long and watch requests in Chrome DevTools.

**Expected behavior**
Loading should be quick. Not sure whether there should be fewer requests, or whether this is normal?

**Screenshots**
Please see the GIF recording below. It's slightly cropped for privacy.
![ezgif-4-ff1a8b406f8b](https://user-images.githubusercontent.com/4933686/84164611-4044f780-aa62-11ea-9914-bf0dff7b719a.gif)

**Applicable Versions:**
 - Netlify CMS version: netlify-cms-app 2.12.12 / netlify-cms-core 2.26.0
 - Git provider: GitHub
 - OS: MacOS 10.15.4, although I've also encountered this on a colleague's Windows/Chrome setup
 - Browser version: Chrome 83.0.4103.97

**CMS configuration**
```
publish_mode: editorial_workflow
site_id: XXXX
site_url: XXXX
logo_url: XXXX
media_folder: "content/images"
public_folder: "/images"
backend:
  name: github
  repo: XXXX
  base_url: XXXX
  auth_endpoint: /oauth/auth
  squash_merges: true
  use_graphql: true

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    media_folder: ""
    public_folder: ""
    preview_path: "/xxxxx/{{slug}}"
    editor:
      preview: false
    sortableFields: ["commit_date", "date", "title", "category"]
    fields:
      - label: Thumbnail
        name: thumbnail
        required: true
        widget: image
        hint: ""
        default: ""
        allow_multiple: false
      - label: Title
        name: title
        required: true
        widget: string
        hint: ""
        default: ""
      - label: Date
        name: date
        required: true
        widget: datetime
        hint: ""
        format: YYYY-MM-DDTHH:mm:ssZZ
        dateFormat: "DD/MM/YYYY"
        timeFormat: "HH:mm"
      - label: Category
        name: category
        required: true
        widget: select
        hint: ""
        default: ""
        options:
          [3 options]
        multiple: ""
      - label: "Scholar authors"
        name: "scholars"
        widget: "relation"
        collection: "scholars"
        searchFields: ["title"]
        valueField: "{{slug}}"
        displayFields: ["{{title}} (Class of {{cohort}})"]
        multiple: true
        required: false
      - label: "Staff authors"
        name: "staff"
        widget: "relation"
        collection: "staff"
        searchFields: ["title"]
        valueField: "{{slug}}"
        displayFields: ["{{title}}"]
        multiple: true
        required: false
      - label: "Trustee authors"
        name: "trustees"
        widget: "relation"
        collection: "trustees"
        searchFields: ["title"]
        valueField: "{{slug}}"
        displayFields: ["{{title}}"]
        multiple: true
        required: false
      - label: Body text
        name: body
        required: false
        widget: markdown
        hint: ""
        default: ""
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
  - name: scholars
    label: Scholars
    folder: content/scholars
    create: true
    media_folder: ""
    public_folder: ""
    editor:
      preview: false
    preview_path: "/xxxx/yyyy/{{slug}}/"
    summary: "{{title}} (Class of {{cohort}})"
    sortableFields: ["commit_date", "title", "commit_author", "cohort"]
    fields:
      - label: Thumbnail
        name: thumbnail
        required: true
        widget: image
        hint: ""
        default: ""
        allow_multiple: false
      - label: Title
        name: title
        required: true
        widget: string
        hint: ""
        default: ""
      - label: Cohort
        name: cohort
        required: true
        widget: select
        hint: ""
        default: ""
        options:
          - "AAA"
          - "BBB"
          - ...about 20 options
        multiple: ""
      - label: Country
        name: country
        required: true
        widget: select
        hint: ""
        default: ""
        options:
          - "AAA"
          - "BBB"
          - ...about 50 options
        multiple: ""
      - label: Institution
        name: institution
        required: false
        widget: select
        hint: ""
        default: ""
        options:
          - "AAA"
          - "BBB"
          - ...about 20 options
        multiple: ""
      - label: Degree
        name: degree
        required: false
        widget: string
        hint: ""
        default: ""
      - label: Body text
        name: body
        required: false
        widget: markdown
        hint: ""
        default: ""
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
  - name: staff
    label: Staff
    folder: content/staff
    create: true
    media_folder: ""
    public_folder: ""
    editor:
      preview: false
    preview_path: "/xxxx/yyyy/{{slug}}/"
    fields:
      - label: Thumbnail
        name: thumbnail
        required: true
        widget: image
        hint: ""
        default: ""
        allow_multiple: false
      - label: Title
        name: title
        required: true
        widget: string
        hint: ""
        default: ""
      - label: Position
        name: position
        required: true
        widget: string
        hint: ""
        default: ""
      - label: Order
        name: order
        required: true
        widget: number
        hint: ""
        default: ""
        valueType: int
        min: "1"
        max: "99"
        step: 1
      - label: Body text
        name: body
        required: false
        widget: markdown
        hint: ""
        default: ""
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
  - name: trustees
    label: Trustees
    folder: content/trustees
    create: true
    media_folder: ""
    public_folder: ""
    editor:
      preview: false
    preview_path: "/xxxx/yyyyy/{{slug}}/"
    fields:
      - label: Thumbnail
        name: thumbnail
        required: true
        widget: image
        hint: ""
        default: ""
        allow_multiple: false
      - label: Title
        name: title
        required: true
        widget: string
        hint: ""
        default: ""
      - label: Order
        name: order
        required: true
        widget: number
        hint: ""
        default: ""
        valueType: int
        min: "1"
        max: "99"
        step: 1
      - label: Nominee
        name: nominee
        required: true
        widget: select
        hint: ""
        default: ""
        options:
          - "AAA"
          - "BBB"
      - label: Body text
        name: body
        required: false
        widget: markdown
        hint: ""
        default: ""
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
```

**Additional context**
