### ISSUE TITLE
TypeError: e.join is not a function

### ISSUE THREAD

**Issue by zuoridangnian** [netlify/netlify-cms#3886]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.50`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
collections:
  - view_filters: []
    name: blog
    slug: "{{slug}}"
    editor:
      preview: false
    folder: content/blog
    publish: true
    sortableFields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    label: Blog
    fields:
      - label: 标题
        name: title
        widget: string
      - label: 发布日期
        name: date
        widget: datetime
      - label: 描述
        name: description
        widget: string
      - label: 特色图片
        name: featured_image
        widget: image
      - label: 分类
        name: category
        widget: string
      - label: 标签
        name: tags
        widget: list
      - label: 内容
        name: body
        widget: markdown
    create: true

```

**Additional context**
