### ISSUE TITLE
Failed to persist entry: TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by mattortiz** [netlify/netlify-cms#3901]
**Describe the bug**

I've deployed a GatsbyJS site with the Netlify CMS at envyforge.com/admin. The Netlify CMS, in production, does load and I'm able to view each of the collection entries defined in the admin/config.yml. However, on save of new or existing cms entries, I get the following error:

> Failed to persist entry: TypeError: Cannot read property 'match' of undefined

As a note: I am able to save in local development using npx netlify-cms-proxy-server.

**To Reproduce**

1. Go to 'envyforge.com/admin' 
2. Click on 'blog' collection
3. Create **new** blog entry (use the hint text if you have questions on what the fields are for)
4. Click on 'Save'
5. See error

**Expected behavior**

To be able to save in product deployment as I am in local dev. 

**Screenshots**

<img width="1537" alt="Screen Shot 2020-06-15 at 1 18 07 AM" src="https://user-images.githubusercontent.com/128472/84634119-3417ca80-aea6-11ea-8b6c-46c6e9833afe.png">

**Applicable Versions:**
 - Netlify CMS version: 2.12.14
 - Git provider: Bitbucket
 - OS: macOS 10.15.5
 - Browser version: Google Chrome 83.0.4103.97 (Official Build) (64-bit)
 - Node.JS version (local): v13.3.0 
 - Note.JS version (production): AWS Amplify - Node.JS: v10.16.0

**CMS configuration**
```yml
backend:
  name: bitbucket
  repo: envyforge/envyforge.com
  branch: develop
  auth_type: implicit
  app_id: myappid

local_backend: true
publish_mode: editorial_workflow
media_folder: static/images
public_folder: src/data/images
site_url: https://envyforge.com/contribute

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/data/blogs"
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "This is the title that will be shown on the blog page.",
        }
      - {
          label: "Path",
          name: "slugPath",
          widget: "string",
          default: "/blog/",
          hint: "Must be /blog/ to control the path that the blog page will render in.",
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "Matt Ortiz",
          hint: "Values: Matt Ortiz or Envy Forge.",
        }
      - {
          label: "Format",
          name: "format",
          widget: "string",
          default: "image",
          hint: "Values: image, quote, video, link or gallery.",
        }
      - {
          label: "Image",
          name: "image",
          widget: "string",
          default: "../images/envyforge-spark-persona-app.png",
          hint: "E.g.: ../images/envyforge-spark-persona-app.png.",
        }
      - {
          label: "Category",
          name: "category",
          widget: "string",
          hint: "E.g.: technology, products & services, practices, this is value creation",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          hint: "E.g.: value-creation, product-management, product-development, growth, investment, agile, lean-startup",
        }
      - {
          label: "Featured",
          name: "is_featured",
          widget: "boolean",
          default: false,
          hint: "This controls whether the post will show as a featured item on the blog.",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "service"
    label: "Service"
    folder: "src/data/services"
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Sort Order",
          name: "sortOrder",
          widget: "string",
          hint: "This is the order (ascending) that the service or practice card will render on the home page within each Category (services or practices).",
        }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "This is the title that will be shown on the home page service or practice card.",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          hint: "This is the description (or overview) that will be shown on the home page service or practice card.",
        }
      - {
          label: "Path",
          name: "slugPath",
          widget: "string",
          default: "/service/",
          hint: "Must be /services/ to control the path the services page will render in.",
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "Matt Ortiz",
          hint: "Values: Matt Ortiz or Envy Forge.",
        }
      - {
          label: "Format",
          name: "format",
          widget: "string",
          default: "image",
          hint: "Values: image, quote, video, link or gallery.",
        }
      - {
          label: "Image",
          name: "image",
          widget: "string",
          default: "../images/envyforge-spark-persona-app.png",
          hint: "E.g.: ../images/envyforge-spark-persona-app.png.",
        }
      - {
          label: "Image Alt",
          name: "imageAlt",
          widget: "string",
          hint: "This is the image alt text that will show for accessiblity.",
        }
      - {
          label: "Category",
          name: "category",
          widget: "string",
          hint: "Values: services or practices.",
        }
      - {
          label: "Read More",
          name: "readMore",
          widget: "boolean",
          default: false,
          hint: "This setting controls the services and practices cards on the home page. False means no Read More link will be on the services and practices cards on the home page. True means a Read More link will be placed on the home page (services and practices sections) that goes to the underlying content (full body and post).",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          hint: "E.g.: value-creation, product-management, product-development, growth, investment, agile, lean-startup",
        }
      - {
          label: "Featured",
          name: "is_featured",
          widget: "boolean",
          default: false,
          hint: "This controls whether the post will show as a featured item on the blog (yes, even if a service).",
        }
      - { label: "Body", name: "body", widget: "markdown" }
```
**Additional context**

Happy to provide additional context. 

Thanks, 

Matt
