### ISSUE TITLE
Bug: media files are duplicated in media library when different fields have the same media folder

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-cms#3920]
**Describe the bug**
If multiple fields under the same collection have the same media folder, files from that folder will be duplicated in the media gallery.

**To Reproduce**
1. Use the following config:
```yaml
media_folder: static/media
public_folder: /media
collections:
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: content/posts
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        media_folder: /static/media
      - label: 'Thumbnail'
        name: 'thumbnail'
        widget: 'image'
        required: false
        media_folder: /static/media
```
2. Make sure `static/media` has some files.
3. Open the editor and try to add an image.
4. See that the media library duplicates the files

**Expected behavior**
Files should not show up as duplicates

**Screenshots**

![image](https://user-images.githubusercontent.com/26760571/85049555-7b9ba080-b19d-11ea-9a53-ace33ce37af5.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms 2.10.51`
