### ISSUE TITLE
404 when saving post

### ISSUE THREAD

**Issue by joefatora** [netlify/netlify-cms#393]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When I try to save a post, I get a warning saying `Failed to persist entry: API_ERROR: Not Found`
and the github API returns a 404.

**- If the current behavior is a bug, please provide the steps to reproduce.**
using this basic config with a metalsmith site:

```yaml
backend:
  name: github
  repo: bequest/external-site
  branch: master

public_folder: "dist/images/uploads"
media_folder: "src/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Blog"
    folder: "src/_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
```

I am able to access the CMS at the netlify url, but cannot save after editing a post
**- What is the expected behavior?**
Post saves without error.

**- Please mention your node.js, and operating system version.**
Using netlify to deploy. No node version is set in package.json
