### ISSUE TITLE
netlify-cms-app.js.map - Filesize

### ISSUE THREAD

**Issue by Berndinox** [netlify/netlify-cms#3946]
**Describe the bug**
netlify-cms-app.js.map has a filesize of ~ 18MB
CloudFlare KV support up to 10MB

**To Reproduce**
`npm install netlify-cms --save`
Create a Config
`gatsby build`
watch for: public/admin/netlify-cms-app.js.map

**Expected behavior**

> **Is there a way to load those file from an external CDN?
> Could the size be reduced?**

**CMS configuration**
```
backend:
  name: github
  repo: Berndinox/klausonl
  branch: master

media_folder: "static/media"
public_folder: "/media"

# Uncomment to leverage Netlify CMS UI authoring flow
# see: https://www.netlifycms.org/docs/configuration-options/#publish-mode
# publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "posts/{{fields.slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

```
