### ISSUE TITLE
local CMS changes not reflected online

### ISSUE THREAD

**Issue by stephaniedavidson** [netlify/netlify-cms#3961]
**Describe the bug**
In my CMS I've added a video and vimeo widget for the post body, which are working locally (gatsby develop -> localhost:8000/admin).  I also updated the Netlify CMS version so I don't get the prompt to recover a blog post every time I go to "new post". All working great locally. I can see the changes reflected in my github repo. 

Problem is on my live site (....netlify.app/admin) the changes are erratic. On netlify.app several times I could not see the vimeo/video body option and I was getting the recover post prompt. If I clear my cache the recovery prompt disappears, and I can see my vimeo/video body options, but I would say every few hours I lose those changes and I'm not sure what's triggering it. Wondering if there's a cache I don't know about that I need to delete, or something I need to add to the config, or if this problem is coming from running gatsby build. 

**To Reproduce**
Sorry but not sure how you could reproduce this because my repo is configured to netlify but here's my repo: https://github.com/stephaniedavidson/portfolio
I do not have any branches, only working on master.

**Expected behavior**
I expect to see my changes reflected live. 

**screengrabs**
![image](https://user-images.githubusercontent.com/656405/86022492-7558c000-b9f8-11ea-90db-198b69e77924.png)
![image](https://user-images.githubusercontent.com/656405/86022506-78ec4700-b9f8-11ea-8f4f-847c3d597d60.png)

**Applicable Versions:**
"netlify-cms-app": "^2.12.15"
github
windows 10
chrome

**CMS configuration**
```yaml
backend:
  name: github
  repo: stephaniedavidson/portfolio
  branch: master

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

media_folder: static/assets
public_folder: /assets

collections:
  - name: work
    label: Work
    label_singular: "Work"
    folder: content
    create: true
    path: "{{slug}}/index"
    identifier_field: title
    media_folder: ""
    public_folder: ""
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: cover, label: "Cover image", widget: file }
      - { name: body, label: Body, widget: markdown }
```
