### ISSUE TITLE
Regex literals flagged as invalid in JS collection config

### ISSUE THREAD

**Issue by Undistraction** [netlify/netlify-cms#3967]
**Describe the bug**
On upgrading `netlify-cms-app` from `2.12.14` to `2.12.15` I am now getting lots of validation errors. These are for regexps. Before they were valid and worked fine. Now I get validation errors in the form: 
```
Error loading the CMS configuration
Config Errors:

'collections[2].fields[4].pattern[0]' should be string
'collections[2].fields[6].pattern[0]' should be string
'collections[2].fields[12].fields[0].pattern[0]' should be string
'collections[2].fields[12].fields[2].pattern[0]' should be string

Check your config.yml file.
```

**To Reproduce**

**Expected behavior**
The field should be valid. 

**Applicable Versions:**

 - Netlify CMS version: 2.12.15
 - Git provider: Gitlab

**CMS configuration**
```
backend:
  name: gitlab
  repo: example
  auth_type: implicit
  app_id: dd68f60373a20b9fe3cec8dab82f079d2f9f576c79d1c51684a4fab85b81d3f8
  api_root: 'https://gitlab.example.com/api/v4'
  base_url: 'https://gitlab.example.com'
  auth_endpoint: oauth/authorize
  slug:
    clean_accents: true
    sanitize_replacement: '-'
  commit_messages:
    create: 'create(cms): {{collection}} / {{slug}}'
    update: 'update(cms): {{collection}} / {{slug}}'
    delete: 'delete(cms): {{collection}} / {{slug}}'
    uploadMedia: 'uploadMedia(cms): {{path}}'
    deleteMedia: 'deleteMedia(cms): {{path}}'
  branch: deps—upgrade-netlify-cms
display_url: 'https://www.example.com'
media_folder: static/uploads
public_folder: /uploads
```

Example collection:
```
const SCHEMA = {
  name: `articles`,
  label: `Articles`,
  label_singular: `Article`,
  description: `Articles available within the blog.`,
  folder: `src/content/articles`,
  sortableFields: [`title`, `publishedDate`],
  public_folder: `../../../static/uploads/`,
  create: true,
  editor: {
    preview: false,
  },
  slug: SLUG_TEMPLATE,
  fields: [
    {
        …
        name: `backgroundColor`,
        label: `Background Color`,
        widget: WIDGET_TYPE.STRING,
        default: `e1e9ee`,
        pattern: /^([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/,
        required: false,
    }
  ]
}
```
