### ISSUE TITLE
TypeError: e.replace is not a function

### ISSUE THREAD

**Issue by ralphilius** [netlify/netlify-cms#3969]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.51`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
public_folder: /blog/assets/blog
backend:
  name: git-gateway
  branch: blog
media_folder: blog/assets/blog
show_preview_links: true
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - view_filters: []
    label_singular: Author
    meta: {}
    name: authors
    slug: "{{name}}"
    folder: blog/_authors
    publish: true
    sortableFields:
      - commit_date
      - name
      - name
    label: Authors
    fields:
      - label: Name
        name: name
        widget: string
        required: true
      - label: Picture
        name: picture
        widget: image
        required: true
    create: true
  - view_filters: []
    meta: {}
    name: blog
    slug: "{{slug}}"
    folder: blog/_posts
    publish: true
    sortableFields:
      - commit_date
      - title
      - date
      - commit_author
    label: Blog
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Post Author
        name: author
        widget: relation
        collection: authors
        searchFields:
          - name
        valueField: name,picture
        displayFields:
          - "{{name}}"
      - label: Excerpt
        name: excerpt
        widget: string
        required: true
      - label: Publish Date
        name: date
        widget: datetime
        required: true
      - label: Cover Image
        name: coverImage
        widget: image
        required: true
      - label: Share Image
        name: ogImage
        widget: image
        required: false
      - label: Body
        name: body
        widget: markdown
        required: true
    create: true

```

**Additional context**
