### ISSUE TITLE
Existing posts / settings not showing in admin

### ISSUE THREAD

**Issue by alastair38** [netlify/netlify-cms#397]
**- Do you want to request a feature or report a bug?**
Bug

**- What is the current behavior?**
Created posts do no show up in the CMS panel. I can add a new post successfully, but it will not subsequently show in the CMS.

The network tab in Chrome developer tools shows `_posts?ref=master` initially responding with a json file of the created posts from GitHub (as you would expect), but `_posts?ref=master` then returns a 204 status with no content. 

A similar issue exists when trying to edit the following YAML data file -   `_data/settings/yml` (see config below) - with the initial response from GitHub containing the existing content being followed by duplicate response with a 204 status. In addition, when trying to save content to `_data/settings/yml` I get the following error

`Uncaught Error: invalid keyPath
    at Q (immutable.js:872)
    at Re (immutable.js:1976)
    at Re (immutable.js:1982)
    at Re (immutable.js:1982)
    at fe.updateIn (immutable.js:1280)
    at fe.setIn (immutable.js:1258)
    at entryDraft.js:56
    at fe.withMutations (immutable.js:1355)
    at u (entryDraft.js:55)
    at combineReducers.js:132`

**- If the current behavior is a bug, please provide the steps to reproduce.**
using this basic config with a jekyll site deployed to Netlify:

```
backend:
  name: github
  repo: alastair38/alastaircox # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "assets/images" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Layout Style", name: "layout", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Settings"
      files:
      - name: "general"
        label: "Site Settings"
        file: "_data/settings.yml"
        description: "General Site Settings"
        fields:
          - {label: "Global title", name: "site_title", widget: "string"}
```

**- What is the expected behavior?**
View and edit existing posts
View and edit existing _data YAML files

**- Please mention your node.js, and operating system version**
Using netlify to deploy
