### ISSUE TITLE
Date format changed -> old dates not sorting correctly in 2.10.52

### ISSUE THREAD

**Issue by lbischof** [netlify/netlify-cms#3973]
**Describe the bug**
After updating to 2.10.52 posts with strict iso dates (`2020-07-02T06:17:54.924Z`) and older posts with iso formatting (`2020-06-12 14:02:29+00:00`) are incorrectly sorted. It seems the date handling/parsing has changed in 2.10.52.

Minimal code to reproduce: https://github.com/lbischof/netlify-cms-issues-3973

**To Reproduce**
1. Start a webserver: `python -m SimpleHTTPServer`
2. Start a local proxy: `npx netlify-cms-proxy-server`
3. Navigate to localhost:8000/admin
4. Sort posts in descending order
5. Posts are sorted as follows: 2, 1, 3, 4, 5 (Firefox) and 4,2,1,5,3 (Chrome)
6. Decrement the version to 2.10.51 in `admin/index.html`
7. Posts are sorted as follows: 5, 4, 3, 2, 1

**Expected behavior**
All date formats (not just 100% correctly formatted) should be sorted correctly when possible.

**Applicable Versions:**
 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: Gitlab (git-gateway)
 - OS: Ubuntu
 - Browser version: Firefox 77.0.1

**Comment by erezrokah** [comment]
Hi @lbischof, thanks for opening this.
Can you share an example content for each file?
We should actually only parse the strict version as a date object:
https://github.com/netlify/netlify-cms/blob/c33db099ac56edfd993de0212a8085d8d9243ce4/packages/netlify-cms-core/src/formats/yaml.js#L20

**Comment by lbischof** [comment]
The following post does not appear in the CMS (only when I search for it) when I update to 2.10.52:
```
---
title: Non-working
date: 2020-07-01T15:20:00.000Z
---
This does not appear in 2.10.52
```
This format works with both versions:
```
---
date: 2020-06-12 14:02:29+00:00
title: Working
---
Old post
```

**Comment by erezrokah** [comment]
Can you share your full `config.yml`?
Also, how many posts are there is total? The fact that searching shows it might be related a pagination bug.

**Comment by lbischof** [comment]
There are 180 posts of which the 20 newest posts do not appear in 2.10.52.

```
backend:
  name: git-gateway
  identity_url: https://website.ch/.netlify/identity
  gateway_url: https://website.ch/.netlify/git
  site_domain: https://website.ch/
  branch: develop

local_backend: true

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
display_url: https://website.ch
logo_url: https://brand.website.ch/images/logo_classic.svg
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    label_singular: "Post"
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name"]
        valueField: "author"
        displayFields: ["name"]
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: true
        options:
          - { label: "Geschäftsbereiche", value: "business-divisons" }
          - { label: "Prozesse", value: "processes" }
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        required: false
        default: true
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "tools" # Used in routes, e.g., /admin/collections/blog
    label: "Tools" # Used in the UI
    label_singular: "Tool"
    folder: "content/tools" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtext", name: "subtext", widget: "string"}
      - {label: "Link", name: "external_link", widget: "string"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "authors" # Used in routes, e.g., /admin/collections/blog
    label: "Authors" # Used in the UI
    label_singular: "Author"
    format: yml
    folder: "data/authors" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{author}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Kürzel"
        name: "author"
        widget: "string"
        pattern: ['^[a-z]+$', "Bitte das Kürzel eingeben"]
```
