### ISSUE TITLE
TypeError: Cannot read property 'fluid' of undefined

### ISSUE THREAD

**Issue by projectssome** [netlify/netlify-cms#3997]
**Describe the bug**
As you can see below, gastby-image is working just fine, but Netlify CMS won't load the preview, returning  this **TypeError: Cannot read property 'fluid' of undefined** error.

**To Reproduce**
I created [this public repo](https://github.com/projectssome/test) with just the needed code, so anyone can easily reproduce. <br>You can also see this site [here](https://frosty-raman.netlify.app/).

**Expected behavior**
Load Netlify CMS preview

**Screenshots**
![Content_Manager](https://user-images.githubusercontent.com/44626533/86981706-bfab1100-c15d-11ea-8b56-8edc366d8c94.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.16`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Index
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: Hero
            name: hero
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Image
                name: image
                widget: image
    publish: true
    sortableFields:
      - commit_date
      - commit_author
    view_filters: []

```
