### ISSUE TITLE
Error: The result of this StaticQuery could not be fetched.This is likely a bug in Gatsby and i...

### ISSUE THREAD

**Issue by alessioprestileo** [netlify/netlify-cms#4004]
**Describe the bug**
Result of StaticQuery could not be fetched.
This happens only in the CMS (as shown in the picture) when trying to preview the index page, but not when rendering the same page in the website.
The static query causing the error is:
```
const useSiteMetadata = () => {
  const data: SiteMetadataQuery = useStaticQuery(
    graphql`
      query SiteMetadata {
        site {
          siteMetadata {
            title
            description
          }
        }
      }
    `,
  )
  const { site } = data

  return site?.siteMetadata
}
```

**To Reproduce**
You can clone this repo:
https://github.com/alessioprestileo/netlify-cms-issue.git

**Expected behavior**
The static query should work and return the same data as when rendering the index page in the website

**Screenshots**
![image](https://user-images.githubusercontent.com/16187074/87247461-44df4000-c454-11ea-883b-23dc2e10dab9.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.16`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/img
public_folder: /img
collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Landing Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: Welcome Section
            name: welcomeSection
            widget: object
            fields:
              - label: Message
                name: message
                widget: markdown
              - label: Video URL
                name: videoUrl
                widget: string
              - label: Blurbs
                name: blurbs
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Text
                    name: text
                    widget: text
          - label: Customer stories
            name: customerStories
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Feedbacks
                name: feedbacks
                widget: list
                fields:
                  - label: Author
                    name: author
                    widget: string
                  - label: Content
                    name: content
                    widget: text
              - label: Key Numbers
                name: keyNumbers
                widget: list
                fields:
                  - label: Number
                    name: number
                    widget: number
                  - label: Description
                    name: description
                    widget: string
          - label: Call To Action
            name: callToAction
            widget: object
            fields:
              - label: Header
                name: header
                widget: string
              - label: Content
                name: content
                widget: text
              - label: Image
                name: image
                widget: image
              - label: Social Media
                name: soMeList
                widget: select
                multiple: true
                options:
                  - Facebook
                  - Twitter
                  - Instagram
    publish: true
    sortableFields:
      - commit_date
      - commit_author
    view_filters: []

```

**Additional context**
