### ISSUE TITLE
Bug(nested-collections-github): can't move new entries to a new location after initial save

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-cms#4018]
To reproduce:
1. Setup nested collections on a GitHub repo + editorial workflow:
```yaml
backend:
  name: github
  repo: <nested-collection-repo>

publish_mode: editorial_workflow

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: posts
    create: true
    nested:
      depth: 100
    fields:
      - label: Title
        name: title
        widget: string
    meta:
      path:
        label: Path
        widget: string
        index_file: index

```
2. Create a new post and enter `test` for title and path.
3. Click save.
4. Enter `test/other` for path.
5. Click save - see that an error occurs:
![image](https://user-images.githubusercontent.com/26760571/87432838-34b09780-c5f1-11ea-85e8-6d06d341fddf.png)
