### ISSUE TITLE
TypeError: Cannot read property 'days1' of undefined

### ISSUE THREAD

**Issue by projectssome** [netlify/netlify-cms#4031]
**Describe the bug**
Whenever I add one more item to this `list`, the preview breaks, as you can see below. Is there a reason for that to be happening? I've already seen the [documentation](https://www.netlifycms.org/docs/widgets/list/) and it's doesn't look to be wrong.

**To Reproduce**
I created [this public repo](https://github.com/projectssome/config), so anyone can easily reproduce.
You can also see this site [here](https://stupefied-mahavira-1332f7.netlify.app).

**Expected behavior**
Add another list without breaking the preview.

**Screenshots**
![Screen Shot 2020-07-16 at 12 27 51 PM](https://user-images.githubusercontent.com/44626533/87691117-a0654280-c760-11ea-8180-01b6f70c66da.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.17`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Index
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: Collapses
            name: collapses
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Days
                name: days
                widget: object
                fields:
                  - label: Days 1
                    name: days1
                    widget: string
                  - label: Days 2
                    name: days2
                    widget: string
                  - label: Days 3
                    name: days3
                    widget: string
    publish: true
    sortableFields:
      - commit_date
      - commit_author
    view_filters: []

```

**Additional context**
