### ISSUE TITLE
Relation Widget resets when using autocomplete 

### ISSUE THREAD

**Issue by haneatic** [netlify/netlify-cms#4061]
**Description**
If you use the autocomplete functionality of the relation widget together with the multiple option it resets the selected items completely and only keeps the last one you picked.

**To Reproduce**
1. Open the dropdown menu of the relation widget
2. Pick any number of items
3. Search for any non selected item
4. Select an entry you found through the search
5. It should be resetted

**Expected behavior**
It should keep previous selected items.

**CMS configuration**
```yml
backend:
  name: git-gateway
  branch: master

local_backend: true

site_url: https://example.com

# publish_mode: editorial_workflow
media_folder: assets/uploads

collections: # A list of collections the CMS should be able to edit
  - name: 'Itemlist'
    label: 'Itemlist'
    create: true
    folder: '_itemlist'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        required: true
      - label: 'Items'
        name: 'Items'
        widget: 'list'
        fields:
          - label: 'Name'
            name: 'Name'
            widget: 'string'
            required: true

  - name: 'Collector'
    label: 'Collector'
    create: true
    folder: '_collector'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        required: true
      - label: 'Items'
        name: 'items'
        widget: 'relation'
        collection: 'Itemlist'
        valueField: 'Items.*.Name'
        searchFields: ['Items.*.Name']
        multiple: true
```

**Additional context**
I actually tried to track down the issue and I think that [this](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-relation/src/RelationControl.js#L52) line is either part of it or responsible for it. When selecting an item you searched for it replaces the already selected items with `undefined`
