### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by projectssome** [netlify/netlify-cms#4066]
**Describe the bug**
As you can see below, the code works for the most part, but specifically in the Preview pane, when I add a `group` element (list) in the CMS, it breaks for some reason. I've noticed that the issue happens in the custom preview template, in [this line](https://github.com/projectssome/testing/blob/9e148885db5be7f65a262d3cc59c99fc9b2ce268/src/components/templates/IndexPageTemplate.js#L12), but I wasn't able to see anything wrong in there. Is there a possible fix to it, please?

I'm posting it here because I couldn't find anyone that had a similar issue. I'm sorry if that's not the right place for this kind of issue, if needed, I can delete.

**To Reproduce**
I created [this](https://github.com/projectssome/testing) public repo with just the code needed, so anyone can easily reproduce.
You can also see this site [here](https://loving-jang.netlify.app/).

**Expected behavior**
Be able to add this `group` element without breaking the Preview pane.

**Screenshots**

**When adding a `group` element**
![Content-Manager](https://user-images.githubusercontent.com/44626533/88337385-9332ef80-cd2e-11ea-9c11-a3331d853e45.png)

**When adding a `subgroup` element (nested list)** - it works as expected
![Content-Manager (1)](https://user-images.githubusercontent.com/44626533/88337513-c2496100-cd2e-11ea-87b3-76dd7c865b8c.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.17`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Index
        name: index
        fields:
          - label: Groups
            name: groups
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Subgroups
                name: subgroups
                widget: list
                fields:
                  - label: Subtitle
                    name: subtitle
                    widget: string
    publish: true
    sortableFields:
      - commit_date
      - commit_author
    view_filters: []

```

**Additional context**
