### ISSUE TITLE
TypeError: Cannot read property 'fluid' of undefined

### ISSUE THREAD

**Issue by maocubillos** [netlify/netlify-cms#4096]
**Describe the bug**
I got it trying to change an image in my home page
**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.19`
 - Git provider: `bitbucket`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: bitbucket
  repo: maocubillos/family-money-website
  branch: master
  auth_type: implicit
  app_id: at8WzAYTSsGt9aLjx4
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/img
public_folder: /img
collections:
  - view_filters: []
    meta: {}
    name: blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: src/pages/blog
    publish: true
    sortableFields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    label: Blog
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Featured Post
        name: featuredpost
        widget: boolean
      - label: Featured Image
        name: featuredimage
        widget: image
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
    create: true
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Landing Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Heading
            name: heading
            widget: string
          - label: Subheading
            name: subheading
            widget: string
          - label: Description
            name: description
            widget: string
      - file: src/pages/about/index.md
        label: About
        name: about
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: about-page
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
    publish: true
    sortableFields:
      - commit_date
      - commit_author
    view_filters: []

```

**Additional context**
