### ISSUE TITLE
netlify-cms-proxy-server returns 500 on entry that has relations to large collections (.git/index.lock: "File exists.")

### ISSUE THREAD

**Issue by stepugnetti** [netlify/netlify-cms#4122]
**Describe the bug**

When opening an entry from a folder collection that has more than one fields of type ncw-file-relation whose target collection is large (~8k entries in my case), the proxy server returns 500 "Unkown error". The log contains the following lines:
>error: Error handling {"branch":"my-branch","action":"getEntry","params":{"branch":"my-branch","path":"my-data.json}}: fatal: Unable to create '/path-to-my-site-repo/.git/index.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

**To Reproduce**

I've seen this happening only in a local build of netlify-cms. I've installed locally-built packages netlify-cms-app, netlify-cms-proxy-server and netlify-cms-ui-default with `npm install --save ...`. I have a local webpack entrypoint that looks like this:
```js
import CMS from 'netlify-cms-app';
import {Widget as RelationWidget} from "@ncwidgets/file-relation";

if(typeof window !== 'undefined'){
    window.CMS = CMS;
}

CMS.registerWidget(RelationWidget);
CMS.init();
```

Click on an entry of that folder collection to reproduce the error.

**Expected behavior**
The editor should display the data of the entry, no 500 error reporting in console.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version:  The versions I tested are tag `netlify-cms-app@2.12.19` and `netlify-cms-app@2.12.13`
 - Git provider: local git repo
 - OS: Ubuntu 18.04
 - Browser version Firefox 79

 - Node.JS version: v12.6.3

**CMS configuration**
I cannot include the complete original configuration and I wasn't able to create a minimal example that reproduce the error. This is a sketch of the original configuration:

```yaml
publish_mode: editorial_workflow
backend:
  name: git-gateway
  repo: ...
  branch: custom-backend
local_backend: true
media_folder: static/images/uploads
collections:
  - label: Blog
    name: posts
    folder: content/blog
    create: true
    fields:
      - name: author
        label: Author
        widget: ncw-file-relation
        collection: lists
        file: authors
        id_field: last
        display_field: first
        target_field: authors
      - label: First Insance of a Large File Collection
        name: city
        widget: ncw-file-relation
        collection: lists
        file: cities
        target_field: cities
        id_field: id
        display_fields: name
      - label: Second Insance of a Large File Collection
        name: city_second
        widget: ncw-file-relation
        collection: lists
        file: cities
        target_field: cities
        id_field: id
        display_fields: name
      - name: title
        label: Title
        widget: string
      - name: type
        widget: hidden
        default: "post"
      - name: body
        label: Text
        widget: markdown
  - label: Open Lists
    name: lists
    files:
      - label: List of All of the Small Towns of the World
        name: cities
        file: data/cities.json
        fields:
          - label: Towns
            label_singular: Town
            name: cities
            widget: list
            allow_add: false
            fields:
              - label: Nome
                name: name
                widget: string
              - label: Code
                name: id
                widget: hidden
```

**Additional context**

Removing one of the two references to the large file collection, no 500 error was returned.

The error is reported only if my locally-built bundle is included  in the admin page: if I include the CDN bundle, everithing is fine.
