### ISSUE TITLE
Failed to load config.yml (404)

### ISSUE THREAD

**Issue by sitefinitysteve** [netlify/netlify-cms#4175]
**Describe the bug**
On localhost I can get to /admin and see the netlifycms login, the network inspector shows it getting the config.yml from /admin/config.yml

When I deploy to Netlify though it seems that it's trying to load it from /config.yml. 

![image](https://user-images.githubusercontent.com/1542376/90562959-164e3680-e171-11ea-9bd7-b98ac8fc3885.png)

If I hit it at the proper /admin/config.yml on live, it's clearly there, why it's being served from root I have no idea.

**To Reproduce**
https://www.sitefinitysteve.com/admin#/

**Expected behavior**
NetlifyCms admin login page

**Screenshots**

**Applicable Versions:**
netlify-cms-app 2.12.19
bootstrap.js:83 netlify-cms-core 2.30.3
index.js:27 netlify-cms 2.10.55
"nuxt": "^2.14.0",**CMS configuration**

```
# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: master

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: 'app/static/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: Settings
    name: settings
    files:
      - label: General
        name: general
        format: json
        file: 'app/content/settings/general.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Title Template', name: titleTemplate, widget: string }
          - { label: Logo, name: logo, widget: image }
          - { label: Icon, name: icon, widget: image }
          - { label: 'Loading Color', name: loadingColor, widget: string, default: '#000000' }
          - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
          - { label: 'SEO Meta Image', name: seoMetaImage, widget: image, required: false }
      - label: Manifest
        name: manifest
        format: json
        file: 'app/content/settings/manifest.json'
        fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Short name', name: shortName, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: 'Theme color', name: themeColor, widget: string }
          - { label: 'Background color', name: backgroundColor, widget: string }
          - { label: Lang, name: lang, widget: string, default: en }

  - name: 'pages'
    label: 'Pages'
    folder: 'app/content/pages'
    create: true
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: text, required: false }
      - { label: Content, name: content, widget: markdown }
      - { label: 'Featured Image', name: featuredImage, widget: image, required: false }
      - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
      - { label: 'SEO Meta Image', name: seoMetaImage, widget: image, required: false }
  - name: 'blog'
    label: 'Blog'
    folder: 'app/content/blog'
    create: true
    slug: '{{slug}}'
    format: 'json'
    sort: 'publishedAt:desc'
    sortableFields: ['publishedAt', 'title']
    fields:
      - { label: Title, name: title, widget: string }
      - { label: 'Published At', name: publishedAt, widget: date }
      - { label: Content, name: content, widget: markdown }
      - { label: 'Featured Image', name: featuredImage, widget: image, required: false }
      - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
      - { label: 'SEO Meta Image', name: seoMetaImage, widget: image, required: false }
```

**Additional context**
netlify.toml
```
[build]
  publish = "dist"
  command = "yarn generate"
  functions = "app/functions"

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    exclude = [
      '**/tools.html',
      '**/200.html',
      '**/about.html',
      '**/contact/success.html',
      '**/admin',
    ]
```
