### ISSUE TITLE
Bug(netlify-cms-widget-relation) removing value causes TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by aequi42** [netlify/netlify-cms#4185]
**Describe the bug**

I have a relation widget with `required: false`. Setting the Value works as expected, but if i try to remove a selected relation, the error appears.

The Stacktrace leads to the following Source:
https://github.com/netlify/netlify-cms/blob/d6a02636cd02dc3969f3efba9fdeb45badd49d70/packages/netlify-cms-widget-relation/src/RelationControl.js#L54-L56
The first item in `initial` is `null`.

It looks like the error was introduced by #4063

I hope i provided all the information you require :)

**To Reproduce**

* Create a collection with an relation and `required: false`.
* Open the Editor, select a value
* Remove the selected value

**Expected behavior**

The selected value should be removed and no error should occour.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/15265105/90985021-85100300-e568-11ea-96c2-441f8572fa4e.png)
(The X-Button only appears if `required: false` is set in config)

![grafik](https://user-images.githubusercontent.com/15265105/90985037-9d801d80-e568-11ea-9002-6922cded2a25.png)
(The error after I click on the X or press Del)

**Applicable Versions:**

 - Netlify CMS version: `netlify-cms-app@2.12.19`
 - Git provider: `proxy`
 - Browser version: `Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4171.0 Safari/537.36`

**CMS configuration**
```yml
backend:
  name: git-gateway

local_backend: true
media_folder: src/images
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: "bands"
    label: "Bands"
    label_singular: "Band"
    folder: "src/data/bands"
    description: "Die Bands auf dem Zwergentanz"
    create: true
    slug: "{{title}}.band"
    media_folder: ""
    public_folder: ""
    path: "{{title}}"
    identifier_field: "id"
    summary: "{{band_name}}"
    editor:
      preview: true
    fields:
      - label: "Id"
        name: "id"
        hint: "Ein slug/id (Keine leerzeichen)"
        widget: "string"
        pattern: ["^[^\\s]*$", "Es sind keine Leerzeichen erlaubt!"]
      - label: "Band Name"
        name: "band_name"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "src/data/events"
    create: true
    slug: "{{id}}"
    path: "{{id}}"
    format: "json"
    identifier_field: "id"
    editor:
      preview: true
    fields:
      - label: Bands
        label_singular: Band
        name: "bands"
        widget: list
        summary: "{{details}} Slot:{{slot}}"
        fields:
          - name: details
            label: Band
            widget: relation
            collection: bands
            required: false
            valueField: "../bands/{{slug}}.md"
            displayFields: ["band_name"]
            searchFields: ["band_name"]
          - name: slot
            label: Slot
            widget: number
```
