### ISSUE TITLE
Media Folder is not Recursive to Sub Folders

### ISSUE THREAD

**Issue by surjithctly** [netlify/netlify-cms#4208]
**Describe the bug**
`media_folder: "static/img"` is only looking for the root folder. Not subfolders.
**To Reproduce**
  
1. Create subfolders inside media folder
2. Check admin / Media Tab
3. Cannot see images inside subfolders

**Expected behavior**

All images inside the selected path should show. 

Example: 
```
/static/img/
/static/img/screens
/static/img/visuals
/static/img/icons
```
 
 
**Applicable Versions:**
Windows, Github, Eleventy, Json data

**CMS configuration**
```yml
backend:
  name: github
  repo: username/repo
media_folder: "static/img"
```
