### ISSUE TITLE
Cannot get local netlify-api backend to work

### ISSUE THREAD

**Issue by onedrawingperday** [netlify/netlify-cms#425]
Hello I am trying to set up a netlify-cms instance with Hugo, that uses the local netlify-git-api backend: https://github.com/netlify/netlify-git-api

But I am unable to get it to work.

I have successfully installed netlify-git-api on my path in Ubuntu 16.04 and set up users with 
`netlify-git-api users add`

When I run `netlify-git-api serve` I get `Starting server on 127.0.0.1:8080`

And when I visit `http://localhost:8080/` I see the following:
```
Local Netlify CMS Backend
This is a simple local backend for Netlify's CMS 
```
When I run `hugo server` on my project directory and visit `http://localhost:1313/admin/` I get the following
```
Error loading the CMS configuration
The config.yml file could not be loaded or failed to parse properly.
Error message: Error: Backend not found: netlify-api
```
I have tried changing netlify-api to netlify_api in config.yml as mentioned in this issue https://github.com/netlify/netlify-cms/issues/40 but nothing happens.

The contents of `config.yml` under` /admin/` in my project directory are the following:
```
backend:
  name: netlify-api
  url: http://localhost:8080

# Use the Editorial workflow - https://github.com/netlify/netlify-cms/blob/master/docs/editorial_workflow.md
publish_mode: editorial_workflow

# Save image uploads to static/img
media_folder: "static/images"
public_folder: "/images"

# Collections
collections: # A list of collections the CMS should be able to edit
  # Used in routes, ie.: /admin/collections/:slug/edit
  - name: "exhibitions"
    # Used in the UI, ie.: "New Post"
    label: "Exhibition"
    # The path to the folder where the documents are stored
    folder: "content/exhibitions"
    # Allow users to create new documents in this collection
    create: true
    # Filename template e.g. YYYY-MM-DD-title.md
    slug: "{{slug}}"
    # The fields each document in this collection have
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      # Use required: false instead of optional: true - https://github.com/netlify/netlify-cms/issues/315
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
# Does not currently work, see https://github.com/netlify/netlify-cms/issues/248
#      - {label: "Tags", name: "tags", widget: "list"}
#      - {label: "Categories", name: "categories", widget: "list"}
```
And the `index.html` under` /admin/ `contains:
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>

  <link rel="stylesheet" href="https://unpkg.com/netlify-cms@^0.3/dist/cms.css" />

</head>
<body>
  <script src="https://unpkg.com/netlify-cms@^0.3/dist/cms.js"></script>
</body>
</html>
```
What am I doing wrong? Or is the netlify-git-api deprecated?
