### ISSUE TITLE
Bitbucket + editorial_workflow - "failed to load entry..." after creating a post

### ISSUE THREAD

**Issue by arthabus** [netlify/netlify-cms#4253]
**Describe the bug**

Bitbucket + editorial_workflow - after creating a post netlify pushes it to a dedicated branch but immediately throws an error when trying to display it: failed to load entry... (see the screenshots below)

**To Reproduce**

Steps to reproduce the behavior. For example:
1. Setup bitbucket connection
2. Enable publish_mode: editorial_workflow
3. Create a post

**Expected behavior**

After creating a post, it's displayed under "draft"

**Screenshots**

Error after saving a post:
<img width="1583" alt="Screen Shot 2020-08-29 at 21 27 19" src="https://user-images.githubusercontent.com/8145834/92301358-84616e80-ef63-11ea-8df4-eebb10794776.png">

The created post is not displayed in draft:
<img width="1303" alt="Screen Shot 2020-08-29 at 21 27 32" src="https://user-images.githubusercontent.com/8145834/92302668-3140e900-ef6e-11ea-9cdf-04fa599d3d60.png">

Even though the file was created successfully in a new branch:
<img width="1253" alt="Screen Shot 2020-08-29 at 21 27 47" src="https://user-images.githubusercontent.com/8145834/92302346-cabacb80-ef6b-11ea-9e60-8235c19b2576.png">

![Screen Shot 2020-09-05 at 11 37 52](https://user-images.githubusercontent.com/8145834/92302413-461c7d00-ef6c-11ea-9056-84b786776039.png)

As a note, I can make it work if I remove "publish_mode: editorial_workflow", however I'm looking to use the editor workflow to store drafts before publishing.

**Applicable Versions:**

 - Netlify CMS version: netlify-cms 2.10.56, netlify-cms-core 2.30.4, netlify-cms-app 2.12.20
 - Git provider: BitBucket
 - OS: MacOS 10.15.6
 - Browser version chrome Version 85.0.4183.83
 - Node.JS version: 8.15.0

**CMS configuration**

```
backend:
  name: bitbucket
  repo: <repo-name-here>
  branch: master
  auth_type: implicit
  app_id: <app-id-here>

media_folder: "src/blog/.vuepress/public/images/"
public_folder: "/blog/images/"
publish_mode: editorial_workflow
collections:
  - label: "Posts"
    name: "posts"
    folder: "src/blog/posts/"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/:slug"}

```

**Additional context**
