### ISSUE TITLE
Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62&a...

### ISSUE THREAD

**Issue by Danielgregoire** [netlify/netlify-cms#4284]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.16`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36`

**CMS configuration**
```
publish_mode: editorial_workflow
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: github
  repo: RightCapitalHQ/rightcapital-help
media_folder: static/assets
public_folder: /assets
collections:
  - view_filters: []
    meta: {}
    name: documents
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: src/documents
    publish: true
    sortableFields:
      - commit_date
      - title
      - commit_author
    label: Documents
    format: frontmatter
    fields:
      - name: path
        label: URL Path
      - name: title
        label: Title
      - name: body
        label: Body
        widget: markdown
      - label: Related documents
        name: relatedDocuments
        widget: list
        field:
          label: Related document
          name: relatedDocument
          widget: relation
          collection: documents
          displayFields:
            - title
          searchFields:
            - title
          valueField: path
      - label: Keywords
        name: keywords
        widget: text
        required: false
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
    create: true
    extension: mdx
  - label: Sidebar
    name: sidebar
    files:
      - label: Sidebar
        name: sidebar
        file: src/config/sidebar.yml
        fields:
          - name: menu
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: URL Path
                name: path
                widget: string
              - label: Description
                name: description
                widget: string
              - name: documents
                label: Documents
                widget: list
                field:
                  label: Document
                  name: document
                  widget: relation
                  collection: documents
                  displayFields:
                    - title
                  searchFields:
                    - title
                  valueField: path
    publish: true
    sortableFields:
      - commit_date
      - commit_author
    view_filters: []

```

**Additional context**
