### ISSUE TITLE
Unsaved changes, and publish new entry fails (netlify deployment).

### ISSUE THREAD

**Issue by ulises-castro** [netlify/netlify-cms#4285]
**Describe the bug**
1 - Infinite unsaved changes, but the entries appear on the workflow section, however when I try to publish it to production, deployment fails.

**To Reproduce**
**1 - Create a new post and filling it up.

2 - Try to save it (Unsaved changes bug, see image)

3 - Publish (Deployment starts but fails, see image)**

**Expected behavior**

**Screenshots**

I do not what is causing this problem as well.
![image](https://user-images.githubusercontent.com/17864276/92633530-834c7c00-f298-11ea-8e76-60ae3268b58f.png)
**When I try to save**
![image](https://user-images.githubusercontent.com/17864276/92631622-374d0780-f297-11ea-8f2f-c4ed6aa73faa.png)
After trying save the post... 
![image](https://user-images.githubusercontent.com/17864276/92631748-6cf1f080-f297-11ea-84a3-296403cd9973.png)

**When I publish a new entry and then deployment fails**

![image](https://user-images.githubusercontent.com/17864276/92633832-fd7d0080-f298-11ea-95ea-31e9210c91a7.png)

**Applicable Versions:**

 - Netlify CMS version: 2.11.23
 - Git provider: Github
 - OS: Manjaro Arch Linux 64bytes
 - Browser version Firefox Developver - Last version

 - Node.JS version: 12.18.3

**CMS configuration**

```yml
backend: # Set up your backend
  name: github
  repo: ulises-castro/****
  preview_context: netlify/deployment

local_backend: false # Optional if you want to use the local proxy mode

publish_mode: editorial_workflow
media_folder: static/assets   # I'm not using these default  assets directories at the moment.
public_folder: /assets

display_url: https://*****.netlify.com/

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    delete: true
    path: "{{slug}}/index"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "images"
    public_folder: "./images"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", valueField: "name", searchFields: ["name"] }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Hero", name: "hero", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "authors"
    label: "Authors"
    folder: "content/authors/authors"
    create: true
    delete: true
    format: "yml"
    identifier_field: "name"
    media_folder: "avatars"
    public_folder: "./avatars"
    editor:
      preview: false
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Bio, name: bio, widget: string }
      - { label: Featured, name: featured, widget: boolean, default: false }
      - { label: Avatar, name: avatar, widget: image }
      - { label: Social, name: social, widget: list, collapsed: false, field: { label: URL, name: url, widget: string } }
```

**Additional context**
**I'm using novela theme.**
