### ISSUE TITLE
Path Meta Field Is Required

### ISSUE THREAD

**Issue by timbomckay** [netlify/netlify-cms#4317]
## Describe the bug
Path meta field appears to be required & conflicts with existing path.

## To Reproduce

**New Page**

1. Click `Create New Page`
1. Fill in title, description & body fields (and any other required fields)
1. Click `Publish Now`
1. Error pops up
> PATH IS REQUIRED. '%{PATH}' IS NOT A VALID PATH

**Edit Existing Page**

1. Select page from menu to edit
1. Path meta field is prepopulated with `/`
1. Click `Publish Now`
1. Receives Error
> PATH '/' ALREADY EXISTS

## Expected behavior

New page shouldn't require the editor to populate the field. Edit page might be an issue with the field configuration and current content as it doesn't already have the field.

## Applicable Versions:

 - Netlify CMS version: (From CDN) https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js || (Delivered) https://unpkg.com/netlify-cms@2.10.56/dist/netlify-cms.js
 - Git provider: GitHub
 - OS: Mac OS 10.15.6
 - Browser version: Chrome 85

## CMS configuration

```yml
collections:
  - name: "page" # Used in routes, ie.: /admin/collections/:slug/edit
    create: true # Allow users to create new documents in this collection
    folder: "content" # The path to the folder where the documents are stored
    label: "Pages" # Used in the UI, ie.: "New Post"
    label_singular: "Page"
    allow_nesting: true
    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    meta: {
      path: {
        widget: string,
        label: 'Path',
        index_file: '_index'
      }
    }
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
```

## Additional context
You can view [my repo](https://github.com/timbomckay/hugo-sandbox) as needed, it's just a sandbox.

**Comment by erezrokah** [comment]
Hi @tienpham94, thanks for opening the issue.
The `path` meta field is meant to be used only when setting up a [nested collection](https://www.netlifycms.org/docs/beta-features/#nested-collections).
Are you missing that part in the configuration?
Also `allow_nesting: true` is not a known collection configuration.

**Comment by timbomckay** [comment]
Oh ok, I think I got that from erquhart's opening message on the [draft posting](https://github.com/netlify/netlify-cms/issues/3227#issue-562911117). Took it as a way to enable the defaults. Are there defaults for the `nested` configuration? Does it always require at least the depth or can you say `nested: true`?

I've updated [the config](https://github.com/timbomckay/hugo-sandbox/blob/master/static/admin/config.yml) with the following

```yml
nested:
      depth: 3 # max depth to show in the collection tree
      summary: '{{ title }}' # optional summary for a tree node, defaults to the inferred title field
```

I'm getting the same errors for both new & existing pages.
