### ISSUE TITLE
Netlify Build fails when I make edit to the cms

### ISSUE THREAD

**Issue by FatGrizzly** [netlify/netlify-cms#4325]
I am using https://github.com/wutali/nextjs-netlify-blog-template After editing the default page,the compile always fails!
**Expected behavior**
It should compile but always fails!
https://app.netlify.com/sites/soundarr/deploys

config.yml
```
collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "posts"
    label: "Posts"
    folder: "src/pages/posts"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"`

```
