### ISSUE TITLE
i18n: data is not duplicated for default value setting

### ISSUE THREAD

**Issue by blackb1rd** [netlify/netlify-cms#4356]
**Describe the bug**
when setting **i18n: duplicate** in string widget, the value is not duplicated from the defalut locale if there is a default value setting

**To Reproduce**
1. Setting:
```yaml
backend:
  name: gitlab

i18n:
  structure:  multiple_files
  locales: [en, th]
  defaultLocale: en

collections:
- name: "test"
  folder: "content"
  path: "{{slug}}/index"
  media_folder: ''
  public_folder: ''
  create: true
  i18n: true
  fields:
  - {label: Author, name: author, widget: string, default: "tester", i18n: duplicate}
```
2. create content without touching the "Author" field(if it was edited, the value will be duplicated).
3. see the non-default locales, there is no  "Author"field.

**Expected behavior**

when setting **i18n: duplicate** in any widgets, the value shall duplicated from the defalut locale.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

netlify-cms-app 2.12.24
netlify-cms-core 2.30.7
netlify-cms 2.10.60

**CMS configuration**

```yaml
backend:
  name: gitlab

i18n:
  structure:  multiple_files
  locales: [en, th]
  defaultLocale: en

collections:
- name: "test"
  folder: "content"
  path: "{{slug}}/index"
  media_folder: ''
  public_folder: ''
  create: true
  i18n: true
  fields:
  - {label: Author, name: author, widget: string, default: "tester", i18n: duplicate}
```

**Additional context**
