### ISSUE TITLE
i18n: support "duplicate" setting on list fields

### ISSUE THREAD

**Issue by cbix** [netlify/netlify-cms#4386]
Currently, list fields only support `i18n: true` and `i18n: false`. For many cases (like a picture carousel) the content needs to be the same among all locales, where `i18n: duplicate` would make sense.

Possible workarounds are using a relation widget and storing the content in a separate collection or setting `i18n: false` and fetching it from the default locale manually. This is less intuitive for either the editors or the developer.

**Comment by erezrokah** [comment]
The challenge here was to mirror the widget behaviour in the side by side editor, so it was postpone as a part of the original PR.

**Comment by cbix** [comment]
I just realized that even other widgets are not storing anything in my frontmatter with `i18n: duplicate` so I need to deal with fetching data from the default locale anyway.
Which makes this purely a netlify-cms frontend issue.

**Comment by barthc** [comment]
> I just realized that even other widgets are not storing anything in my frontmatter with i18n: duplicate

The `duplicate`  flag should work for other widgets, can you show your config?

**Comment by cbix** [comment]
@barthc Ah, you're right, it does work. I probably messed something up by changing a field form `i18n: false` to `i18n: duplicate` and of course the field didn't magically get added in the translated markdown file ;)

**Comment by cbix** [comment]
@barthc Ok I figured out the `hidden` widget doesn't work with `i18n: duplicate` which is kinda crucial for my case to work because editors are supposed to create pages in different collections that get built using different templates.
Versions are netlify-cms-app 2.12.24 and netlify-cms-core 2.30.7 and I'm testing with netlify-cms-proxy-server.

My config.yml:
```yaml
...
i18n:
  structure: multiple_files
  locales: [en, de]
  default_locale: en

collections:
  - name: content-pages
    label: Content Pages
    folder: content/pages
    create: true
    i18n: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: content-page, i18n: duplicate}
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: Image, name: image, widget: image, i18n: duplicate, required: false}
      - {label: Body, name: body, widget: markdown, i18n: true}
```

After creating a new page in netlify-cms, I get two new markdown files in content/pages.
test.en.md:
```Markdown
---
templateKey: content-page
title: test
image: /img/test.png
---
test body
```
and test.de.md:
```Markdown
---
title: testfoo
image: /img/test.png
---
test inhalt
```

In my previous test I had a collection with `create: false` and manually set the `templateKey` field for development.
