### ISSUE TITLE
TypeError: e.get is not a function

### ISSUE THREAD

**Issue by nicco88** [netlify/netlify-cms#4422]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Wanted to produce an array of texts / strings, using the markdown widget

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.11`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36`

**CMS configuration**
```
publish_mode: editorial_workflow
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway

media_folder: static/images/uploads
public_folder: images/uploads
collections:
  # PAGES
  - label: Pages
    name: pages
    files:
      # FAQ PAGE ENGLISH
      - label: FAQ Page English
        name: faqPageFileEn
        file: 'src/content/locales/en/faqPage.yml'
        fields:
          - name: faqPage
            label: FAQ Page
            widget: object
            fields:
              - name: faqHeading
                label: FAQ Heading
                widget: string
                required: true
              - name: faqContent
                label: FAQ Content
                widget: list
                fields:
                  - name: question
                    label: Question
                    widget: string
                    required: true
                  - name: paragraphs
                    label: Paragraphs
                    widget: list
                    fields:
                      - widget: markdown

**Comment by erezrokah** [comment]
Hi @nicco88, can you please fill in the missing parts in the issue template (`Describe the bug`, `To Reproduce`, `Screenshots `)

**Comment by nicco88** [comment]
Sorry, I wasn't sure what was the bug produced by either, however, I was able to solve by changing the config into the following config and it worked:

```yml
      # FAQ PAGE ENGLISH
      - label: FAQ Page English
        name: faqPageFileEn
        file: 'src/content/locales/en/faqPage.yml'
        fields:
          - name: faqPage
            label: FAQ Page
            widget: object
            fields:
              - name: faqHeading
                label: FAQ Heading
                widget: string
                required: true
              - name: faqContent
                label: FAQ Content
                widget: list
                fields:
                  - { label: Question, name: question, widget: string }
                  # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓ THIS FIXED WHAT I WAS TRYING TO ACCOMPLISH
                  - { label: Paragraphs, name: paragraphs, widget: list, field: { widget: markdown, label: Paragraph } }
```
So I'm closing the issue.

@erezrokah thank you for checking out anyway :)
