### ISSUE TITLE
Field hint text

### ISSUE THREAD

**Issue by timbomckay** [netlify/netlify-cms#4466]
**Is your feature request related to a problem? Please describe.**
We're creating something for clients and I'm sure they're not going to know what the variety of fields actually mean. I know the `label` doesn't have to match the `name` but I think a description/hint/help option would benefit the content author to know what that particular field does. Such as why there's a `title` & `linktitle` field, or `description` & `summary` field, or helpful information relating to the field, or even links to documentation more thoroughly describing the field.

**Describe the solution you'd like**
```yml
- name: "page"
  fields:
    - {
      label: "Title",
      name: "title",
      widget: "string",
      help: "The title of the page used in the hero & social meta info"
    },
    - {
      label: "Link Title",
      name: "linktitle",
      widget: "string",
      help: "Title used when linking to this page"
    }
```

**Describe alternatives you've considered**
I can create a section on our own site for documentation describing the various fields, or use CSS `:after` pseudos to hack in some help text, but as far as I can tell this isn't a feature just yet.
