### ISSUE TITLE
config should have required property 'options' - Clearstatus Netlify

### ISSUE THREAD

**Issue by thelynchpin** [netlify/netlify-cms#4489]
I get this error post a successful build and deploy on netlify.

https://youthful-swartz-68b931.netlify.app/

Error loading the CMS configuration
Config Errors:
config should have required property 'options'
Check your config.yml file.

**Comment by erezrokah** [comment]
Hi @thelynchpin, one of your `select` widgets is missing the `options` configuration:
```yml
fields:
    - label: "Name"
    name: "name"
    widget: string
    - label: "Group"
    name: "group"
    widget: select
    multiple: false
    required: false
    - label: "Description"
    name: "description"
    widget: string
    required: false
    - label: "Link"
    name: "link"
    widget: string
    required: false
```
