### ISSUE TITLE
Add ability to disable preview links per collection

### ISSUE THREAD

**Issue by pmpinto** [netlify/netlify-cms#4516]
**Is your feature request related to a problem? Please describe.**
Currently, there doesn't seem to be any way to disable preview links per collection.
We have `show_preview_links` which will disable preview links globally.

**Describe the solution you'd like**
Either something like:
```yml
collections:
  - name: 'authors'
    # …
    preview_path: false
```

or 

```yml
collections:
  - name: 'authors'
    # …
    preview_links: false # to avoid confusion with global 'show_preview_links' option
```

Or any other variant really.
Perhaps global setting would have precedence local setting.

**Additional context**
It would be useful to have something like this for collections that don't actually have a page. For instance, I have an authors collection, but there's no authors page. Authors are related to blog posts. And blog posts need a preview link. Authors don't.
