### ISSUE TITLE
Error when publishing a post (API_ERROR: Failed to execute 'json' on 'Response')

### ISSUE THREAD

**Issue by penguoir** [netlify/netlify-cms#4521]
**Describe the bug**
When trying to publish a document, I get the error message:

```
Failed to persist entry: API_ERROR: Failed to execute 'json' on 'Response': body stream is locked
```

<details>
<summary>
Full trace
</summary>

```
API_ERROR: Failed to execute 'json' on 'Response': body stream is locked
    at new t (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:51:142489)
    at new i (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:51:142796)
    at E.handleRequestError (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:51:158483)
    at E.request (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:51:158866)
    at async E.uploadBlob (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:55:8385)
    at async Promise.all (index 0)
    at async E.persistFiles (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:55:602)
    at async t.runWithLock (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:216:12733)
    at async K.persistEntry (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:28:79228)
    at async Object.onPersist (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:241:79287)
```

</details>

**To Reproduce**
1. Set up repo as shown in https://netlify-cms-now.now.sh/
2. Publish to Vercel
3. In the editor, press "publish"

**Applicable Versions:**
netlify-cms-app 2.13.1
netlify-cms-core 2.33.1
netlify-cms 2.10.66
using GitHub and Vercel

**CMS configuration**

<details>
<summary>
CMS config
</summary>

```
backend:
  name: github
  repo: sheepsixteen/schools
  branch: master
  base_url: [redacted, but I promise it's correct]
  auth_endpoint: api/auth

media_folder: /assets
public_folder: /assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Lesson number", name: "lesson_number", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
```
</details>

**Additional context**

  * I've tried all the steps on the Netlify "common issues" page, including giving access to the OAuth app in my organisation.
  * I thought this might be an issue with the Vercel identity provider, but there isn't a place where `.json()` is called.
