### ISSUE TITLE
Problem with field-specific media_folder

### ISSUE THREAD

**Issue by gtitov** [netlify/netlify-cms#4529]
I want my post to have one cover that is stored in assets so Hugo is able to resize it. Also my post have multiple images inside text (markdown widget) that I want to be stored in static so I can add these with the UI. Hope it's clear: cover in assets to resize, images inside text in static to add them without any code.

I came up with this config.yml:
```yml
backend:
  name: git-gateway
  branch: master
media_folder: 'static/img/blog'
public_folder: '/img/blog'
collections:
  - name: 'blog'
    label: 'Posts'
    folder: 'content/blog'
    create: true
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}'
    editor:
      preview: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Cover'
        name: 'image'
        widget: 'image'
        media_folder: '/assets/covers'
        public_folder: '/covers'
        allow_multiple: false
      - label: 'Post'
        name: 'body'
        widget: 'markdown'
```

Paths to files appears as I expect them to, like that:
```markdown
---
title: Test
date: 2020-11-01T19:40:17.107Z
author: gman
image: /covers/lighthouse.jpg
---
Post body
![Sample](/img/blog/desert.jpg)
```

But the cover is stored in `static/img/blog/lighthouse.jpg` **not** in `assets/covers/lighthouse.jpg`.

So it looks like I can't set field based media folder... Is it even possible to do it as I described? Or I didn't understand docs right? Or I did something wrong?

Here is the [repo](https://github.com/gtitov/kartapost) if needed

_Originally posted by @gtitov in https://github.com/netlify/netlify-cms/pull/3208#issuecomment-720141474_
