### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by theredwillow** [netlify/netlify-cms#4567]
When I try to create lists with fields, the preview widget breaks on the /admin page. I can use the control and add images, etc... just as expected. But I get "TypeError: Cannot read property 'get' of undefined" instead of the preview.

This is probably some kind of user error. I'm new to Netlify and I'm trying to learn how to create an image slideshow/gallery, but this error doesn't help me troubleshoot at all.

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.27`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/img
public_folder: /img
collections:
  - name: required-page
    label: Required Page
    files:
      - file: src/pages/index.md
        label: Home Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: page
          - label: Title
            name: title
            widget: hidden
            default: Home Page
          - label: Description
            name: description
            widget: text
            hint: Please provide a description of what is on this page so that search
              engines can display what to expect on your page more accurately.
          - name: slide
            label: Slideshow
            widget: list
            optional: true
            fields:
              - label: Title
                name: imgTitle
                widget: string
              - label: Image
                name: imgSrc
                widget: image
              - label: Description
                name: imgDesc
                widget: string
          - label: Sections
            name: sections
            widget: list
            field:
              label: Section
              name: section
              widget: markdown
    publish: true
    sortable_fields:
      - commit_date
      - commit_author
    view_filters: []
  - sortable_fields:
      - commit_date
      - title
      - commit_author
      - description
    view_filters: []
    meta: {}
    name: page
    folder: src/pages/other-pages
    publish: true
    label: Page
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: page
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
        hint: Please provide a description of what is on this page so that search
          engines can display what to expect on your page more accurately.
      - label: Sections
        name: sections
        widget: list
        field:
          label: Section
          name: section
          widget: markdown
    create: true

```
