### ISSUE TITLE
Collection view does not reflect the value of boolean fields whose values is 'false'

### ISSUE THREAD

**Issue by eamonnbell** [netlify/netlify-cms#462]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Collection view does not reflect the value of boolean fields whose values is 'false'

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a collection with at least one boolean field

```  
  - name: "booltest"
    label: "Boolean Test"
    folder: "_bools"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Boolean1 - default T", name: "boolean1", widget: "boolean", default: true}
      - {label: "Boolean2 - default F", name: "boolean2", widget: "boolean", default: false}
      - {label: "Boolean3 - no default", name: "boolean3", widget: "boolean"}
```

2. Create new entry in this new collection in CMS UI
3. Change state of at least one boolean field to false
4. Click save
5. Collection view does not reflect the value of boolean fields whose values is 'false'

![image](https://user-images.githubusercontent.com/4513526/27511860-f28d8168-5926-11e7-8419-87ae5a1f8dcd.png)

**- What is the expected behavior?**

The card corresponding to the entry in collection view should show the value of boolean fields whose values is 'false'

**- Please mention your node.js, and operating system version.**

Node v8.1.2 on Linux x86_84 (Chromium 59)
