### ISSUE TITLE
Netlify CMS previews not working for Eleventy sites.

### ISSUE THREAD

**Issue by kylesloper** [netlify/netlify-cms#4649]
#### Just the other day the Previews were working like normal -- see screenshots below:

![image](https://user-images.githubusercontent.com/45979758/100517690-6a12e780-3184-11eb-917b-3daeb54716af.png)

#### And then out of nowhere they stopped -- see screenshots below:

![image](https://user-images.githubusercontent.com/45979758/100517701-8adb3d00-3184-11eb-8cce-4b3a3a9922e0.png)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: Tested in chrome 22, safari, android
 - Node.JS version:

**CMS configuration**

```yaml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  open_authoring: false

media_folder: "static/img" # Media files will be stored in the repo under images/uploads
logo_url: /static\img\moonface-logo.png


collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Link", name: "permalink", widget: "string", default: "(page-title)/index.html" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Hide on navbar", name: "parent", widget: "boolean", default: false }
          - { label: "Title on navbar", name: "key", widget: "string", required: false }
          - { label: "Order on navbar", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown", required: false }
```
