### ISSUE TITLE
Filter does not work with i18n

### ISSUE THREAD

**Issue by martinjagodic** [netlify/netlify-cms#4665]
**Describe the bug**
Property `filter` does not work when you add `i18n: true` to the same collection.

**Expected behavior**
`filter: {field: "visibleInAdmin", value: true}` should work when `i18n: true` is applied.

**Applicable Versions:**
 - Netlify CMS version: 2.10.73
 - Git provider: GitHub
 - OS: MacOS BigSur
 - Browser version Chrome 86

**CMS configuration**
```yaml
...
i18n:
  structure: multiple_files
  locales: [sl, en, hr]

collections:
  - name: "posts"
    label: "Posts"
    i18n: true # if I remove this, fiter is applied
    label_singular: "post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    filter: {field: "visibleInAdmin", value: true}

    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {name: "visibleInAdmin", widget: "hidden", default: true, i18n: duplicate}
```

**Additional context**
Tested on a Hugo project
