### ISSUE TITLE
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130...

### ISSUE THREAD

**Issue by JR-Carroll** [netlify/netlify-cms#4692]
**Describe the bug**
Having blended the netlify tutorial and sourcing the netlify starter blog sample project into my gatsby website, I have all of it working except the 'preview' portion of the WYSIWYG.  

What I'm really looking for is a way to do greater debug on this, as I doubt I'll be able to create a repo for you all to reproduce this.  Right now, all I see is "There's been an error - please open an issue on GitHub." and there isn't any other real substantial details for me to continue to review.

Based on my own research this is likely a problem with page template and/or the wrapper for the preview, but I can't source the problem since everything is minified.  (Following the various web articles to --no-uglify and.or to modify gatsby-node.js webPackConfig block with optimization minifiy: false didn't do anything -- I suspect 'me' error and limited understanding of webpack + gatsby).  

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2183723/101323967-b4503480-3826-11eb-9356-f99b35559f4e.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.14.3`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
  branch: master
  commit_messages: null
  create: Create {{collection}} “{{slug}}”
  update: Update {{collection}} “{{slug}}”
  delete: Delete {{collection}} “{{slug}}”
  uploadMedia: "[skip ci] Upload “{{path}}”"
  deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/img
public_folder: /img
collections:
  - sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    view_filters: []
    meta: {}
    name: blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: src/pages/content/blog
    view_groups: []
    publish: true
    label: Blog
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Featured Post
        name: featuredpost
        widget: boolean
      - label: Featured Image
        name: featuredimage
        widget: image
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
    create: true

```

**Additional context**
Any thoughts on how I can get greater visibility into what the problem is under the hood?  aka a '-v' on the build =P or some other way to source what line(s) are causing this error?
