### ISSUE TITLE
Templating folder for new posts

### ISSUE THREAD

**Issue by wangsongiam** [netlify/netlify-cms#476]
It would be awesome If user create new post with a dynamic folder each time.
for example, a templated folder with a name from the title.
```yaml
  - name: "dynamic blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    folder: "/blog/{{slug}}"
    media_folder: "/blog/{{slug}}"
```
which gives `/blog/YYYY-MM-DD-example-post/index.md`.

### benefits
Users could upload images or other media to the post folder, not another unified media folder. So the images for each post would be sitting inside the related folder, makes it easier to manage.

tree view
```
blog
├── YYYY-MM-DD-example
│   ├── index.md
│   └── image-for-example.png
│   └── image-2-for-example.png
├── YYYY-MM-DD-example-2
│   ├── index.md
│   └── image-for-example-2.png

```
