### ISSUE TITLE
Please replace with a clear and descriptive title

### ISSUE THREAD

**Issue by p3lican** [netlify/netlify-cms#4783]
I'd like to inject a "Game or Event Year" into the slug. Rather than creating fields for day and year, I'd like to be able to strip the year from the single "Event Date" field entry and use that in my slug. 

Basically exactly what you have done for summaries: https://www.netlifycms.org/docs/beta-features/#summary-string-template-transformations.

```
collections:
  - label: "Games"
    name: "games"
    folder: "content/games"
    create: true
    identifier_field: gamenumber
    slug: 'game-{{gamenumber}}-{{opponent.teamname}}-{{gamedate | date('YYYY')}}' <-- something like that
    format: 'json'
    fields:
      - {label: "Game Number", name: "gamenumber", widget: "string"}
      - {label: "Game Date", name: "gamedate", widget: "datetime"}
```
