### ISSUE TITLE
Setting up deploy preview with editorial workflow on GitLab results in two pipelines per commit

### ISSUE THREAD

**Issue by fkohrt** [netlify/netlify-cms#4786]
**Describe the bug**

I am using GitLab as backend and have the editorial workflow enabled. After configuring a GitLab environment/review app in my `.gitlab-ci.yml` to make deploy preview links work, every push to an existing merge request results in two pipelines per commit. The first pipeline is still associated with the previous commit and fails immediately, the second pipeline is associated with the new commit and succeeds. This repeats for every subsequent push through Netlify CMS (but not for manual git commits).

**To Reproduce**

<details>
<summary><code>.gitlab-ci.yml</code></summary>

```yml
image: monachus/hugo

stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - main

deploy_review:
  stage: deploy
  script:
    - hugo
  artifacts:
    paths:
      - public
  environment:
    name: $CI_COMMIT_REF_NAME
    url: "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/"
    auto_stop_in: 1 hour
  only:
    - branches
  except:
    - main
```
</details>

1. Save changes to an existing article
2. Make some more changes to the same article and save
3. Receive two emails, one for a failed pipeline and one for a fixed pipeline

**Expected behavior**

The first pipeline for the old commit should not be triggered.

**Applicable Versions:**

 - Netlify CMS version: 2.10.78
 - Git provider: GitLab
 - OS: Fedora 32
 - Browser version Firefox 83.0

**CMS configuration**

<details>
<summary>Netlify CMS <code>config.yml</code></summary>

```yml
backend:
  name: gitlab
  repo: <repo>
  branch: main
  auth_type: implicit
  app_id: <id>
  preview_context: "pages:deploy"
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
site_url: <url>
logo_url: "/images/site-logo.svg"
collections:
  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "content"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    preview_path: "{{title}}/index.html"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm"}
      - {label: "Last Updated", name: "lastmod", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm", required: false}
      - {label: "Slug", name: "slug", widget: "string", required: false}
      - {label: "Menu", name: "menu", widget: "string", default: "main", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "content/posts"
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    preview_path: "posts/{{year}}/{{month}}/{{title}}/index.html"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Florian", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm"}
      - {label: "Last Updated", name: "lastmod", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm", required: false}
      - {label: "Slug", name: "slug", widget: "string", required: false}
#      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Summary", name: "summary", widget: "string", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
```
</details>

**Additional context**

My actual <code>.gitlab-ci.yml</code> is a little larger, I shortened it for the purpose of this bug report.

<details>
<summary>full <code>.gitlab-ci.yml</code></summary>

```yml
image: monachus/hugo

stages:
  - pre-deploy
  - deploy
  - post-deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

deploy_review:
  stage: deploy
  script:
    - hugo
  artifacts:
    paths:
      - public
  environment:
    name: $CI_COMMIT_REF_NAME
    url: "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/"
    auto_stop_in: 1 hour
  only:
    - /^cms\/.*$/

announce_target_pending:
  stage: pre-deploy
  environment:
    name: demo
  script:
    - 'curl --verbose --request POST --header "PRIVATE-TOKEN: ${API_PRIVATE_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_NAMESPACE}%2F${CI_PROJECT_NAME}/statuses/$CI_COMMIT_SHA?state=pending&context=pages:deploy&target_url=${CI_PAGES_URL}"'
  only:
    - /^cms\/.*$/

announce_target_success:
  stage: post-deploy
  environment:
    name: demo
    auto_stop_in: 1 hour
  script:
    - 'apt-get update && apt-get install -y jq'
    - 'JSON=$(curl --header "PRIVATE-TOKEN: ${API_PRIVATE_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_NAMESPACE}%2F${CI_PROJECT_NAME}/environments?name=$CI_COMMIT_REF_NAME" 2> /dev/null)'
    - 'EXTERNAL_URL=$(echo $JSON | jq -r ".[0].external_url")'
    - 'curl --verbose --request POST --header "PRIVATE-TOKEN: ${API_PRIVATE_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_NAMESPACE}%2F${CI_PROJECT_NAME}/statuses/$CI_COMMIT_SHA?state=success&context=pages:deploy&target_url=${EXTERNAL_URL}"'
  needs: ["deploy_review"]
  only:
    - /^cms\/.*$/

```
</details>
