### ISSUE TITLE
{{fields.slug}} is not taken into account

### ISSUE THREAD

**Issue by fbnlsr** [netlify/netlify-cms#4787]
**Describe the bug**
I'm using a `slug` field on a collection, and when creating/updating an entry, the `{{fields.slug}}` tag I'm using in both the `slug` and `path` tags are ignored, hence the index file I'm creating is in the wrong place.

**Expected behavior**
File should be created in the correct sub-directory, respecting the `{{fields.slug}}` directive.

**Applicable Versions:**
 - Netlify CMS version: 2.10.77
 - Git provider: GitHub

**CMS configuration**
```yml
backend:
  name: "git-gateway"
  branch: "master"
  commit_messages:
    create: ":pencil2: Add new {{collection}}"
    update: ":pencil2: Update {{collection}}"
    delete: ":fire: Remove {{collection}}"
media_folder: "static/img/uploads"
site_url: "https://www.coeurcarre.fr"
logo_url: "https://www.coeurcarre.fr/img/logo-netlify.png"
collections:
  - name: "albums"
    label: "Albums"
    label_singular: "Album"
    folder: "/content/albums"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{year}}-{{month}}-{{day}}-{{fields.slug}}/index"
    path: "{{year}}-{{month}}-{{day}}-{{fields.slug}}/index"
    editor:
      preview: false
    summary: "{{year}}-{{month}}-{{day}} | {{artist}} - {{title}} ({{albumDate}})"
    fields:
      - label: "Titre de l'album"
        name: "title"
        widget: "string"
        required: true
      - label: "Artiste"
        name: "artist"
        widget: "string"
        required: true
      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true
      - label: "Label"
        name: "label"
        widget: "string"
      - label: "Date"
        name: "albumDate"
        widget: "number"
        value_type: "int"
      - label: "Image de couverture"
        name: "cover"
        widget: "image"
        allow_multiple: false
      - label: "Date de publication"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
      - label: "Note (entre 0 et 10)"
        name: "note"
        widget: "number"
      - label: "Brouillon ?"
        name: "draft"
        widget: "boolean"
        default: true
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Lien Discogs"
        name: "discogs"
        widget: "string"
      - label: "Article"
        name: "body"
        widget: "markdown"
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "À propos"
        file: "/content/a-propos/index.md"
        editor:
          preview: false
        fields:
          - label: "Titre"
            name: "title"
            widget: "string"
            required: true
          - name: "menu"
            widget: "hidden"
            default: "main"
          - label: "Contenu"
            name: "body"
            widget: "markdown"
```

**Comment by erezrokah** [comment]
Hi @fbnlsr, I believe the correct configuration for your use case is:
```yaml
# use the field to generate the slug
slug: '{{fields.slug}}' 
# use the generated slug to build the path
path: '{{year}}-{{month}}-{{day}}-{{slug}}/index'
```

Or:
```yaml
# only use slug config if not saving files to sub folders
slug: '{{year}}-{{month}}-{{day}}-{{fields.slug}}/index'
```

I've tested it and it seems to provide the desired result.
Closing the issue, if the suggested config doesn't work, please comment and I'll reopen the it.
