### ISSUE TITLE
I am getting too Long File Names

### ISSUE THREAD

**Issue by haris-aqeel** [netlify/netlify-cms#4788]
```
media_folder: static/assets
public_folder: assets

collections:
  - name: blog_audio
    label: Blog Audio
    folder: content/blog
    create: true
    filter: {field: "Blog Type", value: "audio"}
    fields:
      - { name: "Blog Title", label:  "Blog Title" }
      - { name: "Blog description", label: "Blog Description" }
      - { name: "Blog date", label: "Blog Publish Date", widget: "datetime", dateFormat: "DD MMM, YYYY"}
      - { name: "Blog URL", label: "Blog URL", widget: "string", oneOf: ["video", "audio"], pattern: [ "^http(s)?://.*..*(/)?", "Must be a  Audio URL" ]}
  - name: blog_video
    label: Blog Video
    folder: content/blog
    create: true
    filter: {field: "Blog Type", value: "video"}
    fields:
      - { name: "Blog Title", label:  "Blog Title" }
      - { name: "Blog image", label: "Blog Image", widget: image, oneOf: ["video", "text"] }
      - { name: "Blog description", label: "Blog Description" }
      - { name: "Blog date", label: "Blog Publish Date", widget: "datetime", dateFormat: "DD MMM, YYYY"}
      - { name: "Blog URL", label: "Blog URL", widget: "string", oneOf: ["video", "audio"], pattern: [ "^http(s)?://.*..*(/)?", "Must be a Video URL" ]}
  - name: blog_text
    label: Blog Text
    folder: content/blog
    create: true
    filter: {field: "Blog Type", value: "text"}
    fields:
      - { name: "Blog Path", label:  "Blog Path", widget: "string", required: true, pattern:  ['^[a-z0-9]+(?:-[a-z0-9]+)*$','A Path can have no spaces or special characters']}
      - { name: "Blog Title", label:  "Blog Title" }
      - { name: "Blog image", label: "Blog Image", widget: image, oneOf: ["video", "text"] }
      - { name: "Blog description", label: "Blog Description" }
      - { name: "Blog date", label: "Blog Publish Date", widget: "datetime", dateFormat: "DD MMM, YYYY"}
      - { name: "Blog Detail", label: "Blog Body", widget: markdown, oneOf: ["text"] }
      - { name: "Author Name", label: "Author Name", oneOf: ["text"] }
      - { name: "Author Detail", label: "Author Detail", oneOf: ["text"] }
```

This is a fragment of my Config.yml file. Once I created a blog from it. I am getting too long file names of the created content through netlify CMS. Due to long file names I am not able to use git commands because the git pull commands have some length restrictions. 
You can see this in the below two images
![image](https://user-images.githubusercontent.com/56465230/103484692-a932f900-4e12-11eb-9e09-a2c308d6ba48.png)

![image](https://user-images.githubusercontent.com/56465230/103484681-915b7500-4e12-11eb-8049-76ffe6a66073.png)
