### ISSUE TITLE
Please replace with a clear and descriptive title

### ISSUE THREAD

**Issue by PedroOndh** [netlify/netlify-cms#4841]
**Describe the bug**
When i add a new entry in author collection appears on the list, but is not selectable through the relation widget from other articles. If i hardcode the id of the author Netlify CMS doesn't find it and return an error. If i enter from any other browser or in incognito mode this error dissapear and the author is found. But the error remains even after cleaning the cache on the original browser.

**To Reproduce**

**Expected behavior**
Find the new item in the collection

**Screenshots**
![Captura de pantalla 2021-01-14 a las 10 56 43](https://user-images.githubusercontent.com/45435602/104576494-2864d000-5650-11eb-8ae7-68d5ae5e444b.png)

**Applicable Versions:**
 - Netlify CMS version: 2.10.81
 - Git provider: BitBucket
 - OS: macOS Catalina
 - Browser version: Chrome (maybe happens in other browsers, but as it's dependand on cookies/localStorage or some similar issue couldn't replicate it)

**CMS configuration**

```
backend:
  name: bitbucket
  repo: xxxxxx/cbn-jekyll-cms # Path to your Bitbucket repository
  branch: develop
  auth_type: implicit
  app_id: xxxxxxxx

# for using local backend run "npx netlify-cms-proxy-server" and enter in /admin
local_backend: true

media_folder: "assets/media/uploads"
logo_url: https://xxx/assets/media/logo/logo-animated.gif
display_url: https://xxx

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Blog post"
    description: "Entries sortable by Publish Date or title on 'Sort by' button"
    folder: "collections/_posts"
    filter:
      field: "categories"
      value: "blog"
    sortable_fields: ['publish-date', 'title']
    view_filters:
      - label: '2020'
        field: "publish-date"
        pattern: '2020'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Post Category", name: "categories", widget: "hidden", default: "blog"}
      - {label: "Post Author", name: "author", widget: "relation", collection: "team-members", search_fields: ["name","email"], value_field: "email", display_fields: ["name"], required: false}
      - {label: 'Cover Image', name: 'image', widget: 'image', tagname: '', hint: "File type: PNG / File size: as small as possible (Ask designer)"}
      - {label: "Publish date", name: "publish-date", widget: "datetime", format: "YYYY-MM-DD HH:mm a", default: ""}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h3", required: false}
      - {label: "Permalink", name: "slug", widget: "string", hint: "The URL of this post. WARNING: IF YOU EDIT THIS FIELD YOU CANNOT LEAVE IT BLANK", pattern: ["^[a-zA-Z\\-0-9]+$", "Must not have whitespaces and not being empty"], required: false}
      - {label: 'Meta Description', name: 'description', widget: 'string', required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags",  widget: select, options: ['Products', 'Engineering', 'Customers', 'News', 'Retail', 'Insights', 'Search', 'UX'], multiple: true}
[...]

  - name: "team-members"
    label: "Team Members"
    label_singular: "Team Member"
    folder: "collections/_team-members"
    create: true
    slug: "{{slug}}"
    sortable_fields: ['name']
    identifier_field: name
    fields:
      - {label: "Name and Last Name", name: "name", widget: "string"}
      - {label: "Job title", name: "jobtitle", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Team", name: "team", widget: select, options: ["Leadership", "Search", "Interface", "Data", "UX","Operations","DevOps","Enterprise","Delivery", "Play", "Motive"]}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
      - label: "Social Media"
        name: "social-media"
        widget: "list"
        required: false
        fields:
          - {label: Social Media Name, name: name, widget: select, options: ["Facebook", "Twitter", "Instagram", "Linkedin", "Google"]}
          - {label: URL, name: url, widget: string, hint: "For example: https://www.instagram.com/username/"}
      - {label: "Birth date", name: "birthday", widget: "datetime", format: "YYYY-MM-DD HH:mm a", default: "", required: false}
      - {label: "Tags", name: "tags",  widget: select, options: ['Products', 'Engineering', 'Customers', 'News', 'Retail', 'Insights', 'Search', 'UX'], multiple: true}
      - {label: "Active", name: "active", widget: "boolean", default: true}
```
