### ISSUE TITLE
Can't edit files collections translations

### ISSUE THREAD

**Issue by fedetibaldo** [netlify/netlify-cms#4844]
**Describe the bug**

What appears to be a bug in the admin UI makes editing files collections translations impossible. In particular, I can't edit the translated version of my fields, as every keystroke gets overridden by the state of the main translation.

**To Reproduce**
1. Enable i18n:
```yaml
i18n:
  structure: single_file
  locales: [en, it]
  default_locale: en
```
2. Add the following collection (the relevant parts are the `i18n: true` on the collection and on the intro field)
```yaml
  - name: meta
    label: Meta
    i18n: true
    files:
      - name: about
        label: About
        file: content/meta/about.md
        fields:
          - {label: Intro, name: intro, widget: text, i18n: true}
```
3. Navigate to `/#/collections/meta/entries/about` in your admin interface
4. **Choose your own adventure!**
- - Fill the intro on the English side. See that the Italian side has been filled with the same info automatically. Try to publish. See the error in the console `Uncaught (in promise) TypeError: Cannot read property 'get' of undefined at serializeEntryValues.js:43`

    ![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/21128334/104813737-5cd0bb80-580b-11eb-8df9-4dab72151996.gif)

  - Fill the intro on the English side. Try to edit the intro on the Italian side. Apparently, nothing happens. Try to publish. See the output in the file (the last character I inputted has been appended to the Italian version).
    ```yaml
    ---
    en:
      intro: asd
    it:
      intro: asdd
    ---
    ```
    ![ezgif com-gif-maker (10)](https://user-images.githubusercontent.com/21128334/104813963-a53ca900-580c-11eb-9fa8-307dfd42097d.gif)

**Expected behavior**

I'd expect file translations to work the same way collection translations do.

**Applicable Versions:**

 - Netlify CMS version: 2.14.12
 - Git provider: local backend (`git-gateway` with `netlify-cms-proxy-server`)
 - OS: Windows 10
 - Browser version: Edge Version 87.0.664.75 (Official build) (64-bit)
 - Node.JS version: 12.16.1

**CMS configuration**
```yaml
development:
  backend:
    name: git-gateway
  local_backend: true
  site_url: http://localhost:8000

i18n:
  structure: single_file
  locales: [en, it]
  default_locale: en

media_folder: content/media
public_folder: content/media
site_url: https://fedetibaldo.com

collections:
  - name: meta
    label: Meta
    i18n: true
    files:
      - name: about
        label: About
        file: content/meta/about.md
        fields:
          - {label: Intro, name: intro, widget: text, i18n: true}

  - name: posts
    label: Posts
    folder: content/posts
    create: true
    i18n: true
    # Force relative paths (necessary for gatsby-remark-images)
    # https://www.gatsbyjs.com/plugins/gatsby-remark-images/#usage-in-markdown
    public_folder: '../media'
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Date
        name: date
        widget: datetime
        i18n: duplicate
      - label: Body
        name: body
        widget: markdown
        i18n: true
```

**Additional context**
I'm currently setting `window.CMS_ENV` to "development". I am also running a local cms backend with `npx netlify-cms-proxy-server`

**Comment by fedetibaldo** [comment]
Found the issue. One must add `i18n: true` to the file declaration too, like so:
```yaml
collections:
  - name: meta
    label: Meta
    i18n: true
    files:
      - name: about
        label: About
        i18n: true # <<< NEW
        file: content/meta/about.md
        fields:
          - {label: Intro, name: intro, widget: text, i18n: true}
```

Cheers.
