### ISSUE TITLE
TypeError: e.join is not a function

### ISSUE THREAD

**Issue by Fourmou** [netlify/netlify-cms#4851]
**Describe the bug**

When i try to add a new post this error appears

Error details
TypeError: e.join is not a function

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.84`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0`

**CMS configuration**
```
publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
media_folder: /content/wp-content/uploads
public_folder: /wp-content/uploads
collections:
  - sortable_fields:
      - commit_date
      - title
      - date
      - author
    view_filters: []
    meta: {}
    name: posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: content/posts
    view_groups: []
    publish: true
    label: Post
    fields:
      - label: Type
        name: type
        widget: string
        default: post
      - label: Title
        name: title
        widget: string
      - label: Categories
        name: categories
        widget: list
        default: news
      - label: Author
        name: author
        widget: string
        default: Chris Manoel
      - label: Publish Date
        name: date
        widget: datetime
      - label: Featured Image
        name: image
        widget: image
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
    create: true
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"

```

**Additional context**
