### ISSUE TITLE
Preview Pane doesn't use custom CSS

### ISSUE THREAD

**Issue by vnourdin** [netlify/netlify-cms#4852]
**Describe the bug**
The Preview Pane doesn't use custom CSS (nor custom template).

**Duplicate ?**
Seems close enough to #1599 except I don't know or use Emotion, only pure CSS.

**To Reproduce**
1. Create a project (existing Eleventy blog in my case)
2. Add config for your collections (simple blog articles, nothing tricky)
3. In your `admin/index.html` register your CS in a script block. I tried followings, separately and together:
```
<script>
  CMS.registerPreviewStyle('https://my-blog.com/css/my-blog.css');
  CMS.registerPreviewStyle('/css/my-blog.css'); /* relative path on generated site */
  CMS.registerPreviewStyle('/src/css/my-blog.css'); /* relative path on repository */

  var PostPreview = createClass({
    render: function() {
      var entry = this.props.entry;
      var image = entry.getIn(['data', 'image']);
      var bg = this.props.getAsset(image);
      return h('div', {"className": "text"}, this.props.widgetFor('body'));
    }
  }); /* simple preview with only the body, easy to see the difference */

  CMS.registerPreviewTemplate("posts", PostPreview);
</script>

```
4. Deploy your site and reload Netlify CMS after cleaning cache.

**Expected behavior**
When editing an article/element of a collection, the preview pane on the right use your custom CSS.
Mine have dark background and light text color so easy to see if working or not.

**Screenshots**
![screenshot_no_preview_css](https://user-images.githubusercontent.com/11643685/105083981-fdd2a700-5a95-11eb-9405-2a483ab6157f.jpg)

**Applicable Versions:**
 - Netlify CMS version: 2.10.84
 - Git provider: GitLab
 - OS: Debian stable
 - Browser version Firefox Developer Edition 85.0b9, Google Chrome 87.0.4280.141

**CMS configuration**
```
backend:
  name: gitlab
  repo: me/my-blog
  auth_type: implicit
  app_id: ???

publish_mode: editorial_workflow

media_folder: "src/img"
public_folder: "/img"

site_url: https://my-blog.com/
display_url: https://my-blog.com/

show_preview_links: false

locale: 'fr'

collections:
  - name: "posts"
    label: "Articles"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "titre", name: "title", widget: "string"}
      - {label: "date de publication", name: "date", widget: "datetime"}
      - {label: "description", name: "description", widget: "text"}
      - {label: "image", name: "image", widget: "image", required: false}
      - {label: "description de l'image", name: "image_description", widget: "text", required: false}
      - {label: "contenu", name: "body", widget: "markdown"}

```
