### ISSUE TITLE
Shows Error Loading config.yml Even Though Admin Page Loads

### ISSUE THREAD

**Issue by pjlamb12** [netlify/netlify-cms#4883]
**Describe the bug**
I'm trying to implement the CMS with a Scully app, and when I go to the admin page I see an "Error loading config.yml" error. The weird thing is that the admin page allows me to log in and shows all the admin page content. 

**To Reproduce**
To reproduce, fork [this repo](https://github.com/pjlamb12/scully-netlify-cms) and run `npm run netlify`. Then go to the /admin page.

**Expected behavior**
I would expect the `config.yml` file to be loaded without an error showing.

**Screenshots**
![image](https://user-images.githubusercontent.com/2006222/105950473-ad29f380-602b-11eb-99db-fac5ee872d10.png)

**Applicable Versions:**

 - Netlify CMS version: https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js
 - Git provider: GitHub
 - OS: Built on macOS, deployed to Netlify
 - Browser version: latest Chrome

 - Node.JS version:

**CMS configuration**

```
# prettier-ignore

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
media_folder: 'static/img' # Folder where user uploaded files should go
```
