### ISSUE TITLE
Pages outside of 'path' are also listed in collections

### ISSUE THREAD

**Issue by lbischof** [netlify/netlify-cms#4884]
**Describe the bug**

A folder collection with `path` specified as `{{slug}}/index` also lists pages in `folder` that are not in a subdirectory.

**To Reproduce**
1. Clone repository: `coming...`
2. Start a webserver and local proxy server (see README.md)
3. Visit localhost:8080/admin/
4. See that "This should not appear" is also listed.

**Expected behavior**
I expect that if `path` is specified with a `/`, then all posts/pages that do not fulfill this requirement should be ignored and not listed. 

**Applicable Versions:**

 - Netlify CMS version: 2.10.84

**CMS configuration**

**Comment by smashercosmo** [comment]
I can confirm. Seems like a bug. I'll look into it.

**Comment by smashercosmo** [comment]
@erezrokah I'm trying to replicate it in dev-test demo. This doesn't work. What am I doing wrong?
```js
  window.repoFiles = {
   _test: {
      post1: {
        'index.md': {
          content: '---\ntitle: "post1"\n---\n',
        }
      },
      post2: {
        'index.md': {
          content: '---\ntitle: "post2"\n---\n',
        }
      },
      post3: {
        'index.md': {
          content: '---\ntitle: "post3"\n---\n',
        }
      }
    }
  }
```
```yml
collections:
  - name: 'test'
    label: 'Test'
    folder: '_test'
    path: '{{slug}}/index'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
```
