### ISSUE TITLE
Weird code widget behavior

### ISSUE THREAD

**Issue by arpadgabor** [netlify/netlify-cms#4897]
**Describe the bug**

The `code` widget shows weird behavior on page load and when focused:

1. When the page loads, the window will always (try to) jump to the bottom of the code editor.
2. When focused on the editor, it will automatically resize to `300px` (~13 lines). Also, while typing the editor will not resize to fit the content unless you blur, but then again on focus it resize back.

**To Reproduce**

Add a `code` widget to a collection and type more than ~13 lines.

**Expected behavior**

Code editor to resize based on content and not jump to the end of it on page load.

**Screenshots**

https://user-images.githubusercontent.com/9270494/106400007-8ea96b00-6424-11eb-9419-d0aa167c2f6c.mp4

**Applicable Versions:**

 - Netlify CMS version: 2.10.84
 - Git provider: Github, local backend
 - OS: Windows 10 WSL 2
 - Browser version: Chromium Edge 88.0.705.56

**CMS configuration**

```yml
local_backend: true
backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: static/media
public_folder: /media

editor:
  preview: false

collections:
  - name: articles
    label: Articles
    create: true
    folder: content/articles
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        widget: string

      - name: description
        label: Description
        widget: string

      - name: body
        widget: code
        label: Content
        default_language: markdown
        allow_language_selection: false
        output_code_only: true

      - name: image
        label: Cover Image
        widget: object
        fields:
          - name: default
            widget: image
            label: Default Image
            hint: Will be shown on website, not required.
            required: false
          - name: social
            widget: image
            label: Social-Media Image
            required: true
            hint: Will be shown on social media instead of default image if both present.
```

**Additional context**

Trying to use the code editor instead of the default Markdown editor, main reason being that the `raw` mode in the markdown editor does not have syntax highlighting.

Maybe instead of adjusting the height of the editor to the content, a fullscreen mode (or at least the ability to set the height) would improve the experience.
