### ISSUE TITLE
JSON Frontmatter object widget at the end -> parse error

### ISSUE THREAD

**Issue by asafamr** [netlify/netlify-cms#4908]
netlify-cms-app 2.14.16
netlify-cms-core 2.36.14
netlify-cms 2.10.86

json frontmatter - writing and then parsing collections whose last widget is an object widget raises a JSON parse error 

if i'm not mistaken:
NCMS json frontmatter formatter trims outer curly brackets during serialization 
they are re-added separately if the first/last latter aren't a curly bracket during parsing
when the last widget is an object widget a curly bracket would be removed during serialization but would not be appended later leading to a JSON parse error

I'm creating a PR where the opening and closing brackets are added jointly

**Comment by asafamr** [comment]
a reporducing config yaml

```yaml
backend:
  name: github
  branch: staging
  open_authoring: true
  repo: aaa/bbb
collections:
  - name: planet
    create: true
    extension: json
    fields:
      - name: title
        hint: displayed in viewport and popup
        label: Title
        required: true
        widget: string
      - name: position
        fields:
          - name: x
            label: X
            required: true
            value_type: float
            widget: number
          - name: 'y'
            label: 'Y'
            required: true
            value_type: float
            widget: number
        hint: position in space
        label: Position
        required: true
        widget: object
    filter:
      field: type
      value: planet
    folder: space-data/content
    format: json-frontmatter
    label: Planet
    path: '{{title}}'
media_library:
  name: disabled
publish_mode: editorial_workflow
```
