### ISSUE TITLE
Allow template tags on field's default value to store unique ID or filepath

### ISSUE THREAD

**Issue by regisphilibert** [netlify/netlify-cms#4918]
## Problem

Currently a big limitation of NetlifyCMS is the inability to create relationship based on an immutable data. Other GitBased CMS allow to use the filepath of a content file as relation connexion. 

In NetlifyCMS we usually fallback on using the Title of an entry to establish this relation. But Title can change, and upon doing so, the connexion is lost.

## Solution

Fixing this would mean to insert a certain dynamically generated Front Matter value upon a file creation. Given Front Matter key could then be used as a reference point in establishing relations.

If template tags were allowed on field's `default` key, this would simply mean adding a hidden string populated upon file creation:

```yaml
  - name: path
    widget: hidden
    hidden: true
    default: '{{dirname}}/{{filename}}.{{extension}}'
```
