### ISSUE TITLE
TypeError: e.join is not a function

### ISSUE THREAD

**Issue by OlenaSakhno** [netlify/netlify-cms#4953]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.91`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36`

**CMS configuration**
```
publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
public_folder: /images/uploads
media_folder: /images/uploads
collections:
  - sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
    view_filters: []
    meta: {}
    name: blog
    slug: "{{slug}}"
    folder: posts
    view_groups: []
    publish: true
    label: Blog
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: blog
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Image
        name: image
        widget: image
      - label: Rating (scale of 1-5)
        name: rating
        widget: number
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
    create: true
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"

```

**Additional context**
