### ISSUE TITLE
Failed to persist entry: API_ERROR: Not Found

### ISSUE THREAD

**Issue by oscarruz** [netlify/netlify-cms#4955]
Hi!

I'm new with Netlify CMS and I want to integrate Vuepress with Netlify CMS in the backend.

/blog/.vuepress/public/admin/config.yml:

```
backend:
  name: github
  repo: oscarruz/blog03
  api_root: https://api.github.com
branch: main
media_folder: "blog/.vuepress/public/media"
public_folder: "/media"
site_url: https://blog03-oruz.netlify.app/
display_url: https://blog03-oruz.netlify.app/
publish_mode: editorial_workflow
collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.md"
        delete: false
        fields:
          - {label: Body, name: body, widget: markdown}
  - label: "Posts"
    name: "posts"
    folder: "blog/_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/:slug"}
```
I have created the OAuth from GitHub to Netlify. In Netlify is works the deploy correctly. I'm very confused.

---
Only I want to create a developer scenario with Vuepress + Netlify CMS I know that Github is necessary of course.. but I'm not sure if it's necessary the Netlify config.
---

From this link:[https://blog03-oruz.netlify.app/] I see the default configuration of Vuepress and from /admin I can login to Netlify using Github account when I create a new post show the error message: Failed to persist entry: API_ERROR: Not Found :(

So I have two questions:

1) How to solve this error message?
2) How to config the home page to show the posts from Netlify?

Thanks in avance!

**Comment by erezrokah** [comment]
Hi @oscarruz the `branch: main` part should be under `backend`. Also `api_root` is not required.
Can you try:
```yml
backend:
  name: github
  repo: oscarruz/blog03
  branch: main
```
