### ISSUE TITLE
preview_path not does not correspond to the real path

### ISSUE THREAD

**Issue by tpavel-aspose** [netlify/netlify-cms#4963]
![Uploading image.png…]()
hugo version: 0.80.0
In editor path equal as `conversion-api/conversion-sdk-api/xhtml-converter`
 title: `XHTML converter`
 Preview link now as
`
 netlify.app/html/conversion-api-conversion-sdk-api-xhtml-converter-_index
 `
but must equal
`netlify.app/html/conversion-api/conversion-sdk-api/xhtml-converter/`

my config

```
collections:
  - name: html
    label: HTML
    label_singular: "Page"
    folder: content/html
    slug: "{{slug}}"
    preview_path: "html/{{slug}}"
    create: true
    media_folder: ''
    public_folder: ''
    nested:
      depth: 100
      summary: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Keywords", name: "keywords", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Weight", name: "weight", widget: "number", value_type: "int", default: 10, step: 10, min: 1, max: 1000, required: false }
      - {label: "Type", name: "type", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
    meta: { path: { widget: string, label: "Path", index_file: "_index" } }
    summary: "{{weight}} - {{title}}"
    sortable_fields: ["weight",'title', "commit_author", "commit_date"]
```
