### ISSUE TITLE
Failed to persist entry: API_ERROR: Not Found

### ISSUE THREAD

**Issue by l0u1sg** [netlify/netlify-cms#4977]
Hello, I configured my blog from this repo (https://github.com/W3Layouts/gatsby-starter-delog) except that I get this error when I want to make a post : Failed to persist entry: API_ERROR: Not Found. The github repo is not in an organization, it's private, but I checked the Auth0 for access to private repo. I even tried to pass my repo in public, but nothing works. Here is the content of my config.yml file :
```
backend:
  name: github
  # change repo to your git repository url
  repo: l0u1sg/blog

media_folder: static/assets
public_folder: /assets

collections:
  - name: settings
    label: Settings
    files:
      - name: config
        label: Config
        file: site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Site Title
            required: true
          - widget: string
            name: siteUrl
            label: Website URL
            required: true
          - widget: text
            name: description
            label: Description
            default: ""
            required: false
          - widget: object
            name: home
            label: Homepage Options
            fields:
              - widget: string
                name: title
                label: Title
                default: ""
                required: false
              - widget: markdown
                name: description
                label: Description
                default: ""
                required: false
  - name: blog
    label: Blog
    folder: _data/blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: BlogPost }
      - name: path
        label: Path
        widget: string
        pattern: [".{8,}", "Must have at least 8 characters"]
        hint: "Path must start with /"
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
```

Does anyone have a solution?

**Comment by erezrokah** [comment]
Hi @l0u1sg can you trying setting the default branch to `main`

```yaml
backend:
  name: github
  # change repo to your git repository url
  repo: l0u1sg/blog
  branch: main
```
