### ISSUE TITLE
Config option to escape required fields when in draft stage of editorial workflow

### ISSUE THREAD

**Issue by tonyketcham** [netlify/netlify-cms#5013]
### Is your feature request related to a problem? Please describe.
Using the editorial workflow while working on pieces of long-form content with many required fields may warrant multiple iterations of work to be done on a single entry in order for all of those required fields to be entered in. Currently, I'm not aware of a way to save a draft without all the required fields being filled out.

That's frequently been a pain point I've encountered on a WIP entry and usually just leads me to leave the editor up for multiple days until I can fill everything out and finally be able to save - a very dicey practice if your computer crashes and you somehow lose the `localforage` backup of all that work, which has unfortunately happened to me a couple times. The dirty workaround is to add dummy data to those fields, but then that can easily sneak its way into production and is therefore bad practice in my opinion.

### Describe the solution you'd like
I would like an `editorial_workflow` config option allowing `required` field validation to be turned off for content currently in/going into `draft` status. This would then allow a new entry to be saved as a draft without adding in all of the required fields. Then, content going into the `ready` or `in_review` statuses could run the `required` field validation hook to ensure nothing publish-ready is missing any required fields.

**Comment by tonyketcham** [comment]
Example config:
```yml
publish_mode: editorial_workflow
required_fields:
  - status: draft
    enforced: false
  - status: pending_review
    enforced: false 
  - status: pending_publish
    enforced: true
```

This schema allows future extension of the editorial workflow, such as a feature where users could define additional entry statuses.
