### ISSUE TITLE
Config option for list widget to allow default list when using fields option 

### ISSUE THREAD

**Issue by Pearce-Ropion** [netlify/netlify-cms#5016]
**Is your feature request related to a problem? Please describe.**

Currently, the `default` option on the list widget only allows you to provide a default value when using the `field` option which allows you to specify a comma separated list of string items. However, when using the `fields` option, the `default` option has no effect, instead you must specify defaults for each of the individual fields being used.

From the documentation:
> you may specify a list of strings to populate the basic text field, but declare defaults on the child widgets if you are specifying `fields`

This makes it impossible to, for example, specify a default list of 2 or more items

**Describe the solution you'd like**

Add a new config option for list widgets called `default_list` that allows users to specify the default list that should be applied for new entries.

For example, given the config:
```yml
label: Buttons
label_singular: button
name: buttons
widget: list
fields:
  - label: Text
    name: text
    widget: string
  - label: Link
    name: link
    widget: string
  - label: Type
    name: type
    widget: select
    default: primary
    options:
      - label: Primary
        value: primary
      - label: Secondary
        value: secondary
  - label: Inverted
    name: inverted
    widget: boolean
    required: false
default_list:
  - text: Get Started
    link: /get-started/
    type: primary
    inverted: false
  - text: Book a Demo
    link: /demo/
    type: secondary
    inverted: true
```

The default list in the editor pane should contain 2 items with the shape: 
```javascript
[
    {
        text: "Get Started",
        link: "/get-started/",
        type: "primary",
        inverted: false,
    },
    {
        text: "Book a Demo",
        link: "/demo/",
        type: "secondary",
        inverted: true,
    },
];
```
