### ISSUE TITLE
i18n with multiple_files misidentify "md" within the slug name as extension

### ISSUE THREAD

**Issue by artt** [netlify/netlify-cms#5049]
## Describe the bug

When using i18n with `multiple_files` structure with slug name containing "md", Netlify CMS incorrectly identify the `md` as the file extension, and insert `lx.md` there instead (where `lx` is the language).

## To Reproduce

* Create a `yml` file with the following i18n options:
```yml
i18n:
  structure: multiple_files
  locales: [th, en]
  default_locale: th
```
* Create a collection, for example, with
```yml
folder: content/members
path: "{{title}}/index"
media_folder: ''
public_folder: ''
i18n: true
fields:
  - {name: title, label: Title, i18n: duplicate}
```
* Create a new "member" object whose name contains "md", for example, "Samdy"

## Expected behavior
The following files get created:
```
/content/members
  - /samdy
    - /index.en.md
    - /index.th.md
    - /profile.png
```
## Actual behavior
```
/content/members
  - /saen.mdy/index.md
  - /samdy/profile.png
  - /sath.mdy/index.md
```

**Applicable Versions:**
- netlify-cms-app 2.14.26
- netlify-cms-core 2.38.5
- netlify-cms 2.10.96
 - Git provider: GitHub
 - OS: Mac OS 11
 - Browser version: chrome 88

**CMS configuration**
```yml
backend:
  name: github
  repo: ...
  branch: main
  accept_roles:
    - admin
    - editor

publish_mode: editorial_workflow

site_url: ...

media_folder: media_folder

i18n:
  structure: multiple_files
  locales: [th, en]
  default_locale: th

collections:
- name: members
  label: Members
  label_singular: member
  identifier_field: memberid
  create: true
  folder: content/members
  path: "{{slug}}/index"
  preview_path: '/members/{{memberid}}/'
  media_folder: ''
  public_folder: ''
  summary: '{{name}} - {{org}}'
  i18n: true
  fields:
    - {name: memberid, label: Member ID, i18n: duplicate}
    - {name: name, label: Name, i18n: true}
    - {name: image, label: 'Image', widget: image, i18n: duplicate}
    - {name: email, label: Email, i18n: duplicate, required: false}
    - {name: body, label: Body, widget: markdown, i18n: true}
```
