### ISSUE TITLE
Update suggested for Object Widget documentation.

### ISSUE THREAD

**Issue by tommulkins** [netlify/netlify-cms#5053]
The example in the object widget documentation needs to be updated to reflect the fields belonging to the object are in a list.

Currently:
```
 - label: "Address"
    name: "address"
    widget: "object"
    collapsed: true
    fields: 
      - {label: "Street Address", name: "street", widget: "string"}
      - {label: "City", name: "city", widget: "string"}
      - {label: "Postal Code", name: "post-code", widget: "string"}
```
      
 Correction:
```
 - label: "Address"
    name: "address"
    widget: "object"
    collapsed: true
    fields: 
      [
        {label: "Street Address", name: "street", widget: "string"},
        {label: "City", name: "city", widget: "string"},
        {label: "Postal Code", name: "post-code", widget: "string"},
      ]
```

**Comment by erezrokah** [comment]
Hi @tommulkins, both ways are valid `yaml` syntax to define a list and work in the CMS.
You can check it in http://www.yamllint.com/

Closing the issue. Please comment if I got this wrong

**Comment by tommulkins** [comment]
Hi @erezrokah 

When I try to use the current syntax I get the following error:

![image](https://user-images.githubusercontent.com/11251283/109983402-c845ee00-7cd0-11eb-9910-06481205f487.png)

Here's my complete `collections` yaml portion:

```
collections:
  - name: "articles"
    label: "Articles"
    folder: "src/pages/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "article",
        }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "Resources",
              "Community Investing",
              "Alternative Investing",
              "Finance 101",
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Author Signature",
          name: "authorsignature",
          widget: object,
          fields:
            - { label: Author Name, name: name, widget: string },
            - { label: Author Description, name: description, widget: text },
            - { label: Author Picture, name: picture, widget: image },
        }
```

When I explicitly place the widget object `fields` into an array it works fine:

```
fields:
            [
              { label: Author Name, name: name, widget: string },
              { label: Author Description, name: description, widget: text },
              { label: Author Picture, name: picture, widget: image },
            ],
```

Perhaps I'm missing something I just don't find obvious.

**Comment by erezrokah** [comment]
I think the reason is that you're mixing different styles.
This works:
```yaml
collections:
  - name: "articles"
    label: "Articles"
    folder: "src/pages/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "article",
        }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "Resources",
              "Community Investing",
              "Alternative Investing",
              "Finance 101",
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Author Signature"
        name: "authorsignature"
        widget: object,
        fields:
          - { label: Author Name, name: name, widget: string }
          - { label: Author Description, name: description, widget: text }
          - { label: Author Picture, name: picture, widget: image }
```
