### ISSUE TITLE
TypeError: e.join is not a function

### ISSUE THREAD

**Issue by garytate123** [netlify/netlify-cms#5058]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.96`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: main
media_folder: _site/images/uploads
public_folder: /images/uploads
collections:
  - sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
    view_filters: []
    name: blog
    slug: "{{slug}}"
    folder: posts
    view_groups: []
    publish: true
    label: Blog
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: layouts/post.njk
      - label: Title
        name: title
        widget: string
      - label: "Description:"
        name: "description:"
        widget: string
      - label: Tags
        name: tags
        widget: list
        default: post
      - label: Publish Date
        name: date
        widget: datetime
      - label: Featured Image
        name: thumbnail
        widget: image
      - label: Rating (scale of 1-5)
        name: rating
        widget: hidden
      - label: Body
        name: body
        widget: markdown
    type: folder_based_collection
    create: true
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"

```

**Additional context**
