### ISSUE TITLE
TypeError: Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by woodhull** [netlify/netlify-cms#5060]
**Describe the bug**
Not sure how this happens, but I got it after trying to edit text after inserting an image. 

**To Reproduce**
Not sure

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.14.24`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: main
media_folder: img/uploads
public_folder: /img/uploads
publish_mode: editorial_workflow
collections:
  - sortable_fields:
      - commit_date
      - title
      - date
      - author
    view_filters: []
    name: blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    folder: _posts
    view_groups: []
    publish: true
    label: Blog
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Author
        name: author
        widget: string
        required: false
      - label: Featured Image
        name: featured_image
        widget: string
        required: false
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
    type: folder_based_collection
    create: true
  - sortable_fields:
      - commit_date
      - title
      - commit_author
    view_filters: []
    name: resources
    slug: "{{slug}}"
    editor:
      preview: false
    folder: _resources
    view_groups: []
    publish: true
    label: Resources
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    type: folder_based_collection
    create: true
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"

```

**Additional context**
