### ISSUE TITLE
YAML comments get removed

### ISSUE THREAD

**Issue by pmpinto** [netlify/netlify-cms#5099]
**Describe the bug**
I have a YAML file with some comments at the top. This file is linked to a collection in the CMS. I edit the file through the CMS. The comments are removed.

**To Reproduce**
1. Have a file collection pointing to a YAML file
2. Make sure you have commented lines at the top of that YAML file
3. Edit the file through the CMS
4. Inspect the PR and watch those comments vanish

**Expected behavior**
Comments stay there.

**Applicable Versions:**

 - Netlify CMS version: 2.14.29
 - Git provider: GitHub
 - OS: macOS 11.0.1
 - Browser Brave v1.19.92

 - Node.JS version: v12.17.0

**CMS configuration**
```yml
collections:
  - name: 'something'
    label: 'Something'
    editor:
      preview: false
    files:
      - label: 'My file'
        name: 'my_file'
        file: '_data/my_file.yml'
        fields:
          …
```
