### ISSUE TITLE
Nested Collections ignore editorial_workflow when deleting a file.

### ISSUE THREAD

**Issue by robdodson** [netlify/netlify-cms#5106]
**Describe the bug**
Using nested collections with `editorial_workflow: true`, a pull request is created when an entry is added or edited. But if you delete an entry it doesn't generate a PR for the deletion, it just deletes and commits to `main`.

**To Reproduce**
Add a new post. Merge the PR. Then delete the post.

**Expected behavior**
A PR is generated in which the post is deleted.

**Actual behavior**
A commit on `main` is generated in which the post is deleted.

**Applicable Versions:**

 - Netlify CMS version: netlify-cms-app 2.14.29, netlify-cms-core 2.38.7, netlify-cms 2.10.99
 - Git provider: GitHub
 - OS: macOS
 - Browser version Chrome 88

**CMS configuration**

```yaml
backend:
  name: git-gateway
  branch: main
collections:
  - name: docs
    label: Docs
    label_singular: Doc
    folder: src/docs
    create: true
    # adding a nested object will show the collection folder structure
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
```
