### ISSUE TITLE
Error loading the CMS configuration YAMLSyntaxError: Document contains trailing content not separated by a ... or --- line at line 4, column 7:Please replace with a clear and descriptive title

### ISSUE THREAD

**Issue by bhargavmoveo** [netlify/netlify-cms#5129]
Error loading the CMS configuration
Config Errors:
YAMLSyntaxError: Document contains trailing content not separated by a ... or --- line at line 4, column 7:

  if(true) {
  ^^^^^^^^^^…
  
  
![Screenshot 2021-03-17 at 12 07 20 PM](https://user-images.githubusercontent.com/76469453/111427927-d65a2c80-871c-11eb-91fc-c66d8f0cbf6b.png)

Check your config.yml file.

```
media_folder: static/img
public_folder: /img
collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Home Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: Home Banner
            name: homebanner
            widget: object
            fields:
              - label: Banner Content
                name: bannertitle
                widget: string
                required: false
              - label: Strane Banner Logo
                name: stranebannerlogo
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Banner Flower Block Image
                name: homeblackflowerblock
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Banner Grey diamond Image
                name: homegreydiamondblock
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Banner Grey Diamond Text Image
                name: homegreydiamondtextblock
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Banner Yellow Cart image
                name: homeyellowcartblock
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Banner bottom section icon
                name: iconcrownblack
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Banner bottom section content
                name: bannerbottomtext
                widget: string
                required: false
          - label: Strane two blocks
            name: stranetwoblocks
            widget: object
            fields:
              - label: Strane first block
                name: stranefirstblock
                widget: object
                fields:
                  - label: Strabe block logo
                    name: straneblocklogo
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Content
                    name: content
                    widget: string
                  - label: Button Text
                    name: buttontext
                    widget: string
              - label: Strane second block
                name: stranesecondblock
                widget: object
                fields:
                  - label: Strabe block logo
                    name: straneblocklogo
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Content
                    name: content
                    widget: string
                  - label: Button Text
                    name: buttontext
                    widget: string
          - label: Three Tab
            name: threetab
            widget: object
            fields:
              - label: Vape it
                name: tab1
                widget: object
                fields:
                  - label: Vap cloud image
                    name: vapcloud
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Vap it image
                    name: vapitimage
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: vap it Pax icon
                    name: paxicon
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Left content
                    name: leftcontent
                    widget: markdown
                  - label: Left link text
                    name: leftlinktext
                    widget: string
                  - label: Left link
                    name: leftlink
                    widget: string
                  - label: Right content
                    name: rightcontent
                    widget: markdown
                    required: false
                  - label: Right link text
                    name: rightlinktext
                    widget: string
                    required: false
                  - label: Right link
                    name: rightlink
                    widget: string
                    required: false
              - label: Smoke it
                name: tab2
                widget: object
                fields:
                  - label: Smoke it cloud
                    name: smokecloud
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Smoke it image
                    name: smokeimage
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Smoke it joint
                    name: smokejoint
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Left content
                    name: leftcontent
                    widget: markdown
                  - label: Left link text
                    name: leftlinktext
                    widget: string
                  - label: Left link
                    name: leftlink
                    widget: string
                  - label: Right content
                    name: rightcontent
                    widget: markdown
                    required: false
                  - label: Right link text
                    name: rightlinktext
                    widget: string
                    required: false
                  - label: Right link
                    name: rightlink
                    widget: string
                    required: false
              - label: Dab it
                name: tab3
                widget: object
                fields:
                  - label: Dab it rig
                    name: dabrig
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Dab it image
                    name: dabimage
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Dab it tool
                    name: dabtool
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Dab it torch
                    name: dabtorch
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Left content
                    name: leftcontent
                    widget: markdown
                  - label: Left link text
                    name: leftlinktext
                    widget: string
                  - label: Left link
                    name: leftlink
                    widget: string
                  - label: Right content
                    name: rightcontent
                    widget: markdown
                    required: false
                  - label: Right link text
                    name: rightlinktext
                    widget: string
                    required: false
                  - label: Right link
                    name: rightlink
                    widget: string
                    required: false
      - file: src/pages/strane/index.md
        label: Strane
        name: strane
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: strane-page
          - label: Strane top section
            name: stranetoppart
            widget: object
            fields:
              - label: Strane logo
                name: stranelogo
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Strane top section content
                name: stranetopcontent
                widget: text
          - label: Strane sections
            name: stranepagesections
            widget: list
            default:
              - stranepagesectionname: ''
              - stranepagesectionlink: ''
              - stranesectionimage: ''
              - stranesectionimagereducemotion: ''
              - stranesectionimage2: ''
              - stranesectioncontent: ''
            fields:
              - label: Strane section name
                name: stranepagesectionname
                widget: string
              - label: Stranepage section link
                name: stranepagesectionlink
                widget: string
              - label: Strane section image
                name: stranesectionimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                    default: ''
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
                    default: ''
              - label: Strane section reducemotion image
                name: stranesectionimagereducemotion
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: ''
                    required: false
                  - label: Alt
                    name: alt
                    default: ''
                    widget: string
                    required: false
              - label: Strane section hover image
                name: stranesectionimage2
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                    default: ''
                  - label: Alt
                    name: alt
                    widget: string
                    default: ''
                    required: false
              - label: Stranesectioncontent
                name: stranesectioncontent
                widget: markdown
      - file: src/pages/live/index.md
        label: Live
        name: live
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: live-page
          - label: Live top section
            name: livetoppart
            widget: object
            fields:
              - label: Live logo
                name: livepagelogo
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Live top section content
                name: livetopcontent
                widget: text
          - label: Live slider heading
            name: livepagesliderheading
            widget: string
          - label: Live page slider
            name: livepageslider
            widget: list
            default:
              - livepagesliderimage: ''
              - livepageslidercontent: ''
            fields:
              - label: Slider image
                name: livepagesliderimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: ''
                    required: false
                  - label: Alt
                    name: alt
                    default: ''
                    widget: string
                    required: false
              - label: slider content
                name: livepageslidercontent
                widget: markdown
          - label: Live sections
            name: livepagesections
            widget: list
            default:
              - livepagesectionname: ''
              - livepagesectionlink: ''
              - livesectionimage: ''
              - livesectionimagereducemotion: ''
              - livesectionimage2: ''
              - livesectioncontent: ''
            fields:
              - label: Live section name
                name: livepagesectionname
                widget: string
                required: false
              - label: Live section link
                name: livepagesectionlink
                widget: string
                required: false
              - label: Live section image
                name: livesectionimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: ''
                    required: false
                  - label: Alt
                    name: alt
                    default: ''
                    widget: string
                    required: false
              - label: Live section reducemotion image
                name: livesectionimagereducemotion
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: ''
                    required: false
                  - label: Alt
                    name: alt
                    default: ''
                    widget: string
                    required: false
              - label: Live section image2
                name: livesectionimage2
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: ''
                    required: false
                  - label: Alt
                    name: alt
                    default: ''
                    widget: string
                    required: false
              - label: Live section content
                name: livesectioncontent
                widget: markdown
          - label: Live bottom content
            name: livepagebottomcontent
            widget: markdown
      - file: src/pages/pax/index.md
        label: Pax
        name: pax
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: pax-page
          - label: Pax top section
            name: paxtoppart
            widget: object
            fields:
              - label: Pax logo
                name: paxpagelogo
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Pax logo right
                name: paxpagelogoright
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Pax top section content
                name: paxtopcontent
                widget: text
          - label: Pax sections
            name: paxpagesections
            widget: list
            default:
              - paxsectionimage: ''
              - paxsectionimagereducemotion: ''
              - paxsectionimage2: ''
              - paxsectioncontent: ''
            fields:
              - label: Pax section image
                name: paxsectionimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: ''
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Pax section reducemotion image
                name: paxsectionimagereducemotion
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: ''
                    required: false
                  - label: Alt
                    name: alt
                    default: ''
                    widget: string
                    required: false
              - label: Pax section image2
                name: paxsectionimage2
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: ''
                    required: false
                  - label: Alt
                    name: alt
                    default: ''
                    widget: string
                    required: false
              - label: Pax section content
                name: paxsectioncontent
                widget: markdown
          - label: Pax slider heading
            name: paxpagesliderheading
            widget: string
          - label: Pax slider
            name: paxpageslider
            widget: list
            default:
              - paxpageslidercontent: ''
            fields:
              - label: Paxpageslidercontent
                name: paxpageslidercontent
                widget: markdown
          - label: Pax page sections2
            name: paxpagesections2
            widget: list
            default:
              - paxsectionimage: ''
              - paxsectioncontent: ''
              - paxsectioncontentlink: ''
              - paxsectioncontenturl: ''
              - paxsectioncontentlinkmobile: ''
              - paxsectioncontenturlmobile: ''
              - paxsectioncontentimage: ''
              - paxsectioncontentimagelink: ''
            fields:
              - label: Pax section image
                name: paxsectionimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: ''
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    default: ''
                    required: false
              - label: Pax section content
                name: paxsectioncontent
                widget: markdown
              - label: Pax section content link
                name: paxsectioncontentlink
                widget: string
                required: false
              - label: Pax section content url
                name: paxsectioncontenturl
                widget: string
                required: false
              - label: Pax section content mobile link Name
                name: paxsectioncontentlinkmobile
                widget: string
                required: false
              - label: Pax section content mobile url
                name: paxsectioncontenturlmobile
                widget: string
                required: false
              - label: Pax section content image
                name: paxsectioncontentimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: ''
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    default: ''
                    required: false
              - label: Pax section content image link
                name: paxsectioncontentimagelink
                widget: string
                required: false
      - file: src/pages/faq/index.md
        label: Faq
        name: faq
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: faq-page
          - label: Faq heading
            name: faqpageheading
            widget: string
          - label: Faq category list
            name: faqcategorylist
            widget: list
            default:
              - faqcategoryheading: ''
                faqcategoryheadername: ''
                faqcategoryheaderlink: ''
            fields:
              - label: Faq category heading
                name: faqcategoryheading
                widget: string
              - label: Faq category header name
                name: faqcategoryheadername
                widget: string
              - label: Faq category header link
                name: faqcategoryheaderlink
                widget: string
              - label: Faq category content list
                name: faqcategorycontentlist
                widget: list
                default:
                  - faqcontenttitle: ''
                    faqcontentbody: ''
                fields:
                  - label: Faq content title
                    name: faqcontenttitle
                    widget: text
                  - label: Faq content body
                    name: faqcontentbody
                    widget: markdown
      - file: src/pages/process/index.md
        label: Process
        name: process
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: process-page
          - label: Going back section
            name: goingback
            widget: object
            fields:
              - label: Going back section name
                name: goingbacksectionname
                widget: string
                required: false
              - label: Going back section link
                name: goingbacksectionlink
                widget: string
                required: false
              - label: Journey heading
                name: journeyheading
                widget: string
                required: false
              - label: Going back title image
                name: goingbacktitle
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Going back content
                name: goingbackcontent
                widget: text
                required: false
              - label: Going back crown image
                name: goingbackcrownimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Going back crown text
                name: goingbackcrowntext
                widget: text
                required: false
              - label: Going back stars
                name: goingbackstars
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
          - label: Seed section
            name: seedsection
            widget: object
            fields:
              - label: Seed section name
                name: seedsectionname
                widget: string
                required: false
              - label: Seed section link
                name: seedsectionlink
                widget: string
                required: false
              - label: Search seed title
                name: searchseedtitle
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Search seed title star
                name: searchseedtitlestar
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Search seed content
                name: searchseedcontent
                widget: text
                required: false
              - label: Seed yellow after line
                name: seedyellowafterline
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
          - label: Cultivate section
            name: cultivatesection
            widget: object
            fields:
              - label: Cultivate section name
                name: cultivatesectionname
                widget: string
                required: false
              - label: Cultivate section link
                name: cultivatesectionlink
                widget: string
                required: false
              - label: Cultivate title
                name: cultivatetitle
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Cultivate watering image
                name: cultivatewatering
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Cultivate star image
                name: cultivatestar
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Cultivate star2 image
                name: cultivatestar2
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Cultivate content
                name: cultivatecontent
                widget: text
                required: false
              - label: Cultivate content2
                name: cultivatecontent2
                widget: text
                required: false
              - label: Cultivate flower image
                name: cultivateflower
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Cultivate flower star image
                name: cultivateflowerstar
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
          - label: Harvest section
            name: harvestsection
            widget: object
            fields:
              - label: Harvest section name
                name: harvestsectionname
                widget: string
                required: false
              - label: Harvest section link
                name: harvestsectionlink
                widget: string
                required: false
              - label: Harvest section title
                name: harvestsectiontitle
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Harvest title black dots image
                name: harvesttitleblackdots
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Harvest content
                name: harvestcontent
                widget: markdown
                required: false
              - label: Harvest content2
                name: harvestcontent2
                widget: markdown
                required: false
              - label: Harvest happy image
                name: harvesthappyimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Harvest happy image line
                name: harvesthappyimageline
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Harvest happy image small
                name: harvesthappyimagesmall
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Harvest happy image star
                name: harvesthappyimagestar
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
          - label: Lab magic section
            name: labmagicsection
            widget: object
            fields:
              - label: Lab magic section name
                name: labmagicsectionname
                widget: string
                required: false
              - label: Lab magic section link
                name: labmagicsectionlink
                widget: string
                required: false
              - label: Lab magic section title
                name: labmagicsectiontitle
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Lab magic section title star
                name: labmagicsectiontitlestar
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Lab magic section content
                name: labmagicsectioncontent
                widget: text
                required: false
              - label: Lab magic section content small
                name: labmagicsectioncontentsmall
                widget: text
                required: false
              - label: Lab diamond image
                name: labdiamondimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Lab diamond star
                name: labdiamondstar
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Lab diamond star2
                name: labdiamondstar2
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Lab whip image
                name: labwhipimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Lab product image
                name: labproductimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Lab badder image
                name: labbadderimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Lab star image
                name: labstarimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
          - label: All yours section
            name: allyourssection
            widget: object
            fields:
              - label: All yours section name
                name: allyourssectionname
                widget: string
                required: false
              - label: All yours section link
                name: allyourssectionlink
                widget: string
                required: false
              - label: All yours section title
                name: allyourssectiontitle
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: All yours section title line
                name: allyourssectiontitleline
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: All yours section content
                name: allyourssectioncontent
                widget: text
                required: false
          - label: Signature section
            name: signaturesection
            widget: object
            fields:
              - label: Signature section left
                name: signaturesectionleft
                widget: object
                fields:
                  - label: Signature content
                    name: signaturecontent
                    widget: markdown
                    required: false
                  - label: Signature section left image
                    name: signaturesectionleftimage
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Signature section left image2
                    name: signaturesectionleftimage2
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
              - label: Signature section right
                name: signaturesectionright
                widget: object
                fields:
                  - label: Signature content
                    name: signaturecontent
                    widget: markdown
                    required: false
                  - label: Signature section right image
                    name: signaturesectionrightimage
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Signature right diamond image
                    name: signaturerightdiamondimage
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Signature right diamond2 image
                    name: signaturerightdiamond2image
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
                  - label: Signature right diamond3 image
                    name: signaturerightdiamond3image
                    widget: object
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                      - label: Alt
                        name: alt
                        widget: string
                        required: false
      - file: src/pages/findastore/index.md
        label: Findstore
        name: findastore
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: findastore-page
          - label: Storeaddress
            name: storeaddress
            widget: list
            fields:
              - label: Storename
                name: storename
                widget: string
              - label: Storeaddress
                name: storeaddress
                widget: text
              - label: storeCity
                name: storecity
                widget: string
              - label: Storestate
                name: storestate
                widget: string
              - label: Storezip
                name: storezip
                widget: string
              - label: Storenumber
                name: storenumber
                widget: string
                required: false
              - label: Storeemail
                name: storeemail
                widget: string
                required: false
              - label: Storeurl
                name: storeurl
                widget: string
                required: false
              - label: Storelat
                name: storelat
                widget: string
              - label: Storelng
                name: storelng
                widget: string
```
