### ISSUE TITLE
Posts disappearing from Content Manager - Hugo - Netlify

### ISSUE THREAD

**Issue by rohiaudio** [netlify/netlify-cms#5130]
✅ Accessing the Admin page, using the editorial workflow and media assets all work perfectly fine. ✅ I'm able to create a post— the file is properly created and displays on my Hugo list page.

❌ After reloading or leaving the Content Manager in Netlify-CMS, the post disappears and "no entries found" is displayed. ❌ The post remains on my site, just not on the content manager.

**Applicable Versions:**

 - Netlify CMS version: 2.10.49
 - Git provider: Github
 - OS: N/A - Happens on all devices
 - Browser version Chrome, Safari, Firefox— latest

**CMS configuration**

```
backend:
  name: github
  repo: [redacted] # Path to your Github repository
  branch: master # Branch to update (master by default)
# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

site_url: [redacted]
display_url: [redacted]
collections:
  - name: 'Posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'content/posts'
    identifier_field: 'title'
    create: true
    summary: "{title}}"
    slug: '{{slug}}'
    path: '{{year}}/{{month}}/{{slug}}'
    preview_path: 'posts/{{year}}-{{month}}-{{slug}}'
    editor:
      preview: false
    filter: {field: "language", value: "en"}
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Category', name: 'categories', widget: 'select', options: ["Articles", "Updates", "Review", "Software", "Music"] }
      - { label: 'Tags', name: 'tags', widget: "list", allow_add: true, default: ["Tag"]}
      - { label: 'Image', name: 'image', widget: 'file', allow_multiple: false, required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Comments enabled', name: 'comments', widget: 'boolean', default: true, required: false }
```
