### ISSUE TITLE
Issue registering registerMediaLibrary(cloudinary) along with registerPreviewTemplate

### ISSUE THREAD

**Issue by tonymamo** [netlify/netlify-cms#5164]
**Describe the bug**
I'm trying to integrate `netlify-cms-media-library-cloudinary` into `netlify-cms` in a `gatsby` project.

I have custom preview templates set up, so I've registered my preview templates which use a wrapper to get `styled-components` working, along with trying to register the media library like so:

```
CMS.registerPreviewTemplate('blog', withStyledComponentsRendered(BlogPostPreview));

CMS.registerMediaLibrary(cloudinary);
```

When I view the CMS page, I get an error saying  "Error loading the CMS configuration" (screenshot below).

However, when I comment out all of my `registerPreviewTemplate` lines, the error goes away. I've tried removing the `withStyledComponentsRendered` wrapper, but that doesn't seem to be it.

Any insights? Thanks in advance!

**To Reproduce**

config.yml:
```
media_library:
  name: cloudinary
  config:
    cloud_name: ----- 
    api_key: -----
```

withStyledComponentsRendered.tsx:
```
import React, { useState, useEffect } from 'react';
import { StyleSheetManager } from 'styled-components';

const StyleInjector = ({ children }: { children: any }) => {
  const [iframeRef, setIframeRef] = useState<HTMLHeadElement | null>(null);

  useEffect(() => {
    const iframe = document.getElementsByTagName('iframe')[0];
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const iframeHeadElem = iframe.contentDocument!.head!;
    setIframeRef(iframeHeadElem);
  }, []);

  return iframeRef && <StyleSheetManager target={iframeRef}>{children}</StyleSheetManager>;
};

const withStyledComponentsRendered = (Comp: any) => {
  return (props: any) => (
    <StyleInjector>
      <Comp {...props} />
    </StyleInjector>
  );
};

export default withStyledComponentsRendered;
```

minimal src/cms/cms.ts file 
```
import CMS from 'netlify-cms-app';
import cloudinary from 'netlify-cms-media-library-cloudinary';

import IndexPagePreview from './preview-templates/IndexPagePreview';

import withStyledComponentsRendered from './withStyledComponentsRendered';

CMS.registerMediaLibrary(cloudinary);

CMS.registerPreviewTemplate('index', withStyledComponentsRendered(IndexPagePreview));
...
```

minimal gatsby-config
```
{
  resolve: 'gatsby-plugin-netlify-cms',
  options: {
    publicPath: 'cms',
    modulePath: `${__dirname}/src/cms/cms.ts`,
  },
},
```

**Expected behavior**

I can use the cloudinary media library in conjunction with preview templates

**Screenshots**

<img width="1005" alt="Screen Shot 2021-03-26 at 10 42 42 PM" src="https://user-images.githubusercontent.com/1933657/112707993-a7168e80-8e85-11eb-877e-11a2f295b8d2.png">

working with preview templates commented out:
<img width="859" alt="Screen Shot 2021-03-26 at 10 53 34 PM" src="https://user-images.githubusercontent.com/1933657/112708061-1b513200-8e86-11eb-8ee2-b505bcad8209.png">

**Applicable Versions:**

 - netlify-cms-app 2.14.32
 - netlify-cms-core 2.38.10
 - Git provider: github
 - OS: MacOS 11.2.3
 - Browser version Chrome 89.0.4389.90

 - Node.JS version:

**CMS configuration**

```
backend:
  name: github
  repo: tonymamo/getpackup
  api_root: https://api.github.com
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_library:
  name: cloudinary
  config:
    cloud_name: getpackup 
    api_key: 342326781417379

media_folder: static/img
public_folder: /img

collections:
...
```
