### ISSUE TITLE
Bulleted list behavior in rich text view of Markdown widget is unexpected

### ISSUE THREAD

**Issue by lfracalossiFA** [netlify/netlify-cms#5200]
**Describe the bug**
In the rich text view of a Markdown widget, the "bulleted list" behavior is strange and unexpected.

**To Reproduce**
- In the CMS UI, open a piece of content with a Markdown widget
- Type in some text in the rich-text view
- Select the text and hit the “bulleted list” button.
- Hit return to go to the next line.
- The text on the second line is indented, but does not have a bullet.

Furthermore:
- Selecting the second line of text, click the "bulleted list" item again
- The item is indented a second level and given a second-level bullet.

And even further:
- In the rich text view, type three lines of text
- Select the text and click "bulleted list"
- The first item gets a bullet and an indent. The second and third items are indented but not bulleted.

Since you can’t indent/outdent with the rich text editor, I have to manually go into the Markdown to change it. Which is fine for me, the engineer. I’m not sure I trust my CMS users to do that :wink:

**Expected behavior**
I expect that when you add an item to a bulleted list, you will get a bullet and the same level of indentation as the previous item.

**Screenshots**
![Screen Shot 2021-04-02 at 12 14 08 PM](https://user-images.githubusercontent.com/72401230/113454213-b477cf80-93d5-11eb-87c0-ac038f03486e.png)
![Screen Shot 2021-04-02 at 12 12 43 PM](https://user-images.githubusercontent.com/72401230/113454214-b5106600-93d5-11eb-81e5-9d17edba50e1.png)
![Screen Shot 2021-04-02 at 12 12 28 PM](https://user-images.githubusercontent.com/72401230/113454215-b5106600-93d5-11eb-855e-cb96c793ff6e.png)

**Applicable Versions:**
Netlify CMS version: 2.10.104
Git provider: GitHub
OS: Mac OS Catalina
Browser version: Chrome 89.0.4389.90
Node.JS version: v14.15.1
Jekyll: 4.2.0

**CMS configuration**
```
# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
publish_mode: editorial_workflow
#local_backend: true #only use when developing locally
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
        label: 'Author',
        name: 'author',
        widget: 'relation',
        collection: 'authors',
        display_fields: [display_name],
        search_fields: [display_name],
        value_field: 'name',
      }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'authors'
    label: 'Authors'
    folder: '_authors/'
    create: true
    slug: '{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Short Name', name: 'name', widget: 'string' }
      - { label: 'Display Name', name: 'display_name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'partners'
    label: 'Partners'
    folder: '_partners'
    create: true
    slug: '{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'partner' }
      - { label: 'Partner Name', name: 'name', widget: 'string' }
      - { label: 'Page Title', name: 'title', widget: 'string', hint: 'Sets the &lt;title&gt; tag and social sharing meta tags.'}
      - { label: 'H1', name: 'h1', widget: 'string', hint: 'The top level heading on the page, i.e. Omnata + dbt'}
      - { label: 'Description', name: 'description', widget: 'markdown'}
      - { label: 'dbt + Partner Logo', name: 'logo', widget: 'file'}
      - label: 'Why [Partner] + dbt?'
        name: 'partnerWhy'
        widget: 'object'
        fields:
          - { label: 'Section Title', name: 'title', widget: 'string', default: 'Why [Partner] + dbt?'}
          - label: 'Reasons'
            name: 'reasons'
            widget: list
            hint: 'Numbered list of reasons to choose the partner + dbt. Usually we limit this to three items. Will be numbered automatically.'
            fields:
              - { label: 'Reason', name: 'reason', widget: 'markdown'}
          - label: 'Reasons CTA'
            name: 'reasonsCta'
            widget: 'object'
            hint: 'The call-to-action at the bottom of the Reasons section.'
            fields:
              - {label: 'Button Text', name: 'buttonTxt', widget: 'string'}
              - {label: 'Link', name: 'link', widget: 'string'}
  - name: 'pages'
    label: 'Pages'
    create: false
    editor:
      preview: false
    files:
      - label: 'About Page'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Ecosystem - Index'
        name: 'ecosystem'
        file: 'ecosystem/index.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'string'}
          - { label: 'Description', name: 'description', widget: 'markdown'}
          - label: 'dbt Preferred Consulting Providers'
            name: 'consultingPartners'
            widget: 'object'
            collapsed: true
            fields:
              - {label: 'Name', name: 'name', widget: 'string', default: 'dbt Preferred Consulting Providers'}
              - {label: 'Description', name: 'desc', widget: 'markdown'}
              - label: 'Partners'
                name: 'partners'
                widget: list
                fields:
                  - {label: 'Partner Name', name: 'name', widget: 'string'}
                  - {label: 'Partner URL', name: 'href', widget: 'string', hint: 'For external URLs, please enter the full URL, starting with "http". For internal (www.getdbt.com) links, please enter the relative path (i.e. /ecosystem/fivetran rather than https://www.getdbt.com/ecosystem/fivetran)'}
                  - {label: 'Partner Logo', name: 'logo', widget: 'file'}
                  - {label: 'Same Site?', name: 'sameSite', widget: 'boolean', default: false, required: false, hint: 'Toggle this on if this page is on www.getdbt.com and you have entered a relative URL above.' }
          - label: 'Technology Partners'
            name: 'techPartners'
            widget: 'object'
            collapsed: true
            fields:
              - {label: 'Name', name: 'name', widget: 'string', default: 'Technology Partners'}
              - {label: 'Description', name: 'desc', widget: 'markdown'}
              - label: 'Partners'
                name: 'partners'
                widget: list
                fields:
                  - {label: 'Partner Name', name: 'name', widget: 'string'}
                  - {label: 'Partner URL', name: 'href', widget: 'string', hint: 'For external URLs, please enter the full URL, starting with "http". For internal (www.getdbt.com) links, please enter the relative URL (i.e. /ecosystem/fivetran rather than https://www.getdbt.com/ecosystem/fivetran'}
                  - {label: 'Partner Logo', name: 'logo', widget: 'file'}
                  - {label: 'Same Site?', name: 'sameSite', widget: 'boolean', default: false, required: false, hint: 'Toggle this on if this page is on www.getdbt.com and you have entered a relative URL above.' }
          - label: 'Cloud Partners'
            name: 'cloudPartners'
            widget: 'object'
            collapsed: true
            fields:
              - {label: 'Name', name: 'name', widget: 'string', default: 'Cloud Partners'}
              - {label: 'Description', name: 'desc', widget: 'markdown'}
              - label: 'Partners'
                name: 'partners'
                widget: list
                fields:
                  - {label: 'Partner Name', name: 'name', widget: 'string'}
                  - {label: 'Partner URL', name: 'href', widget: 'string', hint: 'For external URLs, please enter the full URL, starting with "http". For internal (www.getdbt.com) links, please enter the relative URL (i.e. /ecosystem/fivetran rather than https://www.getdbt.com/ecosystem/fivetran'}
                  - {label: 'Partner Logo', name: 'logo', widget: 'file'}
                  - {label: 'Same Site?', name: 'sameSite', widget: 'boolean', default: false, required: false, hint: 'Toggle this on if this page is on www.getdbt.com and you have entered a relative URL above.' }
          - label: 'Become a Partner'
            name: 'becomePartner'
            widget: 'object'
            collapsed: true
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'desc', widget: 'markdown'}
              - {label: 'Button Text', name: 'buttonTxt', widget: 'string'}
              - {label: 'Link', name: 'link', widget: 'string', default: '/ecosystem/getting-started/'}
      - label: 'Ecosystem - Getting Started'
        name: 'getting-started'
        file: 'ecosystem/getting-started.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'string'}
          - { label: 'Description', name: 'description', widget: 'markdown'}
          - label: 'The dbt Preferred Consulting Provider Program'
            name: 'partnerProgram'
            widget: 'object'
            collapsed: true
            fields:
              - { label: 'Title', name: 'title', widget: 'string', default: 'The dbt Preferred Consulting Provider Program'}
              - { label: 'Body', name: 'body', widget: 'markdown'}
              - label: 'Subsections'
                name: 'subsections'
                widget: 'list'
                fields:
                  - { label: 'Subsection Title', name: 'title', widget: 'string'}
                  - { label: 'Subsection Body', name: 'body', widget: 'markdown'}
          - label: 'Technology Partnerships'  
            name: 'techPartnerships'
            widget: 'object'
            collapsed: true
            fields:
              - { label: 'Title', name: 'title', widget: 'string', default: 'Technology Partnerships'}
              - { label: 'Body', name: 'body', widget: 'markdown'}
          - label: 'Become a Partner'
            name: 'becomePartner'
            widget: 'object'
            collapsed: true
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'desc', widget: 'markdown'}
              - {label: 'Button Text', name: 'buttonTxt', widget: 'string'}
              - {label: 'Link', name: 'link', widget: 'string', default: '/ecosystem/getting-started/'}          
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Link, name: link, widget: string}

```

**Additional context**
[Link to discussion in Slack channel.](https://netlifycms.slack.com/archives/CPRR0PQ9E/p1617382401144900)
