### ISSUE TITLE
Add support for open authoring for private repos

### ISSUE THREAD

**Issue by bassam** [netlify/netlify-cms#5201]
**Is your feature request related to a problem? Please describe.**

Current open_authoring is limited to public repos.

**Describe the solution you'd like**

We would like support for open_authoring with private repos. The use case is supporting fork flows for editing content even when the repo is private. 

**Describe alternatives you've considered**

**Additional context**
From what I can tell support for private repos would work if the GH OAuth scope requested [here](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-backend-github/src/AuthenticationPage.js#L83) was `repo` instead of `public_repo` as is the case for open_authoring. I wonder if this can be solved by checking the repo's visibility, and if it's private request `repo` OAuth scope regardless of whether open_authoring is used or not.

**Comment by bassam** [comment]
I was able to make this work by adding `auth_scope: repo` to my config:

```yaml
backend:
  name: github
  branch: main
  repo: myorg/someprivaterepo
  auth_scope: repo
  open_authoring: true
```
