### ISSUE TITLE
Add an option to always create a fork when the user is an origin maintainer

### ISSUE THREAD

**Issue by bassam** [netlify/netlify-cms#5203]
**Is your feature request related to a problem? Please describe.**
When using open authoring if the user making changes had write or admin writes on the repo, the fork flow is skipped and changes are made directly on the repo.

**Describe the solution you'd like**
I'd like an option to always go through a fork flow even when the user making the changes had write/admin access on the repo. This could look something like:

```yaml
backend:
  name: github
  repo: owner/repo
  open_authoring: true
  always_fork: true # creates a fork when using open_authoring even when the user is an origin maintainer
```
**Describe alternatives you've considered**
None

**Additional context**
None.
