### ISSUE TITLE
I am able to upload images just fine when I insert url from cloudnairy in rich text editor. But images won't show up at all in the website. It does show up in the preview when i am adding in rich text editor. https://github.com/jaymehta20/gatsby-starter-hello-world

### ISSUE THREAD

**Issue by jaymehta20** [netlify/netlify-cms#5226]
**Describe the bug**
 Images are not working

Images are not showing up in the website when I add them through the rich text editor. The preview comes up but the image won't load on the website. Only way I can add images is to upload via URL
https://github.com/jaymehta20/gatsby-starter-hello-world

**Comment by erezrokah** [comment]
Hi @jaymehta20, per https://www.netlifycms.org/docs/cloudinary/#connecting-cloudinary-to-netlify-cms you should configure the media library at the top level:

```yaml
backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: 'static/img/'
public_folder: 'static/img/'

media_library:
  name: cloudinary
  config:
    cloud_name: codegrain
    api_key: '973338231686312'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          required: true,
          pattern:
            ['^[a-z0-9]+(?:-[a-z0-9]+)*$', 'A slug can have no spaces or special characters'],
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
```

Also, you'll need to install and register `netlify-cms-media-library-cloudinary` per https://www.netlifycms.org/blog/2019/07/netlify-cms-gatsby-plugin-4-0-0#using-media-libraries-with-netlify-cms-app
