### ISSUE TITLE
Error loading the CMS configuration Config

### ISSUE THREAD

**Issue by tresero** [netlify/netlify-cms#5255]
**Describe the bug**
I can login to the admin link and all works. The issue is all my front end pages show:

`Error loading the CMS configuration
Config Errors:
Error: Failed to load config.yml (404)
Check your config.yml file.`

**Expected behavior**
Doesn't show this

**Screenshots**
![image](https://user-images.githubusercontent.com/1476286/114417354-c5130d00-9b6e-11eb-92bb-d9ccd1df4d17.png)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4] ^2.0
 - Git provider: [e.g. GitHub, BitBucket] GitHub

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'content/articles'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - { label: 'Tags', name: 'tags', widget: 'list'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Featured Image", name: "thumbnail", widget: "image"}
  - name: 'books'
    label: 'Books'
    folder: 'content/books'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - { label: 'Genres', name: 'genres', widget: 'list'}
      - { label: 'Book Link', name: 'booklink', widget: 'string'}
      - { label: 'Tags', name: 'tags', widget: 'list'}
      - { label: 'Cover', name: 'cover', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'content'
    label: 'Content'
    folder: 'content'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Featured Image", name: "thumbnail", widget: "image"}
      - { label: "DisplayFooter", name: "displayFooter", widget: "boolean", default: false}
```
