### ISSUE TITLE
Markdown widget doesn't parse shortcodes if they're "out of order"

### ISSUE THREAD

**Issue by SMores** [netlify/netlify-cms#5258]
**Describe the bug**
When there are several shortcodes in a single markdown field, the markdown widget uses [`Map.find`](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js#L15-L23) to attempt to match the registered editor components' patterns against the remaining uneaten markdown. Because `Map.find` returns after the first instance that returns true, some valid shortcode matches can be "skipped" by the plugin, and parsed as plain text instead.

**To Reproduce**
1. Create a Netlify CMS collection that has a markdown widget field, and at least two custom editor components
2. Open the CMS page for that collection and create a new entity
3. Add two of each of your custom editor components, interleaved. That is:
    ```mdx
    Component One
    Component Two
    Component One
    Component Two
    ```
4. Save your changes and refresh the page

At least one of the four components will not be properly parsed as a shortcode, and will instead be rendered as plain text. Which one is determined by the order in the `Map` instance passed to `createShortcodeTokenizer` (which is nondeterministic, as immutable.js's Map is unordered).

**Expected behavior**
All four components should be parsed as custom components and receive the same visual treatment.

**Screenshots**
Actual behavior:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/5354254/114488019-93d22580-9bde-11eb-911e-21028ea78605.png">

Expected behavior: 
<img width="735" alt="image" src="https://user-images.githubusercontent.com/5354254/114487471-a7c95780-9bdd-11eb-93de-b54a7ae8c504.png">

**Applicable Versions:**

 - Netlify CMS version: 2.14.6
 - Git provider: GitHub
 - OS: macOS 11.1
 - Browser version: Firefox 87.0

 - Node.JS version: v14.5.4

**CMS configuration**
```yaml
local_backend: true
backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: pages
    label: Pages
    folder: src/markdown/pages
    extension: mdx
    format: frontmatter
    create: true
    slug: "{{fields.slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: Slug
        name: slug
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Heading
        name: heading
        widget: string
        required: false
      - label: Subheading
        name: subheading
        widget: string
        required: false
      - label: Show in Navigation Menu
        name: showInNavigation
        widget: boolean
        default: false
      - label: Navigation Menu Order
        name: navigationOrder
        widget: number
        default: 0
        # @see https://www.netlifycms.org/docs/configuration-options/#collections
        pattern:
          - "^[^-]?\\d+$"
          - "Cannot be a negative number"
      - label: Body
        name: body
        widget: markdown
    sortable_fields:
      - navigationOrder
      - slug
      - title
```

**Additional context**
