### ISSUE TITLE
i18n: multiple_files structure for file collections

### ISSUE THREAD

**Issue by jf-home** [netlify/netlify-cms#5280]
Just getting to grips with the Beta i18n capabilities and really like the `multple_folders` and `multiple_files` structures.  However, I am confused by the decision to only support a `single_file` structure for file collections.  I say this reservedly as, clearly, a lot of work must have gone into providing the i18n capabilities and therefore this is in no way a critisism and, quite possibly, may be down to a misunderstanding on my part.  The problem that I have though is generating pages in gatsby-node when the i18n implementation involves a mixed structure of `multiple_files` (i.e. for templated content such as blog posts, product entries etc.) and `single_file` for one off pages (i.e. index, about, contact). 

I'd like to see file collections also support a `multiple_files` structure as that would allow a single `createPage` mechanism in gatsby-node to be used.  Naturally, that would require a single markdown file for language-specific page, using locale as the differentiating factor i.e. index.en.md, index.de.md, index.es.md and so on.
 
If this isn't technically viable, please advise how to go about page generation in gatsby-node when confronted with both `multiple_files` and `single_file` collections.

Thanks in advance for your help!

**Comment by erezrokah** [comment]
Hi @jf-home, the lack of support for file collections was part of scoping down the feature so we can launch it quickly and get more feedback.

**Comment by jf-home** [comment]
Hi @erezrokah, 

I appreciate your prompt response and have outlined my thoughts as requested below...
 

**Requirement**
i18n support for `multiple_files` is required for file collections to enable pages to be dynamically created via the Gatsby `createPage` api. 

**Possible solution**
From a configuration standpoint, it would be preferable for file collections to "inherit" the top level i18n configuration by default, unless specifically stated otherwise.  The `- file:` configuration would need to allow an array of files to be specified, one for each locale.  Example default configuration: 

```
i18n:
  structure: multiple_files
  locales: [en, de, fr]

collections:
   i18n: true
    files:
      - file: ["src/pages/about.en.md","src/pages/about.de.md","src/pages/about.fr.md"]
        label: "About Page"
        name: "about"
        i18n: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page", i18n: duplicate}
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Heading, name: heading, widget: string, i18n: true}
          - {label: "Body", name: "body", widget: "markdown", i18n: true} 
```

What would be particularly useful is to have the ability to specifiy a different file name for each locale, as the file name is often used to influence the slug.  This would provide a better end user experience through the Gatsby site and also improve SEO for each locale.  Example configuration (using kebabcase where necessary): 

```
i18n:
  structure: multiple_files
  locales: [en, de, fr]

collections:
   i18n: true
    files:
      - file: ["src/pages/about.en.md","src/pages/uber.de.md","src/pages/a-propos.fr.md"]
        label: "About Page"
        name: "about"
        i18n: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page", i18n: duplicate}
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Heading, name: heading, widget: string, i18n: true}
          - {label: "Body", name: "body", widget: "markdown", i18n: true}
``` 

  
**Possible alternatives**
If the `- file:` configuration cannot be changed to support an array, then I'd propose that a single file name should be used as at present, however, the CMS would need to perform variable substitution for the locale.  Example: 

```
i18n:
  structure: multiple_files
  locales: [en, de, fr]

collections:
   i18n: true
    files:
      - file: "src/pages/about.{{locale}}.md"
        label: "About Page"
        name: "about"
        i18n: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page", i18n: duplicate}
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Heading, name: heading, widget: string, i18n: true}
          - {label: "Body", name: "body", widget: "markdown", i18n: true} 
```

The drawback with this approach is that it doesn't allow for a different file name (and therefore slug) across locales, so it wouldn't be as effective from an SEO and user experience perspective.
