### ISSUE TITLE
Feature: edit data files with a list at root level

### ISSUE THREAD

**Issue by rriemann** [netlify/netlify-cms#531]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

it seems to be impossible to create data files with a list at root level:

```yaml
- nav_object_1
- nav_object_2
```

The current work-around is to use

```yaml
navigation:
  - nav_object_1
  - nav_object_2
```

However, this may require a change of the template that may be part of libraries (jekyll theme gems).

**- What is the expected behavior?**

I can just create lists also on root level.

**Comment by erquhart** [comment]
Yeah, everything has to have a field name currently. I suppose we could have a boolean "root" property on fields that simply drops the field's value directly into the parent (root for any field not in an object or list widget).

**Comment by rriemann** [comment]
> Would you be up for taking a swing at this?

Unfortunately I'm super busy with university. :(

**Comment by erquhart** [comment]
No problem! I'm sure someone will take it on.

**Comment by r1b** [comment]
I would be happy to implement this - currently it is not possible to use `gatsby-transformer-yaml` with netlify since the transformer[ only supports lists](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-yaml/src/gatsby-node.js#L16).

Any pointers on where to look in the code to get started? I'm pretty new to netlify.

**Comment by r1b** [comment]
I have solved this on the gatsby side with a [custom yaml transformer](https://github.com/computer-lab/gatsby-transformer-yaml-netlify). I would still like to support it here for maximum flexibility :)

**Comment by erquhart** [comment]
Forget the boolean thing I said before, we should apply the `field`/`fields` approach from the list widget to the collection config.

**`fields` vs. `field`**

Here's the list widget using `fields`:
```yaml
# list field config using `fields`
- name: my-list
  label: My List
  widget: list
  fields: [{ name: title, label: title, widget: string }]

# output:
# list: [
#   { title: 'a title' },
#   { title: 'another title' }
# ]
```

Here's the same widget config using `field`:
```
# list field config using `field`
- name: my-list
  label: My List
  widget: list
  field: [{ name: title, label: title, widget: string }]

# output
# list: [
#   'a title',
#   'another title'
# ]

**Comment by kripod** [comment]
Are there any updates regarding the proposals mentioned above? This is a deal-breaker for Gatsby users, please see #1282.

**Comment by talves** [comment]
@kripod I believe this is a feature the CMS should support, Until then, it is **NOT** a deal-breaker for Gatsby users when it is still able to map to a structure the CMS does support at the moment.

**Comment by erquhart** [comment]
This is still happening.

**Comment by bharrisau** [comment]
I've just patched this locally in `netlify-cms-core/src/backend.ts` functions `entryToRaw` and `entryWithFormat`. Around the calls to either `format.toFile` or `format.fromFile` I'm just doing a wrap/unwrap with a special key `rootArray`.

```
  entryWithFormat(collectionOrEntity: unknown) {
    return (entry: EntryValue): EntryValue => {
      const format = resolveFormat(collectionOrEntity, entry);
      if (entry && entry.raw !== undefined) {
        let data = (format && attempt(format.fromFile.bind(format, entry.raw))) || {};
        let data = Array.isArray(data) ? { rootArray: data } : data; //Added wrapper for root arrays
        if (isError(data)) console.error(data);
        return Object.assign(entry, { data: isError(data) ? {} : data });
      }
      let data = format.fromFile(entry);
      return Array.isArray(data) ? { rootArray: data } : data; //Added wrapper for root arrays
    };
  }

  entryToRaw(collection: Collection, entry: EntryMap): string {
    const format = resolveFormat(collection, entry.toJS());
    const fieldsOrder = this.fieldsOrder(collection, entry);
    let data = entry.get('data').toJS();
    let data = data.rootArray || data; // Unwrap root array (this should probably check the fields.length == 1 too)
    return format && format.toFile(data, fieldsOrder);
  }
```

Not as clever as the approach mentioned above - but if you think of it as normalising files to always be a map instead of sometimes passing arrays around then it feels a bit less hacky.

**Comment by cyonder** [comment]
No fix on this since 2017? )=

**Comment by erezrokah** [comment]
Hi @cyonder, we try to get to the most up voted features first. You can see the sorted list here https://github.com/netlify/netlify-cms/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc.
Regardless, we would love a contribution for this.

**Comment by reimertz** [comment]
I just tried to see if I could get the ball rolling on this issue.

1. Parse the single entry file to get array of content
2. Based on that content, generate new  "real" entries
3. Populate the collection with previously generated entries 

Doing edits / adding new content would be similar to above but in reversed order. 

But the assumptions of content being in separate files made it very complicated straight away but maybe my idea was overly complicated?

Would love to get some help / discussion with main contributors to the project. <3

**Comment by erezrokah** [comment]
Hi @reimertz, thanks for pushing this forward.
What do you think about putting a draft PR for it? We can use it for the discussion.

Another option is our [#contributing](https://netlifycms.slack.com/archives/CPRR9L929) channel on Slack https://www.netlifycms.org/chat.

**Comment by vnourdin** [comment]
Hi everyone, any update on this ?
This seems blocking for [Eleventy global data files](https://www.11ty.dev/docs/data-global/) too, if anyone has a workaround for this I'm interested :sweat_smile:

**Comment by erezrokah** [comment]
Hi @vnourdin this would make a great contribution to the CMS if anyone would like to pick it up

**Comment by ManUtopiK** [comment]
Just to said this is also an issue for @nuxt/content with array at the root level of a json. [Like here.](https://content.nuxtjs.org/writing#arrays)

**Comment by hayden2114** [comment]
+1 would love to see support for .json files with array at root level to mimic a MongoDB collection

**Comment by astrawnuts** [comment]
would love to see support for this

**Comment by izanagi1995** [comment]
Still needed :)

**Comment by TheReyzer** [comment]
NEEEEED

**Comment by CKLFish** [comment]
Need it....

**Comment by LakshmyPulickalRajukumar** [comment]
Is there any chance for this to be implemented anytime soon?

**Comment by reteps** [comment]
Here is a workaround:

```typescript
            CMS.registerCustomFormat('flat-json', 'json', {
                fromFile: text => {
                    const body = JSON.parse(text) as Record<string, Record<string, string>>;
                    // Now we want to transform this object into a flat object with a 'key' field
                    const value = { items: Object.entries(body).reduce((acc, [key, value] : [
                        string,
                        Record<string, string>
                    ]) => {
                        acc.push({ key, ...value });
                        return acc;
                    }, [] as Record<string, string>[]) };
                    return value;
                },
                toFile: (value : { items: Record<string, string>[] }) => {
                    const body = value.items.reduce((acc, { key, ...rest }) => {
                        acc[key] = rest;
                        return acc;
                    }, {} as Record<string, Record<string, string>>);
                    return JSON.stringify(body, null, 2);
                }
            });
 ```
 
 
 ```yaml
   - name: 'redirects-collection'
    label: 'Redirects'
    format: 'flat-json'
    files:
    - label: 'All Redirects'
      file: 'sigpwny.com/src/redirects.json'
      name: 'redirects'
      fields:
        - {label: 'Links', name: 'items', widget: 'list', fields: [
            # must be named 'key' for our custom formatter to work
            {label: 'From', name: 'key', widget: 'string', hint: 'Example: "/qrcode"'},
            {label: 'To', name: 'destination', widget: 'string', hint: 'Example: "myurl.com/foo"'},
            {label: 'Status Code', name: 'status', widget: 'hidden', default: 302}
          ]}
```
