### ISSUE TITLE
Toolbar buttons for some block styles are not highlighted on active 

### ISSUE THREAD

**Issue by bytrangle** [netlify/netlify-cms#5338]
**Notes**: This is related to issue #761 

**Describe the bug**

There are two parts to this issue:
- When selecting a block of text in the editor and toggle it to Quoteblock, Bulleted list or Numbered list using toolbar buttons, the buttons are not highlighted. However, the text was converted properly to the chosen text style.
- When clicking away from an existing quoteblock, bulleted list or numbered list, then select or click on them again to focus, the toolbar button is not highlighted either.

**To Reproduce**

Steps to reproduce the behavior. For example:
1. Create a new post
2. Make sure that the editor is set to Rich Text.
3. Enter four lines, with each line separated by an Enter key: Heading 2, Quote block, Bulleted list, Numbered list.
4. Select the “Heading 2” text and click the Heading 2 button in the toolbar. The text turns into heading 2 and the button is darkened.
5. Select the “Quoteblock” and click the Quote block button in the toolbar. The text turns into a quoteblock but the button is not highlighted.
6. Click away from the “Quoteblock” text and click on it again. The button is not highlighted either.
7. Do the same thing for “Bulleted list” and “Numbered list” and you should see the same issue.

Repeat the process above, but change step 1 to edit an existing post. The issue still remains.

**Expected behavior**

When selecting a piece of text and click Quoteblock, Bulleted list or Numbered list button, the button should be highlighted to signal to users that the text has really been converted from paragraph to the above styles.

Similarly, when focusing an existing quoteblock, bulleted list or numbered list, the button should also be highlighted so users understand that if they click the button again, they will turn the text back to a paragraph.

**Screenshots**

![block-buttons-not-highlighting-on-click](https://user-images.githubusercontent.com/28924121/116959926-386cf200-acc9-11eb-8ad5-e734a6bbb830.gif)

**Applicable Versions:**

 - Netlify CMS version: Netlify CMS 2.10, Netlify CMS app 2.14
 - Git provider: GitHub,
 - OS: MacOS Catalina
 - Browser version: Chrome 90

 - Node.JS version: 12.6

**CMS configuration**

```yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["software development", "programming"],
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
```
**Additional context**

Here's what I found when examining the toolbar buttons with React Developer tools:

The component that renders the toolbar button and handles click event for changing text styles is called `<StyledToolbarButton />`.

It also has a prop `isActive` that takes a boolean value. If this value is true, the button takes a color rgb(30, 37, 50) aka highlighted. Otherwise, the value is by default false and the button's color is inherited.

![styled-toolbar-button-components](https://user-images.githubusercontent.com/28924121/116959912-2c813000-acc9-11eb-9993-43cb73fbd037.gif)

This prop's value is changed when we focus on a piece of text in the editor by either clicking or selecting. As you can see, when I focus on the Heading 2 text, the `isActive` prop in the Heading button component changes to `true`. 

For reasons that I don't understand yet, in the Quoteblock, Bulleted list and Numbered list button components, this prop's value remains `false` even when the corresponding text style in the editor is focused.

Is my description clear enough @erquhart ?
