### ISSUE TITLE
Breaking change to public_folder in v2.38.1 (2021-02-15)?

### ISSUE THREAD

**Issue by kennethormandy** [netlify/netlify-cms#5386]
**Describe the bug**

Setting the following config:

```
public_folder: ''  
```

…previously made it possible to save the filename of an upload, without any public path. This seems to have changed after v2.38.0, and broken this behaviour.

Now, it seems like this empty string is resolved as `false`, so you end up with value of the `media_folder`.

**To Reproduce**

When uploading a file called `my-image.png` with the following config:

```yml
media_folder: '../../../static/'
public_folder: ''
```

You’ll end up with:

```
../../../static/my-image.png
```

<img width="849" alt="Screen Shot 2021-05-13 at 11 54 10 AM" src="https://user-images.githubusercontent.com/1581276/118173106-0141c380-b3e2-11eb-9655-927c1189372c.png">

**Expected behavior**

Using the same config with Netlify CMS App v2.14.21 (2021-02-10) and earlier, the path to the file would resolve to the filename (empty string + filename):

```
my-image.png
```

<img width="858" alt="Screen Shot 2021-05-13 at 11 50 27 AM" src="https://user-images.githubusercontent.com/1581276/118173124-0868d180-b3e2-11eb-8bff-bdb2b1707514.png">

You don’t necessarily need to upload a new file either—if you replace a file with one already in your media library, you can also see the file change paths even though the only thing that has changed is the CMS version.

**Applicable Versions:**

As far as I’ve been able to tell, this works as expected in Netlify CMS App v2.14.21 (2021-02-10)

- netlify-cms-app 2.14.21
- netlify-cms-core 2.38.0

…and breaks in the release after that:

- netlify-cms-app 2.14.22
- netlify-cms-core 2.38.1

**CMS configuration**

```yml
media_folder: static/assets
public_folder: /assets
show_preview_links: false
collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post Example'
    create: true
    folder: 'src/data/example'
    media_folder: '../../../static/my-example-data/{{fields.name}}'

    # I think this is on the only
    # portion that is relevant, because if
    # I change it to '/' or '/test/', then
    # it works as expected.
    public_folder: ''

    extension: json
    format: json
    slug: '{{slug}}'
    identifier_field: name
    fields:
      - name: files
        label: 'Files'
        widget: object
        required: true
        fields:
          - name: exampleFile
            label: 'Example File'
            widget: file
            required: false
```

Thanks!
