### ISSUE TITLE
Add sorting ability to list of entries

### ISSUE THREAD

**Issue by phae** [netlify/netlify-cms#54]
User needs:
- to more efficiently be able to locate a post when browsing manually

So, we should add some basic filters to reorder the list of posts that have already gone live.  

Minimum options for now.

Acceptance criteria:
- [ ] User can click a link to re-order the posts from newest to oldest, and visa versa
- [ ] User can click a link to re-order the posts in alphabetical and reverse-alphabetical
#50 is prerequisite for this.

**Comment by loremipson** [comment]
Requesting some more flexibility here. What do you all think about accepting some optional yaml in the config that would result in both additional fields being displayed in the entry list, as well as making them sortable?

Something like: 

```yaml
collections:
  - name: posts
     label: Posts
     folder: src/posts
     create: true
     fields:
       - { name: title, label: Title, widget: string }
       - { name: publishedDate, label: Published Date, widget: datetime }
       - { name: editedDate, label: Edited Date, widget: datetime }
       - { name: body, label: Body, widget: markdown }
     sortableFields: ["title", "publishedDate", "editedDate"]
```
