### ISSUE TITLE
GitLab CI/CD is being triggered without a .gitlab-ci.yml file

### ISSUE THREAD

**Issue by tomknappramos** [netlify/netlify-cms#5423]
**Describe the bug**

GitLab CI/CD is being triggered without a .gitlab-ci.yml file or any specific setup in GitLab

**To Reproduce**

Create a site with the preact-cli template. 
That will create a repo in your personal GitLab (but I wanted mine to be in a GitLab group). 
Move the GitLab repo into a group.
Create a new Netlify site for the newly named repo (which is now in a group).
Turn on identity and the git gateway in Netlify for the new site.
Invite someone to edit and make a change to the site from within the https://site.netlify.app/admin panel.

**Expected behavior**

As far as I'm aware, the build is supposed to occur within Netlify, not in GitLab, right?

I don't think this was happening until I moved the repo into the group and created the new site in Netlify.

**Screenshots**

GitLab:
![Capture](https://user-images.githubusercontent.com/10470943/119210887-9a0fb900-ba4a-11eb-90ba-0405e33096dd.JPG)

Repo:
![files](https://user-images.githubusercontent.com/10470943/119210914-bdd2ff00-ba4a-11eb-8707-9054ad74f732.JPG)

**Applicable Versions:**

 - Netlify CMS version: netlify-cms-app 2.15.9, bootstrap.js:83 netlify-cms-core 2.40.5, index.js:27 netlify-cms 2.10.129
 - Git provider: GitLab
 - OS: N/A
 - Browser version N/A
 
 - Node.JS version: N/A

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Cover", name: "cover", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
```

**Additional context**

I think I have 2 Netlify CMS sites pointing to the same repo (the original site and the new site). Would that affect anything?

I feel as though Netlify CMS is manually triggering the build via an API call, perhaps? I don't think I have anything in GitLab that would cause a CI/CD to get triggered.
