### ISSUE TITLE
[translation] "Add" buttons, in list widgets, are not translatables

### ISSUE THREAD

**Issue by vnourdin** [netlify/netlify-cms#5471]
**Describe the bug**
The "Add" button, allowing to add a new item in a list object, have a hard-coded text, so it's not possible to translate.

**Expected behavior**
Allow translation of the button.

**Screenshots**
I am using the French translation, but the button is in English :
![image](https://user-images.githubusercontent.com/11643685/120892928-cada1b80-c610-11eb-82a0-5253b89253e4.png)

**Comment by vnourdin** [comment]
This button is defined in `packages/netlify-cms-ui-default/src/ObjectWidgetTopBar.js`, but `t` isn't accessible from there.
If I understand well, I should add it in the `ObjectWidgetTopBar` class' propTypes, but if I do so, I must also pass `t` wherever a `ObjectWidgetTopBar` is instantiated in the code, right?

I've spot two places: `packages/netlify-cms-widget-list/src/ListControl.js` and `packages/netlify-cms-widget-object/src/ObjectControl.js`, but those two doesn't seems to have `t` neither, I must tho add it to their propTypes too and continue like this? :sweat_smile:

**Comment by vnourdin** [comment]
I see another hard-coded value, when a list item have no `name` value, it shows "No name".
The "No " is hard-coded in `packages/netlify-cms-widget-list/src/ListControl.js` l.428, so a fix could be included in the fix for "Add" buttons, but I don't understand why it is "No name" instead of "No nom", as my field `name` as `nom` for label...

**Comment by erezrokah** [comment]
Hi @vnourdin, thank you for opening the issue.
Propagating the `t` is the way to go 👍 

> it is "No name" instead of "No nom", as my field `name` as `nom` for label.

Not sure, maybe share the `config.yml` that reproduces this?

**Comment by vnourdin** [comment]
Here is my test config:
```yaml
backend:
  name: test-repo

media_folder: "/src/img"
public_folder: "/img"

collections:
  - label: "root"
    name: "root"
    folder: "src/root"
    create: true
    fields:
      - label: "things"
        name: "things"
        label_singular: "a thing"
        widget: "list"
        fields:
          - { label: "thing", name: "name", widget: "string" }
          - { label: "stuff", name: "stuff", widget: "string" }
```
It gives that result
![cms_text](https://user-images.githubusercontent.com/11643685/121031528-b598f480-c7aa-11eb-9151-c31723547fcf.gif)

I see two problems:
* When a list contains only one item, it displays `1 an item` if you defined a `label_singular`
* When the `name` field is empty, it displays "No name" instead of using the label, "No thing" in my case

There is also a "problem" in the home page which display "No Entries" instead of "No root", and this is not translatable neither:
![image](https://user-images.githubusercontent.com/11643685/121032192-55ef1900-c7ab-11eb-9ac6-dc28af8b01da.png)
