### ISSUE TITLE
"API_ERROR: Unknown error" when using `npx netlify-cms-proxy-server`

### ISSUE THREAD

**Issue by JWesorick** [netlify/netlify-cms#5472]
**Describe the bug**

When using netlify local backend, and navigating to edit pages, it fails with `API_ERROR: Unknown error". (On just viewing the edit page, not on save.)

**To Reproduce**

1. `npx netlify-cms-proxy-server`
2. `gatsby develop`
3. Go to `/admin`.
4. Click on a page to edit, in my case "Teachings", click on a teaching.

**Expected behavior**

Expect to be able to edit pages.

**Screenshots**

<img width="860" alt="Screen Shot 2021-06-06 at 3 28 33 PM" src="https://user-images.githubusercontent.com/801062/120917943-11e11300-c6dc-11eb-815b-f005ed52dee8.png">

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4] netlify-cms-app@2.15.17
 - Git provider: [e.g. GitHub, BitBucket] GitHub
 - OS: [e.g. Windows 7] MacOS (M1)
 - Browser version [e.g. chrome 22, safari 11] Chrome 91.0.4472.77, Firefox 89.0

 - Node.JS version: 14.3.0
 - NPM: 7.10.0
 - Gatsby: 3.6.2

**CMS configuration**

```yml
# project: &PROJECT
#   - { name: title, widget: string }
#   - { name: description, widget: string }

# aliases:
#   - &TITLE {label: 'Title', name: 'title', widget: 'string' }

image_fields: &image_fields
  - label: Source
    name: src
    widget: image
    hint: "Must set image or video."
    required: false
    default: ""
  - label: Alt Text
    name: alt
    hint: "Description of what is in the image for people with disabilities."
    required: false
    default: ""
  - label: Title
    name: title
    hint: "Title of image. Shows when someone hovers over the image. Also used by search engines."
    required: false
    default: ""

video_fields: &video_fields
  - label: YouTube Video ID
    name: "ytid"
    widget: "string"
    hint: "Can be YT ID Ex IMR1a-LS-Ww or full share url like https://youtu.be/IMR1a-LS-Ww?t=3079. Does not support youtube.com urls."
    required: false
    default: ""

button_fields: &button_fields
  - label: Button Text
    name: button_text
    required: false
    widget: string
  - label: Button Destination
    name: button_href
    required: false
    widget: string

hero_fields: &hero_fields
  - label: Background Image
    name: image
    widget: image
    hint: "Must set image or video."
    media_folder: "/{{media_folder}}"
    public_folder: "{{public_folder}}"
    required: false
  - label: Background Video
    name: video
    widget: file
    required: false
    hint: "Must set image or video."
    media_folder: "/{{media_folder}}/video"
    public_folder: "{{public_folder}}/video"
  - label: Heading
    name: heading
    widget: string
  - label: Subheading
    name: subheading
    widget: stringm
    required: false
  - label: Info
    name: info
    widget: string
    required: false
  - label: Buttons
    name: buttons
    widget: list
    required: false
    collapsed: true
    fields: *button_fields

blurb_fields: &blurb_fields
  - label: Heading
    name: heading
    widget: string
  - label: Subheading
    name: description
    widget: text
  - label: Hook
    name: hook
    widget: string
    required: false
  - label: Image
    name: image
    widget: object
    summary: "{{fields.title}}"
    collapsed: true
    fields: *image_fields
  - label: Video
    name: video
    widget: object
    collapsed: true
    fields: *video_fields
  - label: Hide
    name: hide
    required: false
    widget: boolean
  - label: Buttons
    name: buttons
    widget: list
    required: false
    collapsed: true
    fields: *button_fields

open_graph_fields: &open_graph_fields
  - label: Title
    name: title
    widget: string
    required: false
  - label: Description
    name: description
    widget: string
    required: false
  - label: Image
    name: image
    widget: image
    required: false

backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

publish_mode: editorial_workflow

local_backend: true
media_folder: static/media
public_folder: /media

collections:
  - name: settings
    label: Settings
    files:
      - file: src/settings/navigation.md
        label: Navigation
        name: navigation
        fields:
          - label: Primary Nav Items
            name: primary_items
            widget: list
            fields:
              - label: Label
                name: label
                widget: string
              - label: To
                name: to
                widget: string
                required: false
                hint: Don't set if nav items is going to have any secondary items.
              - label: External
                name: external
                required: false
                hint: Check if item links to external site not.
                widget: boolean
              - label: Secondary Nav Items
                name: secondary_items
                widget: list
                fields:
                  - label: Label
                    name: label
                    widget: string
                  - label: To
                    name: to
                    required: false
                    hint: Optional but you should really set this or the link does nothing.
                    widget: string
                  - label: External
                    name: external
                    required: false
                    widget: boolean
                    hint: Check if item links to external site not.
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: Hero,
              name: hero,
              widget: object,
              required: false,
              collapsed: true,
              summary: "{{fields.heading}}",
              fields: *hero_fields,
            }
          - {
              label: "Compact Blurbs",
              name: "compact_blurbs",
              widget: boolean,
              required: false,
              hint: "Use compact blurbs styles.",
            }
          - {
              label: Blurbs,
              name: blurbs,
              widget: list,
              collapsed: true,
              fields: *blurb_fields,
            }
          - {
              label: Open Graph Tags,
              name: open_graph,
              widget: object,
              collapsed: true,
              fields: *open_graph_fields,
            }
      - file: "src/pages/teachings/index.md"
        label: "Teachings Page"
        name: "teachings"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "teachings-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: Hero,
              name: hero,
              widget: object,
              required: false,
              collapsed: true,
              summary: "{{fields.heading}}",
              fields: *hero_fields,
            }
          - {
              label: "Compact Blurbs",
              name: "compact_blurbs",
              widget: boolean,
              required: false,
              hint: "Use compact blurbs styles.",
            }
          - {
              label: Blurbs,
              name: blurbs,
              widget: list,
              collapsed: true,
              fields: *blurb_fields,
            }
          - {
              label: Open Graph Tags,
              name: open_graph,
              widget: object,
              collapsed: true,
              fields: *open_graph_fields,
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        hide: true
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - {
              label: Hero,
              name: hero,
              widget: object,
              collapsed: true,
              summary: "{{fields.heading}}",
              fields: *hero_fields,
            }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: "Compact Blurbs",
              name: "compact_blurbs",
              widget: boolean,
              required: false,
              hint: "Use compact blurbs styles.",
            }
          - {
              label: Blurbs,
              name: blurbs,
              widget: list,
              collapsed: true,
              fields: *blurb_fields,
            }
          - {
              label: Open Graph Tags,
              name: open_graph,
              widget: object,
              collapsed: true,
              fields: *open_graph_fields,
            }
      - file: "src/pages/watch/index.md"
        label: "Watch"
        name: "watch"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "watch-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: Hero,
              name: hero,
              widget: object,
              collapsed: true,
              summary: "{{fields.heading}}",
              fields: *hero_fields,
            }
          - {
              label: "Compact Blurbs",
              name: "compact_blurbs",
              widget: boolean,
              required: false,
              hint: "Use compact blurbs styles.",
            }
          - {
              label: Blurbs,
              name: blurbs,
              widget: list,
              collapsed: true,
              fields: *blurb_fields,
            }
          - {
              label: Open Graph Tags,
              name: open_graph,
              widget: object,
              collapsed: true,
              fields: *open_graph_fields,
            }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        hide: true
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: Hero,
              name: hero,
              widget: object,
              collapsed: true,
              summary: "{{fields.heading}}",
              fields: *hero_fields,
            }
          - {
              label: "Compact Blurbs",
              name: "compact_blurbs",
              widget: boolean,
              required: false,
              hint: "Use compact blurbs styles.",
            }
          - {
              label: Blurbs,
              name: blurbs,
              widget: list,
              collapsed: true,
              fields: *blurb_fields,
            }
          - {
              label: Open Graph Tags,
              name: open_graph,
              widget: object,
              collapsed: true,
              fields: *open_graph_fields,
            }
  - name: "ad_hoc_pages"
    label: "Generic Pages"
    folder: "src/pages"
    filter: { field: "templateKey", value: "generic-page" }
    create: true
    nested:
      depth: 10
    meta: { path: { widget: string, label: "Path", index_file: "index" } }
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "generic-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - {
          label: Hero,
          name: hero,
          widget: object,
          collapsed: true,
          summary: "{{fields.heading}}",
          fields: *hero_fields,
        }
      - {
          label: "Compact Blurbs",
          name: "compact_blurbs",
          widget: boolean,
          required: false,
          hint: "Use compact blurbs styles.",
        }
      - {
          label: Blurbs,
          name: blurbs,
          widget: list,
          collapsed: true,
          fields: *blurb_fields,
        }
      - {
          label: Open Graph Tags,
          name: open_graph,
          widget: object,
          collapsed: true,
          fields: *open_graph_fields,
        }
  - name: "teaching_series"
    label: "Teaching Series"
    folder: "src/pages/teachings"
    path: "{{slug}}/index"
    filter: { field: "templateKey", value: "series-page" }
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "series-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "file" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: Open Graph Tags,
          name: open_graph,
          widget: object,
          collapsed: true,
          fields: *open_graph_fields,
        }
  - name: "teachings"
    label: "Teachings"
    folder: "src/pages/teachings"
    path: "{{teaching_series}}/{{slug}}"
    summary: "{{title}} by {{speaker}}"
    sortable_fields: ["title", "date", "speaker", "teaching_series"]
    view_groups:
      - label: Series
        field: teaching_series
      - label: Year
        field: date
        pattern: \d{4}
    filter: { field: "templateKey", value: "teaching-page" }
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "teaching-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Speaker",
          name: "speaker",
          widget: "relation",
          collection: "people",
          search_fields: ["name"],
          value_field: "name",
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Audio",
          name: "audio_file",
          required: false,
          widget: "file",
          media_folder: "/static/media/teaching-audio",
          public_folder: "/media/teaching-audio",
        }
      - {
          label: Video,
          name: video,
          widget: object,
          collapsed: true,
          fields: *video_fields,
        }
      - {
          label: "Handout",
          name: "handout_file",
          required: false,
          widget: "file",
          media_folder: "/static/media/teaching-handouts",
          public_folder: "/media/teaching-handouts",
        }
      - {
          label: "Series",
          name: "teaching_series",
          widget: "relation",
          collection: "teaching_series",
          search_fields: ["title"],
          value_field: "title",
        }
      - {
          label: Open Graph Tags,
          name: open_graph,
          widget: object,
          collapsed: true,
          fields: *open_graph_fields,
        }
  - name: "people"
    label: "People"
    folder: "src/pages/people"
    filter: { field: "templateKey", value: "people-page" }
    create: true
    identifier_field: name
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: people-page,
        }
      - { label: Name, name: name, widget: string }
      - { label: Image, name: image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown, required: false }
      - {
          label: Open Graph Tags,
          name: open_graph,
          widget: object,
          collapsed: true,
          fields: *open_graph_fields,
        }
  - name: "forms"
    label: "Forms"
    folder: "src/pages/forms"
    create: true
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: form-page,
        }
      - { label: Title, name: title, widget: string }
      - { label: Image, name: image, widget: image }
      - { label: URL, name: url, widget: string }
      - {
          label: Open Graph Tags,
          name: open_graph,
          widget: object,
          collapsed: true,
          fields: *open_graph_fields,
        }
  - name: "events"
    label: "Events"
    folder: "src/pages/events"
    create: true
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: event-page,
        }
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown, required: false }
      - { label: When, name: when, widget: datetime }
      - { label: Where, name: where, widget: string, required: false }
      - { label: Preview Image, name: image, widget: image }
      - { label: Recurring, name: recurring, required: false, widget: boolean }
      - {
          label: Recurring When,
          name: recurring_when,
          required: false,
          widget: string,
        }
      - {
          label: Hero,
          name: hero,
          widget: object,
          collapsed: true,
          summary: "{{fields.heading}}",
          fields: *hero_fields,
        }
      - {
          label: Blurbs,
          name: blurbs,
          widget: list,
          collapsed: true,
          fields: *blurb_fields,
        }
      - {
          label: Open Graph Tags,
          name: open_graph,
          widget: object,
          collapsed: true,
          fields: *open_graph_fields,
        }

```

**Additional context**

```
API_ERROR: Unknown error
    t http://localhost:8000/admin/netlify-cms-app.js:54
    i http://localhost:8000/admin/netlify-cms-app.js:54
    request http://localhost:8000/admin/netlify-cms-app.js:493
    getMedia http://localhost:8000/admin/netlify-cms-app.js:493
    getMedia http://localhost:8000/admin/netlify-cms-app.js:28
    f http://localhost:8000/admin/netlify-cms-app.js:34
    loadMedia http://localhost:8000/admin/netlify-cms-app.js:34
    r http://localhost:8000/admin/netlify-cms-app.js:164
    r http://localhost:8000/admin/netlify-cms-app.js:22
    componentDidMount http://localhost:8000/admin/netlify-cms-app.js:216
    React 12
    notify http://localhost:8000/admin/netlify-cms-app.js:22
    notifyNestedSubs http://localhost:8000/admin/netlify-cms-app.js:22
    handleChangeWrapper http://localhost:8000/admin/netlify-cms-app.js:22
    v http://localhost:8000/admin/netlify-cms-app.js:43
    waitUntilAction http://localhost:8000/admin/netlify-cms-app.js:58
    r http://localhost:8000/admin/netlify-cms-app.js:164
    dispatch http://localhost:8000/admin/netlify-cms-app.js:43
    authenticateUser http://localhost:8000/admin/netlify-cms-app.js:43
    promise callback*t.authenticateUser/< http://localhost:8000/admin/netlify-cms-app.js:43
    r http://localhost:8000/admin/netlify-cms-app.js:164
    _ http://localhost:8000/admin/netlify-cms-app.js:148
    loadConfig http://localhost:8000/admin/netlify-cms-app.js:43
    r http://localhost:8000/admin/netlify-cms-app.js:164
    _ http://localhost:8000/admin/netlify-cms-app.js:148
    js http://localhost:8000/admin/cms.js:14361
    factory http://localhost:8000/admin/cms.js:48787
    __webpack_require__ http://localhost:8000/admin/cms.js:48180
    <anonymous> http://localhost:8000/admin/cms.js:49495
    <anonymous> http://localhost:8000/admin/cms.js:49499
netlify-cms-app.js:34:39826
    f http://localhost:8000/admin/netlify-cms-app.js:34
    (Async: promise callback)
    f http://localhost:8000/admin/netlify-cms-app.js:34
    loadMedia http://localhost:8000/admin/netlify-cms-app.js:34
    r http://localhost:8000/admin/netlify-cms-app.js:164
    r http://localhost:8000/admin/netlify-cms-app.js:22
    componentDidMount http://localhost:8000/admin/netlify-cms-app.js:216
    React 12
    notify http://localhost:8000/admin/netlify-cms-app.js:22
    notifyNestedSubs http://localhost:8000/admin/netlify-cms-app.js:22
    handleChangeWrapper http://localhost:8000/admin/netlify-cms-app.js:22
    v http://localhost:8000/admin/netlify-cms-app.js:43
    waitUntilAction http://localhost:8000/admin/netlify-cms-app.js:58
    r http://localhost:8000/admin/netlify-cms-app.js:164
    dispatch http://localhost:8000/admin/netlify-cms-app.js:43
    authenticateUser http://localhost:8000/admin/netlify-cms-app.js:43
    (Async: promise callback)
    authenticateUser http://localhost:8000/admin/netlify-cms-app.js:43
    r http://localhost:8000/admin/netlify-cms-app.js:164
    _ http://localhost:8000/admin/netlify-cms-app.js:148
    loadConfig http://localhost:8000/admin/netlify-cms-app.js:43
    r http://localhost:8000/admin/netlify-cms-app.js:164
    _ http://localhost:8000/admin/netlify-cms-app.js:148
    js http://localhost:8000/admin/cms.js:14361
    factory http://localhost:8000/admin/cms.js:48787
    __webpack_require__ http://localhost:8000/admin/cms.js:48180
    <anonymous> http://localhost:8000/admin/cms.js:49495
    <anonymous> http://localhost:8000/admin/cms.js:49499

```

`POST http://localhost:8081/api/v1`
request: `{"branch":"master","action":"getMedia","params":{"branch":"master","mediaFolder":"static/media"}}`
response: `{"error":"Unknown error"}`
