### ISSUE TITLE
Map/Dictionary Widget

### ISSUE THREAD

**Issue by bmackinney** [netlify/netlify-cms#5489]
https://answers.netlify.com/t/map-dictionary-fields/5241 has problem faced and solution found.

I'm making a files collection for hugo configuration files, and to edit the taxonomies field requires users to be able to define keys and values, resulting in something like:
```toml
[taxonomies]
featured = "featured"
topic = "topics"
tag = "tags"
team = "team"
```
I originally thought the code widget would work, but it outputs only strings.
