### ISSUE TITLE
Add customization of collection search

### ISSUE THREAD

**Issue by pmac** [netlify/netlify-cms#549]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

When viewing a collection, the search function seems to only search a single field named "title".

**- What is the expected behavior?**

Configuration should exist allowing one to set which fields should be included in collection search, very much like a "relation" field widget. Something like:

```yaml
collections:
  - name: releases
    label: Releases
    folder: "content/releases"
    create: true
    searchFields: ["product", "channel", "version"]
```

Alternately, allow for dynamic creation of `title` field in absence of one in the model (very much like `slug`) to be used for display and search:

```yaml
collections:
  - name: releases
    label: Releases
    folder: "content/releases"
    create: true
    title: "{product} {channel} {version}"
```

**- Please mention your node.js, and operating system version.**

This is just in the web interface for the CMS admin.
