### ISSUE TITLE
Deleted Netlify Identity User Stays Logged In

### ISSUE THREAD

**Issue by beepy** [netlify/netlify-cms#5551]
**Describe the bug**
A Netlify Identity user who is logged in stays logged in and able to make changes even after the user is deleted.

**To Reproduce**
1. On one computer/browser, create a user by going to your site using Netlify Identity & Netlify CMS
2. Confirm this new user is able to interact with the CMS and make changes
3. On another computer/browser, log in to the Netlify dashboard and delete the newly created user at `https://app.netlify.com/sites/<app-slug>/identity/<user-id>`
4. On the first computer/browser as the now-deleted user, make a change and publish it.
5. Observe that the deleted user was able to make a change

**Expected behavior**
At least, nothing (observe no change), or, at best, an error or a forced log out of the user.

**Screenshots**
n/a

**Applicable Versions:**

 - Netlify CMS version: 2.10.140 (netlify-cms-app 2.15.20, netlify-cms-core 2.41.0)
 - Git provider: GitHub
 - OS: macOS 11.4
 - Browser version: Vivaldi 3.8

**CMS configuration**
```yml
backend:
  name: git-gateway
  branch: feature/alipes-21

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
slug:
  encoding: 'ascii'
  clean_accents: true
collections:
  #
  # post
  # a blog post
  #
  - name: 'post'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'content/posts'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Author'
        name: 'author'
        widget: 'relation'
        collection: 'bio'
        search_fields: ['name', 'title']
        value_field: '{{slug}}'
        display_fields: ['name', 'title']
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: 'Image'
        name: 'image'
        widget: 'object'
        fields:
          - label: 'Image'
            name: 'image'
            widget: 'image'
          - label: 'Alt Text'
            name: 'alt_text'
            widget: 'string'
            required: false
          - label: 'Title'
            name: 'title'
            widget: 'string'
            required: false
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - label: 'Blocks'
        label_singular: 'Block'
        name: 'blocks'
        widget: list
        types:
          - label: 'Text'
            name: 'text'
            field: { label: 'Text', name: 'body', widget: 'markdown' }
          - label: 'Image'
            name: 'image'
            widget: 'object'
            fields:
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Alt Text'
                name: 'alt_text'
                widget: 'string'
                required: false
              - label: 'Title'
                name: 'title'
                widget: 'string'
                required: false
              - label: 'Caption'
                name: 'caption'
                widget: 'markdown'
                required: false
          - label: 'Embed'
            name: 'embed'
            field: { label: 'Embed Code', name: 'body', widget: 'text' }
          - label: 'Raw HTML'
            name: 'rawHtml'
            field: { label: 'Unsanitized HTML', name: 'body', widget: 'text' }
  #
  # case-study
  # a case study featured in the work section
  #
  - name: 'case-study'
    label: 'Case Studies'
    label_singular: 'Case Study'
    folder: 'content/case-studies'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', hint: 'Used for the window title/bookmark' }
      - { label: 'Title Tag Line', name: 'title_tag_line', widget: 'string', hint: 'Shown at the top of the case study’s page', required: false }
      - { label: 'Summary Tag Line', name: 'summary_tag_line', widget: 'string', hint: 'Shown below the case study’s thumbnail on the main case studies page', required: false }
      - { label: 'Featured', name: 'featured', widget: 'boolean', hint: 'Shown at the top of the main work page' }
      - label: 'Tags'
        name: 'tags'
        widget: 'relation'
        multiple: true
        options_length: 100
        collection: 'case-study-tag'
        search_fields: ['title']
        value_field: '{{slug}}'
        display_fields: ['title']
      - label: 'Thumbnail Image'
        name: 'image'
        widget: 'image'
        hint: 'Portrait orientation, 11:16'
      - label: 'Slider Images'
        name: 'images'
        widget: 'list'
        summary: '{{fields.image}}'
        fields:
          - { label: Image, name: image, widget: image, hint: 'Landscape orientation, 16:11' }
          - { label: 'Description', name: 'title', widget: 'string', hint: 'For screen readers' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false, hint: 'Text shown below the images and above the card. Use an H3 tag.' }
      - label: 'Cards'
        name: 'blocks'
        widget: 'list'
        summary: '{{fields.category}} - {{fields.title}}'
        fields:
          - { label: 'Category', name: 'category', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown', required: false, hint: 'Text shown in modal when card is clicked' }
      - label: 'Results'
        name: 'results'
        widget: 'list'
        summary: '{{fields.image}}'
        fields:
          - { label: Image, name: image, widget: image, hint: 'Portrait orientation, 11:16'}
          - { label: 'Body', name: 'body', widget: 'markdown', required: false, hint: 'Use an H4 tag.' }
          - label: 'Numbers'
            name: 'numbers'
            widget: 'list'
            summary: '{{fields.number}} - {{ fields.title}}'
            fields:
              - { label: 'Number', name: 'number', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
  #
  # bio
  # people to appear on the about page
  #
  - name: 'bio'
    label: 'Bios'
    label_singular: 'Bio'
    folder: 'content/bios'
    format: 'frontmatter'
    create: true
    slug: '{{name}}'
    identifier_field: name
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Full Title', name: 'title', widget: 'string', required: false }
      - { label: 'Short Title', name: 'short_title', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - label: 'Team'
        name: 'team'
        widget: 'select'
        options:
          - { label: 'Creative', value: 'creative' }
          - { label: 'Strategy', value: 'strategy' }
          - { label: 'Technology', value: 'technology' }
      - { label: 'Current employee (link to bio in posts)', name: 'active', widget: 'boolean', default: false }
      - { label: 'Portrait Image', name: 'image', widget: 'image', required: false, hint: 'Square with face horizontally centered' }
  #
  # job
  # opening to appear on the careers page
  #
  - name: 'job'
    label: 'Jobs'
    label_singular: 'Job'
    folder: 'content/jobs'
    format: 'frontmatter'
    create: true
    slug: '{{title}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Team'
        name: 'team'
        widget: 'select'
        options:
          - { label: 'Creative', value: 'creative' }
          - { label: 'Strategy', value: 'strategy' }
          - { label: 'Technology', value: 'technology' }
      - label: 'Sort Order'
        name: 'sort_order'
        widget: 'number'
        value_type: 'int'
        default: 1
        min: 1
        max: 100
        step: 1
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  #
  # front-featured
  # special content for the front/home page
  #
  - name: 'front-featured'
    label: 'Front Page'
    folder: 'content/front-featured'
    format: 'frontmatter'
    create: false
    slug: 'index'
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Hero Images
        name: images
        widget: list
        fields:
          - { label: Image, name: image, widget: image, hint: 'Must be 450x800' }
          - { label: 'Description', name: 'title', widget: 'string', hint: 'For screen readers' }
      - label: Featured Case Studies
        name: caseStudies
        widget: list
        max: 2
        fields:
          - label: 'Case Study'
            name: caseStudy
            collection: case-study
            widget: relation
            search_fields: ['title']
            value_field: '{{slug}}'
            display_fields: ['title']
      - &capabilities_by_discipline
        label: Capabilities by Discipline
        name: capabilities
        widget: list
        max: 3
        fields:
          - label: 'Discipline'
            name: 'discipline'
            widget: string
          - label: Capabilities
            name: capabilities
            widget: list
            fields:
              - label: Capability
                name: capability
                widget: string
  #
  # work-featured
  # special content for the work page
  #
  - name: 'work-featured'
    label: 'Work Page'
    folder: 'content/work-featured'
    format: 'frontmatter'
    create: false
    slug: 'index'
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Featured Case Studies
        name: caseStudies
        widget: list
        max: 3
        fields:
          - label: 'Case Study'
            name: caseStudy
            collection: case-study
            widget: relation
            search_fields: ['title']
            value_field: '{{slug}}'
            display_fields: ['title']
      - label: Featured Tags
        name: featuredTags
        widget: list
        max: 6
        fields:
          - label: 'Tag Group Title'
            name: title
            widget: string
          - label: 'Tags'
            name: 'tags'
            widget: 'relation'
            multiple: true
            options_length: 100
            collection: 'case-study-tag'
            search_fields: ['title']
            value_field: '{{slug}}'
            display_fields: ['title']
  #
  # staff-list
  # list of people to appear on the about page (which people should appear in what order)
  #
  - name: 'staff-list'
    label: 'Staff List'
    folder: 'content/staff-list'
    format: 'frontmatter'
    create: false
    slug: 'index'
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - *capabilities_by_discipline
      - label: Staff
        name: staff
        widget: list
        fields:
          - label: 'Staff Member'
            name: bio
            collection: bio
            widget: relation
            search_fields: ['name', 'title']
            value_field: '{{slug}}'
            display_fields: ['name', 'title']
  #
  # case-study-tag
  # tag for case studies - both those that are featured on the site, and those that are
  # kept just as records for future reference
  #
  - name: 'case-study-tag'
    label: 'Case Study Tags'
    label_singular: 'Case Study Tag'
    folder: 'content/case-study-tags'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Public', name: 'public', widget: 'boolean', default: false }
  #
  # case-study-reference
  # a case study kept for internal records
  #
  - name: 'case-study-reference'
    label: 'Case Study Reference'
    label_singular: 'Case Study Reference Record'
    folder: 'content/case-study-reference'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Tags'
        name: 'tags'
        widget: 'relation'
        multiple: true
        options_length: 100
        collection: 'case-study-tag'
        search_fields: ['title']
        value_field: '{{slug}}'
        display_fields: ['title']
      - { label: 'Body', name: 'body', widget: 'markdown', required: false, hint: 'Include links to relevant material, e.g. capes deck.' }
```
