### ISSUE TITLE
Can't log into the CMS

### ISSUE THREAD

**Issue by Penguibird** [netlify/netlify-cms#5635]
**Describe the bug**
When I go to my site/admin/ and press the log in with github button, a pop up opens, says authorized and then stays there. Doesn't close, the other window doesn't redirect to the CMS, nothing.

I'm using Netlify CMS without Netlify, my site is hosted on my server. When I was running the site locally I could access the CMS without a problem. I'm not sure what I should change.

**To Reproduce**
1. Host a gatsby site on your own, get a custom domain for it.
2. Set up Netlify CMS
3. Try to log in to your site with github

**Applicable Versions:**
netlify-cms-core 2.40.11
netlify-cms-app 2.15.17

**CMS configuration**
```yaml
backend:
  name: github
  repo: penguibird/kousekPoKousku
  branch: master
  site_domain: cms.netlify.com


media_folder: static/img
public_folder: /img

collections:
  - name: 'aktuality'
    label: 'Aktuality'
    folder: 'content/aktuality'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{name}}/index'
    preview: false
    identifier_field: name,
    fields:
    - { label: "ID", name: "id", widget: "id"}
    - { label: "Nazev", name: 'name', widget: 'string'}
    - {label: 'Datum', name: 'date', widget: 'dateTime', format: 'DD-MM-YYYY'}
    - {label: 'Text', name: 'body', widget: 'markdown'}
    - label: 'Obrazek'
      name: 'image'
      widget: 'object'
      collapsed: true
      fields:
      - {label: 'Obrazek', name: 'image', widget: 'image'}
      - {label: 'Popis obrazku', name: 'imageAlt', widget: 'string'}
  - name: 'aktualityZahrada'
    label: 'Aktuality Zahrada'
    folder: 'content/aktualityZahrada'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{name}}/index'
    preview: false
    identifier_field: name,
    fields:
    - { label: "ID", name: "id", widget: "id"}
    - { label: "Nazev", name: 'name', widget: 'string'}
    - {label: 'Datum', name: 'date', widget: 'dateTime', format: 'DD-MM-YYYY'}
    - {label: 'Text', name: 'body', widget: 'markdown'}
    - label: 'Obrazek'
      name: 'image'
      widget: 'object'
      collapsed: true
      fields:
      - {label: 'Obrazek', name: 'image', widget: 'image'}
      - {label: 'Popis obrazku', name: 'imageAlt', widget: 'string'}
  - name: 'projekty'
    label: 'Projekty'
    folder: 'content/projekty'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    preview: false
    # identifier_field: name,
    fields:
      - { label: "ID", name: "id", widget: "ncw-id"}
      - { label: 'Nazev', name: 'title', widget: 'string' }
      - { label: 'Cena', name: 'price', widget: 'number' }
      - { label: 'Rok', name: 'year', widget: 'number', value_type: 'int', min: 2000, max: 2100, step: 1, default: 2020, format: 'YYYY' }
      - { label: 'Popis', name: 'description', widget: 'markdown' }
      - label: 'Obrazek'
        name: 'image'
        widget: 'object'
        collapsed: false
        required: false
        fields:
        - {label: 'Obrazek', name: 'image', widget: 'image', required: false}
        - {label: 'Popis obrazku', name: 'imageAlt', widget: 'string', required: false}
      - {label: 'Podporen z kouskovani?', name: 'kouskovani', widget: 'boolean', required: false}
      - {label: 'Nazev mista', name: 'locationName', widget: 'string', required: false}
      - label: 'GPS souradnice'
        name: 'position' 
        widget: 'object'
        collapsed: false
        fields: 
        - {label: 'Lat', name: 'lat', widget: 'number', value_type: 'float'}
        - {label: 'Lng', name: 'lng', widget: 'number', value_type: 'float'}
```

The link to the site is https://kousekpokousku.cz and the cms is at https://kousekpokousku.cz/admin/

I can make the repo public, if it would help.
