### ISSUE TITLE
Search, sort, group by template tags in summary

### ISSUE THREAD

**Issue by martinjagodic** [netlify/netlify-cms#5724]
It is great that we can add template tags to the summary of a collection entry, for instance `{{dirname}}` is useful on nested files. However, it is not possible to group, sort, or search by these.

A solution would support template tags in the config for `sortable_fields` and `view_groups` and return search results containing tags in the summary.

Proposed config:
```yml
collections:
  - name: posts
    label: Posts
    label_singular: post
    folder: content/posts
    path: '{{slug}}/_index'
    sortable_fields: ['{{dirname}}', 'title', 'weight']
    view_groups: [
      {label: Category, field: category},
      {label: Directory, field: '{{dirname}}'},
    ]
    summary: "{{dirname}} - {{title}}"
    fields: [
      {name: title, label: Title, widget: string},
      {name: category, label: Category, widget: string},
      {name: weight, label: Weight, widget: number},
    ]
```
