### ISSUE TITLE
Only default locale editable i18n

### ISSUE THREAD

**Issue by tw1t611** [netlify/netlify-cms#5770]
**Describe the bug**
In the admin ui, only the default locale is shown.
Therefor it is not possible to edit other locale.

**To Reproduce**
1. Goto Admin UI -> any Collection
2. Open an entry

**Expected behavior**
Other locales are shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/13353525/131402268-973e1c74-00b8-473b-832f-017118192932.png)

**Applicable Versions:**

 - Netlify CMS version: 2.10.160
 - Git provider: gitlab
 - OS: fedora
 - Browser version: Mozilla Firefox 90.0.2

**CMS configuration**
```yml
backend:
  name: gitlab
  repo: tw1t611/bestnotebook-tech
  branch: main

# publish_mode: editorial_workflow # will not publish into main
media_folder: public/images # Media files will be stored in the repo under public/images
public_folder: /images # The src attribute for uploaded media will begin with /images

i18n:
  structure: multiple_folders
  locales: [en, de]
  default_locale: en

collections:
  - label: "Pages"
    name: "pages"
    folder: "public/content/pages"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Content"
        name: "content"
        widget: "list"
        summary: "{{fields.name}}"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" }

  - label: "Blog"
    name: "blog"
    folder: "public/content/posts"
    create: true
    i18n: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Notebooks"
    name: "notebooks"
    folder: "public/content/notebooks"
    create: true
    i18n: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Model", name: "model", widget: "string" }
      - { label: "Variant", name: "variant", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "content", widget: "markdown" }
      - label: "CPU"
        name: "cpu"
        widget: "relation"
        collection: "cpus"
        search_fields: ["name"]
        value_field: "name"

  - label: "CPUs"
    name: "cpus"
    folder: "public/content/cpus"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Cores", name: "cores", widget: "number" }
```

**Additional Context**
- Tried adding the locale folders
- Tried pushing content for other locale
  - `public/content/posts/de/asdf.md` exists
- Content was downloaded to local branch
