### ISSUE TITLE
Add support for multiple media libraries

### ISSUE THREAD

**Issue by aminimalanimal** [netlify/netlify-cms#5901]
I would like to use Netlify CMS’s git-based media library for icons and Cloudinary for larger images and videos. If there is a way to set image management on a per field basis, I haven't been able to find it yet.

The `image` widget currently supports `media_library` configuration to occur within the field, but seemingly not _selection_.

What if setting `media_library` to `null`/`false`/`local`/`netlify` allowed the built-in media manager to take over?

```yml
  label: Icon
  name: icon
  widget: image
  media_folder: /assets/icons/
  media_library: netlify
```

This thought could go further, such as wanting to use multiple third-party services at once. Perhaps it should be possible to globally register multiple media libraries by name and choose which one is used per field.
