### ISSUE TITLE
Collection list contains broken entries when a Scots Gaelic (GD) translation is added

### ISSUE THREAD

**Issue by anjackson** [netlify/netlify-cms#5909]
**Describe the bug**
I have a Hugo site that uses multiple files to store localised content, and have set NetlifyCMS up to edit this collection as shown at https://github.com/ukwa/ukwa-site/blob/169c23635637857029f9d64548f55966ddd94b8f/static/admin/config.yml#L43-L61

```
  - name: "info"
    label: "Information Page"
    folder: content/info
    create: false
    path: "{{slug}}/index"
    i18n: 
      structure: multiple_files
      locales: [en, cy, gd]
      default_locale: en
    preview_path: "info/{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Body
        name: body
        widget: markdown
        i18n: true
```

i.e. three languages are supported. When I add the English and Welsh, this works as expected. But when adding the Scots Gaelic, another item shows up in the collections list, like this:

![netlify-cms-bug](https://user-images.githubusercontent.com/87843/137904396-bec67568-7203-4dfb-bbcb-b25fa87bb095.png)

i.e. the item that says 'Rabhadh is Toirt a-nuas' is just the GD-locale title of the 'Notice and Takedown' page. If you click on 'Rabhadh is Toirt a-nuas' the editor shows but the edit panes are empty. If you click on 'Notice and Takedown' you can edit the page and it's translated versions just fine.

**To Reproduce**

I can reproduce this simply by adding a `gd` locale translation of a given page.

**Expected behavior**

Just show an entry for each page once, using the default locale as the title.

**Screenshots**

See above.

**Applicable Versions:**

- netlify-cms@2.10.173
- GitHub provider via `git-gateway`
- OS: Windows 10
- Firefox or Chrome (latest versions)

**CMS configuration**

https://github.com/ukwa/ukwa-site/blob/169c23635637857029f9d64548f55966ddd94b8f/static/admin/config.yml

**Additional context**

As `gd` is a fairly uncommon locale, perhaps it's missing from some list of known locales?
