### ISSUE TITLE
Allow displaying a different field that the linked `valueField` in `Relation` widget

### ISSUE THREAD

**Issue by medfreeman** [netlify/netlify-cms#591]
**- Do you want to request a *feature* or report a *bug*?**

Feature
Needs #597 first.

**- What is the current behavior?**

The [`Relation` widget](https://github.com/netlify/netlify-cms/blob/5b502aa68004118d8036d99f14126e998ddc5533/src/components/Widgets/RelationControl.js) allows linking to another collection item.
The `searchFields` property defines in what item fields netlify will look for the user provided string.
The `valueField` property defines what value will be stored in the relation field, thus creating a link between the current item and searched item.

**- Context**

I created a `menus` collection that can link to `pages` collection items on two levels:

```
  - name: "menus"
    label: "Menu"
    editor:
      preview: false
    folder: "content/menus"
    create: true
    widget: "object"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Items"
        name: "items"
        widget: "list"
        fields:
          - { label: "Page", name: "page", widget: "relation", collection: "pages", searchFields: ["title", "body"], valueField: "uuid" }
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Page", name: "page", widget: "relation", collection: "pages", searchFields: ["title", "body"], valueField: "uuid" }
```

I also created an `uuid` *read-only* widget that allows linking to a page by a *constant* unique per-item field, thus preventing the menu links to break in the case the `valueField` is set to `title` and the user changes the page `title` for example.

**- What is the expected behavior?**

Add a `displayField` property that would allow displaying a different field that the linked `valueField`.

In my above example i would have `uuid` as `valueField` and `title` as `displayField`.
The user would see the page title as menu entry, but the stored value would be the uuid.
