### ISSUE TITLE
Nested field access in name

### ISSUE THREAD

**Issue by robinvdvleuten** [netlify/netlify-cms#595]
It would be very nice to have the possibility to have nested fields access in field names.

Currently when I am configuring a nested field like this;

```yml
files:
      - file: 'site/content/_index.md'
        name: sections
        label: 'Sections'
        fields:
          - name: about
            label: 'About'
            widget: object
            fields:
              - { name: title, label: 'Title', widget: string }
              - { name: body, label: 'Body', widget: markdown }
```

It gives me the following;

```bash
-section-----
|--about----|
|----title--|
|----body---|
-------------
```

But if would be nice if I can just do this;

```yml
files:
      - file: 'site/content/_index.md'
        name: about
        label: 'About'
        fields:
         - { name: 'about.title', label: 'Title', widget: string }
         - { name: 'about.body', label: 'Body', widget: markdown }
```

And having this output;

```bash
-about-------
|--title----|
|--body-----|
-------------
```

**Comment by erquhart** [comment]
Providing more control over the data model makes sense, agreed. Just need to figure out how the api should work, I think we can do better than dot notation (but maybe not?).

**Comment by 01ivr3** [comment]
If I understand this correctly, this adding this feature could help clean up the editor experience quite a lot.

Say I have the following front matter on some Hugo pages.

```
menu:
  main:
    weight: '1'
```

Setting this one integer value per page will determine both the sort order and whether the page is included in Hugo's built-in nav system. Hugo will take care of the rest using the page title as the default lable for each entry and auto-generating the relative links.

Now someone please correct me if I am wrong, but to make this one field editable in NetlifyCMS, I believe I need something like the following in config.yml:
```
- label: "Menu"
  name: "menu"
  widget: "object"
  fields:
    - label: "Main"
      name: "main"
      widget: "object"
      fields:
        - {label: "Weight", name: "weight", widget: "number"}
```
This will yield a three layer deep nested object UI in NetlifyCMS to edit one single field, which looks about as hideous as it sounds.
