### ISSUE TITLE
List items should not require a `name`

### ISSUE THREAD

**Issue by julienma** [netlify/netlify-cms#596]
**- Do you want to request a *feature* or report a *bug*?**
Question, maybe feature.

**- What is the current behavior?**

The way I define opengraph pictures on  my site (using hugo) is to have an `images` array with values being path to pictures as string, not as an object.

It should be output as this in the front matter:

```
images:
  - /img/1.jpg
  - /img/2.jpg
```

So I set up these CMS fields:

```
      - name: "images"
        label: "OpenGraph Images"
        required: false
        widget: "list"
        fields:
          - {label: "Upload image", widget: "image"}
```

However it seems `name` is always output, no matter what I tried:

```
          - {label: "Upload image", widget: "image"}
// OR
          - {label: "Upload image", widget: "image", name: }
// OR
          - {label: "Upload image", widget: "image", name: ""}
```

and so this is the current output:

```
images:
  - 'null': /img/1.jpg
// OR
    undefined: /img/1.jpg
```

**- Question:**

Is there any way currently to have multiple list items without any `name`?
