### ISSUE TITLE
Gitlab pkce backend not passing client_id to gitlab

### ISSUE THREAD

**Issue by mryanb** [netlify/netlify-cms#6158]
**Describe the bug**
Using Gitlab 

**To Reproduce**

**Expected behavior**

**Screenshots**
Using Gitlab self hosted as a backend for Netlify CMS is resulting in and error message of `Missing required parameter: client_id`.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/3656391/151039503-0fc520c6-7827-469d-ae79-dd16d6f76fff.png">

How to reproduce:
1. Once clicking on "Login with GitLab"
2. Get redirected to `https://{{gitlab-domain}}/oauth/authorize?provider=gitlab&site_id=cms.netlify.com&scope=api
3. Get error

Following the docs from here: https://www.netlifycms.org/docs/gitlab-backend/#client-side-pkce-authorization

**Applicable Versions:**

 - Netlify CMS version: netlify-cms-app 2.9.7
 - Git provider: Gitlab  14.6.0-ee (self hosted)
 - OS: MacOS 12.1
 - Browser version: Firefox 95.0.2, Chrome 97.0.4692.99
 - Node.JS version: NPM 8.3.2

**CMS configuration**
Sensitive info changed to vars
```
backend:
  name: gitlab
  repo: {{the-group-name-here}}/articles
  auth_type: pkce
  app_id: {{app-id-goes-here}}
  api_root: https://{{gitlab-domain}}/api/v4
  base_url: https://{{gitlab-domain}}
  auth_endpoint: oauth/authorize
  branch: develop
```

**Additional context**
Here is the Gitlab config:
![image](https://user-images.githubusercontent.com/3656391/151039248-b415943a-9dbf-4742-9541-1e714cb93ad4.png)

**Comment by mryanb** [comment]
Resolved with an updated version of Netlify CMS.

**Comment by ErvinLlojku** [comment]
Hi @mryanb what version did you update to? Thanks

**Comment by pplupo** [comment]
I also need to know how to get around this. Which version has the fix, @mryanb ? Could you fix it, @ErvinLlojku ?

**Comment by lorenzode** [comment]
I just solved this by updating to v2.10.192.

**Comment by pplupo** [comment]
@lorenzode thank you very much. I'm was trying page. Before it was `https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js` and the version being loaded was 2.10.192. I've tried `https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js explicitly` and it didn't work either. I'm changing this on the admin.html page.

This is my yml backend config:
```
backend:
  name: gitlab
  repo: blog
  # branch: master # Branch to update (optional; defaults to master)
  site_domain: semblog.gitlab.io/blog
  base_url: https://gitlab.com
  auth_endpoint: oauth/authorize
  cms_label_prefix: netlify-cms/
```
Am I missing anything?

**Comment by mryanb** [comment]
Hi @pplupo 

 We're running on `netlify-cms 2.10.189` with the Gitlab backend working successfully. Note: we're using Gitlab self hosted.

Here is the relevant configs for the Gitlab backend portion too:


```
backend:
  name: gitlab
  repo: {{group-name-here}}/{{project-name-here}}
  auth_type: pkce
  app_id: {{your-gitlab app-here}}
  api_root: https://{{gitlab-host-name-here}}/api/v4
  base_url: {{gitlab-host-name-here}}
  auth_endpoint: oauth/authorize
  branch: develop
```
