### ISSUE TITLE
When title is updated on an entry, also update markdown files for related entries

### ISSUE THREAD

**Issue by AaratiAkkapeddi** [netlify/netlify-cms#6161]
I've noticed that when an entry title field is updated, if this entry is related to any other entry via the title, the stored title in the related entry does not update. 

For example, let's say **projects** can have multiple **artists** 
Project 1 has two artists, John and Jane. The md file for Project 1 looks like this:
```
---
title: Project 1
description: A cool project
artists: 
     artist: 'John'
     artist: 'Jane'
```
If I update Jane's name to Jane Doe, although Jane's md file updates to `name: 'Jane Doe'` instead of `name: 'Jane'`,  my Project 1 md file still has`artist:  'Jane'` instead of `artist: 'Jane Doe'`
