### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toLocaleDateString')

### ISSUE THREAD

**Issue by tagcaddy22** [netlify/netlify-cms#6174]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50708016/152001244-c4fdc905-33db-4e2f-abb3-46676c27edbd.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.14.26`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`

**CMS configuration**
```
backend:
  name: github
  repo: oort-dev/docs-site
  branch: main
media_folder: docs/assets
public_folder: /assets
logo_url: https://storage.googleapis.com/oort-marketing/assets/img/oort_logo_dark.png
collections:
  - sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
    view_filters: []
    name: doc
    folder: docs
    view_groups: []
    publish: true
    label: Doc
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: docTemplate
      - name: title
        label: Title
        required: true
        default: ""
      - name: path
        label: Path
        required: true
      - name: date
        label: Date
        widget: datetime
      - label: Author
        name: author
        widget: hidden
        disabled: true
      - name: tags
        label: Tags
        widget: list
      - name: body
        label: Body
        widget: markdown
        required: true
    type: folder_based_collection
    create: true
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"

```

**Additional context**
