### ISSUE TITLE
Nested Collections used with Docusaurus 2 shows "no entries" in the CMS

### ISSUE THREAD

**Issue by placeholdergit** [netlify/netlify-cms#6200]
**Describe the bug**
When using Nested Collections feature NetlifyCMS with [Docusaurus 2 static site generator](https://docusaurus.io/), the CMS shows "no entries":

![](https://i.imgur.com/lfc2Sf7.png)

**To Reproduce**

1. Go to https://docusauruscms.netlify.app/admin/
2. Click on Log in to register (registrations are open)
3. Check the "no entries" message by clicking on nested folders.
4. Compare the file and folder structure on [GitHub code](https://github.com/placeholdergit/docusauruscms/tree/main/docs):

![](https://i.imgur.com/xjkSG7x.png)

**Expected behavior**
Nested Collections should show entries (files) in nested folders inside CMS. Curretly it only shows folders and not entries inside it.

**Applicable Versions:**

 - Netlify CMS version: 2.10.186
 - Git provider: GitHub
 - OS: Windows 11
 - Browser version Chrome 98

 - Node.JS version: v14.15.1

**CMS configuration**

The collection `docs` has nested collections feature.

```yml
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: 'assets/uploads'
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'docs'
    label: 'docs'
    label_singular: 'Doc'
    identifier_field: 'title'
    format: 'frontmatter'
    folder: 'docs'
    create: true
    # adding a nested object will show the collection folder structure
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: 'blog'
    label: 'Blog'
    folder: 'blog'
    create: true
    slug: '{{date}}-{{id}}'
    identifier_field: 'title'
    extension: 'md'
    format: 'frontmatter'
    editor:
      preview: false
    fields:
      - { label: 'Slug', name: 'id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', required: false }
      - { label: 'Author Title', name: 'author_title', widget: 'string', required: false }
      - { label: 'Author URL', name: 'author_url', widget: 'string', required: false }
      - { label: 'Author Image', name: 'author_image_url', widget: 'image', allow_multiple: false, required: false }
      - { label: 'Hide Table of Contents', name: 'hide_table_of_contents', widget: 'boolean', default: false }
      - { label: 'Tags', name: 'tags', widget: 'list', default: [], required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD', timeFormat: false }
      - { label: 'Description', name: 'description', required: false }
      - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: 'src/pages'
    path: '{{id}}'
    create: true
    slug: '{{id}}'
    identifier_field: 'title'
    extension: 'js'
    format: 'frontmatter'
    editor:
      preview: false
    fields:
      - { label: 'Slug', name: 'id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }


```

**Additional context**

Code: https://github.com/placeholdergit/docusauruscms

You can login and test the admin Netlify CMS panel here: https://docusauruscms.netlify.app/admin and try it live.
