### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'get') on creating nested lists

### ISSUE THREAD

**Issue by luanraithz** [netlify/netlify-cms#6257]
**Describe the bug**

I'm getting the following error on the console when I try to create a `type: list` inside another `type: list`.

**To Reproduce**
I was able to reproduce using the gatsby template with the following config.yml:
```yaml
backend:
  name: git-gateway
  branch: master

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
           - label: 'Conteúdo'
             name: 'content'
             widget: 'list'
             types:
               - label: "Linha"
                 label_singular: "Nova linha (múltiplos elementos)"
                 name: 'line'
                 widget: 'list'
                 types:
                   - label: 'Texto'
                     name: 'text'
                     widget: 'object'
                     fields:
                       - label: "Texto"
                         name: "value"
                         widget: "string"

```

**Screenshots**

![image](https://user-images.githubusercontent.com/27583162/156176880-94d94a11-d59e-43b4-b5ce-dbd27a5112e4.png)
