### ISSUE TITLE
Locale selector is not working on single file collections

### ISSUE THREAD

**Issue by martinjagodic** [netlify/netlify-cms#6262]
**Describe the bug**
When you change a value on the locale dropdown, the content of the page does not correspond to the change. If you have the side-by-side editor enabled, you get this error in console when switching on the right panel: `this.props.onLocaleChange is not a function`.

**To Reproduce**
Go to a files collection with i18n
Try to change the locale
open your console
Turn on the side-by-side editor and switch the locale on both sides

**Expected behavior**
The editors content should change according to the desired locale

**Applicable Versions:**

 - Netlify CMS version: 2.10.187
 - Git provider: GitHub
 - OS: MacOS
 - Browser version Brave [Version 1.35.104 Chromium: 98.0.4758.109 (Official Build) (x86_64)](https://brave.com/latest/)

**CMS configuration**
```yaml
backend:
  name: git-gateway
  branch: main

i18n:
  structure: multiple_files
  locales: [en, de, it]

collections:
  - name: taxonomies
    label: Taxonomies
    format: json
    i18n:
      structure: single_file
      locales: [en, de, it]
    files: [
      {label: Travel type ideas, name: travelTypes, file: data/travelTypes.json, 18n: true, fields: [
        {name: title, label: Title, widget: string, 18n: true},
      ]},
    ]
```
