### ISSUE TITLE
Relation widget does not work with i18n file collection

### ISSUE THREAD

**Issue by martinjagodic** [netlify/netlify-cms#6264]
**Describe the bug**
The relation widget does not work with i18n file collection. When you click on it, you can see a loading indicator, but the options list is empty. If you have a predefined value it will also not work.

**To Reproduce**
1. Configure a file collection with i18n
2. try to add a file from it as a relation widget on another collection.
3. click on the relation dropdown

**Expected behavior**
There should be an options list like on a working relation widget

**Applicable Versions:**

 - Netlify CMS version: 2.10.187
 - Git provider: GitHub
 - OS: MacOS
 - Browser version Brave Version 1.35.104 Chromium: 98.0.4758.109 (Official Build) (x86_64)

**CMS configuration**
```yaml
backend:
  name: git-gateway
  branch: main

i18n:
  structure: multiple_files
  locales: [en, hr, de]

collections:
  - name: taxonomies
    label: Taxonomies
    format: json
    i18n:
      structure: single_file
      locales: [en, hr, de]
    files: [
      {label: Travel type ideas, name: travelTypes, file: data/travelTypes.json, 18n: true, fields: [
        {name: title, label: Title, widget: string, 18n: true},
        {name: id, label: ID, widget: string, 18n: true},
      ]},
    ]

  - name: travel-ideas
    label: Travel Ideas
    folder: content/travel-ideas
    i18n: true
    fields: [
      {name: title, label: Title, widget: string, 18n: true},
      {name: travelType, label: Travel type, widget: relation, collection: taxonomies, file: data/travelTypes.json, search_fields: ["items.*.title"], display_fields: ["items.*.title"], value_field: "items.*.id", i18n: duplicate},
      ]},
    ]
```
