### ISSUE TITLE
Support Hugo Page Bundles with current day/month/year/slug-title on Netlify CMS

### ISSUE THREAD

**Issue by buinguyenhoangtho** [netlify/netlify-cms#6336]
**Describe the solution you'd like**
Hello. Im currenly plan to use Netlify CMS on my blog. But my posts. I want to made my article organize as bundle with this template
```
/contents/posts/current-day-month-year-slug-title/index.md
# at index
---
title: "article title"
---
Hello
```

**Additional context**

Is there anyway to achive it? I love Netlify and thinking switch to Netifly CMS 
- My current config
```
collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    # Where to store posts (relative to the project root)
    folder: "content/posts"
    # Support Hugo page bundles that puts index.md and images in folders named by slug
    path: "{{slug}}/index"
    media_folder: "images"
    public_folder: "images"
```

**Comment by michael-proulx** [comment]
You can already do that.

https://www.netlifycms.org/docs/configuration-options/#slug

```yml
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { ... }
```
