### ISSUE TITLE
List of datetime crashes

### ISSUE THREAD

**Issue by Nico-L** [netlify/netlify-cms#634]
**- Do you want to request a *feature* or report a *bug*?**
bug 

**- What is the current behavior?**
setup a list of datime widgets causes an error:
```
Uncaught Error: Minified React error #31 etc...
 at t (cms.js:1)
    at n (cms.js:45)
    at r (cms.js:45)
    at n (cms.js:70)
    at g._reconcilerUpdateChildren (cms.js:70)
    at g._updateChildren (cms.js:70)
    at g.updateChildren (cms.js:70)
    at g._updateDOMChildren (cms.js:70)
    at g.updateComponent (cms.js:70)
    at g.receiveComponent (cms.js:70)
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. In config.yml, in fields add
```
       - label: "Date Events"
         name: "eventsDate"
         widget: list
         fields:
           - {label: "eventDate", name:"dateEvent", widget: "datetime"}
```
2. load the cms and add a new entry
3. add a new date events and pick a date
4. the error appear and the form can not be updated anymore, the date picker does not diseapear.

**- What is the expected behavior?**
A list of date, with date picking

**- Please mention your node.js, and operating system version.**
Netlify CMS version 0.4.6 on Netlify hosting

I want to create a collection of events. Each events can span over one or several dates. So it seems that the list widget suits my needs.

As a side question: is it possible to change the date language?
