### ISSUE TITLE
List Widget Variable types aren't working anymore

### ISSUE THREAD

**Issue by solidevolution** [netlify/netlify-cms#6473]
**Describe the bug**
Since today the list widget variable types feature doesn't work local or live on netlify.

**To Reproduce**
1. Create a config like described in https://www.netlifycms.org/docs/beta-features/#list-widget-variable-types
2. Try to create or edit an entry

**Expected behavior**
Netlify shows the "page builder"

**Screenshots**
<img width="492" alt="Bildschirmfoto 2022-05-17 um 21 51 11" src="https://user-images.githubusercontent.com/6850773/168898147-151b9103-fb98-40c3-8c03-27c9964eaec2.png">
<img width="690" alt="Bildschirmfoto 2022-05-17 um 21 51 06" src="https://user-images.githubusercontent.com/6850773/168898160-a43f6602-a91d-4d9f-a4c3-1dffb78e19f1.png">

**Applicable Versions:**
 - Netlify CMS version: 2.10.192
 - Git provider: GitHub
 - OS: MacOS
 - Browser: Chrome

**CMS configuration**
```
- name: 'pages'
    i18n: true
    label: 'Pages'
    label_singular: 'Page'
    folder: 'content/all'
    create: false
    delete: false
    format: 'frontmatter'
    path: '{{slug}}/index'
    slug: '{{slug}}'
    identifier_field: url
    extension: md
    preview_path: '{{slug}}'
    summary: '{{dirname}} - {{title}}'
    fields:
      - label: 'URL'
        name: 'url'
        i18n: true
        widget: 'string'
        required: true
      - label: 'Title'
        name: 'title'
        i18n: true
        widget: 'string'
        required: true
      - label: 'Description'
        name: 'description'
        i18n: true
        widget: 'string'
        required: true
      - label: 'Sections'
        name: 'sections'
        i18n: true
        widget: 'list'
        types:
          - label: 'Cover'
            name: 'cover'
            widget: object
            summary: 'Cover - {{fields.mediaLandscape}}'
            fields:
              - label: 'Landscape (16-9)'
                name: 'mediaLandscape'
                i18n: duplicate
                widget: 'image'
                required: true
                allow_multiple: false
              - label: 'Portrait (9-16)'
                name: 'mediaPortrait'
                i18n: duplicate
                widget: 'image'
                required: false
                allow_multiple: false

...

```

**Additional context**
No change on the netlify configuration.

No change in the version (same then yesterday)

Use the following scripts:

```
<script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
```
