### ISSUE TITLE
Gitlab Backend as Oauth Client for Netlify CMS. 

### ISSUE THREAD

**Issue by davli921** [netlify/netlify-cms#6529]
Im trying to connect Gitlab backend as Ouath client with Netlify CMS.

I have followed the docs and configured my config.yml accordingly: https://www.netlifycms.org/docs/gitlab-backend/

```
backend:   
  name: gitlab   
  branch: branchName 
  repo: xyz-repo 
  auth_type: pkce 
  app_id: asdasdasdgfasdf23w451234asdfa  
  site_domain: https://www.mydomain.com/   
  auth_endpoint: oauth/authorize
```

And I have registered my Gitlab Application as OAUTH client in the Netlify UI as mentioned here https://docs.netlify.com/visitor-access/oauth-provider-tokens/#netlify-ui-settings

But it still wont work

Is the reason that it is not working because I am not hosting my page on Netlify?

Does the page has to be hosted on Netlify to use Gitlab Backend as Oauth client for Netlify CMS?
