### ISSUE TITLE
Getting a "Git Gateway Error: [object Object]" error upon getting timed out and logged out, staying permanent until password reset

### ISSUE THREAD

**Issue by VitroidFPV** [netlify/netlify-cms#6539]
**Describe the bug**
When I leave the CMS open for an extended period of time, it throws a message saying `You have been logged out, please back up any data and login again`. Upon re-loading the page, it prompts me to log in with Netlify Identity. I'm using Git Gateway, and Google/Github for user login. I log in with google, select the account I want to log in with, and it all seems to go correctly. Though immediately after, it takes me back to the login screen, and when I press the button to log in with Netlify identity, it throws the error, always, until I end a password reset for my account

**To Reproduce:**
1. Leave CMS open in the background until prompted that I've been logged out
2. Refresh the page, gets to the login screen
3. Log in as normal, select Google as the login method, and select my account
4. Immediately goes back to login page, upon successive attempts to use the login button, only get the error

**Expected behavior**
I expect to be able to log in normally after selecting all of the correct options

**Screenshots**
![image](https://user-images.githubusercontent.com/76877124/185202237-f8c8c8ae-89a7-4f7a-a20a-8792fa50cd63.png)
![image](https://user-images.githubusercontent.com/76877124/185202336-128ca77f-ef0b-4bb4-8a7e-2dc1ab5945e6.png)

**Applicable Versions:**

 - Netlify CMS version: netlify-cms 2.10.192
 - Git provider: GitHub
 - OS: Windows 10 and 11
 - Browser version Brave 1.42.95, Chromium: 104.0.5112.81

**CMS configuration**
```yml
backend:
  name: git-gateway
  branch: svelte
collections:
  - name: FAQ
    label: FAQ
    folder: modules/faqs/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{Category}}-{{title}}"
    fields:
      - name: Category
        widget: "select"
        options:
          - { label: "Starting Out", value: "Starting Out" }
          - { label: "Building", value: "Building" }
          - { label: "Betaflight", value: "Betaflight" }
          - { label: "Video", value: "Video" }
          - { label: "Radio", value: "Radio" }
          - { label: "Hardware", value: "Hardware" }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Question", name: "title", widget: "text"}
      - {label: "ID", name: "id", widget: "text"}
      - {label: "Answer", name: "answer", widget: "markdown"}

  - name: 5" Beginner Build
    label: 5" Beginner Build
    folder: modules/buildLists/5inchBeginner/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{Category}}-{{title}}"
    fields:
      - label: Category
        name: Category
        widget: "select"
        options:
          - { label: "Frames", value: "Frames" }
          - { label: "Motors", value: "Motors" }
          - { label: "Flight Controllers", value: "Flight Controllers" }
          - { label: "ESCs", value: "ESCs" }
          - { label: "Video Transmitters", value: "Video Transmitters" }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Link", name: "link", widget: "text"}
      - {label: "Description", name: "text", widget: "text"}

      - {label: "Price", name: "price", widget: "text"}
      - {label: "Point 1", name: "point1", widget: "text", required: false}
      - {label: "Point 2", name: "point2", widget: "text", required: false}
      - {label: "Point 3", name: "point3", widget: "text", required: false}
      - {label: "Point 4", name: "point4", widget: "text", required: false}
      - {label: "Point 5", name: "point5", widget: "text", required: false}

  - name: 3" Cinewhoop Build
    label: 3" Cinewhoop Build
    folder: modules/buildLists/3inchCinewhoop/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{Category}}-{{title}}"
    fields:
      - label: Category
        name: Category
        widget: "select"
        options:
          - { label: "Frames", value: "Frames" }
          - { label: "Motors", value: "Motors" }
          - { label: "Flight Controllers", value: "Flight Controllers" }
          - { label: "ESCs", value: "ESCs" }
          - { label: "AIOs", value: "AIOs" }
          - { label: "Video Transmitters", value: "Video Transmitters" }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Link", name: "link", widget: "text"}
      - {label: "Description", name: "text", widget: "text"}

      - {label: "Price", name: "price", widget: "text"}
      - {label: "Point 1", name: "point1", widget: "text", required: false}
      - {label: "Point 2", name: "point2", widget: "text", required: false}
      - {label: "Point 3", name: "point3", widget: "text", required: false}
      - {label: "Point 4", name: "point4", widget: "text", required: false}
      - {label: "Point 5", name: "point5", widget: "text", required: false}

  - name: 1s - 2s Toothpick Build
    label: 1s - 2s Toothpick Build
    folder: modules/buildLists/1s2sToothpick/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{Category}}-{{title}}"
    fields:
      - label: Category
        name: Category
        widget: "select"
        options:
          - { label: "Frames", value: "Frames" }
          - { label: "Motors", value: "Motors" }
          - { label: "AIOs", value: "AIOs" }
          - { label: "Video Transmitters", value: "Video Transmitters" }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Link", name: "link", widget: "text"}
      - {label: "Description", name: "text", widget: "text"}

      - {label: "Price", name: "price", widget: "text"}
      - {label: "Point 1", name: "point1", widget: "text", required: false}
      - {label: "Point 2", name: "point2", widget: "text", required: false}
      - {label: "Point 3", name: "point3", widget: "text", required: false}
      - {label: "Point 4", name: "point4", widget: "text", required: false}
      - {label: "Point 5", name: "point5", widget: "text", required: false}
    
media_folder: "/static/uploads/"
public_folder: "/uploads/"

site_url: https://vitroidfpv-sv.netlify.app/
display_url: https://vitroidfpv-sv.netlify.app/
logo_url: https://vitroidfpv-sv.netlify.app/favicon.png
```

**Additional context**
Doesn't seem to happen all of the time, though it working fine is usually an exception
