### ISSUE TITLE
API_ERROR: tree.path contains a malformed path component

### ISSUE THREAD

**Issue by tattooseoul** [netlify/netlify-cms#6804]
Before a couple of months ago, the CMS worked perfectly. But now, when I write a new post/page and I click on the save button, I get the following error message:

> API_ERROR: tree.path contains a malformed path component

Here is my config.yml file:

```
backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "/static/media" # Folder where user uploaded files should go
public_folder: "/media"
site_url: https://joelgie.com
editor:
  preview: true
locale: 'fr'

local_backend: true
i18n:
  structure: multiple_folders
  locales: [ en, fr ]
  default_locale: en
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{month}}-{{year}}{{slug}}" # Filename template, e.g., DD-MM-YYYY-title.md
    nested:
      depth: 100 
    path: "{{filename}}/index"  
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page" # Used in routes, e.g., /admin/collections/pages
    label: "Pages" # Used in the UI
    folder: "content/page" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    nested:
      depth: 100 
    path: "{{filename}}/index" 
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
```
