### ISSUE TITLE
"Stuck" on old commit / changes made through Decap or manually not shown in the CMS

### ISSUE THREAD

**Issue by charludo** [netlify/netlify-cms#7457]
**Describe the bug**

I have set Decap up with my own Forgejo instance, and initially, everything seemed to work. I can auth through Forgejo, and am then presented with a list of my blogposts. I can edit them or create new ones, and when clicking "publish", the changes/new posts will be committed to the repo, on the correct (and only) branch. (A workflow then publishes these changes, so 1-2 minutes after making any change through Decap, the newly built site is public and accurately reflects these changes.)

The problem: inside decap itself, I am stuck with the "initial" repo state. New posts/commits - whether created through Decap or manually - do not appear. Changes to existing content do not appear. Even manually deleting a post and committing that change, then logging into Decap from a completely fresh device on a previously unused internet connection with any and all caching I can think of disabled.... The post is still there in Decap.

Actually, typing this out, I wonder if Decap might indeed be stuck at the very first commit of my repo. I do not have many commits, so it is a bit hard to verify.

**To Reproduce**

No idea, sorry. 

**Expected behavior**

Changes made - whether through Decap or manually - are reflected in Decap

**Screenshots**

**Applicable Versions:**

 - Decap CMS version: 3.6.2
 - Git provider: Forgejo
 - OS: Linux
 - Browser version Firefox 136

 - Node.JS version: n/a

**CMS configuration**

```
backend:
  name: gitea
  repo: me/personal-site
  app_id: [...]
  api_root: https://git.[...]/api/v1
  base_url: https://git.[...]
  auth_endpoint: https://git.[...]/login/oauth/authorize
  branch: main
site_url: https://blog.[...].com
display_url: https://blog.[...].com
media_folder: ""
public_folder: ""
collections:
  - name: "entries" # Used in routes, e.g., /admin/collections/blog
    label: "Entries" # Used in the UI
    folder: "entries" # The path to the folder where the documents are stored
    extension: "md"
    path: "{{slug}}/item"
    format: "yaml-frontmatter"
    media_folder: '.'
    public_folder: '.'
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Sort", name: "sort", widget: "number", required: false }
      - { label: "From", name: "from", widget: "string", required: false }
      - { label: "Until", name: "until", widget: "string", required: false }
      - { label: "Collections", name: "collections", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
```

**Additional context**
