### ISSUE TITLE
[i18n]: no editors for non-default languages

### ISSUE THREAD

**Issue by tpluscode** [netlify/netlify-cms#7505]
**Describe the bug**

I wanted to set up editing with translations. So far, I only tried locally with decap-server

When editing or creating a collection entry, only the default language is displayed for editing.

**To Reproduce**

1. Run `decap-server` and `http-server` to serve the repo as-is
3. Create a new file in the UI
4. Switch languages

**Expected behavior**

The widgets should be rendered but they are invisible (present in HTML though).
Also, the "Fill in from another locale" appears to do nothing

I also populated the translation files by hand, and they are still not displayed

**Screenshots**

https://github.com/user-attachments/assets/3f060e5e-a77d-4602-aa2f-29768916abe3

**Applicable Versions:**

 - Decap CMS version: 3.6.4
 - Git provider: local
 - OS: macOS
 - Browser version: Brave

 - Node.JS version:

**CMS configuration**

```yaml
# Uncomment for local development
local_backend: true

backend:
  name: github
  branch: main
  repo: zazukoians/decap-i18n

i18n:
  structure: multiple_folders
  default_local: de
  locales: [de, fr, it, en]

collections:
  - name: Showcases
    label: "Showcases"
    folder: "showcases"
    i18n: true
    extension: md
    widget: "list"
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - name: body
        label: Body
        widget: markdown
```
