### ISSUE TITLE
i18n: "Fill in from another locale" appears to do nothing

### ISSUE THREAD

**Issue by tpluscode** [netlify/netlify-cms#7507]
**Describe the bug**

As a follow

**To Reproduce**

1. Set up i18n
1. Create a new item
2. Write some content in default language
3. Choose `Fill in from another locale` and select another locale

**Expected behavior**

The content in the second language should be immediately updated. Instead, it is necessary to switch the language back and forth for the UI to update

**Screenshots**

https://github.com/user-attachments/assets/0ffbd7dc-c014-4f3e-8c57-49b451dfb5a2

**Applicable Versions:**

 - Decap CMS version: 3.6.4
 - Git provider: local
 - OS: macos
 - Browser version: Brave 1.79.119

 - Node.JS version:

**CMS configuration**

```yaml
backend:
  name: github
  branch: main
  repo: zazukoians/decap-i18n

publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

i18n:
  structure: multiple_folders
  default_local: de
  locales: [de, fr, it, en]

collections:
  - name: Showcases
    label: "Showcases"
    folder: "showcases"
    i18n: true
    extension: md
    widget: "list"
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - name: body
        label: Body
        widget: markdown
        i18n: true
```
