### ISSUE TITLE
_data in admin

### ISSUE THREAD

**Issue by chris10an** [netlify/netlify-cms#825]
Is it possbile to get make YAML files stored in _data to show up in the admin and be editable? Like they do in Forestry.io?

**Comment by tech4him1** [comment]
Yes, you should be able to do something like this in your CMS config:
```yaml
collections:
  - name: "data" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Data Files" # Used in the UI, ie.: "New Post"
    folder: "_data"
    format: "yaml"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Question", name: "title", widget: "string", tagname: "h1"}
      - {label: "Answer", name: "body", widget: "markdown"}
```
You just create a reqular folder-type collection and add the `format: yaml` key to it.

If you only want to edit specific (pre-defined) files, you can also use a file-type collection, like this:
https://github.com/netlify/netlify-cms/blob/d9905b4a6aa73a8065be524e0c61a66c623fa64a/example/config.yml#L28-L46
