### ISSUE TITLE
List reordering bug

### ISSUE THREAD

**Issue by taussoe** [netlify/netlify-cms#985]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When reordering a list the content of a markdown widget gets moved to another list items markdown widget

**- If the current behavior is a bug, please provide the steps to reproduce.**
Create two list items with a markdown widget inside. Drag the bottom list item above another.

**- Please mention your CMS, node.js, and operating system version.**
NetlifyCMS 1.0.1, node.js, gatsby, react

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "kontaktpersoner"
    label: "Kontakt personer"
    description: >
      Vedligeholdelse af kontaktpersoner
    folder: "src/pages/kontaktpersoner"
    create: true
    fields:
      - {label: "Path", name: "path", widget: "hidden", default: "/kontaktpersoner"}
      - {label: "Profilbillede", name: "contactimage", widget: image}
      - {label: "Navn", name: "title", widget: "string"}
      - {label: "Titel", name: "contacttitle", widget: "string"}
      - {label: "Uddannelse", name: "contacteducation", widget: "string", required: false}
      - {label: "Telefon", name: "contacttelephone", widget: "string"}
      - {label: "Email", name: "contactemail", widget: "string"}
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "src/pages/home/home.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/"}
          - {label: "SEO Title", name: title, widget: string}
          - {label: "SEO Image", name: image, widget: image}
          - {label: "SEO Description", name: description, widget: string}
          - {label: Komponenter, name: components, widget: object, fields: [{label: Sektioner, name: sektioner, widget: list, fields: [{label: "Menu navn", name: menuname, widget: string}, {label: "Component", name: "component", widget: "select", options: ["Hero", "Statement", "PictureLeft", "PictureRight", "Instagram", "Kontakt"]},{label: Image, name: image, widget: image}, {label: "Overskrift", name: overskrift, widget: string}, {label: Text, name: text, widget: "markdown"}]}]}
      - file: "src/pages/about/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
```
