### ISSUE TITLE
Config.yml 404 error depending on URL

### ISSUE THREAD

**Issue by TristianK3604** [netlify/netlify-cms#999]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug
**- What is the current behavior?**
When typing in `/admin`, it reports a 404 in finding `config.yml` (it redirects to `/admin#/`). When typing in `/admin/`, it works (it redirects to `/admin/#/`).
**- If the current behavior is a bug, please provide the steps to reproduce.**
Rather than entering `/admin/` or `/admin/#` when trying to access Netlify CMS, type in `/admin`.
**- What is the expected behavior?**
Expected behavior is to find the `config.yml` file at `/admin/config.yml` rather than `/admin#/config.yml`.

**- Please mention your CMS, node.js, and operating system version.**

Netlify CMS 1.0, Node.js 6.12.3

**- Please link or paste your `config.yml` below if applicable.**
````yaml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  
publish_mode: editorial_workflow
media_folder: "images"

collections:
  - name: "scripts" # Used in routes, e.g., /admin/collections/blog
    label: "Script Page" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "script"}
      - {label: "Script Name", name: "title", widget: "string"}
      - {label: "GitHub Username", name: "gh_username", widget: "string"}
      - {label: "Repository Name", name: "repo_name", widget: "string"}
      - {label: "Screenshot", name: "screenshot", widget: "image", required: false}
      - {label: "Documentation URL", name: "doc_url", widget: "string"}
      - label: "Category"
        name: "categories"
        widget: "select"
        options:
         - { label: "Blog", value: "Blog" }
         - { label: "Documentation", value: "Documentation" }
         - { label: "Other", value: "Other" }
      - label: "Does this repository use Netlify CMS?"
        name: "cms"
        widget: "select"
        options:
         - { label: "No", value: "false" }
         - { label: "Yes", value: "true" }
      - {label: "Description", name: "body", widget: "markdown"}
````
